#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Sleep 15000
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 651
    Send("{c up}")
    Sleep 807
    Send("{c down}")
    Sleep 208
    Send("{s down}")
    Sleep 13
    Send("{c up}")
    Sleep 247
    Send("{s up}")
    Sleep 156
    Send("{z down}")
    Sleep 417
    Send("{m down}")
    Sleep 13
    Send("{z up}")
    Sleep 599
    Send("{m up}")
    Sleep 221
    Send("{m down}")
    Sleep 195
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 91
    Send("{z up}")
    Sleep 117
    Send("{s down}")
    Sleep 560
    Send("{s up}")
    Sleep 273
    Send("{s down}")
    Sleep 169
    Send("{s up}")
    Sleep 39
    Send("{c down}")
    Sleep 91
    Send("{c up}")
    Sleep 117
    Send("{g down}")
    Sleep 547
    Send("{g up}")
    Sleep 286
    Send("{s down}")
    Sleep 182
    Send("{s up}")
    Sleep 26
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{g down}")
    Sleep 299
    Send("{g up}")
    Sleep 117
    Send("{s down}")
    Sleep 286
    Send("{s up}")
    Sleep 130
    Send("{z down}")
    Sleep 378
    Send("{z up}")
    Sleep 39
    Send("{m down}")
    Sleep 612
    Send("{m up}")
    Sleep 221
    Send("{m down}")
    Sleep 195
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 91
    Send("{z up}")
    Sleep 117
    Send("{s down}")
    Sleep 560
    Send("{s up}")
    Sleep 273
    Send("{s down}")
    Sleep 169
    Send("{s up}")
    Sleep 39
    Send("{c down}")
    Sleep 91
    Send("{c up}")
    Sleep 117
    Send("{g down}")
    Sleep 547
    Send("{g up}")
    Sleep 286
    Send("{s down}")
    Sleep 182
    Send("{s up}")
    Sleep 26
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{g down}")
    Sleep 299
    Send("{g up}")
    Sleep 117
    Send("{s down}")
    Sleep 286
    Send("{s up}")
    Sleep 130
    Send("{z down}")
    Sleep 378
    Send("{z up}")
    Sleep 39
    Send("{m down}")
    Sleep 586
    Send("{m up}")
    Sleep 247
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{s down}")
    Sleep 586
    Send("{s up}")
    Sleep 247
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{x down}")
    Sleep 586
    Send("{x up}")
    Sleep 247
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{c down}")
    Sleep 273
    Send("{c up}")
    Sleep 143
    Send("{s down}")
    Sleep 339
    Send("{s up}")
    Sleep 78
    Send("{z down}")
    Sleep 391
    Send("{z up}")
    Sleep 26
    Send("{m down}")
    Sleep 586
    Send("{m up}")
    Sleep 247
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{s down}")
    Sleep 586
    Send("{s up}")
    Sleep 247
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{x down}")
    Sleep 586
    Send("{x up}")
    Sleep 247
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{c down}")
    Sleep 273
    Send("{c up}")
    Sleep 143
    Send("{s down}")
    Sleep 339
    Send("{s up}")
    Sleep 78
    Send("{z down}")
    Sleep 391
    Send("{z up}")
    Sleep 26
    Send("{m down}")
    Sleep 586
    Send("{m up}")
    Sleep 247
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{s down}")
    Sleep 586
    Send("{s up}")
    Sleep 247
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{x down}")
    Sleep 117
    Send("{x up}")
    Sleep 91
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 130
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 130
    Send("{x down}")
    Sleep 117
    Send("{x up}")
    Sleep 91
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 130
    Send("{x down}")
    Sleep 91
    Send("{x up}")
    Sleep 117
    Send("{c down}")
    Sleep 117
    Send("{c up}")
    Sleep 91
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 130
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 130
    Send("{c down}")
    Sleep 208
    Send("{c up}")
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{c down}")
    Sleep 91
    Send("{c up}")
    Sleep 117
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 651
    Send("{c up}")
    Sleep 807
    Send("{c down}")
    Sleep 208
    Send("{s down}")
    Sleep 13
    Send("{c up}")
    Sleep 247
    Send("{s up}")
    Sleep 156
    Send("{z down}")
    Sleep 417
    Send("{m down}")
    Sleep 13
    Send("{z up}")
    Sleep 599
    Send("{m up}")
    Sleep 221
    Send("{m down}")
    Sleep 195
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 91
    Send("{z up}")
    Sleep 117
    Send("{s down}")
    Sleep 560
    Send("{s up}")
    Sleep 273
    Send("{s down}")
    Sleep 169
    Send("{s up}")
    Sleep 39
    Send("{c down}")
    Sleep 91
    Send("{c up}")
    Sleep 117
    Send("{g down}")
    Sleep 547
    Send("{g up}")
    Sleep 286
    Send("{s down}")
    Sleep 182
    Send("{s up}")
    Sleep 26
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{g down}")
    Sleep 299
    Send("{g up}")
    Sleep 117
    Send("{s down}")
    Sleep 286
    Send("{s up}")
    Sleep 130
    Send("{z down}")
    Sleep 378
    Send("{z up}")
    Sleep 39
    Send("{m down}")
    Sleep 612
    Send("{m up}")
    Sleep 221
    Send("{m down}")
    Sleep 195
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 91
    Send("{z up}")
    Sleep 117
    Send("{s down}")
    Sleep 560
    Send("{s up}")
    Sleep 273
    Send("{s down}")
    Sleep 169
    Send("{s up}")
    Sleep 39
    Send("{c down}")
    Sleep 91
    Send("{c up}")
    Sleep 117
    Send("{g down}")
    Sleep 547
    Send("{g up}")
    Sleep 286
    Send("{s down}")
    Sleep 182
    Send("{s up}")
    Sleep 26
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{g down}")
    Sleep 299
    Send("{g up}")
    Sleep 117
    Send("{s down}")
    Sleep 286
    Send("{s up}")
    Sleep 130
    Send("{z down}")
    Sleep 378
    Send("{z up}")
    Sleep 39
    Send("{m down}")
    Sleep 586
    Send("{m up}")
    Sleep 247
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{s down}")
    Sleep 586
    Send("{s up}")
    Sleep 247
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{x down}")
    Sleep 586
    Send("{x up}")
    Sleep 247
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{c down}")
    Sleep 273
    Send("{c up}")
    Sleep 143
    Send("{s down}")
    Sleep 339
    Send("{s up}")
    Sleep 78
    Send("{z down}")
    Sleep 391
    Send("{z up}")
    Sleep 26
    Send("{m down}")
    Sleep 586
    Send("{m up}")
    Sleep 247
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{s down}")
    Sleep 586
    Send("{s up}")
    Sleep 247
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{x down}")
    Sleep 586
    Send("{x up}")
    Sleep 247
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{c down}")
    Sleep 273
    Send("{c up}")
    Sleep 143
    Send("{s down}")
    Sleep 339
    Send("{s up}")
    Sleep 78
    Send("{z down}")
    Sleep 391
    Send("{z up}")
    Sleep 26
    Send("{m down}")
    Sleep 586
    Send("{m up}")
    Sleep 247
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{s down}")
    Sleep 586
    Send("{s up}")
    Sleep 247
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{x down}")
    Sleep 117
    Send("{x up}")
    Sleep 91
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 130
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 130
    Send("{x down}")
    Sleep 117
    Send("{x up}")
    Sleep 91
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 130
    Send("{x down}")
    Sleep 91
    Send("{x up}")
    Sleep 117
    Send("{c down}")
    Sleep 117
    Send("{c up}")
    Sleep 91
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 130
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 130
    Send("{c down}")
    Sleep 208
    Send("{c up}")
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{c down}")
    Sleep 91
    Send("{c up}")
    Sleep 117
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 651
    Send("{c up}")
    Sleep 599
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{g down}")
    Sleep 156
    Send("{g up}")
    Sleep 52
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{x down}")
    Sleep 156
    Send("{x up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{m down}")
    Sleep 156
    Send("{m up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 234
    Send("{z down}")
    Sleep 391
    Send("{z up}")
    Sleep 26
    Send("{m down}")
    Sleep 612
    Send("{m up}")
    Sleep 221
    Send("{m down}")
    Sleep 195
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 91
    Send("{z up}")
    Sleep 117
    Send("{s down}")
    Sleep 560
    Send("{s up}")
    Sleep 273
    Send("{s down}")
    Sleep 169
    Send("{s up}")
    Sleep 39
    Send("{c down}")
    Sleep 91
    Send("{c up}")
    Sleep 117
    Send("{g down}")
    Sleep 547
    Send("{g up}")
    Sleep 286
    Send("{s down}")
    Sleep 182
    Send("{s up}")
    Sleep 26
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{g down}")
    Sleep 299
    Send("{g up}")
    Sleep 117
    Send("{s down}")
    Sleep 286
    Send("{s up}")
    Sleep 130
    Send("{z down}")
    Sleep 378
    Send("{z up}")
    Sleep 39
    Send("{m down}")
    Sleep 612
    Send("{m up}")
    Sleep 221
    Send("{m down}")
    Sleep 195
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 91
    Send("{z up}")
    Sleep 117
    Send("{s down}")
    Sleep 560
    Send("{s up}")
    Sleep 273
    Send("{s down}")
    Sleep 169
    Send("{s up}")
    Sleep 39
    Send("{c down}")
    Sleep 91
    Send("{c up}")
    Sleep 117
    Send("{g down}")
    Sleep 547
    Send("{g up}")
    Sleep 286
    Send("{s down}")
    Sleep 182
    Send("{s up}")
    Sleep 26
    Send("{c down}")
    Sleep 156
    Send("{c up}")
    Sleep 52
    Send("{g down}")
    Sleep 299
    Send("{g up}")
    Sleep 117
    Send("{s down}")
    Sleep 286
    Send("{s up}")
    Sleep 130
    Send("{z down}")
    Sleep 378
    Send("{z up}")
    Sleep 39
    Send("{m down}")
    Sleep 586
    Send("{m up}")
    Sleep 247
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{s down}")
    Sleep 586
    Send("{s up}")
    Sleep 247
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{x down}")
    Sleep 586
    Send("{x up}")
    Sleep 247
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{c down}")
    Sleep 273
    Send("{c up}")
    Sleep 143
    Send("{s down}")
    Sleep 339
    Send("{s up}")
    Sleep 78
    Send("{z down}")
    Sleep 391
    Send("{z up}")
    Sleep 26
    Send("{m down}")
    Sleep 586
    Send("{m up}")
    Sleep 247
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{s down}")
    Sleep 586
    Send("{s up}")
    Sleep 247
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{x down}")
    Sleep 586
    Send("{x up}")
    Sleep 247
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{c down}")
    Sleep 273
    Send("{c up}")
    Sleep 143
    Send("{s down}")
    Sleep 339
    Send("{s up}")
    Sleep 78
    Send("{z down}")
    Sleep 391
    Send("{z up}")
    Sleep 26
    Send("{m down}")
    Sleep 586
    Send("{m up}")
    Sleep 247
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{s down}")
    Sleep 586
    Send("{s up}")
    Sleep 247
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 104
    Send("{x down}")
    Sleep 117
    Send("{x up}")
    Sleep 91
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 130
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 130
    Send("{x down}")
    Sleep 117
    Send("{x up}")
    Sleep 91
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 130
    Send("{x down}")
    Sleep 91
    Send("{x up}")
    Sleep 117
    Send("{c down}")
    Sleep 117
    Send("{c up}")
    Sleep 91
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 130
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 130
    Send("{c down}")
    Sleep 208
    Send("{c up}")
    Send("{s down}")
    Sleep 156
    Send("{s up}")
    Sleep 52
    Send("{c down}")
    Sleep 91
    Send("{c up}")
    Sleep 117
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1471
    Send("{s down}")
    Sleep 195
    Send("{s up}")
    Sleep 13
    Send("{c down}")
    Sleep 195
    Send("{c up}")
    Sleep 13
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1471
    Send("{s down}")
    Sleep 195
    Send("{s up}")
    Sleep 13
    Send("{c down}")
    Sleep 195
    Send("{c up}")
    Sleep 13
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1471
    Send("{s down}")
    Sleep 195
    Send("{s up}")
    Sleep 13
    Send("{c down}")
    Sleep 195
    Send("{c up}")
    Sleep 13
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 612
    Send("{c up}")
    Sleep 1888
    Send("{g down}")
    Sleep 677
    Send("{g up}")
    Sleep 573
    Send("{s down}")
    Sleep 391
    Send("{s up}")
    Sleep 26
    Send("{x down}")
    Sleep 234
    Send("{x up}")
    Sleep 182
    Send("{x down}")
    Sleep 326
    Send("{x up}")
    Sleep 91
    Send("{c down}")
    Sleep 4844
    Send("{c up}")
    Sleep 156
    Send("{c down}")
    Sleep 260
    Send("{c up}")
}
