#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{g down}")
    Send("{m down}")
    Sleep 39
    Send("{g up}")
    Sleep 9
    Send("{m up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 39
    Send("{g up}")
    Sleep 6
    Send("{m up}")
    Sleep 67
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 95
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 47
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 95
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 289
    Send("{g down}")
    Send("{m down}")
    Sleep 47
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 132
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Send("{m down}")
    Sleep 39
    Send("{m up}")
    Send("{g up}")
    Sleep 75
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 76
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 37
    Send("{g down}")
    Send("{m down}")
    Sleep 132
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 287
    Send("{g down}")
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 170
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 132
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 287
    Send("{g down}")
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 95
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{m up}")
    Send("{g up}")
    Sleep 43
    Send("{g down}")
    Send("{m down}")
    Sleep 127
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 95
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{m up}")
    Send("{g up}")
    Sleep 41
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 41
    Send("{m up}")
    Send("{g up}")
    Sleep 73
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 233
    Send("{g up}")
    Send("{m up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 170
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 41
    Send("{g down}")
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 289
    Send("{g down}")
    Send("{m down}")
    Sleep 47
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 146
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 132
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 95
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Send("{m down}")
    Sleep 39
    Send("{m up}")
    Send("{g up}")
    Sleep 75
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 41
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Send("{m down}")
    Sleep 41
    Send("{m up}")
    Send("{g up}")
    Sleep 75
    Send("{m down}")
    Send("{g down}")
    Sleep 233
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 41
    Send("{g down}")
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 39
    Send("{g up}")
    Sleep 7
    Send("{m up}")
    Sleep 67
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 95
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 39
    Send("{m up}")
    Send("{g up}")
    Sleep 75
    Send("{m down}")
    Send("{g down}")
    Sleep 233
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 4
    Send("{g up}")
    Sleep 95
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 132
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Sleep 4
    Send("{g down}")
    Sleep 231
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 299
    Send("{g down}")
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 233
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Send("{m down}")
    Sleep 41
    Send("{m up}")
    Send("{g up}")
    Sleep 73
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 82
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 299
    Send("{g down}")
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 95
    Send("{m down}")
    Send("{g down}")
    Sleep 170
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 75
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 95
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 4
    Send("{m down}")
    Sleep 127
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Sleep 4
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 287
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 47
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 7
    Send("{m up}")
    Sleep 291
    Send("{g down}")
    Send("{m down}")
    Sleep 39
    Send("{m up}")
    Send("{g up}")
    Sleep 76
    Send("{m down}")
    Send("{g down}")
    Sleep 233
    Send("{g up}")
    Send("{m up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 95
    Send("{m down}")
    Send("{g down}")
    Sleep 170
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 132
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 39
    Send("{g up}")
    Sleep 7
    Send("{m up}")
    Sleep 69
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 95
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 37
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 233
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 97
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 4
    Send("{m down}")
    Sleep 127
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 82
    Send("{g down}")
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 289
    Send("{g down}")
    Send("{m down}")
    Sleep 47
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 9
    Send("{m up}")
    Sleep 289
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 233
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 101
    Send("{m down}")
    Send("{g down}")
    Sleep 164
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 99
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 164
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 82
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 233
    Send("{g up}")
    Send("{m up}")
    Sleep 101
    Send("{m down}")
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 132
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 287
    Send("{g down}")
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 95
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 41
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Sleep 4
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 9
    Send("{m up}")
    Sleep 289
    Send("{g down}")
    Sleep 4
    Send("{m down}")
    Sleep 47
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 233
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{m up}")
    Send("{g up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 132
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 37
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 71
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 95
    Send("{m down}")
    Send("{g down}")
    Sleep 170
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 37
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Send("{m down}")
    Sleep 41
    Send("{g up}")
    Sleep 7
    Send("{m up}")
    Sleep 63
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 287
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 37
    Send("{g up}")
    Sleep 9
    Send("{m up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 97
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 164
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 299
    Send("{g down}")
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 233
    Send("{g up}")
    Send("{m up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 76
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 235
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 95
    Send("{m down}")
    Send("{g down}")
    Sleep 170
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 69
    Send("{m up}")
    Send("{g up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 6
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Send("{m down}")
    Sleep 47
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 289
    Send("{g down}")
    Send("{m down}")
    Sleep 43
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 149
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 49
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 101
    Send("{m down}")
    Send("{g down}")
    Sleep 164
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 151
    Send("{m up}")
    Send("{g up}")
    Sleep 76
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 41
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 11
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 285
    Send("{g down}")
    Send("{m down}")
    Sleep 50
    Send("{m up}")
    Send("{g up}")
    Sleep 65
    Send("{m down}")
    Send("{g down}")
    Sleep 235
    Send("{g up}")
    Send("{m up}")
    Sleep 97
    Send("{m down}")
    Send("{g down}")
    Sleep 170
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 67
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 37
    Send("{m up}")
    Send("{g up}")
    Sleep 75
    Send("{m down}")
    Send("{g down}")
    Sleep 233
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 97
    Send("{m down}")
    Sleep 2
    Send("{g down}")
    Sleep 166
    Send("{g up}")
    Sleep 19
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Send("{g up}")
    Sleep 78
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 129
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 80
    Send("{g down}")
    Sleep 4
    Send("{m down}")
    Sleep 146
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 295
    Send("{g down}")
    Sleep 4
    Send("{m down}")
    Sleep 47
    Send("{m up}")
    Send("{g up}")
    Sleep 63
    Send("{m down}")
    Send("{g down}")
    Sleep 237
    Send("{g up}")
    Send("{m up}")
    Sleep 99
    Send("{m down}")
    Send("{g down}")
    Sleep 168
    Send("{g up}")
    Sleep 17
    Send("{m up}")
    Sleep 147
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 147
    Send("{m up}")
    Send("{g up}")
    Sleep 80
    Send("{g down}")
    Send("{m down}")
    Sleep 65
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Send("{m down}")
    Sleep 131
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 82
    Send("{g down}")
    Send("{m down}")
    Sleep 149
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 297
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 384
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 60
    Send("{c down}")
    Send("{n down}")
    Sleep 345
    Send("{n up}")
    Sleep 4
    Send("{c up}")
    Sleep 97
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 373
    Send("{c up}")
    Sleep 7
    Send("{m up}")
    Sleep 1854
    Send("{n down}")
    Send("{c down}")
    Sleep 349
    Send("{n up}")
    Sleep 2
    Send("{c up}")
    Sleep 101
    Send("{g down}")
    Send("{m down}")
    Sleep 382
    Send("{g up}")
    Sleep 6
    Send("{m up}")
    Sleep 58
    Send("{c down}")
    Sleep 2
    Send("{n down}")
    Sleep 345
    Send("{n up}")
    Sleep 2
    Send("{c up}")
    Sleep 99
    Send("{c down}")
    Send("{m down}")
    Sleep 384
    Send("{m up}")
    Send("{c up}")
    Sleep 1853
    Send("{n down}")
    Send("{c down}")
    Sleep 353
    Send("{c up}")
    Send("{n up}")
    Sleep 99
    Send("{g down}")
    Send("{m down}")
    Sleep 384
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 58
    Send("{c down}")
    Sleep 2
    Send("{n down}")
    Sleep 336
    Send("{n up}")
    Sleep 13
    Send("{c up}")
    Sleep 97
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 382
    Send("{m up}")
    Send("{c up}")
    Sleep 1851
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 351
    Send("{c up}")
    Send("{n up}")
    Sleep 99
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 384
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 58
    Send("{c down}")
    Sleep 2
    Send("{n down}")
    Sleep 345
    Send("{n up}")
    Sleep 4
    Send("{c up}")
    Sleep 99
    Send("{c down}")
    Send("{m down}")
    Sleep 382
    Send("{m up}")
    Send("{c up}")
    Sleep 2302
    Send("{g down}")
    Send("{m down}")
    Sleep 636
    Send("{g up}")
    Sleep 9
    Send("{m up}")
    Sleep 24
    Send("{c down}")
    Send("{n down}")
    Sleep 651
    Send("{n up}")
    Send("{c up}")
    Sleep 22
    Send("{c down}")
    Sleep 222
    Send("{g down}")
    Sleep 19
    Send("{c up}")
    Sleep 166
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 662
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Send("{m down}")
    Send("{c down}")
    Sleep 1099
    Send("{m up}")
    Sleep 2
    Send("{c up}")
    Sleep 21
    Send("{g down}")
    Send("{m down}")
    Sleep 646
    Send("{m up}")
    Send("{g up}")
    Sleep 24
    Send("{c down}")
    Send("{n down}")
    Sleep 651
    Send("{c up}")
    Sleep 2
    Send("{n up}")
    Sleep 21
    Send("{c down}")
    Sleep 222
    Send("{g down}")
    Sleep 19
    Send("{c up}")
    Sleep 166
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Send("{c down}")
    Sleep 664
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Sleep 4
    Send("{m down}")
    Send("{c down}")
    Sleep 1095
    Send("{m up}")
    Sleep 2
    Send("{c up}")
    Sleep 19
    Send("{g down}")
    Send("{m down}")
    Sleep 647
    Send("{m up}")
    Send("{g up}")
    Sleep 26
    Send("{c down}")
    Send("{n down}")
    Sleep 649
    Send("{n up}")
    Send("{c up}")
    Sleep 21
    Send("{c down}")
    Sleep 224
    Send("{g down}")
    Sleep 19
    Send("{c up}")
    Sleep 166
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Send("{c down}")
    Sleep 666
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Sleep 2
    Send("{m down}")
    Send("{c down}")
    Sleep 1099
    Send("{c up}")
    Send("{m up}")
    Sleep 19
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 646
    Send("{m up}")
    Send("{g up}")
    Sleep 28
    Send("{c down}")
    Send("{n down}")
    Sleep 647
    Send("{n up}")
    Send("{c up}")
    Sleep 22
    Send("{c down}")
    Sleep 224
    Send("{g down}")
    Sleep 17
    Send("{c up}")
    Sleep 166
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 662
    Send("{n up}")
    Sleep 4
    Send("{c up}")
    Sleep 4
    Send("{m down}")
    Send("{c down}")
    Sleep 1097
    Send("{m up}")
    Sleep 15
    Send("{c up}")
    Sleep 6
    Send("{g down}")
    Sleep 4
    Send("{m down}")
    Sleep 3573
    Send("{g up}")
    Send("{m up}")
    Sleep 7
    Send("{m down}")
    Send("{g down}")
    Sleep 3575
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 6
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 220
    Send("{c down}")
    Sleep 2
    Send("{n down}")
    Sleep 32
    Send("{g up}")
    Sleep 21
    Send("{m up}")
    Sleep 164
    Send("{n up}")
    Sleep 21
    Send("{c up}")
    Sleep 209
    Send("{g down}")
    Send("{m down}")
    Sleep 2774
    Send("{m up}")
    Sleep 2
    Send("{g up}")
    Sleep 136
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 220
    Send("{c down}")
    Send("{n down}")
    Sleep 34
    Send("{g up}")
    Sleep 21
    Send("{m up}")
    Sleep 164
    Send("{n up}")
    Sleep 22
    Send("{c up}")
    Sleep 207
    Send("{g down}")
    Send("{m down}")
    Sleep 2765
    Send("{m up}")
    Sleep 9
    Send("{g up}")
    Sleep 136
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 651
    Send("{m up}")
    Sleep 2
    Send("{c up}")
    Sleep 17
    Send("{g down}")
    Send("{m down}")
    Sleep 446
    Send("{c down}")
    Sleep 43
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 170
    Send("{g down}")
    Sleep 15
    Send("{c up}")
    Sleep 209
    Send("{n down}")
    Send("{c down}")
    Sleep 52
    Send("{g up}")
    Sleep 149
    Send("{c up}")
    Sleep 2
    Send("{n up}")
    Sleep 21
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 614
    Send("{c up}")
    Sleep 17
    Send("{n up}")
    Sleep 39
    Send("{m down}")
    Send("{c down}")
    Sleep 1118
    Send("{c up}")
    Send("{m up}")
    Sleep 2
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 664
    Send("{m up}")
    Send("{c up}")
    Sleep 4
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 446
    Send("{c down}")
    Sleep 52
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 170
    Send("{g down}")
    Sleep 15
    Send("{c up}")
    Sleep 207
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 52
    Send("{g up}")
    Sleep 147
    Send("{c up}")
    Sleep 4
    Send("{n up}")
    Sleep 21
    Send("{n down}")
    Send("{c down}")
    Sleep 616
    Send("{c up}")
    Sleep 15
    Send("{n up}")
    Sleep 41
    Send("{m down}")
    Send("{c down}")
    Sleep 1116
    Send("{c up}")
    Send("{m up}")
    Sleep 4
    Send("{c down}")
    Send("{m down}")
    Sleep 666
    Send("{m up}")
    Send("{c up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Sleep 448
    Send("{c down}")
    Sleep 50
    Send("{g up}")
    Sleep 4
    Send("{m up}")
    Sleep 170
    Send("{g down}")
    Sleep 13
    Send("{c up}")
    Sleep 211
    Send("{n down}")
    Send("{c down}")
    Sleep 50
    Send("{g up}")
    Sleep 151
    Send("{c up}")
    Sleep 4
    Send("{n up}")
    Sleep 19
    Send("{n down}")
    Send("{c down}")
    Sleep 618
    Send("{c up}")
    Sleep 15
    Send("{n up}")
    Sleep 37
    Send("{m down}")
    Send("{c down}")
    Sleep 1119
    Send("{c up}")
    Send("{m up}")
    Sleep 2
    Send("{c down}")
    Send("{m down}")
    Sleep 666
    Send("{m up}")
    Send("{c up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Sleep 446
    Send("{c down}")
    Sleep 52
    Send("{g up}")
    Sleep 6
    Send("{m up}")
    Sleep 166
    Send("{g down}")
    Sleep 17
    Send("{c up}")
    Sleep 207
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 52
    Send("{g up}")
    Sleep 149
    Send("{c up}")
    Sleep 2
    Send("{n up}")
    Sleep 21
    Send("{n down}")
    Send("{c down}")
    Sleep 616
    Send("{c up}")
    Sleep 15
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 1119
    Send("{g down}")
    Send("{m down}")
    Sleep 21
    Send("{m up}")
    Sleep 15
    Send("{c up}")
    Sleep 578
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 45
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 291
    Send("{c up}")
    Send("{n up}")
    Sleep 2618
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 612
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 43
    Send("{n down}")
    Send("{c down}")
    Sleep 293
    Send("{c up}")
    Send("{n up}")
    Sleep 2618
    Send("{g down}")
    Send("{m down}")
    Sleep 614
    Send("{g up}")
    Sleep 7
    Send("{m up}")
    Sleep 50
    Send("{n down}")
    Send("{c down}")
    Sleep 293
    Send("{c up}")
    Send("{n up}")
    Sleep 2619
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 610
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 43
    Send("{n down}")
    Send("{c down}")
    Sleep 282
    Send("{c up}")
    Send("{n up}")
    Sleep 6213
    Send("{g down}")
    Send("{m down}")
    Sleep 636
    Send("{g up}")
    Sleep 9
    Send("{m up}")
    Sleep 26
    Send("{c down}")
    Send("{n down}")
    Sleep 649
    Send("{c up}")
    Sleep 2
    Send("{n up}")
    Sleep 21
    Send("{c down}")
    Sleep 224
    Send("{g down}")
    Sleep 17
    Send("{c up}")
    Sleep 166
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 664
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Sleep 4
    Send("{m down}")
    Send("{c down}")
    Sleep 1097
    Send("{m up}")
    Sleep 13
    Send("{c up}")
    Sleep 6
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 646
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 24
    Send("{c down}")
    Send("{n down}")
    Sleep 649
    Send("{n up}")
    Send("{c up}")
    Sleep 22
    Send("{c down}")
    Sleep 222
    Send("{g down}")
    Sleep 19
    Send("{c up}")
    Sleep 166
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Send("{c down}")
    Sleep 666
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 1097
    Send("{m up}")
    Sleep 2
    Send("{c up}")
    Sleep 21
    Send("{g down}")
    Send("{m down}")
    Sleep 636
    Send("{m up}")
    Send("{g up}")
    Sleep 34
    Send("{c down}")
    Send("{n down}")
    Sleep 651
    Send("{n up}")
    Send("{c up}")
    Sleep 24
    Send("{c down}")
    Sleep 220
    Send("{g down}")
    Sleep 21
    Send("{c up}")
    Sleep 164
    Send("{g up}")
    Sleep 43
    Send("{n down}")
    Send("{c down}")
    Sleep 664
    Send("{n up}")
    Sleep 2
    Send("{c up}")
    Sleep 4
    Send("{m down}")
    Send("{c down}")
    Sleep 1097
    Send("{m up}")
    Sleep 15
    Send("{c up}")
    Sleep 6
    Send("{g down}")
    Sleep 4
    Send("{m down}")
    Sleep 644
    Send("{m up}")
    Send("{g up}")
    Sleep 24
    Send("{c down}")
    Send("{n down}")
    Sleep 651
    Send("{c up}")
    Sleep 2
    Send("{n up}")
    Sleep 19
    Send("{c down}")
    Sleep 226
    Send("{g down}")
    Sleep 17
    Send("{c up}")
    Sleep 166
    Send("{g up}")
    Sleep 43
    Send("{n down}")
    Send("{c down}")
    Sleep 662
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 1097
    Send("{m up}")
    Sleep 2
    Send("{c up}")
    Sleep 19
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 1080
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 24
    Send("{g down}")
    Sleep 201
    Send("{g up}")
    Sleep 24
    Send("{h down}")
    Sleep 162
    Send("{h up}")
    Sleep 60
    Send("{m down}")
    Send("{c down}")
    Sleep 1897
    Send("{m up}")
    Sleep 19
    Send("{c up}")
    Sleep 99
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 1080
    Send("{g up}")
    Sleep 15
    Send("{m up}")
    Sleep 22
    Send("{g down}")
    Sleep 201
    Send("{g up}")
    Sleep 22
    Send("{h down}")
    Sleep 164
    Send("{h up}")
    Sleep 60
    Send("{m down}")
    Send("{c down}")
    Sleep 1897
    Send("{m up}")
    Sleep 19
    Send("{c up}")
    Sleep 101
    Send("{g down}")
    Send("{m down}")
    Sleep 1082
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 26
    Send("{g down}")
    Sleep 198
    Send("{g up}")
    Sleep 24
    Send("{h down}")
    Sleep 164
    Send("{h up}")
    Sleep 60
    Send("{m down}")
    Send("{c down}")
    Sleep 1896
    Send("{m up}")
    Sleep 9
    Send("{c up}")
    Sleep 110
    Send("{g down}")
    Send("{m down}")
    Sleep 1080
    Send("{g up}")
    Sleep 13
    Send("{m up}")
    Sleep 26
    Send("{g down}")
    Sleep 198
    Send("{g up}")
    Sleep 24
    Send("{h down}")
    Sleep 162
    Send("{h up}")
    Sleep 62
    Send("{m down}")
    Send("{c down}")
    Sleep 1899
    Send("{m up}")
    Sleep 7
    Send("{c up}")
    Sleep 112
    Send("{g down}")
    Send("{m down}")
    Sleep 644
    Send("{m up}")
    Send("{g up}")
    Sleep 24
    Send("{c down}")
    Send("{n down}")
    Sleep 651
    Send("{n up}")
    Send("{c up}")
    Sleep 21
    Send("{c down}")
    Sleep 224
    Send("{g down}")
    Sleep 19
    Send("{c up}")
    Sleep 166
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 662
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Sleep 2
    Send("{m down}")
    Send("{c down}")
    Sleep 1097
    Send("{m up}")
    Sleep 2
    Send("{c up}")
    Sleep 21
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 634
    Send("{g up}")
    Sleep 9
    Send("{m up}")
    Sleep 24
    Send("{c down}")
    Send("{n down}")
    Sleep 651
    Send("{n up}")
    Send("{c up}")
    Sleep 21
    Send("{c down}")
    Sleep 224
    Send("{g down}")
    Sleep 19
    Send("{c up}")
    Sleep 168
    Send("{g up}")
    Sleep 37
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 664
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Sleep 4
    Send("{m down}")
    Send("{c down}")
    Sleep 1097
    Send("{c up}")
    Send("{m up}")
    Sleep 21
    Send("{g down}")
    Send("{m down}")
    Sleep 646
    Send("{m up}")
    Send("{g up}")
    Sleep 28
    Send("{c down}")
    Send("{n down}")
    Sleep 649
    Send("{n up}")
    Send("{c up}")
    Sleep 21
    Send("{c down}")
    Sleep 222
    Send("{g down}")
    Sleep 21
    Send("{c up}")
    Sleep 164
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Send("{c down}")
    Sleep 666
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Sleep 2
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 1095
    Send("{m up}")
    Sleep 2
    Send("{c up}")
    Sleep 19
    Send("{g down}")
    Send("{m down}")
    Sleep 647
    Send("{m up}")
    Send("{g up}")
    Sleep 24
    Send("{c down}")
    Sleep 2
    Send("{n down}")
    Sleep 649
    Send("{n up}")
    Send("{c up}")
    Sleep 21
    Send("{c down}")
    Sleep 224
    Send("{g down}")
    Sleep 21
    Send("{c up}")
    Sleep 164
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Send("{c down}")
    Sleep 666
    Send("{n up}")
    Sleep 4
    Send("{c up}")
    Sleep 4
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 1097
    Send("{m up}")
    Sleep 13
    Send("{c up}")
    Sleep 9
    Send("{g down}")
    Send("{m down}")
    Sleep 644
    Send("{m up}")
    Send("{g up}")
    Sleep 24
    Send("{c down}")
    Send("{n down}")
    Sleep 651
    Send("{n up}")
    Send("{c up}")
    Sleep 22
    Send("{c down}")
    Sleep 224
    Send("{g down}")
    Sleep 19
    Send("{c up}")
    Sleep 164
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Send("{c down}")
    Sleep 664
    Send("{n up}")
    Sleep 4
    Send("{c up}")
    Sleep 2
    Send("{m down}")
    Send("{c down}")
    Sleep 1099
    Send("{m up}")
    Sleep 15
    Send("{c up}")
    Sleep 6
    Send("{g down}")
    Sleep 4
    Send("{m down}")
    Sleep 642
    Send("{g up}")
    Sleep 2
    Send("{m up}")
    Sleep 24
    Send("{c down}")
    Send("{n down}")
    Sleep 651
    Send("{c up}")
    Sleep 2
    Send("{n up}")
    Sleep 22
    Send("{c down}")
    Sleep 220
    Send("{g down}")
    Sleep 19
    Send("{c up}")
    Sleep 166
    Send("{g up}")
    Sleep 43
    Send("{n down}")
    Send("{c down}")
    Sleep 662
    Send("{n up}")
    Sleep 4
    Send("{c up}")
    Sleep 4
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 1095
    Send("{m up}")
    Sleep 15
    Send("{c up}")
    Sleep 6
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 646
    Send("{m up}")
    Send("{g up}")
    Sleep 24
    Send("{c down}")
    Send("{n down}")
    Sleep 651
    Send("{n up}")
    Send("{c up}")
    Sleep 21
    Send("{c down}")
    Sleep 226
    Send("{g down}")
    Sleep 17
    Send("{c up}")
    Sleep 168
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Sleep 2
    Send("{c down}")
    Sleep 662
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Sleep 2
    Send("{c down}")
    Sleep 2
    Send("{m down}")
    Sleep 1095
    Send("{m up}")
    Sleep 2
    Send("{c up}")
    Sleep 19
    Send("{g down}")
    Sleep 2
    Send("{m down}")
    Sleep 646
    Send("{m up}")
    Send("{g up}")
    Sleep 26
    Send("{c down}")
    Sleep 2
    Send("{n down}")
    Sleep 647
    Send("{c up}")
    Sleep 2
    Send("{n up}")
    Sleep 21
    Send("{c down}")
    Sleep 224
    Send("{g down}")
    Sleep 17
    Send("{c up}")
    Sleep 166
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Send("{c down}")
    Sleep 666
    Send("{n up}")
    Sleep 6
    Send("{c up}")
    Sleep 4
    Send("{m down}")
    Send("{c down}")
    Sleep 1095
    Send("{m up}")
    Sleep 4
    Send("{c up}")
    Sleep 19
    Send("{m down}")
    Send("{g down}")
    Sleep 4039
    Send("{g up}")
    Send("{m up}")
    Sleep 7
    Send("{m down}")
    Send("{g down}")
    Sleep 5234
    Send("{g up}")
    Send("{m up}")
    Sleep 9
    Send("{g down}")
    Send("{m down}")
    Sleep 359
    Send("{m up}")
    Send("{g up}")
}
