#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 142
    Send("{m up}")
    Sleep 82
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 82
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 132
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 91
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 132
    Send("{m up}")
    Sleep 91
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 91
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 142
    Send("{m up}")
    Sleep 82
    Send("{m down}")
    Sleep 142
    Send("{m up}")
    Sleep 82
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 132
    Send("{m up}")
    Sleep 91
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 142
    Send("{m up}")
    Sleep 75
    Send("{m down}")
    Sleep 153
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 91
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 132
    Send("{m up}")
    Sleep 91
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 91
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 424
    Send("{m up}")
    Sleep 26
    Send("{n down}")
    Sleep 446
    Send("{c down}")
    Sleep 4
    Send("{n up}")
    Sleep 4
    Send("{n down}")
    Sleep 7
    Send("{n up}")
    Sleep 317
    Send("{c up}")
    Sleep 1905
    Send("{n down}")
    Sleep 373
    Send("{n up}")
    Sleep 78
    Send("{m down}")
    Sleep 422
    Send("{m up}")
    Sleep 24
    Send("{n down}")
    Sleep 448
    Send("{c down}")
    Sleep 2
    Send("{n up}")
    Sleep 6
    Send("{n down}")
    Sleep 9
    Send("{n up}")
    Sleep 313
    Send("{c up}")
    Sleep 1907
    Send("{n down}")
    Sleep 373
    Send("{n up}")
    Sleep 78
    Send("{m down}")
    Sleep 424
    Send("{m up}")
    Sleep 22
    Send("{n down}")
    Sleep 448
    Send("{n up}")
    Sleep 2
    Send("{c down}")
    Sleep 4
    Send("{n down}")
    Sleep 9
    Send("{n up}")
    Sleep 315
    Send("{c up}")
    Sleep 1897
    Send("{n down}")
    Sleep 382
    Send("{n up}")
    Sleep 76
    Send("{m down}")
    Sleep 425
    Send("{m up}")
    Sleep 22
    Send("{n down}")
    Sleep 448
    Send("{c down}")
    Sleep 4
    Send("{n up}")
    Sleep 6
    Send("{n down}")
    Sleep 4
    Send("{n up}")
    Sleep 319
    Send("{c up}")
    Sleep 2354
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 28
    Send("{g down}")
    Sleep 196
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{g down}")
    Sleep 183
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 37
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{g down}")
    Sleep 183
    Send("{g up}")
    Sleep 43
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{g down}")
    Sleep 181
    Send("{g up}")
    Sleep 43
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 142
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 82
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 132
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 91
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 187
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 43
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{g down}")
    Sleep 181
    Send("{g up}")
    Sleep 43
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 187
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 187
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{g down}")
    Sleep 183
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{g down}")
    Sleep 183
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 37
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{g down}")
    Sleep 185
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 30
    Send("{n down}")
    Sleep 196
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 91
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 84
    Send("{m down}")
    Sleep 140
    Send("{m up}")
    Sleep 86
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 144
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 80
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 136
    Send("{m up}")
    Sleep 88
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 146
    Send("{m up}")
    Sleep 78
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 90
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{g down}")
    Sleep 181
    Send("{g up}")
    Sleep 43
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{g down}")
    Sleep 183
    Send("{g up}")
    Sleep 43
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{g down}")
    Sleep 185
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 37
    Send("{n down}")
    Sleep 187
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{g down}")
    Sleep 183
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 37
    Send("{n down}")
    Sleep 187
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 43
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{g down}")
    Sleep 181
    Send("{g up}")
    Sleep 43
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 37
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{g down}")
    Sleep 181
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 37
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 185
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 187
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 187
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{g down}")
    Sleep 185
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{g down}")
    Sleep 183
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 43
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 43
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{g down}")
    Sleep 185
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{g down}")
    Sleep 183
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{g down}")
    Sleep 183
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 43
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{n down}")
    Sleep 187
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{g down}")
    Sleep 185
    Send("{g up}")
    Sleep 39
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 43
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{g down}")
    Sleep 183
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 39
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 43
    Send("{n down}")
    Sleep 181
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{g down}")
    Sleep 185
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{m down}")
    Sleep 185
    Send("{m up}")
    Sleep 41
    Send("{m down}")
    Sleep 181
    Send("{m up}")
    Sleep 43
    Send("{m down}")
    Sleep 183
    Send("{m up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 39
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 43
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{g down}")
    Sleep 181
    Send("{g up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 183
    Send("{n up}")
    Sleep 41
    Send("{n down}")
    Sleep 185
    Send("{n up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 181
    Send("{c up}")
    Sleep 43
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{c down}")
    Sleep 183
    Send("{c up}")
    Sleep 41
    Send("{c down}")
    Sleep 185
    Send("{c up}")
    Sleep 39
    Send("{m down}")
    Sleep 4036
    Send("{m up}")
    Sleep 12
    Send("{m down}")
    Sleep 5228
    Send("{m up}")
    Sleep 12
    Send("{m down}")
    Sleep 362
    Send("{m up}")
}
