#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{x down}")
    Sleep 919
    Send("{x up}")
    Sleep 465
    Send("{v down}")
    Sleep 919
    Send("{v up}")
    Sleep 465
    Send("{c down}")
    Sleep 919
    Send("{c up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{x down}")
    Sleep 919
    Send("{x up}")
    Sleep 465
    Send("{v down}")
    Sleep 919
    Send("{v up}")
    Sleep 465
    Send("{c down}")
    Sleep 919
    Send("{c up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{x down}")
    Sleep 919
    Send("{x up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{x down}")
    Sleep 919
    Send("{x up}")
    Sleep 465
    Send("{z down}")
    Sleep 919
    Send("{z up}")
    Sleep 465
    Send("{v down}")
    Sleep 919
    Send("{v up}")
    Sleep 465
    Send("{c down}")
    Sleep 919
    Send("{c up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{b down}")
    Sleep 919
    Send("{b up}")
    Sleep 465
    Send("{z down}")
    Sleep 919
    Send("{z up}")
    Sleep 465
    Send("{j down}")
    Sleep 919
    Send("{j up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{q down}")
    Sleep 919
    Send("{q up}")
    Sleep 465
    Send("{m down}")
    Sleep 919
    Send("{m up}")
    Sleep 465
    Send("{j down}")
    Sleep 919
    Send("{j up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{s down}")
    Sleep 1381
    Send("{s up}")
    Sleep 4
    Send("{n down}")
    Sleep 1381
    Send("{n up}")
    Sleep 4
    Send("{x down}")
    Sleep 1381
    Send("{x up}")
    Sleep 4
    Send("{n down}")
    Sleep 1381
    Send("{n up}")
    Sleep 4
    Send("{c down}")
    Sleep 919
    Send("{c up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{v down}")
    Sleep 919
    Send("{v up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{b down}")
    Send("{7 down}")
    Send("{3 down}")
    Sleep 919
    Send("{3 up}")
    Send("{7 up}")
    Send("{b up}")
    Sleep 465
    Send("{b down}")
    Send("{7 down}")
    Send("{3 down}")
    Sleep 919
    Send("{3 up}")
    Send("{7 up}")
    Send("{b up}")
    Sleep 465
    Send("{3 down}")
    Send("{h down}")
    Send("{7 down}")
    Send("{e down}")
    Sleep 919
    Send("{e up}")
    Send("{3 up}")
    Send("{h up}")
    Send("{7 up}")
    Sleep 465
    Send("{h down}")
    Send("{7 down}")
    Send("{w down}")
    Sleep 919
    Send("{w up}")
    Send("{7 up}")
    Send("{h up}")
    Sleep 465
    Send("{n down}")
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 919
    Send("{y up}")
    Send("{n up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 465
    Send("{n down}")
    Send("{w down}")
    Send("{y down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Send("{y up}")
    Send("{n up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 4
    Send("{2 down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 458
    Send("{t up}")
    Send("{e up}")
    Send("{2 up}")
    Sleep 4
    Send("{j down}")
    Send("{e down}")
    Send("{r down}")
    Sleep 919
    Send("{r up}")
    Send("{e up}")
    Send("{j up}")
    Sleep 465
    Send("{j down}")
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 919
    Send("{r up}")
    Send("{j up}")
    Send("{7 up}")
    Send("{w up}")
    Sleep 4
    Send("{6 down}")
    Send("{r down}")
    Send("{w down}")
    Sleep 458
    Send("{w up}")
    Send("{r up}")
    Send("{6 up}")
    Sleep 4
    Send("{m down}")
    Send("{w down}")
    Send("{r down}")
    Send("{6 down}")
    Sleep 919
    Send("{6 up}")
    Send("{m up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 465
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 458
    Send("{t up}")
    Sleep 4
    Send("{r down}")
    Sleep 458
    Send("{r up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 465
    Send("{z down}")
    Send("{r down}")
    Send("{t down}")
    Send("{b down}")
    Sleep 919
    Send("{b up}")
    Send("{z up}")
    Send("{r up}")
    Send("{t up}")
    Sleep 465
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 919
    Send("{t up}")
    Send("{e up}")
    Send("{q up}")
    Sleep 465
    Send("{2 down}")
    Send("{e down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 919
    Send("{7 up}")
    Send("{2 up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 465
    Send("{s down}")
    Send("{e down}")
    Send("{y down}")
    Send("{e down}")
    Sleep 919
    Send("{e up}")
    Send("{s up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 465
    Send("{x down}")
    Send("{b down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 919
    Send("{t up}")
    Send("{x up}")
    Send("{b up}")
    Send("{e up}")
    Sleep 465
    Send("{w down}")
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 919
    Send("{y up}")
    Send("{w up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 465
    Send("{w down}")
    Send("{6 down}")
    Send("{u down}")
    Send("{r down}")
    Sleep 919
    Send("{r up}")
    Send("{w up}")
    Send("{6 up}")
    Send("{u up}")
    Sleep 465
    Send("{q down}")
    Send("{r down}")
    Send("{6 down}")
    Send("{q down}")
    Sleep 919
    Send("{q up}")
    Send("{q up}")
    Send("{r up}")
    Send("{6 up}")
    Sleep 465
    Send("{m down}")
    Send("{r down}")
    Send("{w down}")
    Send("{6 down}")
    Sleep 919
    Send("{6 up}")
    Send("{m up}")
    Send("{r up}")
    Send("{w up}")
    Sleep 465
    Send("{m down}")
    Send("{w down}")
    Send("{6 down}")
    Send("{r down}")
    Sleep 919
    Send("{r up}")
    Send("{m up}")
    Send("{w up}")
    Send("{6 up}")
    Sleep 465
    Send("{m down}")
    Send("{w down}")
    Send("{6 down}")
    Send("{r down}")
    Sleep 919
    Send("{r up}")
    Send("{m up}")
    Send("{w up}")
    Send("{6 up}")
    Sleep 465
    Send("{q down}")
    Send("{r down}")
    Send("{6 down}")
    Send("{q down}")
    Sleep 919
    Send("{q up}")
    Send("{q up}")
    Send("{r up}")
    Send("{6 up}")
    Sleep 465
    Send("{2 down}")
    Send("{r down}")
    Send("{6 down}")
    Send("{u down}")
    Sleep 919
    Send("{u up}")
    Send("{2 up}")
    Send("{r up}")
    Send("{6 up}")
    Sleep 465
    Send("{2 down}")
    Send("{r down}")
    Send("{6 down}")
    Send("{u down}")
    Sleep 919
    Send("{u up}")
    Send("{2 up}")
    Send("{r up}")
    Send("{6 up}")
    Sleep 465
    Send("{w down}")
    Send("{r down}")
    Send("{t down}")
    Send("{u down}")
    Sleep 919
    Send("{u up}")
    Send("{w up}")
    Send("{r up}")
    Send("{t up}")
    Sleep 465
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Send("{q down}")
    Sleep 919
    Send("{q up}")
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 465
    Send("{j down}")
    Send("{w down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 919
    Send("{t up}")
    Send("{j up}")
    Send("{w up}")
    Send("{e up}")
    Sleep 465
    Send("{n down}")
    Send("{q down}")
    Send("{r down}")
    Send("{q down}")
    Sleep 919
    Send("{q up}")
    Send("{n up}")
    Send("{q up}")
    Send("{r up}")
    Sleep 465
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 919
    Send("{r up}")
    Send("{w up}")
    Send("{j up}")
    Sleep 465
    Send("{x down}")
    Send("{r down}")
    Send("{6 down}")
    Send("{u down}")
    Sleep 919
    Send("{u up}")
    Send("{x up}")
    Send("{r up}")
    Send("{6 up}")
    Sleep 465
    Send("{z down}")
    Send("{r down}")
    Send("{y down}")
    Send("{q down}")
    Sleep 919
    Send("{q up}")
    Send("{z up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 465
    Send("{z down}")
    Send("{e down}")
    Send("{t down}")
    Send("{q down}")
    Sleep 919
    Send("{q up}")
    Send("{z up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 465
    Send("{v down}")
    Sleep 919
    Send("{v up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{j down}")
    Sleep 919
    Send("{j up}")
    Sleep 465
    Send("{z down}")
    Sleep 919
    Send("{z up}")
    Sleep 465
    Send("{j down}")
    Sleep 919
    Send("{j up}")
    Sleep 465
    Send("{x down}")
    Sleep 919
    Send("{x up}")
    Sleep 465
    Send("{z down}")
    Sleep 919
    Send("{z up}")
    Sleep 465
    Send("{z down}")
    Sleep 919
    Send("{z up}")
    Sleep 465
    Send("{v down}")
    Sleep 919
    Send("{v up}")
    Sleep 465
    Send("{v down}")
    Sleep 919
    Send("{v up}")
    Sleep 465
    Send("{c down}")
    Sleep 919
    Send("{c up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{x down}")
    Sleep 919
    Send("{x up}")
    Sleep 465
    Send("{v down}")
    Sleep 919
    Send("{v up}")
    Sleep 465
    Send("{c down}")
    Sleep 919
    Send("{c up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{x down}")
    Sleep 919
    Send("{x up}")
    Sleep 465
    Send("{v down}")
    Sleep 919
    Send("{v up}")
    Sleep 465
    Send("{c down}")
    Sleep 919
    Send("{c up}")
    Sleep 465
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Sleep 465
    Send("{x down}")
    Sleep 919
    Send("{x up}")
    Sleep 465
    Send("{g down}")
    Sleep 919
    Send("{g up}")
    Sleep 465
    Send("{b down}")
    Sleep 919
    Send("{b up}")
    Sleep 465
    Send("{x down}")
    Sleep 919
    Send("{x up}")
    Sleep 465
    Send("{d down}")
    Send("{t down}")
    Send("{7 down}")
    Send("{3 down}")
    Sleep 919
    Send("{3 up}")
    Send("{d up}")
    Send("{t up}")
    Send("{7 up}")
    Sleep 465
    Send("{z down}")
    Send("{3 down}")
    Send("{t down}")
    Send("{y down}")
    Sleep 919
    Send("{y up}")
    Send("{z up}")
    Send("{3 up}")
    Send("{t up}")
    Sleep 465
    Send("{s down}")
    Send("{e down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 919
    Send("{7 up}")
    Send("{s up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 465
    Send("{x down}")
    Send("{r down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 919
    Send("{w up}")
    Send("{x up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 465
    Send("{b down}")
    Send("{j down}")
    Send("{w down}")
    Send("{e down}")
    Sleep 919
    Send("{e up}")
    Send("{b up}")
    Send("{j up}")
    Send("{w up}")
    Sleep 465
    Send("{h down}")
    Send("{r down}")
    Send("{w down}")
    Send("{j down}")
    Sleep 919
    Send("{j up}")
    Send("{h up}")
    Send("{r up}")
    Send("{w up}")
    Sleep 465
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Send("{n up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 465
    Send("{n down}")
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Send("{n up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 465
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Send("{n up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 465
    Send("{n down}")
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Send("{n up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 465
    Send("{n down}")
    Send("{n down}")
    Send("{w down}")
    Send("{e down}")
    Sleep 919
    Send("{e up}")
    Send("{n up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 465
    Send("{n down}")
    Send("{e down}")
    Send("{2 down}")
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Send("{n up}")
    Send("{e up}")
    Send("{2 up}")
    Sleep 465
    Send("{x down}")
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 919
    Send("{w up}")
    Send("{x up}")
    Send("{v up}")
    Send("{n up}")
    Sleep 465
    Send("{x down}")
    Send("{g down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 919
    Send("{w up}")
    Send("{x up}")
    Send("{g up}")
    Send("{n up}")
    Sleep 465
    Send("{w down}")
    Send("{x down}")
    Send("{g down}")
    Send("{n down}")
    Sleep 919
    Send("{n up}")
    Send("{w up}")
    Send("{x up}")
    Send("{g up}")
    Sleep 465
    Send("{x down}")
    Send("{g down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 919
    Send("{w up}")
    Send("{x up}")
    Send("{g up}")
    Send("{n up}")
    Sleep 465
    Send("{b down}")
    Send("{j down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 919
    Send("{t up}")
    Send("{b up}")
    Send("{j up}")
    Send("{w up}")
    Sleep 465
    Send("{x down}")
    Send("{t down}")
    Send("{j down}")
    Send("{w down}")
    Sleep 919
    Send("{w up}")
    Send("{x up}")
    Send("{t up}")
    Send("{j up}")
    Sleep 465
    Send("{j down}")
    Send("{w down}")
    Send("{t down}")
    Send("{j down}")
    Sleep 919
    Send("{j up}")
    Send("{j up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 465
    Send("{b down}")
    Send("{j down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 919
    Send("{t up}")
    Send("{b up}")
    Send("{j up}")
    Send("{w up}")
    Sleep 465
    Send("{x down}")
    Send("{5 down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 5535
    Send("{n up}")
    Send("{x up}")
    Send("{5 up}")
    Send("{w up}")
}
