#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Sleep 15652
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Sleep 130
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Sleep 130
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Sleep 130
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Sleep 130
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{h down}")
    Send("{n down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{n up}")
    Send("{h up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{h down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Sleep 130
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{n down}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Send("{n up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z down}")
    Send("{s down}")
    Sleep 130
    Send("{s up}")
    Send("{z up}")
    Send("{h down}")
    Send("{c down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c up}")
    Send("{h up}")
    Send("{n down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{n up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{s down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{s up}")
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Send("{n down}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{n up}")
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{s down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{s up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{c down}")
    Send("{n down}")
    Sleep 130
    Send("{c up}")
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{n up}")
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{n down}")
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{n down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{n up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{c down}")
    Send("{z down}")
    Send("{s down}")
    Sleep 130
    Send("{s up}")
    Send("{z up}")
    Send("{c up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{n down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{n up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{n up}")
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{n down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{n up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{c down}")
    Send("{z down}")
    Send("{s down}")
    Sleep 130
    Send("{s up}")
    Send("{z up}")
    Send("{c up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{n down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{n up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{n down}")
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{n down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{n up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{c down}")
    Send("{z down}")
    Send("{s down}")
    Sleep 130
    Send("{s up}")
    Send("{z up}")
    Send("{c up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{n down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Send("{c down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{n up}")
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{h down}")
    Send("{z down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{c down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{c down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z down}")
    Send("{h down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{h up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{c down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{c down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{h up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{c down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{c down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Sleep 130
    Send("{c down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{z down}")
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 130
    Send("{h down}")
    Sleep 130
    Send("{h up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Sleep 3261
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Sleep 130
    Send("{s down}")
    Sleep 130
    Send("{s up}")
    Sleep 130
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Sleep 130
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{n down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{n up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{s down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{s up}")
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Send("{n down}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{n up}")
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{n down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{n up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{s down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{s up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{n down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{n up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{s down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{s up}")
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Send("{n down}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{n up}")
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{n down}")
    Send("{j down}")
    Send("{z down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{z up}")
    Send("{j up}")
    Send("{n up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j up}")
    Sleep 130
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{z down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{z up}")
    Send("{c down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{c up}")
    Send("{s down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{z up}")
    Send("{s up}")
    Send("{j down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{j up}")
    Send("{c down}")
    Send("{n down}")
    Sleep 130
    Send("{c up}")
    Send("{c down}")
    Send("{z down}")
    Send("{j down}")
    Sleep 130
    Send("{n up}")
    Send("{j up}")
    Send("{z up}")
    Send("{c up}")
}
