#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Sleep 8348
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{j down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{j up}")
    Send("{j down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{j up}")
    Send("{j down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{j up}")
    Send("{j down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{j up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{x up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{m up}")
    Send("{m down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{m up}")
    Send("{j down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{j up}")
    Send("{j down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{j up}")
    Send("{j down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{j up}")
    Send("{j down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{j up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{z up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 130
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{s up}")
    Send("{h up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 130
    Send("{h up}")
    Send("{s up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{s up}")
    Send("{h up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{j up}")
    Send("{d up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 130
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{s up}")
    Send("{h up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{s up}")
    Send("{h up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 130
    Send("{s up}")
    Send("{h up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{d down}")
    Send("{j down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{d down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{d up}")
    Send("{d down}")
    Send("{j down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{d down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{d up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 130
    Send("{s up}")
    Send("{h up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{s up}")
    Send("{h up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{j up}")
    Send("{d up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 130
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 261
    Send("{s up}")
    Send("{h up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{s up}")
    Send("{h up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 130
    Send("{s up}")
    Send("{h up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{j up}")
    Send("{d up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 130
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{d down}")
    Sleep 261
    Send("{d up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 130
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 130
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 130
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{n down}")
    Send("{x down}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 1826
    Send("{n down}")
    Send("{x down}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 130
    Send("{n up}")
    Send("{w up}")
    Send("{x up}")
    Sleep 913
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{s up}")
    Send("{h up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 130
    Send("{s up}")
    Send("{h up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 261
    Send("{s up}")
    Send("{h up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{h down}")
    Send("{s down}")
    Sleep 130
    Send("{s up}")
    Send("{h up}")
    Send("{s down}")
    Send("{h down}")
    Sleep 261
    Send("{h up}")
    Send("{s up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 261
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{b down}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{b up}")
    Send("{m down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{m up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 261
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{v down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{v up}")
    Send("{j down}")
    Send("{v down}")
    Sleep 261
    Send("{v up}")
    Send("{j up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 261
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{b down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Send("{b up}")
    Send("{z down}")
    Send("{b down}")
    Sleep 261
    Send("{b up}")
    Send("{z up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{x up}")
    Send("{n up}")
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{n up}")
    Send("{x down}")
    Send("{n down}")
    Sleep 261
    Send("{n up}")
    Send("{x up}")
}
