#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{g down}")
    Send("{5 down}")
    Sleep 1654
    Send("{g up}")
    Send("{5 up}")
    Sleep 85
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{n down}")
    Sleep 214
    Send("{n up}")
    Sleep 221
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{n down}")
    Sleep 214
    Send("{n up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Sleep 214
    Send("{m up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{n down}")
    Sleep 214
    Send("{n up}")
    Sleep 221
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{n down}")
    Sleep 214
    Send("{n up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{n down}")
    Sleep 214
    Send("{n up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{n down}")
    Sleep 214
    Send("{n up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{n down}")
    Sleep 214
    Send("{n up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{n down}")
    Sleep 214
    Send("{n up}")
    Sleep 221
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{n down}")
    Sleep 208
    Send("{n up}")
    Sleep 215
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{n down}")
    Sleep 208
    Send("{n up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{n down}")
    Sleep 208
    Send("{n up}")
    Sleep 215
    Send("{b down}")
    Sleep 208
    Send("{b up}")
    Sleep 215
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{c down}")
    Sleep 208
    Send("{c up}")
    Sleep 215
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{s down}")
    Sleep 208
    Send("{s up}")
    Sleep 215
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{s down}")
    Sleep 96
    Send("{g up}")
    Send("{s up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{z down}")
    Sleep 96
    Send("{g up}")
    Send("{z up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{n down}")
    Send("{g down}")
    Sleep 96
    Send("{n up}")
    Send("{g up}")
    Sleep 10
    Send("{h down}")
    Sleep 96
    Send("{h up}")
    Sleep 10
    Send("{n down}")
    Sleep 104
    Send("{n up}")
    Sleep 107
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{n down}")
    Send("{g down}")
    Sleep 96
    Send("{n up}")
    Send("{g up}")
    Sleep 10
    Send("{h down}")
    Sleep 96
    Send("{h up}")
    Sleep 10
    Send("{n down}")
    Sleep 104
    Send("{n up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{s down}")
    Sleep 96
    Send("{g up}")
    Send("{s up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{z down}")
    Sleep 96
    Send("{g up}")
    Send("{z up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Sleep 215
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{n down}")
    Send("{g down}")
    Sleep 96
    Send("{n up}")
    Send("{g up}")
    Sleep 10
    Send("{h down}")
    Sleep 96
    Send("{h up}")
    Sleep 10
    Send("{n down}")
    Sleep 104
    Send("{n up}")
    Sleep 107
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{n down}")
    Send("{g down}")
    Sleep 96
    Send("{n up}")
    Send("{g up}")
    Sleep 10
    Send("{h down}")
    Sleep 96
    Send("{h up}")
    Sleep 10
    Send("{n down}")
    Sleep 104
    Send("{n up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{x down}")
    Send("{j down}")
    Sleep 96
    Send("{x up}")
    Send("{j up}")
    Sleep 10
    Send("{s down}")
    Sleep 96
    Send("{s up}")
    Sleep 10
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{x down}")
    Send("{j down}")
    Sleep 96
    Send("{x up}")
    Send("{j up}")
    Sleep 10
    Send("{s down}")
    Sleep 96
    Send("{s up}")
    Sleep 10
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{x down}")
    Send("{j down}")
    Sleep 96
    Send("{x up}")
    Send("{j up}")
    Sleep 10
    Send("{s down}")
    Sleep 96
    Send("{s up}")
    Sleep 10
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{x down}")
    Send("{j down}")
    Sleep 96
    Send("{x up}")
    Send("{j up}")
    Sleep 10
    Send("{s down}")
    Sleep 96
    Send("{s up}")
    Sleep 10
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{m down}")
    Sleep 124
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{x down}")
    Sleep 124
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Sleep 124
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{x down}")
    Sleep 124
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Sleep 124
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{s down}")
    Sleep 124
    Send("{s up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Sleep 124
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{z down}")
    Sleep 124
    Send("{z up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Sleep 124
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{x down}")
    Sleep 124
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Sleep 124
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{x down}")
    Sleep 124
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 124
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{x down}")
    Sleep 124
    Send("{x up}")
    Sleep 13
    Send("{h down}")
    Sleep 124
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 126
    Send("{n up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{h down}")
    Sleep 124
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 126
    Send("{n up}")
    Sleep 13
    Send("{x down}")
    Sleep 124
    Send("{x up}")
    Sleep 13
    Send("{h down}")
    Sleep 124
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 126
    Send("{n up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{h down}")
    Sleep 124
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 126
    Send("{n up}")
    Sleep 13
    Send("{m down}")
    Sleep 122
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 122
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{x down}")
    Sleep 122
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 122
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Sleep 122
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 122
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{x down}")
    Sleep 122
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 122
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Sleep 122
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 122
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{s down}")
    Sleep 122
    Send("{s up}")
    Sleep 13
    Send("{v down}")
    Sleep 122
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Sleep 122
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 122
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{z down}")
    Sleep 122
    Send("{z up}")
    Sleep 13
    Send("{v down}")
    Sleep 122
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Sleep 120
    Send("{m up}")
    Sleep 12
    Send("{v down}")
    Sleep 119
    Send("{v up}")
    Sleep 12
    Send("{g down}")
    Sleep 119
    Send("{g up}")
    Sleep 12
    Send("{m down}")
    Send("{m down}")
    Sleep 342
    Send("{m up}")
    Send("{m up}")
    Sleep 37
    Send("{n down}")
    Send("{m down}")
    Send("{n down}")
    Sleep 329
    Send("{n up}")
    Send("{m up}")
    Send("{n up}")
    Sleep 35
    Send("{b down}")
    Send("{m down}")
    Send("{b down}")
    Sleep 316
    Send("{b up}")
    Send("{m up}")
    Send("{b up}")
    Sleep 34
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 304
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 33
    Send("{c down}")
    Send("{m down}")
    Send("{c down}")
    Sleep 293
    Send("{c up}")
    Send("{m up}")
    Send("{c up}")
    Sleep 31
    Send("{x down}")
    Send("{m down}")
    Send("{x down}")
    Sleep 285
    Send("{x up}")
    Send("{m up}")
    Send("{x up}")
    Sleep 31
    Send("{s down}")
    Send("{m down}")
    Send("{s down}")
    Sleep 285
    Send("{s up}")
    Send("{m up}")
    Send("{s up}")
    Sleep 31
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 80
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 80
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 80
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 80
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 80
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 80
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 80
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 80
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 80
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 80
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 80
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 80
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{d down}")
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Send("{d up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 80
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 80
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 80
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 80
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{d down}")
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Send("{d up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 80
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 80
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 80
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{n down}")
    Sleep 74
    Send("{n up}")
    Sleep 76
    Send("{b down}")
    Sleep 74
    Send("{b up}")
    Sleep 76
    Send("{g down}")
    Sleep 74
    Send("{g up}")
    Sleep 76
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{n down}")
    Sleep 74
    Send("{n up}")
    Sleep 76
    Send("{b down}")
    Sleep 74
    Send("{b up}")
    Sleep 76
    Send("{g down}")
    Sleep 74
    Send("{g up}")
    Sleep 76
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{n down}")
    Sleep 74
    Send("{n up}")
    Sleep 76
    Send("{b down}")
    Sleep 74
    Send("{b up}")
    Sleep 76
    Send("{g down}")
    Sleep 74
    Send("{g up}")
    Sleep 76
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{n down}")
    Sleep 74
    Send("{n up}")
    Sleep 76
    Send("{b down}")
    Sleep 74
    Send("{b up}")
    Sleep 76
    Send("{g down}")
    Sleep 74
    Send("{g up}")
    Sleep 76
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{n down}")
    Sleep 74
    Send("{n up}")
    Sleep 76
    Send("{b down}")
    Sleep 74
    Send("{b up}")
    Sleep 76
    Send("{g down}")
    Sleep 74
    Send("{g up}")
    Sleep 76
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{n down}")
    Sleep 74
    Send("{n up}")
    Sleep 76
    Send("{b down}")
    Sleep 74
    Send("{b up}")
    Sleep 76
    Send("{g down}")
    Sleep 74
    Send("{g up}")
    Sleep 76
    Send("{x down}")
    Send("{x down}")
    Sleep 74
    Send("{x up}")
    Send("{x up}")
    Sleep 76
    Send("{s down}")
    Sleep 74
    Send("{s up}")
    Sleep 76
    Send("{m down}")
    Sleep 74
    Send("{m up}")
    Sleep 76
    Send("{n down}")
    Sleep 74
    Send("{n up}")
    Sleep 76
    Send("{x down}")
    Send("{x down}")
    Sleep 74
    Send("{x up}")
    Send("{x up}")
    Sleep 76
    Send("{s down}")
    Sleep 74
    Send("{s up}")
    Sleep 76
    Send("{m down}")
    Sleep 74
    Send("{m up}")
    Sleep 76
    Send("{n down}")
    Sleep 74
    Send("{n up}")
    Sleep 76
    Send("{m down}")
    Send("{m down}")
    Sleep 72
    Send("{m up}")
    Send("{m up}")
    Sleep 74
    Send("{n down}")
    Sleep 72
    Send("{n up}")
    Sleep 74
    Send("{b down}")
    Sleep 72
    Send("{b up}")
    Sleep 74
    Send("{g down}")
    Sleep 72
    Send("{g up}")
    Sleep 74
    Send("{m down}")
    Send("{m down}")
    Sleep 72
    Send("{m up}")
    Send("{m up}")
    Sleep 74
    Send("{n down}")
    Sleep 72
    Send("{n up}")
    Sleep 74
    Send("{b down}")
    Sleep 72
    Send("{b up}")
    Sleep 74
    Send("{g down}")
    Sleep 72
    Send("{g up}")
    Sleep 74
    Send("{m down}")
    Send("{m down}")
    Sleep 72
    Send("{m up}")
    Send("{m up}")
    Sleep 74
    Send("{n down}")
    Sleep 72
    Send("{n up}")
    Sleep 74
    Send("{b down}")
    Sleep 72
    Send("{b up}")
    Sleep 74
    Send("{g down}")
    Sleep 72
    Send("{g up}")
    Sleep 74
    Send("{m down}")
    Send("{m down}")
    Sleep 72
    Send("{m up}")
    Send("{m up}")
    Sleep 74
    Send("{n down}")
    Sleep 72
    Send("{n up}")
    Sleep 74
    Send("{b down}")
    Sleep 72
    Send("{b up}")
    Sleep 74
    Send("{g down}")
    Sleep 72
    Send("{g up}")
    Sleep 74
    Send("{m down}")
    Send("{m down}")
    Sleep 72
    Send("{m up}")
    Send("{m up}")
    Sleep 74
    Send("{n down}")
    Sleep 72
    Send("{n up}")
    Sleep 74
    Send("{b down}")
    Sleep 72
    Send("{b up}")
    Sleep 74
    Send("{g down}")
    Sleep 72
    Send("{g up}")
    Sleep 74
    Send("{m down}")
    Send("{m down}")
    Sleep 70
    Send("{m up}")
    Send("{m up}")
    Sleep 73
    Send("{n down}")
    Sleep 70
    Send("{n up}")
    Sleep 73
    Send("{b down}")
    Sleep 69
    Send("{b up}")
    Sleep 71
    Send("{g down}")
    Sleep 69
    Send("{g up}")
    Sleep 71
    Send("{m down}")
    Send("{m down}")
    Sleep 67
    Send("{m up}")
    Send("{m up}")
    Sleep 69
    Send("{n down}")
    Sleep 67
    Send("{n up}")
    Sleep 69
    Send("{b down}")
    Sleep 67
    Send("{b up}")
    Sleep 69
    Send("{g down}")
    Sleep 67
    Send("{g up}")
    Sleep 69
    Send("{m down}")
    Send("{m down}")
    Sleep 67
    Send("{m up}")
    Send("{m up}")
    Sleep 69
    Send("{n down}")
    Sleep 67
    Send("{n up}")
    Sleep 69
    Send("{b down}")
    Sleep 67
    Send("{b up}")
    Sleep 69
    Send("{g down}")
    Sleep 67
    Send("{g up}")
    Sleep 69
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 579
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 579
    Send("{b down}")
    Send("{b down}")
    Sleep 208
    Send("{b up}")
    Send("{b up}")
    Sleep 23
    Send("{x down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 208
    Send("{x up}")
    Send("{b up}")
    Send("{m up}")
    Sleep 23
    Send("{g down}")
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Send("{g up}")
    Sleep 23
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 208
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 23
    Send("{g down}")
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Send("{g up}")
    Sleep 23
    Send("{s down}")
    Send("{g down}")
    Send("{j down}")
    Sleep 208
    Send("{s up}")
    Send("{g up}")
    Send("{j up}")
    Sleep 23
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 208
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 23
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 579
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 579
    Send("{b down}")
    Send("{b down}")
    Sleep 208
    Send("{b up}")
    Send("{b up}")
    Sleep 23
    Send("{x down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 208
    Send("{x up}")
    Send("{b up}")
    Send("{m up}")
    Sleep 23
    Send("{g down}")
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Send("{g up}")
    Sleep 23
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 208
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 23
    Send("{g down}")
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Send("{g up}")
    Sleep 23
    Send("{s down}")
    Send("{g down}")
    Send("{j down}")
    Sleep 208
    Send("{s up}")
    Send("{g up}")
    Send("{j up}")
    Sleep 23
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 208
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 23
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 208
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 484
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 579
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 117
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 117
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 117
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 117
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 117
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 117
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 579
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{m down}")
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 114
    Send("{m up}")
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
}
