#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{c down}")
    Sleep 107
    Send("{c up}")
    Sleep 110
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{v down}")
    Sleep 107
    Send("{v up}")
    Sleep 110
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{v down}")
    Sleep 214
    Send("{v up}")
    Sleep 221
    Send("{c down}")
    Sleep 107
    Send("{c up}")
    Sleep 110
    Send("{z down}")
    Sleep 107
    Send("{z up}")
    Sleep 110
    Send("{c down}")
    Sleep 214
    Send("{c up}")
    Sleep 221
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{c down}")
    Sleep 107
    Send("{c up}")
    Sleep 110
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{n down}")
    Sleep 107
    Send("{n up}")
    Sleep 110
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{n down}")
    Sleep 785
    Send("{n up}")
    Sleep 85
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{c down}")
    Sleep 107
    Send("{c up}")
    Sleep 110
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 221
    Send("{v down}")
    Sleep 107
    Send("{v up}")
    Sleep 110
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{v down}")
    Sleep 214
    Send("{v up}")
    Sleep 221
    Send("{c down}")
    Sleep 107
    Send("{c up}")
    Sleep 110
    Send("{z down}")
    Sleep 107
    Send("{z up}")
    Sleep 110
    Send("{c down}")
    Sleep 214
    Send("{c up}")
    Sleep 221
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{c down}")
    Sleep 107
    Send("{c up}")
    Sleep 110
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{n down}")
    Sleep 107
    Send("{n up}")
    Sleep 110
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{n down}")
    Send("{n down}")
    Sleep 785
    Send("{n up}")
    Send("{n up}")
    Sleep 85
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{h down}")
    Sleep 107
    Send("{h up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{h down}")
    Sleep 107
    Send("{h up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{s down}")
    Sleep 426
    Send("{s up}")
    Sleep 443
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{h down}")
    Sleep 107
    Send("{h up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{2 down}")
    Sleep 107
    Send("{2 up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{2 down}")
    Sleep 214
    Send("{2 up}")
    Sleep 221
    Send("{w down}")
    Sleep 107
    Send("{w up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{w down}")
    Sleep 214
    Send("{w up}")
    Sleep 221
    Send("{2 down}")
    Sleep 107
    Send("{2 up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{2 down}")
    Sleep 214
    Send("{2 up}")
    Sleep 221
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{h down}")
    Sleep 107
    Send("{h up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{2 down}")
    Sleep 107
    Send("{2 up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{2 down}")
    Sleep 214
    Send("{2 up}")
    Sleep 221
    Send("{w down}")
    Sleep 107
    Send("{w up}")
    Sleep 110
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{w down}")
    Sleep 214
    Send("{w up}")
    Sleep 221
    Send("{2 down}")
    Sleep 426
    Send("{2 up}")
    Sleep 443
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{c down}")
    Sleep 104
    Send("{c up}")
    Sleep 107
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{v down}")
    Sleep 104
    Send("{v up}")
    Sleep 107
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{v down}")
    Sleep 208
    Send("{v up}")
    Sleep 215
    Send("{c down}")
    Sleep 104
    Send("{c up}")
    Sleep 107
    Send("{z down}")
    Sleep 104
    Send("{z up}")
    Sleep 107
    Send("{c down}")
    Sleep 208
    Send("{c up}")
    Sleep 215
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{c down}")
    Sleep 104
    Send("{c up}")
    Sleep 107
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{n down}")
    Sleep 104
    Send("{n up}")
    Sleep 107
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{n down}")
    Sleep 763
    Send("{n up}")
    Sleep 83
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{c down}")
    Sleep 104
    Send("{c up}")
    Sleep 107
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 215
    Send("{v down}")
    Sleep 104
    Send("{v up}")
    Sleep 107
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{v down}")
    Sleep 208
    Send("{v up}")
    Sleep 215
    Send("{c down}")
    Sleep 104
    Send("{c up}")
    Sleep 107
    Send("{z down}")
    Sleep 104
    Send("{z up}")
    Sleep 107
    Send("{c down}")
    Sleep 208
    Send("{c up}")
    Sleep 215
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{c down}")
    Sleep 104
    Send("{c up}")
    Sleep 107
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{m down}")
    Sleep 763
    Send("{m up}")
    Sleep 83
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{g down}")
    Send("{w down}")
    Sleep 104
    Send("{g up}")
    Send("{w up}")
    Sleep 107
    Send("{e down}")
    Sleep 104
    Send("{e up}")
    Sleep 107
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{g down}")
    Send("{5 down}")
    Sleep 208
    Send("{g up}")
    Send("{5 up}")
    Sleep 215
    Send("{r down}")
    Sleep 104
    Send("{r up}")
    Sleep 107
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{g down}")
    Send("{r down}")
    Sleep 208
    Send("{g up}")
    Send("{r up}")
    Sleep 215
    Send("{e down}")
    Sleep 104
    Send("{e up}")
    Sleep 107
    Send("{q down}")
    Sleep 104
    Send("{q up}")
    Sleep 107
    Send("{g down}")
    Send("{e down}")
    Sleep 208
    Send("{g up}")
    Send("{e up}")
    Sleep 215
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{g down}")
    Send("{w down}")
    Sleep 104
    Send("{g up}")
    Send("{w up}")
    Sleep 107
    Send("{e down}")
    Sleep 104
    Send("{e up}")
    Sleep 107
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{u down}")
    Sleep 104
    Send("{u up}")
    Sleep 107
    Send("{y down}")
    Sleep 104
    Send("{y up}")
    Sleep 107
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{n down}")
    Send("{w down}")
    Sleep 104
    Send("{n up}")
    Send("{w up}")
    Sleep 107
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{y down}")
    Sleep 763
    Send("{y up}")
    Sleep 83
    Send("{u down}")
    Sleep 104
    Send("{u up}")
    Sleep 107
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{5 down}")
    Send("{w down}")
    Sleep 104
    Send("{5 up}")
    Send("{w up}")
    Sleep 107
    Send("{e down}")
    Sleep 104
    Send("{e up}")
    Sleep 107
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{5 down}")
    Send("{5 down}")
    Sleep 208
    Send("{5 up}")
    Send("{5 up}")
    Sleep 215
    Send("{r down}")
    Sleep 104
    Send("{r up}")
    Sleep 107
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{5 down}")
    Send("{r down}")
    Sleep 208
    Send("{5 up}")
    Send("{r up}")
    Sleep 215
    Send("{e down}")
    Sleep 104
    Send("{e up}")
    Sleep 107
    Send("{q down}")
    Sleep 104
    Send("{q up}")
    Sleep 107
    Send("{5 down}")
    Send("{e down}")
    Sleep 208
    Send("{5 up}")
    Send("{e up}")
    Sleep 215
    Send("{u down}")
    Sleep 104
    Send("{u up}")
    Sleep 107
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{5 down}")
    Send("{w down}")
    Sleep 104
    Send("{5 up}")
    Send("{w up}")
    Sleep 107
    Send("{e down}")
    Sleep 104
    Send("{e up}")
    Sleep 107
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{u down}")
    Sleep 104
    Send("{u up}")
    Sleep 107
    Send("{y down}")
    Sleep 104
    Send("{y up}")
    Sleep 107
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{y down}")
    Send("{w down}")
    Sleep 104
    Send("{y up}")
    Send("{w up}")
    Sleep 107
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{y down}")
    Sleep 763
    Send("{y up}")
    Sleep 83
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{6 down}")
    Sleep 104
    Send("{6 up}")
    Sleep 107
    Send("{7 down}")
    Send("{5 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{u down}")
    Sleep 104
    Send("{u up}")
    Sleep 66
    Send("{5 up}")
    Sleep 41
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 208
    Send("{2 up}")
    Sleep 173
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{w down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 208
    Send("{w up}")
    Sleep 173
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 208
    Send("{2 up}")
    Sleep 173
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{6 down}")
    Sleep 104
    Send("{6 up}")
    Sleep 107
    Send("{7 down}")
    Send("{5 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{u down}")
    Sleep 104
    Send("{u up}")
    Sleep 66
    Send("{5 up}")
    Sleep 41
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 208
    Send("{2 up}")
    Sleep 173
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{w down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 208
    Send("{w up}")
    Sleep 173
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{2 down}")
    Sleep 414
    Send("{2 up}")
    Sleep 8
    Send("{5 down}")
    Send("{7 down}")
    Sleep 381
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{6 down}")
    Sleep 104
    Send("{6 up}")
    Sleep 107
    Send("{7 down}")
    Send("{5 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 104
    Send("{5 up}")
    Sleep 3
    Send("{u down}")
    Sleep 104
    Send("{u up}")
    Sleep 107
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 208
    Send("{2 up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 215
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{w down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 208
    Send("{w up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 215
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 208
    Send("{2 up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 215
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{6 down}")
    Sleep 104
    Send("{6 up}")
    Sleep 107
    Send("{7 down}")
    Send("{5 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 104
    Send("{5 up}")
    Sleep 3
    Send("{u down}")
    Sleep 104
    Send("{u up}")
    Sleep 107
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 208
    Send("{2 up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 215
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{w down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 208
    Send("{w up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 215
    Send("{2 down}")
    Sleep 414
    Send("{2 up}")
    Sleep 8
    Send("{5 down}")
    Send("{7 down}")
    Sleep 381
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{m down}")
    Sleep 102
    Send("{m up}")
    Sleep 105
    Send("{2 down}")
    Sleep 102
    Send("{2 up}")
    Sleep 105
    Send("{g down}")
    Send("{w down}")
    Sleep 102
    Send("{g up}")
    Send("{w up}")
    Sleep 105
    Send("{e down}")
    Sleep 102
    Send("{e up}")
    Sleep 105
    Send("{5 down}")
    Sleep 102
    Send("{5 up}")
    Sleep 105
    Send("{w down}")
    Sleep 102
    Send("{w up}")
    Sleep 105
    Send("{g down}")
    Send("{5 down}")
    Sleep 204
    Send("{g up}")
    Send("{5 up}")
    Sleep 210
    Send("{r down}")
    Sleep 102
    Send("{r up}")
    Sleep 105
    Send("{2 down}")
    Sleep 102
    Send("{2 up}")
    Sleep 105
    Send("{g down}")
    Send("{r down}")
    Sleep 204
    Send("{g up}")
    Send("{r up}")
    Sleep 210
    Send("{e down}")
    Sleep 102
    Send("{e up}")
    Sleep 105
    Send("{q down}")
    Sleep 102
    Send("{q up}")
    Sleep 105
    Send("{g down}")
    Send("{e down}")
    Sleep 204
    Send("{g up}")
    Send("{e up}")
    Sleep 210
    Send("{m down}")
    Sleep 102
    Send("{m up}")
    Sleep 105
    Send("{2 down}")
    Sleep 102
    Send("{2 up}")
    Sleep 105
    Send("{g down}")
    Send("{w down}")
    Sleep 102
    Send("{g up}")
    Send("{w up}")
    Sleep 105
    Send("{e down}")
    Sleep 102
    Send("{e up}")
    Sleep 105
    Send("{5 down}")
    Sleep 102
    Send("{5 up}")
    Sleep 105
    Send("{w down}")
    Sleep 102
    Send("{w up}")
    Sleep 105
    Send("{m down}")
    Send("{5 down}")
    Sleep 102
    Send("{m up}")
    Send("{5 up}")
    Sleep 105
    Send("{u down}")
    Sleep 102
    Send("{u up}")
    Sleep 105
    Send("{y down}")
    Sleep 102
    Send("{y up}")
    Sleep 105
    Send("{5 down}")
    Sleep 102
    Send("{5 up}")
    Sleep 105
    Send("{n down}")
    Send("{w down}")
    Sleep 102
    Send("{n up}")
    Send("{w up}")
    Sleep 105
    Send("{5 down}")
    Sleep 102
    Send("{5 up}")
    Sleep 105
    Send("{y down}")
    Sleep 414
    Send("{n down}")
    Send("{w down}")
    Sleep 373
    Send("{n up}")
    Send("{w up}")
    Send("{y up}")
    Sleep 40
    Send("{u down}")
    Sleep 100
    Send("{u up}")
    Sleep 103
    Send("{2 down}")
    Sleep 100
    Send("{2 up}")
    Sleep 103
    Send("{5 down}")
    Send("{w down}")
    Sleep 100
    Send("{5 up}")
    Send("{w up}")
    Sleep 103
    Send("{e down}")
    Sleep 100
    Send("{e up}")
    Sleep 103
    Send("{5 down}")
    Sleep 100
    Send("{5 up}")
    Sleep 103
    Send("{w down}")
    Sleep 100
    Send("{w up}")
    Sleep 103
    Send("{5 down}")
    Send("{5 down}")
    Sleep 200
    Send("{5 up}")
    Send("{5 up}")
    Sleep 206
    Send("{r down}")
    Sleep 100
    Send("{r up}")
    Sleep 103
    Send("{2 down}")
    Sleep 100
    Send("{2 up}")
    Sleep 103
    Send("{5 down}")
    Send("{r down}")
    Sleep 200
    Send("{5 up}")
    Send("{r up}")
    Sleep 206
    Send("{e down}")
    Sleep 100
    Send("{e up}")
    Sleep 103
    Send("{q down}")
    Sleep 100
    Send("{q up}")
    Sleep 103
    Send("{5 down}")
    Send("{e down}")
    Sleep 200
    Send("{5 up}")
    Send("{e up}")
    Sleep 206
    Send("{u down}")
    Sleep 98
    Send("{u up}")
    Sleep 102
    Send("{2 down}")
    Sleep 96
    Send("{2 up}")
    Sleep 99
    Send("{5 down}")
    Send("{w down}")
    Sleep 94
    Send("{5 up}")
    Send("{w up}")
    Sleep 97
    Send("{e down}")
    Sleep 92
    Send("{e up}")
    Sleep 95
    Send("{5 down}")
    Sleep 90
    Send("{5 up}")
    Sleep 93
    Send("{w down}")
    Sleep 89
    Send("{w up}")
    Sleep 91
    Send("{5 down}")
    Sleep 87
    Send("{5 up}")
    Sleep 90
    Send("{u down}")
    Sleep 85
    Send("{u up}")
    Sleep 88
    Send("{5 down}")
    Sleep 84
    Send("{5 up}")
    Sleep 86
    Send("{w down}")
    Sleep 82
    Send("{w up}")
    Sleep 85
    Send("{u down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 81
    Send("{5 up}")
    Sleep 83
    Send("{u down}")
    Sleep 79
    Send("{u up}")
    Send("{w up}")
    Send("{u up}")
    Sleep 82
    Send("{u down}")
    Sleep 570
    Send("{u up}")
    Sleep 62
    Send("{u down}")
    Send("{u down}")
    Sleep 78
    Send("{u up}")
    Sleep 80
    Send("{2 down}")
    Sleep 78
    Send("{2 up}")
    Sleep 80
    Send("{w down}")
    Sleep 78
    Send("{w up}")
    Sleep 80
    Send("{e down}")
    Sleep 78
    Send("{e up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{5 down}")
    Send("{u down}")
    Sleep 78
    Send("{5 up}")
    Sleep 80
    Send("{w down}")
    Sleep 78
    Send("{w up}")
    Sleep 80
    Send("{5 down}")
    Sleep 155
    Send("{5 up}")
    Sleep 99
    Send("{u up}")
    Sleep 62
    Send("{r down}")
    Send("{u down}")
    Sleep 78
    Send("{r up}")
    Sleep 80
    Send("{2 down}")
    Sleep 78
    Send("{2 up}")
    Sleep 80
    Send("{r down}")
    Sleep 155
    Send("{r up}")
    Sleep 99
    Send("{u up}")
    Sleep 62
    Send("{e down}")
    Send("{u down}")
    Sleep 78
    Send("{e up}")
    Sleep 80
    Send("{q down}")
    Sleep 78
    Send("{q up}")
    Sleep 80
    Send("{e down}")
    Sleep 155
    Send("{e up}")
    Sleep 99
    Send("{u up}")
    Sleep 62
    Send("{u down}")
    Send("{u down}")
    Sleep 78
    Send("{u up}")
    Sleep 80
    Send("{2 down}")
    Sleep 78
    Send("{2 up}")
    Sleep 80
    Send("{w down}")
    Sleep 78
    Send("{w up}")
    Sleep 80
    Send("{e down}")
    Sleep 78
    Send("{e up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{5 down}")
    Send("{u down}")
    Sleep 78
    Send("{5 up}")
    Sleep 80
    Send("{w down}")
    Sleep 78
    Send("{w up}")
    Sleep 80
    Send("{5 down}")
    Sleep 78
    Send("{5 up}")
    Sleep 80
    Send("{u down}")
    Sleep 78
    Send("{u up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 78
    Send("{y up}")
    Sleep 80
    Send("{5 down}")
    Sleep 78
    Send("{5 up}")
    Sleep 80
    Send("{w down}")
    Sleep 78
    Send("{w up}")
    Sleep 80
    Send("{5 down}")
    Sleep 78
    Send("{5 up}")
    Sleep 19
    Send("{y up}")
    Send("{w up}")
    Sleep 62
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 570
    Send("{y up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 62
    Send("{u down}")
    Send("{u down}")
    Sleep 78
    Send("{u up}")
    Sleep 80
    Send("{2 down}")
    Sleep 78
    Send("{2 up}")
    Sleep 80
    Send("{w down}")
    Sleep 78
    Send("{w up}")
    Sleep 80
    Send("{e down}")
    Sleep 78
    Send("{e up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{5 down}")
    Send("{u down}")
    Sleep 78
    Send("{5 up}")
    Sleep 80
    Send("{w down}")
    Sleep 78
    Send("{w up}")
    Sleep 80
    Send("{5 down}")
    Sleep 155
    Send("{5 up}")
    Sleep 99
    Send("{u up}")
    Sleep 62
    Send("{r down}")
    Send("{u down}")
    Sleep 78
    Send("{r up}")
    Sleep 80
    Send("{2 down}")
    Sleep 78
    Send("{2 up}")
    Sleep 80
    Send("{r down}")
    Sleep 155
    Send("{r up}")
    Sleep 99
    Send("{u up}")
    Sleep 62
    Send("{e down}")
    Send("{u down}")
    Sleep 78
    Send("{e up}")
    Sleep 80
    Send("{q down}")
    Sleep 78
    Send("{q up}")
    Sleep 80
    Send("{e down}")
    Sleep 155
    Send("{e up}")
    Sleep 99
    Send("{u up}")
    Sleep 62
    Send("{u down}")
    Send("{u down}")
    Sleep 78
    Send("{u up}")
    Sleep 80
    Send("{2 down}")
    Sleep 78
    Send("{2 up}")
    Sleep 80
    Send("{w down}")
    Sleep 78
    Send("{w up}")
    Sleep 80
    Send("{e down}")
    Sleep 78
    Send("{e up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{5 down}")
    Send("{u down}")
    Sleep 78
    Send("{5 up}")
    Sleep 80
    Send("{w down}")
    Sleep 78
    Send("{w up}")
    Sleep 80
    Send("{5 down}")
    Sleep 78
    Send("{5 up}")
    Sleep 80
    Send("{u down}")
    Sleep 78
    Send("{u up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 78
    Send("{y up}")
    Sleep 80
    Send("{5 down}")
    Sleep 78
    Send("{5 up}")
    Sleep 80
    Send("{y down}")
    Send("{w down}")
    Sleep 78
    Send("{y up}")
    Send("{w up}")
    Sleep 80
    Send("{5 down}")
    Sleep 78
    Send("{5 up}")
    Sleep 19
    Send("{y up}")
    Send("{w up}")
    Sleep 62
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 570
    Send("{y up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 62
    Send("{5 down}")
    Send("{5 down}")
    Sleep 78
    Send("{5 up}")
    Sleep 80
    Send("{6 down}")
    Sleep 78
    Send("{6 up}")
    Sleep 80
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 80
    Send("{u down}")
    Sleep 78
    Send("{u up}")
    Sleep 19
    Send("{5 up}")
    Sleep 62
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 78
    Send("{2 up}")
    Sleep 80
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 49
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 155
    Send("{2 up}")
    Sleep 130
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{w down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 78
    Send("{w up}")
    Sleep 78
    Send("{w up}")
    Send("{5 up}")
    Sleep 2
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 80
    Send("{w down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 155
    Send("{w up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 160
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 78
    Send("{2 up}")
    Sleep 78
    Send("{2 up}")
    Send("{5 up}")
    Sleep 2
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 155
    Send("{2 up}")
    Sleep 130
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{5 down}")
    Send("{5 down}")
    Sleep 78
    Send("{5 up}")
    Sleep 65
    Send("{5 up}")
    Sleep 15
    Send("{6 down}")
    Send("{5 down}")
    Sleep 78
    Send("{6 up}")
    Send("{5 up}")
    Sleep 80
    Send("{7 down}")
    Send("{5 down}")
    Sleep 78
    Send("{7 up}")
    Send("{5 up}")
    Sleep 80
    Send("{u down}")
    Send("{5 down}")
    Sleep 78
    Send("{u up}")
    Send("{5 up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 78
    Send("{2 up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 80
    Send("{7 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 78
    Send("{7 up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 155
    Send("{2 up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 160
    Send("{w down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 78
    Send("{w up}")
    Send("{w up}")
    Send("{5 up}")
    Sleep 80
    Send("{7 down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 78
    Send("{7 up}")
    Send("{w up}")
    Send("{5 up}")
    Sleep 80
    Send("{w down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 155
    Send("{w up}")
    Send("{w up}")
    Send("{5 up}")
    Sleep 160
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 310
    Send("{2 up}")
    Sleep 260
    Send("{2 up}")
    Send("{5 up}")
    Sleep 62
    Send("{5 down}")
    Send("{5 down}")
    Sleep 78
    Send("{5 up}")
    Sleep 80
    Send("{6 down}")
    Sleep 78
    Send("{6 up}")
    Sleep 80
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 80
    Send("{u down}")
    Sleep 78
    Send("{u up}")
    Sleep 19
    Send("{5 up}")
    Sleep 62
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 78
    Send("{2 up}")
    Sleep 80
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 49
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 155
    Send("{2 up}")
    Sleep 130
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{3 down}")
    Send("{3 down}")
    Send("{5 down}")
    Sleep 78
    Send("{3 up}")
    Sleep 78
    Send("{3 up}")
    Send("{5 up}")
    Sleep 2
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 80
    Send("{3 down}")
    Send("{5 down}")
    Send("{7 down}")
    Sleep 155
    Send("{3 up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 160
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 78
    Send("{2 up}")
    Sleep 78
    Send("{2 up}")
    Send("{5 up}")
    Sleep 2
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 155
    Send("{2 up}")
    Sleep 130
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{5 down}")
    Send("{5 down}")
    Sleep 78
    Send("{5 up}")
    Sleep 65
    Send("{5 up}")
    Sleep 15
    Send("{6 down}")
    Send("{5 down}")
    Sleep 78
    Send("{6 up}")
    Send("{5 up}")
    Sleep 80
    Send("{7 down}")
    Send("{5 down}")
    Sleep 78
    Send("{7 up}")
    Send("{5 up}")
    Sleep 80
    Send("{u down}")
    Send("{5 down}")
    Sleep 78
    Send("{u up}")
    Send("{5 up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 78
    Send("{2 up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 80
    Send("{7 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 78
    Send("{7 up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 155
    Send("{2 up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 160
    Send("{3 down}")
    Send("{3 down}")
    Send("{5 down}")
    Sleep 78
    Send("{3 up}")
    Send("{3 up}")
    Send("{5 up}")
    Sleep 80
    Send("{7 down}")
    Send("{3 down}")
    Send("{5 down}")
    Sleep 78
    Send("{7 up}")
    Send("{3 up}")
    Send("{5 up}")
    Sleep 80
    Send("{3 down}")
    Send("{3 down}")
    Send("{5 down}")
    Sleep 155
    Send("{3 up}")
    Send("{3 up}")
    Send("{5 up}")
    Sleep 160
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 310
    Send("{2 up}")
    Sleep 260
    Send("{2 up}")
    Send("{5 up}")
    Sleep 62
    Send("{u down}")
    Send("{u down}")
    Sleep 74
    Send("{u up}")
    Sleep 76
    Send("{2 down}")
    Sleep 74
    Send("{2 up}")
    Sleep 76
    Send("{w down}")
    Sleep 74
    Send("{w up}")
    Sleep 76
    Send("{e down}")
    Sleep 74
    Send("{e up}")
    Sleep 18
    Send("{u up}")
    Sleep 59
    Send("{5 down}")
    Send("{u down}")
    Sleep 74
    Send("{5 up}")
    Sleep 76
    Send("{w down}")
    Sleep 74
    Send("{w up}")
    Sleep 76
    Send("{5 down}")
    Sleep 148
    Send("{5 up}")
    Sleep 94
    Send("{u up}")
    Sleep 59
    Send("{r down}")
    Send("{u down}")
    Sleep 74
    Send("{r up}")
    Sleep 76
    Send("{2 down}")
    Sleep 74
    Send("{2 up}")
    Sleep 76
    Send("{r down}")
    Sleep 148
    Send("{r up}")
    Sleep 94
    Send("{u up}")
    Sleep 59
    Send("{e down}")
    Send("{u down}")
    Sleep 74
    Send("{e up}")
    Sleep 76
    Send("{q down}")
    Sleep 74
    Send("{q up}")
    Sleep 76
    Send("{e down}")
    Sleep 148
    Send("{e up}")
    Sleep 94
    Send("{u up}")
    Sleep 59
    Send("{u down}")
    Send("{u down}")
    Sleep 74
    Send("{u up}")
    Sleep 76
    Send("{2 down}")
    Sleep 74
    Send("{2 up}")
    Sleep 76
    Send("{w down}")
    Sleep 74
    Send("{w up}")
    Sleep 76
    Send("{e down}")
    Sleep 74
    Send("{e up}")
    Sleep 18
    Send("{u up}")
    Sleep 59
    Send("{5 down}")
    Send("{u down}")
    Sleep 74
    Send("{5 up}")
    Sleep 76
    Send("{w down}")
    Sleep 74
    Send("{w up}")
    Sleep 76
    Send("{5 down}")
    Sleep 74
    Send("{5 up}")
    Sleep 76
    Send("{u down}")
    Sleep 74
    Send("{u up}")
    Sleep 18
    Send("{u up}")
    Sleep 59
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 74
    Send("{y up}")
    Sleep 76
    Send("{5 down}")
    Sleep 74
    Send("{5 up}")
    Sleep 76
    Send("{w down}")
    Sleep 74
    Send("{w up}")
    Sleep 76
    Send("{5 down}")
    Sleep 74
    Send("{5 up}")
    Sleep 18
    Send("{y up}")
    Send("{w up}")
    Sleep 59
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 541
    Send("{y up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 59
    Send("{u down}")
    Send("{u down}")
    Sleep 72
    Send("{u up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{2 down}")
    Send("{u down}")
    Sleep 72
    Send("{2 up}")
    Send("{u up}")
    Sleep 74
    Send("{w down}")
    Send("{u down}")
    Sleep 72
    Send("{w up}")
    Send("{u up}")
    Sleep 74
    Send("{e down}")
    Send("{u down}")
    Sleep 72
    Send("{e up}")
    Send("{u up}")
    Sleep 74
    Send("{5 down}")
    Send("{u down}")
    Sleep 72
    Send("{5 up}")
    Send("{u up}")
    Sleep 74
    Send("{w down}")
    Send("{u down}")
    Sleep 72
    Send("{w up}")
    Send("{u up}")
    Sleep 74
    Send("{5 down}")
    Send("{u down}")
    Sleep 144
    Send("{5 up}")
    Send("{u up}")
    Sleep 149
    Send("{r down}")
    Send("{u down}")
    Sleep 72
    Send("{r up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{2 down}")
    Send("{u down}")
    Sleep 72
    Send("{2 up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{r down}")
    Send("{u down}")
    Sleep 133
    Send("{u up}")
    Sleep 11
    Send("{r up}")
    Sleep 149
    Send("{e down}")
    Send("{u down}")
    Sleep 72
    Send("{e up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{q down}")
    Send("{u down}")
    Sleep 72
    Send("{q up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{e down}")
    Send("{u down}")
    Sleep 133
    Send("{u up}")
    Sleep 11
    Send("{e up}")
    Sleep 149
    Send("{u down}")
    Send("{u down}")
    Sleep 72
    Send("{u up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{2 down}")
    Send("{u down}")
    Sleep 72
    Send("{2 up}")
    Send("{u up}")
    Sleep 74
    Send("{w down}")
    Send("{u down}")
    Sleep 72
    Send("{w up}")
    Send("{u up}")
    Sleep 74
    Send("{e down}")
    Send("{u down}")
    Sleep 72
    Send("{e up}")
    Send("{u up}")
    Sleep 74
    Send("{5 down}")
    Send("{u down}")
    Sleep 70
    Send("{5 up}")
    Send("{u up}")
    Sleep 73
    Send("{w down}")
    Send("{u down}")
    Sleep 70
    Send("{w up}")
    Send("{u up}")
    Sleep 73
    Send("{5 down}")
    Send("{u down}")
    Sleep 69
    Send("{5 up}")
    Send("{u up}")
    Sleep 71
    Send("{u down}")
    Send("{u down}")
    Sleep 69
    Send("{u up}")
    Send("{u up}")
    Sleep 71
    Send("{5 down}")
    Send("{u down}")
    Sleep 67
    Send("{5 up}")
    Send("{u up}")
    Sleep 69
    Send("{w down}")
    Sleep 67
    Send("{w up}")
    Sleep 69
    Send("{5 down}")
    Sleep 67
    Send("{5 up}")
    Sleep 69
    Send("{u down}")
    Sleep 67
    Send("{u up}")
    Sleep 69
    Send("{u down}")
    Sleep 492
    Send("{u up}")
    Sleep 133
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 41
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 208
    Send("{w up}")
    Send("{u up}")
    Sleep 563
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 41
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 208
    Send("{w up}")
    Send("{u up}")
    Sleep 484
    Send("{u down}")
    Sleep 57
    Send("{u up}")
    Sleep 59
    Send("{2 down}")
    Sleep 57
    Send("{2 up}")
    Sleep 59
    Send("{w down}")
    Sleep 57
    Send("{w up}")
    Sleep 59
    Send("{e down}")
    Sleep 57
    Send("{e up}")
    Sleep 59
    Send("{5 down}")
    Sleep 57
    Send("{5 up}")
    Sleep 59
    Send("{w down}")
    Sleep 57
    Send("{w up}")
    Sleep 59
    Send("{5 down}")
    Sleep 57
    Send("{5 up}")
    Sleep 59
    Send("{u down}")
    Sleep 57
    Send("{u up}")
    Sleep 59
    Send("{7 down}")
    Sleep 57
    Send("{7 up}")
    Sleep 59
    Send("{5 down}")
    Sleep 57
    Send("{5 up}")
    Sleep 59
    Send("{7 down}")
    Sleep 57
    Send("{7 up}")
    Sleep 59
    Send("{2 down}")
    Sleep 57
    Send("{2 up}")
    Sleep 59
    Send("{u down}")
    Sleep 416
    Send("{u up}")
    Sleep 124
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 41
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 208
    Send("{w up}")
    Send("{u up}")
    Sleep 563
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 41
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 208
    Send("{w up}")
    Send("{u up}")
    Sleep 484
    Send("{u down}")
    Sleep 57
    Send("{u up}")
    Sleep 59
    Send("{2 down}")
    Sleep 57
    Send("{2 up}")
    Sleep 59
    Send("{w down}")
    Sleep 57
    Send("{w up}")
    Sleep 59
    Send("{e down}")
    Sleep 57
    Send("{e up}")
    Sleep 59
    Send("{5 down}")
    Sleep 57
    Send("{5 up}")
    Sleep 59
    Send("{w down}")
    Sleep 57
    Send("{w up}")
    Sleep 59
    Send("{5 down}")
    Sleep 57
    Send("{5 up}")
    Sleep 59
    Send("{u down}")
    Sleep 57
    Send("{u up}")
    Sleep 59
    Send("{7 down}")
    Sleep 57
    Send("{7 up}")
    Sleep 59
    Send("{5 down}")
    Sleep 57
    Send("{5 up}")
    Sleep 59
    Send("{7 down}")
    Sleep 57
    Send("{7 up}")
    Sleep 59
    Send("{2 down}")
    Sleep 57
    Send("{2 up}")
    Sleep 59
    Send("{u down}")
    Sleep 416
    Send("{u up}")
    Sleep 124
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 41
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 208
    Send("{w up}")
    Send("{u up}")
    Sleep 563
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 41
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 208
    Send("{w up}")
    Send("{u up}")
    Sleep 563
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 41
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 56
    Send("{6 down}")
    Sleep 65
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 56
    Send("{6 down}")
    Sleep 65
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 208
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 14
    Send("{6 down}")
    Sleep 55
    Send("{y up}")
    Send("{7 down}")
    Sleep 10
    Send("{6 up}")
    Send("{y down}")
    Sleep 31
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 39
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 56
    Send("{6 down}")
    Sleep 65
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 56
    Send("{6 down}")
    Sleep 65
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 208
    Send("{w up}")
    Send("{u up}")
    Sleep 1948
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 41
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 208
    Send("{w up}")
    Send("{u up}")
}
