#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{x down}")
    Send("{x down}")
    Sleep 825
    Send("{x up}")
    Send("{x up}")
    Sleep 75
    Send("{x down}")
    Send("{x down}")
    Sleep 400
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 400
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Send("{j up}")
    Sleep 50
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{j down}")
    Send("{j down}")
    Sleep 147
    Send("{j up}")
    Send("{j up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Send("{v up}")
    Sleep 50
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{v up}")
    Send("{v up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Send("{z up}")
    Sleep 50
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{z down}")
    Send("{z down}")
    Sleep 147
    Send("{z up}")
    Send("{z up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Send("{b up}")
    Sleep 50
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{b up}")
    Send("{b up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Send("{n up}")
    Sleep 50
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 400
    Send("{x up}")
    Send("{x up}")
    Sleep 50
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x up}")
    Send("{x up}")
    Sleep 3
    Send("{x down}")
    Send("{x down}")
    Sleep 1125
    Send("{x up}")
    Send("{x up}")
}
