#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Sleep 3
    Send("{q down}")
    Sleep 147
    Send("{q up}")
    Sleep 3
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 50
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 50
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 147
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 3
    Send("{n down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 147
    Send("{n up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 3
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 147
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 3
    Send("{w down}")
    Send("{t down}")
    Sleep 147
    Send("{w up}")
    Send("{t up}")
    Sleep 3
    Send("{n down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{n up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{n down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{n up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{n down}")
    Send("{w down}")
    Sleep 147
    Send("{n up}")
    Send("{w up}")
    Sleep 3
    Send("{b down}")
    Send("{q down}")
    Sleep 147
    Send("{b up}")
    Send("{q up}")
    Sleep 3
    Send("{n down}")
    Send("{q down}")
    Sleep 147
    Send("{n up}")
    Send("{q up}")
    Sleep 3
    Send("{n down}")
    Send("{w down}")
    Sleep 250
    Send("{n up}")
    Send("{w up}")
    Sleep 200
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Sleep 3
    Send("{q down}")
    Sleep 147
    Send("{q up}")
    Sleep 3
    Send("{v down}")
    Send("{j down}")
    Send("{w down}")
    Sleep 250
    Send("{v up}")
    Send("{j up}")
    Send("{w up}")
    Sleep 50
    Send("{v down}")
    Send("{j down}")
    Send("{w down}")
    Sleep 250
    Send("{v up}")
    Send("{j up}")
    Send("{w up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Sleep 147
    Send("{j up}")
    Send("{w up}")
    Sleep 3
    Send("{j down}")
    Send("{e down}")
    Sleep 147
    Send("{j up}")
    Send("{e up}")
    Sleep 3
    Send("{n down}")
    Send("{q down}")
    Send("{r down}")
    Sleep 250
    Send("{n up}")
    Send("{q up}")
    Send("{r up}")
    Sleep 50
    Send("{n down}")
    Send("{q down}")
    Send("{r down}")
    Sleep 250
    Send("{n up}")
    Send("{q up}")
    Send("{r up}")
    Sleep 50
    Send("{q down}")
    Send("{r down}")
    Sleep 147
    Send("{q up}")
    Send("{r up}")
    Sleep 3
    Send("{q down}")
    Send("{t down}")
    Sleep 147
    Send("{q up}")
    Send("{t up}")
    Sleep 3
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{n down}")
    Send("{w down}")
    Sleep 147
    Send("{n up}")
    Send("{w up}")
    Sleep 3
    Send("{q down}")
    Sleep 147
    Send("{q up}")
    Sleep 3
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 350
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Sleep 3
    Send("{q down}")
    Sleep 147
    Send("{q up}")
    Sleep 3
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 50
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 50
    Send("{n down}")
    Send("{w down}")
    Sleep 147
    Send("{n up}")
    Send("{w up}")
    Sleep 3
    Send("{n down}")
    Send("{r down}")
    Sleep 147
    Send("{n up}")
    Send("{r up}")
    Sleep 3
    Send("{j down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{j up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{j up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 50
    Send("{w down}")
    Send("{t down}")
    Sleep 147
    Send("{w up}")
    Send("{t up}")
    Sleep 3
    Send("{w down}")
    Send("{y down}")
    Sleep 147
    Send("{w up}")
    Send("{y up}")
    Sleep 3
    Send("{w down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 250
    Send("{w up}")
    Send("{t up}")
    Send("{7 up}")
    Sleep 50
    Send("{w down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 250
    Send("{w up}")
    Send("{t up}")
    Send("{7 up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Sleep 147
    Send("{r up}")
    Send("{y up}")
    Sleep 3
    Send("{e down}")
    Send("{t down}")
    Sleep 147
    Send("{e up}")
    Send("{t up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Sleep 147
    Send("{r up}")
    Send("{y up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 200
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{j up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Sleep 147
    Send("{r up}")
    Send("{y up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 200
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 250
    Send("{n up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 50
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 250
    Send("{n up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Sleep 147
    Send("{w up}")
    Send("{r up}")
    Sleep 3
    Send("{m down}")
    Send("{w down}")
    Sleep 147
    Send("{m up}")
    Send("{w up}")
    Sleep 3
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 147
    Send("{n up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 453
    Send("{y down}")
    Sleep 147
    Send("{y up}")
    Sleep 3
    Send("{q down}")
    Sleep 147
    Send("{q up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 250
    Send("{r up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 250
    Send("{r up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 147
    Send("{r up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 3
    Send("{y down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 147
    Send("{y up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 3
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 147
    Send("{7 up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 3
    Send("{w down}")
    Send("{t down}")
    Sleep 147
    Send("{w up}")
    Send("{t up}")
    Sleep 3
    Send("{y down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{y up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{y down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{y up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{y down}")
    Send("{w down}")
    Sleep 147
    Send("{y up}")
    Send("{w up}")
    Sleep 3
    Send("{t down}")
    Send("{q down}")
    Sleep 147
    Send("{t up}")
    Send("{q up}")
    Sleep 3
    Send("{y down}")
    Send("{q down}")
    Sleep 147
    Send("{y up}")
    Send("{q up}")
    Sleep 3
    Send("{y down}")
    Send("{w down}")
    Sleep 250
    Send("{y up}")
    Send("{w up}")
    Sleep 200
    Send("{y down}")
    Sleep 147
    Send("{y up}")
    Sleep 3
    Send("{q down}")
    Sleep 147
    Send("{q up}")
    Sleep 3
    Send("{r down}")
    Send("{7 down}")
    Send("{w down}")
    Sleep 250
    Send("{r up}")
    Send("{7 up}")
    Send("{w up}")
    Sleep 50
    Send("{r down}")
    Send("{7 down}")
    Send("{w down}")
    Sleep 250
    Send("{r up}")
    Send("{7 up}")
    Send("{w up}")
    Sleep 50
    Send("{7 down}")
    Send("{w down}")
    Sleep 147
    Send("{7 up}")
    Send("{w up}")
    Sleep 3
    Send("{7 down}")
    Send("{e down}")
    Sleep 147
    Send("{7 up}")
    Send("{e up}")
    Sleep 3
    Send("{y down}")
    Send("{q down}")
    Send("{r down}")
    Sleep 250
    Send("{y up}")
    Send("{q up}")
    Send("{r up}")
    Sleep 50
    Send("{y down}")
    Send("{q down}")
    Send("{r down}")
    Sleep 250
    Send("{y up}")
    Send("{q up}")
    Send("{r up}")
    Sleep 50
    Send("{q down}")
    Send("{r down}")
    Sleep 147
    Send("{q up}")
    Send("{r up}")
    Sleep 3
    Send("{q down}")
    Send("{t down}")
    Sleep 147
    Send("{q up}")
    Send("{t up}")
    Sleep 3
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{y down}")
    Send("{w down}")
    Sleep 147
    Send("{y up}")
    Send("{w up}")
    Sleep 3
    Send("{q down}")
    Sleep 147
    Send("{q up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 250
    Send("{r up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 350
    Send("{y down}")
    Sleep 147
    Send("{y up}")
    Sleep 3
    Send("{q down}")
    Sleep 147
    Send("{q up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 250
    Send("{r up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 250
    Send("{r up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 50
    Send("{y down}")
    Send("{w down}")
    Sleep 147
    Send("{y up}")
    Send("{w up}")
    Sleep 3
    Send("{y down}")
    Send("{r down}")
    Sleep 147
    Send("{y up}")
    Send("{r up}")
    Sleep 3
    Send("{7 down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 50
    Send("{7 down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 50
    Send("{w down}")
    Send("{t down}")
    Sleep 147
    Send("{w up}")
    Send("{t up}")
    Sleep 3
    Send("{w down}")
    Send("{y down}")
    Sleep 147
    Send("{w up}")
    Send("{y up}")
    Sleep 3
    Send("{w down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 250
    Send("{w up}")
    Send("{t up}")
    Send("{7 up}")
    Sleep 50
    Send("{w down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 250
    Send("{w up}")
    Send("{t up}")
    Send("{7 up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Sleep 147
    Send("{r up}")
    Send("{y up}")
    Sleep 3
    Send("{e down}")
    Send("{t down}")
    Sleep 147
    Send("{e up}")
    Send("{t up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Sleep 147
    Send("{r up}")
    Send("{y up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 200
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{7 down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Sleep 147
    Send("{r up}")
    Send("{y up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 200
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 250
    Send("{y up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 50
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 250
    Send("{y up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{2 down}")
    Sleep 147
    Send("{2 up}")
    Sleep 3
    Send("{y down}")
    Send("{w down}")
    Sleep 250
    Send("{y up}")
    Send("{w up}")
    Sleep 50
    Send("{y down}")
    Send("{w down}")
    Sleep 250
    Send("{y up}")
    Send("{w up}")
    Sleep 50
    Send("{y down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{y up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{q down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{q up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{7 down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 50
    Send("{w down}")
    Send("{y down}")
    Sleep 147
    Send("{w up}")
    Send("{y up}")
    Sleep 3
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 303
    Send("{y down}")
    Send("{r down}")
    Sleep 147
    Send("{y up}")
    Send("{r up}")
    Sleep 3
    Send("{y down}")
    Send("{w down}")
    Sleep 147
    Send("{y up}")
    Send("{w up}")
    Sleep 3
    Send("{y down}")
    Sleep 147
    Send("{y up}")
    Sleep 753
    Send("{w down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 147
    Send("{w up}")
    Send("{t up}")
    Send("{7 up}")
    Sleep 453
    Send("{7 down}")
    Send("{t down}")
    Sleep 147
    Send("{7 up}")
    Send("{t up}")
    Sleep 3
    Send("{7 down}")
    Send("{w down}")
    Sleep 147
    Send("{7 up}")
    Send("{w up}")
    Sleep 3
    Send("{7 down}")
    Sleep 147
    Send("{7 up}")
    Sleep 753
    Send("{2 down}")
    Send("{e down}")
    Sleep 147
    Send("{2 up}")
    Send("{e up}")
    Sleep 3
    Send("{2 down}")
    Send("{e down}")
    Sleep 250
    Send("{2 up}")
    Send("{e up}")
    Sleep 50
    Send("{b down}")
    Send("{w down}")
    Sleep 400
    Send("{b up}")
    Send("{w up}")
    Sleep 50
    Send("{n down}")
    Send("{2 down}")
    Send("{r down}")
    Sleep 400
    Send("{n up}")
    Send("{2 up}")
    Send("{r up}")
    Sleep 200
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{t down}")
    Sleep 147
    Send("{t up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 147
    Send("{w up}")
    Send("{r up}")
    Send("{7 up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 147
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 603
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 147
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 3
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 147
    Send("{q up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 603
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 147
    Send("{w up}")
    Send("{r up}")
    Send("{7 up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 147
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 603
    Send("{2 down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 250
    Send("{2 up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 50
    Send("{2 down}")
    Send("{r down}")
    Sleep 250
    Send("{2 up}")
    Send("{r up}")
    Sleep 50
    Send("{n down}")
    Send("{e down}")
    Sleep 250
    Send("{n up}")
    Send("{e up}")
    Sleep 50
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 350
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{n down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 525
    Send("{n up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 75
    Send("{t down}")
    Sleep 147
    Send("{t up}")
    Sleep 3
    Send("{y down}")
    Sleep 147
    Send("{y up}")
    Sleep 3
    Send("{q down}")
    Send("{t down}")
    Sleep 250
    Send("{q up}")
    Send("{t up}")
    Sleep 50
    Send("{q down}")
    Send("{r down}")
    Sleep 250
    Send("{q up}")
    Send("{r up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{n down}")
    Send("{q down}")
    Send("{r down}")
    Sleep 250
    Send("{n up}")
    Send("{q up}")
    Send("{r up}")
    Sleep 50
    Send("{n down}")
    Send("{q down}")
    Send("{t down}")
    Sleep 250
    Send("{n up}")
    Send("{q up}")
    Send("{t up}")
    Sleep 50
    Send("{n down}")
    Send("{q down}")
    Send("{y down}")
    Sleep 250
    Send("{n up}")
    Send("{q up}")
    Send("{y up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 350
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{t down}")
    Sleep 147
    Send("{t up}")
    Sleep 3
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{q up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 350
    Send("{t down}")
    Sleep 147
    Send("{t up}")
    Sleep 3
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{2 down}")
    Send("{e down}")
    Sleep 250
    Send("{2 up}")
    Send("{e up}")
    Sleep 50
    Send("{2 down}")
    Send("{r down}")
    Sleep 250
    Send("{2 up}")
    Send("{r up}")
    Sleep 50
    Send("{2 down}")
    Send("{e down}")
    Sleep 250
    Send("{2 up}")
    Send("{e up}")
    Sleep 50
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 350
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{q down}")
    Sleep 147
    Send("{q up}")
    Sleep 3
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 147
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 453
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{y down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{y up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 350
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{q down}")
    Send("{t down}")
    Sleep 250
    Send("{q up}")
    Send("{t up}")
    Sleep 50
    Send("{q down}")
    Send("{r down}")
    Sleep 250
    Send("{q up}")
    Send("{r up}")
    Sleep 50
    Send("{q down}")
    Send("{t down}")
    Sleep 250
    Send("{q up}")
    Send("{t up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{q down}")
    Send("{t down}")
    Sleep 250
    Send("{q up}")
    Send("{t up}")
    Sleep 50
    Send("{q down}")
    Send("{r down}")
    Sleep 250
    Send("{q up}")
    Send("{r up}")
    Sleep 50
    Send("{r down}")
    Send("{7 down}")
    Send("{w down}")
    Sleep 250
    Send("{r up}")
    Send("{7 up}")
    Send("{w up}")
    Sleep 350
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{y down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{y up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{y down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{y up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 50
    Send("{w down}")
    Send("{y down}")
    Sleep 250
    Send("{w up}")
    Send("{y up}")
    Sleep 50
    Send("{7 down}")
    Send("{w down}")
    Send("{7 down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{7 up}")
    Sleep 50
    Send("{7 down}")
    Send("{w down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Sleep 50
    Send("{7 down}")
    Send("{t down}")
    Sleep 250
    Send("{7 up}")
    Send("{t up}")
    Sleep 50
    Send("{y down}")
    Send("{r down}")
    Sleep 250
    Send("{y up}")
    Send("{r up}")
    Sleep 350
    Send("{t down}")
    Sleep 147
    Send("{t up}")
    Sleep 3
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{y down}")
    Send("{w down}")
    Sleep 250
    Send("{y up}")
    Send("{w up}")
    Sleep 350
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{2 down}")
    Sleep 147
    Send("{2 up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 650
    Send("{w down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 250
    Send("{w up}")
    Send("{t up}")
    Send("{7 up}")
    Sleep 650
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{q up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{q up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{q up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 147
    Send("{q up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 3
    Send("{t down}")
    Sleep 147
    Send("{t up}")
    Sleep 603
    Send("{7 down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 650
    Send("{y down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{y up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 650
    Send("{y down}")
    Send("{r down}")
    Sleep 250
    Send("{y up}")
    Send("{r up}")
    Sleep 50
    Send("{y down}")
    Send("{t down}")
    Sleep 250
    Send("{y up}")
    Send("{t up}")
    Sleep 50
    Send("{y down}")
    Send("{e down}")
    Sleep 250
    Send("{y up}")
    Send("{e up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 400
    Send("{r up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 400
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 400
    Send("{w up}")
    Send("{r up}")
    Send("{7 up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{e down}")
    Sleep 147
    Send("{e up}")
    Sleep 3
    Send("{r down}")
    Sleep 147
    Send("{r up}")
    Sleep 3
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{q up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 250
    Send("{q up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{r down}")
    Send("{q down}")
    Sleep 250
    Send("{r up}")
    Send("{q up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 147
    Send("{q up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 3
    Send("{t down}")
    Sleep 147
    Send("{t up}")
    Sleep 603
    Send("{7 down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{7 up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 650
    Send("{y down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{y up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 650
    Send("{y down}")
    Send("{r down}")
    Sleep 250
    Send("{y up}")
    Send("{r up}")
    Sleep 50
    Send("{y down}")
    Send("{t down}")
    Sleep 250
    Send("{y up}")
    Send("{t up}")
    Sleep 50
    Send("{y down}")
    Send("{e down}")
    Sleep 250
    Send("{y up}")
    Send("{e up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 400
    Send("{r up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 500
    Send("{w down}")
    Sleep 1125
    Send("{w up}")
}
