#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{u down}")
    Sleep 130
    Send("{u up}")
    Send("{u down}")
    Sleep 130
    Send("{u up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{7 down}")
    Sleep 130
    Send("{7 up}")
    Send("{7 down}")
    Sleep 130
    Send("{7 up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{u down}")
    Sleep 130
    Send("{u up}")
    Send("{u down}")
    Sleep 130
    Send("{u up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{7 down}")
    Sleep 130
    Send("{7 up}")
    Send("{7 down}")
    Sleep 130
    Send("{7 up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Sleep 130
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{w down}")
    Sleep 652
    Send("{w up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 391
    Send("{t up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Sleep 130
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Sleep 130
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{q down}")
    Sleep 1174
    Send("{q up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 130
    Send("{r up}")
    Send("{y up}")
    Sleep 130
    Send("{y down}")
    Send("{r down}")
    Sleep 130
    Send("{y up}")
    Send("{r up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{r up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{r up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{r up}")
    Send("{w down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{w up}")
    Send("{w down}")
    Send("{t down}")
    Sleep 652
    Send("{t up}")
    Send("{w up}")
    Send("{y down}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{y up}")
    Sleep 130
    Send("{y down}")
    Send("{r down}")
    Sleep 130
    Send("{y up}")
    Send("{r up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{r up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{r up}")
    Send("{w down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{w up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{r up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{r up}")
    Send("{t down}")
    Send("{w down}")
    Sleep 261
    Send("{t up}")
    Send("{w up}")
    Send("{w down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w up}")
    Send("{y down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{y up}")
    Send("{t down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{t up}")
    Send("{r down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{r up}")
    Send("{r down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{r up}")
    Send("{r down}")
    Send("{t down}")
    Sleep 261
    Send("{r up}")
    Send("{t up}")
    Send("{w down}")
    Send("{r down}")
    Sleep 261
    Send("{w up}")
    Send("{r up}")
    Send("{w down}")
    Send("{e down}")
    Sleep 261
    Send("{e up}")
    Send("{w up}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Sleep 130
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{q down}")
    Send("{e down}")
    Send("{q down}")
    Sleep 1174
    Send("{q up}")
    Send("{e up}")
    Send("{q up}")
    Sleep 1043
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{6 down}")
    Sleep 130
    Send("{6 up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{6 down}")
    Sleep 65
    Send("{6 up}")
    Send("{t down}")
    Sleep 65
    Send("{t up}")
    Send("{r down}")
    Sleep 65
    Send("{r up}")
    Send("{w down}")
    Sleep 65
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Sleep 130
    Send("{t down}")
    Send("{q down}")
    Sleep 1043
    Send("{q up}")
    Send("{t up}")
    Sleep 130
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Sleep 130
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{6 down}")
    Sleep 130
    Send("{6 up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{e down}")
    Sleep 130
    Send("{e up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{2 down}")
    Send("{2 down}")
    Sleep 261
    Send("{2 up}")
    Send("{2 up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{6 down}")
    Sleep 130
    Send("{6 up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Send("{3 down}")
    Sleep 1174
    Send("{3 up}")
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{r up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{q down}")
    Send("{e down}")
    Sleep 522
    Send("{e up}")
    Send("{q up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 522
    Send("{y up}")
    Send("{w up}")
    Send("{e down}")
    Send("{t down}")
    Sleep 522
    Send("{t up}")
    Send("{e up}")
    Send("{y down}")
    Send("{r down}")
    Sleep 522
    Send("{r up}")
    Send("{y up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 522
    Send("{t up}")
    Send("{q up}")
    Send("{y down}")
    Send("{e down}")
    Sleep 522
    Send("{y up}")
    Send("{e up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 1043
    Send("{w up}")
    Send("{y up}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{6 down}")
    Sleep 130
    Send("{6 up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{5 down}")
    Sleep 130
    Send("{5 up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{e down}")
    Sleep 130
    Send("{e up}")
    Send("{3 down}")
    Sleep 130
    Send("{3 up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{2 down}")
    Send("{6 down}")
    Sleep 913
    Send("{2 up}")
    Send("{6 up}")
    Send("{7 down}")
    Send("{3 down}")
    Sleep 1174
    Send("{3 up}")
    Send("{7 up}")
    Sleep 1043
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{6 down}")
    Sleep 130
    Send("{6 up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{6 down}")
    Sleep 65
    Send("{6 up}")
    Send("{t down}")
    Sleep 65
    Send("{t up}")
    Send("{r down}")
    Sleep 65
    Send("{r up}")
    Send("{w down}")
    Sleep 65
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Sleep 130
    Send("{t down}")
    Send("{q down}")
    Sleep 1043
    Send("{t up}")
    Send("{q up}")
    Sleep 130
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Sleep 130
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{6 down}")
    Sleep 130
    Send("{6 up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{e down}")
    Sleep 130
    Send("{e up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{2 down}")
    Send("{2 down}")
    Sleep 261
    Send("{2 up}")
    Send("{2 up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{6 down}")
    Sleep 130
    Send("{6 up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Send("{3 down}")
    Sleep 1174
    Send("{3 up}")
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{r up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{q down}")
    Send("{e down}")
    Sleep 522
    Send("{e up}")
    Send("{q up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 522
    Send("{y up}")
    Send("{w up}")
    Send("{e down}")
    Send("{t down}")
    Sleep 522
    Send("{t up}")
    Send("{e up}")
    Send("{y down}")
    Send("{r down}")
    Sleep 522
    Send("{r up}")
    Send("{y up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 522
    Send("{t up}")
    Send("{q up}")
    Send("{y down}")
    Send("{e down}")
    Sleep 522
    Send("{y up}")
    Send("{e up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 1043
    Send("{w up}")
    Send("{y up}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{6 down}")
    Sleep 130
    Send("{6 up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{5 down}")
    Sleep 130
    Send("{5 up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{e down}")
    Sleep 130
    Send("{e up}")
    Send("{3 down}")
    Sleep 130
    Send("{3 up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{2 down}")
    Send("{6 down}")
    Sleep 913
    Send("{6 up}")
    Send("{2 up}")
    Send("{7 down}")
    Send("{3 down}")
    Sleep 1174
    Send("{7 up}")
    Send("{3 up}")
    Send("{j down}")
    Sleep 1565
    Send("{j up}")
    Send("{r down}")
    Sleep 522
    Send("{r up}")
    Send("{e down}")
    Sleep 1043
    Send("{e up}")
    Send("{w down}")
    Sleep 1043
    Send("{w up}")
    Send("{r down}")
    Sleep 2087
    Send("{r up}")
    Sleep 2087
    Send("{j down}")
    Sleep 1565
    Send("{j up}")
    Send("{r down}")
    Sleep 522
    Send("{r up}")
    Send("{e down}")
    Sleep 1043
    Send("{e up}")
    Send("{w down}")
    Sleep 1043
    Send("{w up}")
    Send("{w down}")
    Sleep 2087
    Send("{w up}")
    Sleep 2087
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{m down}")
    Sleep 130
    Send("{m up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Sleep 261
    Send("{w down}")
    Send("{r down}")
    Sleep 196
    Send("{w up}")
    Sleep 65
    Send("{r up}")
    Send("{y down}")
    Send("{e down}")
    Sleep 130
    Send("{e up}")
    Send("{y up}")
    Sleep 261
    Send("{6 down}")
    Send("{q down}")
    Sleep 261
    Send("{6 up}")
    Send("{q up}")
    Send("{t down}")
    Send("{e down}")
    Sleep 130
    Send("{e up}")
    Send("{t up}")
    Sleep 130
    Send("{r down}")
    Send("{w down}")
    Sleep 261
    Send("{r up}")
    Send("{w up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{q up}")
    Send("{e down}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{e up}")
    Send("{w down}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{w up}")
    Sleep 261
    Send("{w down}")
    Send("{r down}")
    Sleep 196
    Send("{w up}")
    Sleep 65
    Send("{r up}")
    Send("{e down}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{e up}")
    Sleep 261
    Send("{6 down}")
    Send("{q down}")
    Sleep 261
    Send("{6 up}")
    Send("{q up}")
    Send("{e down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{e up}")
    Sleep 130
    Send("{r down}")
    Send("{w down}")
    Sleep 261
    Send("{r up}")
    Send("{w up}")
    Send("{y down}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{y up}")
    Send("{e down}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{e up}")
    Send("{r down}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{7 up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{w up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{6 down}")
    Send("{2 down}")
    Sleep 261
    Send("{2 up}")
    Send("{6 up}")
    Send("{2 down}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{2 up}")
    Send("{6 down}")
    Send("{2 down}")
    Sleep 261
    Send("{2 up}")
    Send("{6 up}")
    Send("{2 down}")
    Send("{6 down}")
    Sleep 130
    Send("{6 up}")
    Send("{2 up}")
    Send("{6 down}")
    Send("{2 down}")
    Sleep 261
    Send("{6 up}")
    Send("{2 up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{u down}")
    Sleep 261
    Send("{u up}")
    Send("{t up}")
    Send("{u down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{u up}")
    Send("{t down}")
    Send("{u down}")
    Sleep 261
    Send("{u up}")
    Send("{t up}")
    Send("{u down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{u up}")
    Send("{t down}")
    Send("{u down}")
    Sleep 261
    Send("{t up}")
    Send("{u up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{7 up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{w up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{w up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{w up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{w up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{7 up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{y down}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 130
    Send("{y up}")
    Send("{w up}")
    Send("{w down}")
    Send("{y down}")
    Sleep 261
    Send("{y up}")
    Send("{w up}")
    Send("{6 down}")
    Send("{2 down}")
    Sleep 261
    Send("{2 up}")
    Send("{6 up}")
    Send("{2 down}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{2 up}")
    Send("{6 down}")
    Send("{2 down}")
    Sleep 261
    Send("{2 up}")
    Send("{6 up}")
    Send("{2 down}")
    Send("{6 down}")
    Sleep 130
    Send("{6 up}")
    Send("{2 up}")
    Send("{6 down}")
    Send("{2 down}")
    Sleep 261
    Send("{6 up}")
    Send("{2 up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{u down}")
    Sleep 261
    Send("{u up}")
    Send("{t up}")
    Send("{u down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{u up}")
    Send("{t down}")
    Send("{u down}")
    Sleep 261
    Send("{u up}")
    Send("{t up}")
    Send("{u down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{u up}")
    Send("{t down}")
    Send("{u down}")
    Sleep 261
    Send("{t up}")
    Send("{u up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{7 up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{7 up}")
    Send("{r up}")
    Send("{7 down}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{7 up}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 261
    Send("{r up}")
    Send("{7 up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{q up}")
    Send("{t up}")
    Send("{q down}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q up}")
    Send("{t down}")
    Send("{q down}")
    Sleep 261
    Send("{t up}")
    Send("{q up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{w down}")
    Sleep 261
    Send("{w up}")
    Send("{y down}")
    Sleep 391
    Send("{y up}")
    Send("{6 down}")
    Sleep 261
    Send("{6 up}")
    Send("{t down}")
    Sleep 261
    Send("{t up}")
    Send("{r down}")
    Sleep 261
    Send("{r up}")
    Send("{w down}")
    Sleep 130
    Send("{w up}")
    Send("{r down}")
    Sleep 130
    Send("{r up}")
    Send("{t down}")
    Sleep 130
    Send("{t up}")
}
