#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{h down}")
    Send("{2 down}")
    Sleep 106
    Send("{h up}")
    Send("{2 up}")
    Sleep 338
    Send("{h down}")
    Send("{2 down}")
    Sleep 106
    Send("{h up}")
    Send("{2 up}")
    Sleep 338
    Send("{h down}")
    Send("{2 down}")
    Sleep 106
    Send("{h up}")
    Send("{2 up}")
    Sleep 338
    Send("{h down}")
    Send("{2 down}")
    Sleep 51
    Send("{h up}")
    Send("{2 up}")
    Sleep 171
    Send("{b down}")
    Send("{3 down}")
    Sleep 106
    Send("{b up}")
    Send("{3 up}")
    Sleep 338
    Send("{b down}")
    Send("{3 down}")
    Sleep 106
    Send("{b up}")
    Send("{3 up}")
    Sleep 338
    Send("{b down}")
    Send("{3 down}")
    Sleep 106
    Send("{b up}")
    Send("{3 up}")
    Sleep 338
    Send("{b down}")
    Send("{3 down}")
    Sleep 106
    Send("{b up}")
    Send("{3 up}")
    Sleep 116
    Send("{3 down}")
    Sleep 51
    Send("{3 up}")
    Sleep 171
    Send("{b down}")
    Send("{3 down}")
    Sleep 106
    Send("{b up}")
    Send("{3 up}")
    Sleep 116
    Send("{h down}")
    Send("{q down}")
    Sleep 106
    Send("{h up}")
    Send("{q up}")
    Sleep 338
    Send("{h down}")
    Send("{q down}")
    Sleep 106
    Send("{h up}")
    Send("{q up}")
    Sleep 338
    Send("{h down}")
    Send("{q down}")
    Sleep 106
    Send("{h up}")
    Send("{q up}")
    Sleep 338
    Send("{h down}")
    Send("{q down}")
    Sleep 51
    Send("{h up}")
    Send("{q up}")
    Sleep 171
    Send("{v down}")
    Send("{q down}")
    Sleep 106
    Send("{v up}")
    Send("{q up}")
    Sleep 338
    Send("{v down}")
    Send("{q down}")
    Sleep 106
    Send("{v up}")
    Send("{q up}")
    Sleep 338
    Send("{v down}")
    Send("{q down}")
    Sleep 106
    Send("{v up}")
    Send("{q up}")
    Sleep 338
    Send("{v down}")
    Send("{q down}")
    Sleep 106
    Send("{v up}")
    Send("{q up}")
    Sleep 116
    Send("{q down}")
    Sleep 51
    Send("{q up}")
    Sleep 171
    Send("{v down}")
    Send("{q down}")
    Sleep 106
    Send("{v up}")
    Send("{q up}")
}
