#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{g down}")
    Send("{5 down}")
    Sleep 1654
    Send("{g up}")
    Send("{5 up}")
    Sleep 85
    Send("{m down}")
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{x down}")
    Send("{g down}")
    Sleep 107
    Send("{x up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{c down}")
    Sleep 107
    Send("{c up}")
    Sleep 110
    Send("{g down}")
    Send("{m down}")
    Sleep 107
    Send("{g up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{g down}")
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Send("{g up}")
    Sleep 221
    Send("{v down}")
    Send("{m down}")
    Sleep 107
    Send("{v up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{v down}")
    Send("{g down}")
    Sleep 214
    Send("{v up}")
    Send("{g up}")
    Sleep 221
    Send("{c down}")
    Send("{m down}")
    Sleep 107
    Send("{c up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{z down}")
    Sleep 107
    Send("{z up}")
    Sleep 110
    Send("{c down}")
    Send("{g down}")
    Sleep 214
    Send("{c up}")
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{x down}")
    Send("{g down}")
    Sleep 107
    Send("{x up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{c down}")
    Sleep 107
    Send("{c up}")
    Sleep 110
    Send("{g down}")
    Send("{m down}")
    Sleep 107
    Send("{g up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{g down}")
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{n down}")
    Send("{x down}")
    Sleep 107
    Send("{n up}")
    Sleep 107
    Send("{x up}")
    Sleep 3
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{x down}")
    Send("{n down}")
    Sleep 107
    Send("{x up}")
    Sleep 107
    Send("{n up}")
    Sleep 3
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{n down}")
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{n down}")
    Sleep 214
    Send("{n up}")
    Sleep 136
    Send("{n up}")
    Sleep 85
    Send("{m down}")
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{x down}")
    Send("{g down}")
    Sleep 107
    Send("{x up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{c down}")
    Sleep 107
    Send("{c up}")
    Sleep 110
    Send("{g down}")
    Send("{m down}")
    Sleep 107
    Send("{g up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{g down}")
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Send("{g up}")
    Sleep 221
    Send("{v down}")
    Send("{m down}")
    Sleep 107
    Send("{v up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{v down}")
    Send("{g down}")
    Sleep 214
    Send("{v up}")
    Send("{g up}")
    Sleep 221
    Send("{c down}")
    Send("{m down}")
    Sleep 107
    Send("{c up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{z down}")
    Sleep 107
    Send("{z up}")
    Sleep 110
    Send("{c down}")
    Send("{g down}")
    Sleep 214
    Send("{c up}")
    Send("{g up}")
    Sleep 221
    Send("{m down}")
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 107
    Send("{s up}")
    Sleep 110
    Send("{x down}")
    Send("{g down}")
    Sleep 107
    Send("{x up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{c down}")
    Sleep 107
    Send("{c up}")
    Sleep 110
    Send("{g down}")
    Send("{m down}")
    Sleep 107
    Send("{g up}")
    Sleep 107
    Send("{m up}")
    Sleep 3
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 110
    Send("{g down}")
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{n down}")
    Send("{x down}")
    Sleep 107
    Send("{n up}")
    Sleep 107
    Send("{x up}")
    Sleep 3
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{x down}")
    Send("{n down}")
    Sleep 107
    Send("{x up}")
    Sleep 107
    Send("{n up}")
    Sleep 3
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 110
    Send("{n down}")
    Send("{n down}")
    Send("{x down}")
    Sleep 214
    Send("{x up}")
    Sleep 221
    Send("{n down}")
    Sleep 214
    Send("{n up}")
    Sleep 136
    Send("{n up}")
    Send("{n up}")
    Sleep 85
    Send("{g down}")
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{h down}")
    Sleep 107
    Send("{h up}")
    Sleep 110
    Send("{j down}")
    Send("{s down}")
    Sleep 107
    Send("{j up}")
    Sleep 107
    Send("{s up}")
    Sleep 3
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{s down}")
    Send("{g down}")
    Sleep 107
    Send("{s up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{s down}")
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Send("{s up}")
    Sleep 221
    Send("{x down}")
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 107
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{x down}")
    Send("{n down}")
    Sleep 214
    Send("{x up}")
    Send("{n up}")
    Sleep 221
    Send("{s down}")
    Send("{g down}")
    Sleep 107
    Send("{s up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{s down}")
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{h down}")
    Sleep 107
    Send("{h up}")
    Sleep 110
    Send("{j down}")
    Send("{s down}")
    Sleep 107
    Send("{j up}")
    Sleep 107
    Send("{s up}")
    Sleep 3
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{s down}")
    Send("{g down}")
    Sleep 107
    Send("{s up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{s down}")
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Send("{s up}")
    Sleep 221
    Send("{x down}")
    Send("{x down}")
    Sleep 107
    Send("{x up}")
    Sleep 107
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{x down}")
    Send("{n down}")
    Sleep 214
    Send("{x up}")
    Send("{n up}")
    Sleep 221
    Send("{s down}")
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 212
    Send("{s up}")
    Sleep 8
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{h down}")
    Sleep 107
    Send("{h up}")
    Sleep 110
    Send("{j down}")
    Send("{s down}")
    Sleep 107
    Send("{j up}")
    Sleep 107
    Send("{s up}")
    Sleep 3
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{2 down}")
    Send("{g down}")
    Sleep 107
    Send("{2 up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{2 down}")
    Send("{s down}")
    Sleep 214
    Send("{2 up}")
    Send("{s up}")
    Sleep 221
    Send("{w down}")
    Send("{x down}")
    Sleep 107
    Send("{w up}")
    Sleep 107
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{w down}")
    Send("{n down}")
    Sleep 214
    Send("{w up}")
    Send("{n up}")
    Sleep 221
    Send("{2 down}")
    Send("{g down}")
    Sleep 107
    Send("{2 up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{2 down}")
    Send("{s down}")
    Sleep 214
    Send("{2 up}")
    Send("{s up}")
    Sleep 221
    Send("{g down}")
    Send("{g down}")
    Sleep 107
    Send("{g up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{h down}")
    Sleep 107
    Send("{h up}")
    Sleep 110
    Send("{j down}")
    Send("{s down}")
    Sleep 107
    Send("{j up}")
    Sleep 107
    Send("{s up}")
    Sleep 3
    Send("{m down}")
    Sleep 107
    Send("{m up}")
    Sleep 110
    Send("{2 down}")
    Send("{g down}")
    Sleep 107
    Send("{2 up}")
    Sleep 107
    Send("{g up}")
    Sleep 3
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{2 down}")
    Send("{s down}")
    Sleep 214
    Send("{2 up}")
    Send("{s up}")
    Sleep 221
    Send("{w down}")
    Send("{x down}")
    Sleep 107
    Send("{w up}")
    Sleep 107
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Sleep 107
    Send("{j up}")
    Sleep 110
    Send("{w down}")
    Send("{n down}")
    Sleep 214
    Send("{w up}")
    Send("{n up}")
    Sleep 221
    Send("{2 down}")
    Send("{g down}")
    Sleep 214
    Send("{g up}")
    Sleep 212
    Send("{2 up}")
    Sleep 8
    Send("{s down}")
    Sleep 214
    Send("{s up}")
    Sleep 221
    Send("{m down}")
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Send("{g down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{c down}")
    Sleep 104
    Send("{c up}")
    Sleep 107
    Send("{g down}")
    Send("{m down}")
    Sleep 104
    Send("{g up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Send("{g up}")
    Sleep 215
    Send("{v down}")
    Send("{m down}")
    Sleep 104
    Send("{v up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{v down}")
    Send("{g down}")
    Sleep 208
    Send("{v up}")
    Send("{g up}")
    Sleep 215
    Send("{c down}")
    Send("{m down}")
    Sleep 104
    Send("{c up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{z down}")
    Sleep 104
    Send("{z up}")
    Sleep 107
    Send("{c down}")
    Send("{g down}")
    Sleep 208
    Send("{c up}")
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Send("{g down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{c down}")
    Sleep 104
    Send("{c up}")
    Sleep 107
    Send("{g down}")
    Send("{m down}")
    Sleep 104
    Send("{g up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{n down}")
    Send("{x down}")
    Sleep 104
    Send("{n up}")
    Sleep 104
    Send("{x up}")
    Sleep 3
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{x down}")
    Send("{n down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{n up}")
    Sleep 3
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{n down}")
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{n down}")
    Sleep 208
    Send("{n up}")
    Sleep 132
    Send("{n up}")
    Sleep 83
    Send("{m down}")
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Send("{g down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{c down}")
    Sleep 104
    Send("{c up}")
    Sleep 107
    Send("{g down}")
    Send("{m down}")
    Sleep 104
    Send("{g up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Send("{g up}")
    Sleep 215
    Send("{v down}")
    Send("{m down}")
    Sleep 104
    Send("{v up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{v down}")
    Send("{g down}")
    Sleep 208
    Send("{v up}")
    Send("{g up}")
    Sleep 215
    Send("{c down}")
    Send("{m down}")
    Sleep 104
    Send("{c up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{z down}")
    Sleep 104
    Send("{z up}")
    Sleep 107
    Send("{c down}")
    Send("{g down}")
    Sleep 208
    Send("{c up}")
    Send("{g up}")
    Sleep 215
    Send("{m down}")
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{x down}")
    Send("{m down}")
    Sleep 104
    Send("{x up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{c down}")
    Sleep 104
    Send("{c up}")
    Sleep 107
    Send("{g down}")
    Send("{n down}")
    Sleep 104
    Send("{g up}")
    Sleep 104
    Send("{n up}")
    Sleep 3
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Send("{b down}")
    Sleep 104
    Send("{g up}")
    Sleep 104
    Send("{b up}")
    Sleep 3
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{g down}")
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{g down}")
    Send("{c down}")
    Sleep 104
    Send("{g up}")
    Sleep 104
    Send("{c up}")
    Sleep 3
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 107
    Send("{m down}")
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{s down}")
    Sleep 208
    Send("{s up}")
    Sleep 132
    Send("{m up}")
    Sleep 83
    Send("{m down}")
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{g down}")
    Send("{w down}")
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 8
    Send("{g up}")
    Send("{w up}")
    Sleep 2
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{e down}")
    Send("{g down}")
    Sleep 104
    Send("{e up}")
    Send("{g up}")
    Sleep 107
    Send("{5 down}")
    Send("{m down}")
    Sleep 104
    Send("{5 up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{g down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 7
    Send("{g up}")
    Send("{5 up}")
    Sleep 3
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{r down}")
    Send("{m down}")
    Sleep 104
    Send("{r up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{g down}")
    Send("{r down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 96
    Send("{g up}")
    Send("{s up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 7
    Send("{g up}")
    Send("{r up}")
    Sleep 3
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{e down}")
    Send("{m down}")
    Sleep 104
    Send("{e up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{q down}")
    Sleep 104
    Send("{q up}")
    Sleep 107
    Send("{g down}")
    Send("{e down}")
    Send("{g down}")
    Send("{z down}")
    Sleep 96
    Send("{g up}")
    Send("{z up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 7
    Send("{g up}")
    Send("{e up}")
    Sleep 3
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{m down}")
    Send("{m down}")
    Sleep 104
    Send("{m up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{g down}")
    Send("{w down}")
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 8
    Send("{g up}")
    Send("{w up}")
    Sleep 2
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{e down}")
    Send("{g down}")
    Sleep 104
    Send("{e up}")
    Send("{g up}")
    Sleep 107
    Send("{5 down}")
    Send("{m down}")
    Sleep 104
    Send("{5 up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{5 down}")
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 8
    Send("{5 up}")
    Sleep 2
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{u down}")
    Send("{g down}")
    Sleep 104
    Send("{u up}")
    Send("{g up}")
    Sleep 107
    Send("{y down}")
    Send("{x down}")
    Sleep 104
    Send("{y up}")
    Sleep 104
    Send("{x up}")
    Sleep 3
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{n down}")
    Send("{w down}")
    Send("{n down}")
    Send("{g down}")
    Sleep 96
    Send("{n up}")
    Send("{g up}")
    Sleep 8
    Send("{n up}")
    Send("{w up}")
    Sleep 2
    Send("{h down}")
    Sleep 96
    Send("{h up}")
    Sleep 10
    Send("{5 down}")
    Send("{n down}")
    Sleep 104
    Send("{5 up}")
    Send("{n up}")
    Sleep 107
    Send("{y down}")
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{n down}")
    Send("{g down}")
    Sleep 96
    Send("{n up}")
    Send("{g up}")
    Sleep 10
    Send("{h down}")
    Sleep 96
    Send("{h up}")
    Sleep 10
    Send("{n down}")
    Sleep 104
    Send("{n up}")
    Sleep 25
    Send("{y up}")
    Sleep 83
    Send("{u down}")
    Send("{m down}")
    Sleep 104
    Send("{u up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{5 down}")
    Send("{w down}")
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 8
    Send("{5 up}")
    Send("{w up}")
    Sleep 2
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{e down}")
    Send("{g down}")
    Sleep 104
    Send("{e up}")
    Send("{g up}")
    Sleep 107
    Send("{5 down}")
    Send("{m down}")
    Sleep 104
    Send("{5 up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{5 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 7
    Send("{5 up}")
    Send("{5 up}")
    Sleep 3
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{r down}")
    Send("{m down}")
    Sleep 104
    Send("{r up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{5 down}")
    Send("{r down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 96
    Send("{g up}")
    Send("{s up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 7
    Send("{5 up}")
    Send("{r up}")
    Sleep 3
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{e down}")
    Send("{m down}")
    Sleep 104
    Send("{e up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{q down}")
    Sleep 104
    Send("{q up}")
    Sleep 107
    Send("{5 down}")
    Send("{e down}")
    Send("{g down}")
    Send("{z down}")
    Sleep 96
    Send("{g up}")
    Send("{z up}")
    Sleep 10
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 7
    Send("{5 up}")
    Send("{e up}")
    Sleep 3
    Send("{g down}")
    Sleep 104
    Send("{g up}")
    Sleep 107
    Send("{u down}")
    Send("{m down}")
    Sleep 104
    Send("{u up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{2 down}")
    Sleep 104
    Send("{2 up}")
    Sleep 107
    Send("{5 down}")
    Send("{w down}")
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 8
    Send("{5 up}")
    Send("{w up}")
    Sleep 2
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{e down}")
    Send("{g down}")
    Sleep 104
    Send("{e up}")
    Send("{g up}")
    Sleep 107
    Send("{5 down}")
    Send("{m down}")
    Sleep 104
    Send("{5 up}")
    Sleep 104
    Send("{m up}")
    Sleep 3
    Send("{w down}")
    Sleep 104
    Send("{w up}")
    Sleep 107
    Send("{5 down}")
    Send("{g down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{x up}")
    Sleep 8
    Send("{5 up}")
    Sleep 2
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 10
    Send("{u down}")
    Send("{g down}")
    Sleep 104
    Send("{u up}")
    Send("{g up}")
    Sleep 107
    Send("{y down}")
    Send("{x down}")
    Sleep 104
    Send("{y up}")
    Sleep 104
    Send("{x up}")
    Sleep 3
    Send("{5 down}")
    Sleep 104
    Send("{5 up}")
    Sleep 107
    Send("{y down}")
    Send("{w down}")
    Send("{n down}")
    Send("{g down}")
    Sleep 96
    Send("{n up}")
    Send("{g up}")
    Sleep 8
    Send("{y up}")
    Send("{w up}")
    Sleep 2
    Send("{h down}")
    Sleep 96
    Send("{h up}")
    Sleep 10
    Send("{5 down}")
    Send("{n down}")
    Sleep 104
    Send("{5 up}")
    Send("{n up}")
    Sleep 107
    Send("{y down}")
    Send("{x down}")
    Sleep 208
    Send("{x up}")
    Sleep 215
    Send("{n down}")
    Send("{g down}")
    Sleep 96
    Send("{n up}")
    Send("{g up}")
    Sleep 10
    Send("{h down}")
    Sleep 96
    Send("{h up}")
    Sleep 10
    Send("{n down}")
    Sleep 104
    Send("{n up}")
    Sleep 25
    Send("{y up}")
    Sleep 83
    Send("{5 down}")
    Send("{g down}")
    Sleep 104
    Send("{5 up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{6 down}")
    Sleep 104
    Send("{6 up}")
    Sleep 107
    Send("{7 down}")
    Send("{5 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 8
    Send("{7 up}")
    Sleep 2
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{u down}")
    Send("{s down}")
    Sleep 104
    Send("{u up}")
    Send("{s up}")
    Sleep 66
    Send("{5 up}")
    Sleep 41
    Send("{2 down}")
    Send("{g down}")
    Sleep 104
    Send("{2 up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 7
    Send("{2 up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 66
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{w down}")
    Send("{x down}")
    Sleep 104
    Send("{w up}")
    Sleep 104
    Send("{x up}")
    Sleep 3
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{w down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{x down}")
    Send("{j down}")
    Sleep 96
    Send("{x up}")
    Send("{j up}")
    Sleep 10
    Send("{s down}")
    Sleep 96
    Send("{s up}")
    Sleep 7
    Send("{w up}")
    Sleep 3
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 66
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{2 down}")
    Send("{g down}")
    Sleep 104
    Send("{2 up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 7
    Send("{2 up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 66
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{5 down}")
    Send("{g down}")
    Sleep 104
    Send("{5 up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{6 down}")
    Sleep 104
    Send("{6 up}")
    Sleep 107
    Send("{7 down}")
    Send("{5 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 8
    Send("{7 up}")
    Sleep 2
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{u down}")
    Send("{s down}")
    Sleep 104
    Send("{u up}")
    Send("{s up}")
    Sleep 66
    Send("{5 up}")
    Sleep 41
    Send("{2 down}")
    Send("{g down}")
    Sleep 104
    Send("{2 up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 7
    Send("{2 up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 66
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{w down}")
    Send("{x down}")
    Sleep 104
    Send("{w up}")
    Sleep 104
    Send("{x up}")
    Sleep 3
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{w down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{x down}")
    Send("{j down}")
    Sleep 96
    Send("{x up}")
    Send("{j up}")
    Sleep 10
    Send("{s down}")
    Sleep 96
    Send("{s up}")
    Sleep 7
    Send("{w up}")
    Sleep 3
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 66
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{2 down}")
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 206
    Send("{2 up}")
    Sleep 8
    Send("{5 down}")
    Send("{7 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 66
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{5 down}")
    Send("{g down}")
    Sleep 104
    Send("{5 up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{6 down}")
    Sleep 104
    Send("{6 up}")
    Sleep 107
    Send("{7 down}")
    Send("{5 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 8
    Send("{7 up}")
    Sleep 2
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 7
    Send("{5 up}")
    Sleep 3
    Send("{u down}")
    Send("{s down}")
    Sleep 104
    Send("{u up}")
    Send("{s up}")
    Sleep 107
    Send("{2 down}")
    Send("{g down}")
    Sleep 104
    Send("{2 up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 7
    Send("{2 up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{w down}")
    Send("{x down}")
    Sleep 104
    Send("{w up}")
    Sleep 104
    Send("{x up}")
    Sleep 3
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{w down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{x down}")
    Send("{j down}")
    Sleep 96
    Send("{x up}")
    Send("{j up}")
    Sleep 10
    Send("{s down}")
    Sleep 96
    Send("{s up}")
    Sleep 7
    Send("{w up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 3
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{2 down}")
    Send("{g down}")
    Sleep 104
    Send("{2 up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 7
    Send("{2 up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{5 down}")
    Send("{g down}")
    Sleep 104
    Send("{5 up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{6 down}")
    Sleep 104
    Send("{6 up}")
    Sleep 107
    Send("{7 down}")
    Send("{5 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 8
    Send("{7 up}")
    Sleep 2
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 7
    Send("{5 up}")
    Sleep 3
    Send("{u down}")
    Send("{s down}")
    Sleep 104
    Send("{u up}")
    Send("{s up}")
    Sleep 107
    Send("{2 down}")
    Send("{g down}")
    Sleep 104
    Send("{2 up}")
    Sleep 104
    Send("{g up}")
    Sleep 3
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{2 down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 7
    Send("{2 up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 3
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 107
    Send("{w down}")
    Send("{x down}")
    Sleep 104
    Send("{w up}")
    Sleep 104
    Send("{x up}")
    Sleep 3
    Send("{7 down}")
    Sleep 104
    Send("{7 up}")
    Sleep 107
    Send("{w down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{x down}")
    Send("{j down}")
    Sleep 96
    Send("{x up}")
    Send("{j up}")
    Sleep 10
    Send("{s down}")
    Sleep 96
    Send("{s up}")
    Sleep 7
    Send("{w up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 3
    Send("{x down}")
    Sleep 104
    Send("{x up}")
    Sleep 107
    Send("{2 down}")
    Send("{g down}")
    Sleep 208
    Send("{g up}")
    Sleep 206
    Send("{2 up}")
    Sleep 8
    Send("{5 down}")
    Send("{7 down}")
    Send("{s down}")
    Send("{j down}")
    Sleep 96
    Send("{s up}")
    Send("{j up}")
    Sleep 10
    Send("{z down}")
    Sleep 96
    Send("{z up}")
    Sleep 10
    Send("{s down}")
    Sleep 104
    Send("{s up}")
    Sleep 66
    Send("{5 up}")
    Send("{7 up}")
    Sleep 41
    Send("{m down}")
    Send("{m down}")
    Sleep 102
    Send("{m up}")
    Sleep 23
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 70
    Send("{2 down}")
    Sleep 55
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 34
    Send("{2 up}")
    Sleep 92
    Send("{g up}")
    Sleep 13
    Send("{g down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 102
    Send("{g up}")
    Send("{w up}")
    Sleep 23
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 70
    Send("{e down}")
    Sleep 55
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 34
    Send("{e up}")
    Sleep 92
    Send("{g up}")
    Sleep 13
    Send("{5 down}")
    Send("{m down}")
    Sleep 102
    Send("{5 up}")
    Sleep 23
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 70
    Send("{w down}")
    Sleep 55
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 34
    Send("{w up}")
    Sleep 92
    Send("{g up}")
    Sleep 13
    Send("{g down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 124
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 66
    Send("{g up}")
    Send("{5 up}")
    Sleep 58
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{r down}")
    Send("{m down}")
    Sleep 102
    Send("{r up}")
    Sleep 23
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 70
    Send("{2 down}")
    Sleep 55
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 34
    Send("{2 up}")
    Sleep 92
    Send("{g up}")
    Sleep 13
    Send("{g down}")
    Send("{r down}")
    Send("{s down}")
    Sleep 124
    Send("{s up}")
    Sleep 13
    Send("{v down}")
    Sleep 66
    Send("{g up}")
    Send("{r up}")
    Sleep 58
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{e down}")
    Send("{m down}")
    Sleep 102
    Send("{e up}")
    Sleep 23
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 70
    Send("{q down}")
    Sleep 55
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 34
    Send("{q up}")
    Sleep 92
    Send("{g up}")
    Sleep 13
    Send("{g down}")
    Send("{e down}")
    Send("{z down}")
    Sleep 124
    Send("{z up}")
    Sleep 13
    Send("{v down}")
    Sleep 66
    Send("{g up}")
    Send("{e up}")
    Sleep 58
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 126
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Send("{m down}")
    Sleep 102
    Send("{m up}")
    Sleep 23
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 70
    Send("{2 down}")
    Sleep 55
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 34
    Send("{2 up}")
    Sleep 92
    Send("{g up}")
    Sleep 13
    Send("{g down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 102
    Send("{g up}")
    Send("{w up}")
    Sleep 23
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 70
    Send("{e down}")
    Sleep 55
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 34
    Send("{e up}")
    Sleep 92
    Send("{g up}")
    Sleep 13
    Send("{5 down}")
    Send("{m down}")
    Sleep 102
    Send("{5 up}")
    Sleep 23
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 70
    Send("{w down}")
    Sleep 55
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 34
    Send("{w up}")
    Sleep 92
    Send("{g up}")
    Sleep 13
    Send("{m down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 102
    Send("{m up}")
    Send("{5 up}")
    Sleep 23
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 70
    Send("{u down}")
    Sleep 55
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 34
    Send("{u up}")
    Sleep 92
    Send("{g up}")
    Sleep 13
    Send("{y down}")
    Send("{x down}")
    Sleep 102
    Send("{y up}")
    Sleep 23
    Send("{x up}")
    Sleep 13
    Send("{h down}")
    Sleep 70
    Send("{5 down}")
    Sleep 55
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 34
    Send("{5 up}")
    Sleep 92
    Send("{n up}")
    Sleep 13
    Send("{n down}")
    Send("{w down}")
    Send("{g down}")
    Sleep 102
    Send("{n up}")
    Send("{w up}")
    Sleep 23
    Send("{g up}")
    Sleep 13
    Send("{h down}")
    Sleep 70
    Send("{5 down}")
    Sleep 55
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 34
    Send("{5 up}")
    Sleep 92
    Send("{n up}")
    Sleep 13
    Send("{y down}")
    Send("{x down}")
    Sleep 124
    Send("{x up}")
    Sleep 13
    Send("{h down}")
    Sleep 124
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 126
    Send("{n up}")
    Sleep 13
    Send("{n down}")
    Send("{w down}")
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{h down}")
    Sleep 124
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 99
    Send("{n up}")
    Send("{w up}")
    Send("{y up}")
    Sleep 27
    Send("{n up}")
    Sleep 13
    Send("{u down}")
    Send("{m down}")
    Sleep 100
    Send("{u up}")
    Sleep 22
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 68
    Send("{2 down}")
    Sleep 54
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 33
    Send("{2 up}")
    Sleep 90
    Send("{g up}")
    Sleep 13
    Send("{5 down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 100
    Send("{5 up}")
    Send("{w up}")
    Sleep 22
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 68
    Send("{e down}")
    Sleep 54
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 33
    Send("{e up}")
    Sleep 90
    Send("{g up}")
    Sleep 13
    Send("{5 down}")
    Send("{m down}")
    Sleep 100
    Send("{5 up}")
    Sleep 22
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 68
    Send("{w down}")
    Sleep 54
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 33
    Send("{w up}")
    Sleep 90
    Send("{g up}")
    Sleep 13
    Send("{5 down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 122
    Send("{x up}")
    Sleep 13
    Send("{v down}")
    Sleep 65
    Send("{5 up}")
    Send("{5 up}")
    Sleep 57
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{r down}")
    Send("{m down}")
    Sleep 100
    Send("{r up}")
    Sleep 22
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 68
    Send("{2 down}")
    Sleep 54
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 33
    Send("{2 up}")
    Sleep 90
    Send("{g up}")
    Sleep 13
    Send("{5 down}")
    Send("{r down}")
    Send("{s down}")
    Sleep 122
    Send("{s up}")
    Sleep 13
    Send("{v down}")
    Sleep 65
    Send("{5 up}")
    Send("{r up}")
    Sleep 57
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{e down}")
    Send("{m down}")
    Sleep 100
    Send("{e up}")
    Sleep 22
    Send("{m up}")
    Sleep 13
    Send("{v down}")
    Sleep 68
    Send("{q down}")
    Sleep 54
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 33
    Send("{q up}")
    Sleep 90
    Send("{g up}")
    Sleep 13
    Send("{5 down}")
    Send("{e down}")
    Send("{z down}")
    Sleep 122
    Send("{z up}")
    Sleep 13
    Send("{v down}")
    Sleep 65
    Send("{5 up}")
    Send("{e up}")
    Sleep 57
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 124
    Send("{g up}")
    Sleep 13
    Send("{u down}")
    Send("{m down}")
    Sleep 98
    Send("{u up}")
    Sleep 22
    Send("{m up}")
    Sleep 12
    Send("{v down}")
    Sleep 67
    Send("{2 down}")
    Sleep 52
    Send("{v up}")
    Sleep 12
    Send("{g down}")
    Sleep 32
    Send("{2 up}")
    Sleep 87
    Send("{g up}")
    Sleep 12
    Send("{5 down}")
    Send("{w down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 94
    Send("{5 up}")
    Send("{w up}")
    Sleep 97
    Send("{e down}")
    Sleep 92
    Send("{e up}")
    Sleep 59
    Send("{m up}")
    Send("{m up}")
    Sleep 37
    Send("{5 down}")
    Send("{n down}")
    Send("{m down}")
    Send("{n down}")
    Sleep 90
    Send("{5 up}")
    Sleep 93
    Send("{w down}")
    Sleep 89
    Send("{w up}")
    Sleep 56
    Send("{n up}")
    Send("{m up}")
    Send("{n up}")
    Sleep 35
    Send("{5 down}")
    Send("{b down}")
    Send("{m down}")
    Send("{b down}")
    Sleep 87
    Send("{5 up}")
    Sleep 90
    Send("{u down}")
    Sleep 85
    Send("{u up}")
    Sleep 54
    Send("{b up}")
    Send("{m up}")
    Send("{b up}")
    Sleep 34
    Send("{5 down}")
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 84
    Send("{5 up}")
    Sleep 86
    Send("{w down}")
    Sleep 82
    Send("{w up}")
    Sleep 52
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 33
    Send("{u down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{c down}")
    Send("{m down}")
    Send("{c down}")
    Sleep 81
    Send("{5 up}")
    Sleep 83
    Send("{u down}")
    Sleep 79
    Send("{u up}")
    Send("{w up}")
    Send("{u up}")
    Sleep 50
    Send("{c up}")
    Send("{m up}")
    Send("{c up}")
    Sleep 31
    Send("{u down}")
    Send("{x down}")
    Send("{m down}")
    Send("{x down}")
    Sleep 285
    Send("{x up}")
    Send("{m up}")
    Send("{x up}")
    Sleep 31
    Send("{s down}")
    Send("{m down}")
    Send("{s down}")
    Sleep 254
    Send("{u up}")
    Sleep 31
    Send("{s up}")
    Send("{m up}")
    Send("{s up}")
    Sleep 31
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{2 down}")
    Send("{n down}")
    Sleep 78
    Send("{2 up}")
    Send("{n up}")
    Sleep 80
    Send("{w down}")
    Send("{b down}")
    Sleep 78
    Send("{w up}")
    Send("{b up}")
    Sleep 80
    Send("{e down}")
    Send("{g down}")
    Sleep 78
    Send("{e up}")
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{5 up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{w down}")
    Send("{n down}")
    Sleep 78
    Send("{w up}")
    Send("{n up}")
    Sleep 80
    Send("{5 down}")
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 78
    Send("{5 up}")
    Sleep 2
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{r down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{r up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{2 down}")
    Send("{n down}")
    Sleep 78
    Send("{2 up}")
    Send("{n up}")
    Sleep 80
    Send("{r down}")
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 78
    Send("{r up}")
    Sleep 2
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{e down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{e up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{q down}")
    Send("{n down}")
    Sleep 78
    Send("{q up}")
    Send("{n up}")
    Sleep 80
    Send("{e down}")
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 78
    Send("{e up}")
    Sleep 2
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{2 down}")
    Send("{n down}")
    Sleep 78
    Send("{2 up}")
    Send("{n up}")
    Sleep 80
    Send("{w down}")
    Send("{b down}")
    Sleep 78
    Send("{w up}")
    Send("{b up}")
    Sleep 80
    Send("{e down}")
    Send("{g down}")
    Sleep 78
    Send("{e up}")
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{5 up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{w down}")
    Send("{n down}")
    Sleep 78
    Send("{w up}")
    Send("{n up}")
    Sleep 80
    Send("{5 down}")
    Send("{b down}")
    Sleep 78
    Send("{5 up}")
    Send("{b up}")
    Sleep 80
    Send("{u down}")
    Send("{g down}")
    Sleep 78
    Send("{u up}")
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{y up}")
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{5 down}")
    Send("{s down}")
    Sleep 78
    Send("{5 up}")
    Send("{s up}")
    Sleep 80
    Send("{w down}")
    Send("{m down}")
    Sleep 78
    Send("{w up}")
    Send("{m up}")
    Sleep 80
    Send("{5 down}")
    Send("{n down}")
    Sleep 78
    Send("{5 up}")
    Send("{n up}")
    Sleep 19
    Send("{y up}")
    Send("{w up}")
    Sleep 62
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 19
    Send("{y up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 62
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{2 down}")
    Send("{n down}")
    Sleep 78
    Send("{2 up}")
    Send("{n up}")
    Sleep 80
    Send("{w down}")
    Send("{b down}")
    Sleep 78
    Send("{w up}")
    Send("{b up}")
    Sleep 80
    Send("{e down}")
    Send("{g down}")
    Sleep 78
    Send("{e up}")
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{5 up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{w down}")
    Send("{n down}")
    Sleep 78
    Send("{w up}")
    Send("{n up}")
    Sleep 80
    Send("{5 down}")
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 78
    Send("{5 up}")
    Sleep 2
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{r down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{r up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{2 down}")
    Send("{n down}")
    Sleep 78
    Send("{2 up}")
    Send("{n up}")
    Sleep 80
    Send("{r down}")
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 78
    Send("{r up}")
    Sleep 2
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{e down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{e up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{q down}")
    Send("{n down}")
    Sleep 78
    Send("{q up}")
    Send("{n up}")
    Sleep 80
    Send("{e down}")
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 78
    Send("{e up}")
    Sleep 2
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{2 down}")
    Send("{n down}")
    Sleep 78
    Send("{2 up}")
    Send("{n up}")
    Sleep 80
    Send("{w down}")
    Send("{b down}")
    Sleep 78
    Send("{w up}")
    Send("{b up}")
    Sleep 80
    Send("{e down}")
    Send("{g down}")
    Sleep 78
    Send("{e up}")
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 78
    Send("{5 up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 80
    Send("{w down}")
    Send("{n down}")
    Sleep 78
    Send("{w up}")
    Send("{n up}")
    Sleep 80
    Send("{5 down}")
    Send("{b down}")
    Sleep 78
    Send("{5 up}")
    Send("{b up}")
    Sleep 80
    Send("{u down}")
    Send("{g down}")
    Sleep 78
    Send("{u up}")
    Send("{g up}")
    Sleep 19
    Send("{u up}")
    Sleep 62
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{y up}")
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{5 down}")
    Send("{s down}")
    Sleep 78
    Send("{5 up}")
    Send("{s up}")
    Sleep 80
    Send("{y down}")
    Send("{w down}")
    Send("{m down}")
    Sleep 78
    Send("{y up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 80
    Send("{5 down}")
    Send("{n down}")
    Sleep 78
    Send("{5 up}")
    Send("{n up}")
    Sleep 19
    Send("{y up}")
    Send("{w up}")
    Sleep 62
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{m down}")
    Sleep 78
    Send("{m up}")
    Sleep 80
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 19
    Send("{y up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 62
    Send("{5 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{5 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{6 down}")
    Send("{c down}")
    Sleep 78
    Send("{6 up}")
    Send("{c up}")
    Sleep 80
    Send("{7 down}")
    Send("{x down}")
    Sleep 78
    Send("{7 up}")
    Send("{x up}")
    Sleep 80
    Send("{u down}")
    Send("{s down}")
    Sleep 78
    Send("{u up}")
    Send("{s up}")
    Sleep 19
    Send("{5 up}")
    Sleep 62
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{2 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{7 down}")
    Send("{c down}")
    Sleep 78
    Send("{7 up}")
    Send("{c up}")
    Sleep 49
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 78
    Send("{2 up}")
    Sleep 2
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 49
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{w down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{w up}")
    Send("{x up}")
    Send("{x up}")
    Sleep 78
    Send("{w up}")
    Send("{5 up}")
    Sleep 2
    Send("{7 down}")
    Send("{s down}")
    Sleep 78
    Send("{7 up}")
    Send("{s up}")
    Sleep 80
    Send("{w down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 78
    Send("{w up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 2
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{2 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 78
    Send("{2 up}")
    Send("{5 up}")
    Sleep 2
    Send("{7 down}")
    Send("{c down}")
    Sleep 78
    Send("{7 up}")
    Send("{c up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 78
    Send("{2 up}")
    Sleep 2
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 49
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{5 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{5 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 65
    Send("{5 up}")
    Sleep 15
    Send("{6 down}")
    Send("{5 down}")
    Send("{c down}")
    Sleep 78
    Send("{6 up}")
    Send("{5 up}")
    Send("{c up}")
    Sleep 80
    Send("{7 down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 78
    Send("{7 up}")
    Send("{5 up}")
    Send("{x up}")
    Sleep 80
    Send("{u down}")
    Send("{5 down}")
    Send("{s down}")
    Sleep 78
    Send("{u up}")
    Send("{5 up}")
    Send("{s up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{2 up}")
    Send("{2 up}")
    Send("{5 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{7 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{c down}")
    Sleep 78
    Send("{7 up}")
    Send("{2 up}")
    Send("{5 up}")
    Send("{c up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 78
    Send("{2 up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 2
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{w down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 78
    Send("{w up}")
    Send("{w up}")
    Send("{5 up}")
    Send("{x up}")
    Send("{x up}")
    Sleep 80
    Send("{7 down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{s down}")
    Sleep 78
    Send("{7 up}")
    Send("{w up}")
    Send("{5 up}")
    Send("{s up}")
    Sleep 80
    Send("{w down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 78
    Send("{w up}")
    Send("{w up}")
    Send("{5 up}")
    Sleep 2
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 74
    Send("{2 up}")
    Sleep 6
    Send("{x down}")
    Sleep 78
    Send("{x up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 19
    Send("{2 up}")
    Send("{5 up}")
    Sleep 62
    Send("{5 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{5 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{6 down}")
    Send("{v down}")
    Sleep 78
    Send("{6 up}")
    Send("{v up}")
    Sleep 80
    Send("{7 down}")
    Send("{d down}")
    Sleep 78
    Send("{7 up}")
    Send("{d up}")
    Sleep 80
    Send("{u down}")
    Send("{s down}")
    Sleep 78
    Send("{u up}")
    Send("{s up}")
    Sleep 19
    Send("{5 up}")
    Sleep 62
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{2 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{7 down}")
    Send("{v down}")
    Sleep 78
    Send("{7 up}")
    Send("{v up}")
    Sleep 49
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 78
    Send("{2 up}")
    Sleep 2
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 49
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{3 down}")
    Send("{3 down}")
    Send("{5 down}")
    Send("{d down}")
    Send("{d down}")
    Sleep 78
    Send("{3 up}")
    Send("{d up}")
    Send("{d up}")
    Sleep 78
    Send("{3 up}")
    Send("{5 up}")
    Sleep 2
    Send("{7 down}")
    Send("{s down}")
    Sleep 78
    Send("{7 up}")
    Send("{s up}")
    Sleep 80
    Send("{3 down}")
    Send("{5 down}")
    Send("{7 down}")
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 78
    Send("{3 up}")
    Send("{5 up}")
    Send("{7 up}")
    Sleep 2
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{2 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 78
    Send("{2 up}")
    Send("{5 up}")
    Sleep 2
    Send("{7 down}")
    Send("{v down}")
    Sleep 78
    Send("{7 up}")
    Send("{v up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 78
    Send("{2 up}")
    Sleep 2
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 49
    Send("{2 up}")
    Send("{5 up}")
    Sleep 31
    Send("{5 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{5 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 65
    Send("{5 up}")
    Sleep 15
    Send("{6 down}")
    Send("{5 down}")
    Send("{v down}")
    Sleep 78
    Send("{6 up}")
    Send("{5 up}")
    Send("{v up}")
    Sleep 80
    Send("{7 down}")
    Send("{5 down}")
    Send("{d down}")
    Sleep 78
    Send("{7 up}")
    Send("{5 up}")
    Send("{d up}")
    Sleep 80
    Send("{u down}")
    Send("{5 down}")
    Send("{s down}")
    Sleep 78
    Send("{u up}")
    Send("{5 up}")
    Send("{s up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{2 up}")
    Send("{2 up}")
    Send("{5 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{7 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{v down}")
    Sleep 78
    Send("{7 up}")
    Send("{2 up}")
    Send("{5 up}")
    Send("{v up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 78
    Send("{2 up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 2
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 80
    Send("{3 down}")
    Send("{3 down}")
    Send("{5 down}")
    Send("{d down}")
    Send("{d down}")
    Sleep 78
    Send("{3 up}")
    Send("{3 up}")
    Send("{5 up}")
    Send("{d up}")
    Send("{d up}")
    Sleep 80
    Send("{7 down}")
    Send("{3 down}")
    Send("{5 down}")
    Send("{s down}")
    Sleep 78
    Send("{7 up}")
    Send("{3 up}")
    Send("{5 up}")
    Send("{s up}")
    Sleep 80
    Send("{3 down}")
    Send("{3 down}")
    Send("{5 down}")
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 78
    Send("{3 up}")
    Send("{3 up}")
    Send("{5 up}")
    Sleep 2
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 80
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 78
    Send("{g up}")
    Send("{g up}")
    Sleep 80
    Send("{v down}")
    Sleep 78
    Send("{v up}")
    Sleep 74
    Send("{2 up}")
    Sleep 6
    Send("{d down}")
    Sleep 78
    Send("{d up}")
    Sleep 80
    Send("{s down}")
    Sleep 78
    Send("{s up}")
    Sleep 19
    Send("{2 up}")
    Send("{5 up}")
    Sleep 62
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{2 down}")
    Send("{n down}")
    Sleep 74
    Send("{2 up}")
    Send("{n up}")
    Sleep 76
    Send("{w down}")
    Send("{b down}")
    Sleep 74
    Send("{w up}")
    Send("{b up}")
    Sleep 76
    Send("{e down}")
    Send("{g down}")
    Sleep 74
    Send("{e up}")
    Send("{g up}")
    Sleep 18
    Send("{u up}")
    Sleep 59
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{5 up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{w down}")
    Send("{n down}")
    Sleep 74
    Send("{w up}")
    Send("{n up}")
    Sleep 76
    Send("{5 down}")
    Send("{b down}")
    Sleep 74
    Send("{b up}")
    Sleep 74
    Send("{5 up}")
    Sleep 2
    Send("{g down}")
    Sleep 74
    Send("{g up}")
    Sleep 18
    Send("{u up}")
    Sleep 59
    Send("{r down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{r up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{2 down}")
    Send("{n down}")
    Sleep 74
    Send("{2 up}")
    Send("{n up}")
    Sleep 76
    Send("{r down}")
    Send("{b down}")
    Sleep 74
    Send("{b up}")
    Sleep 74
    Send("{r up}")
    Sleep 2
    Send("{g down}")
    Sleep 74
    Send("{g up}")
    Sleep 18
    Send("{u up}")
    Sleep 59
    Send("{e down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{e up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{q down}")
    Send("{n down}")
    Sleep 74
    Send("{q up}")
    Send("{n up}")
    Sleep 76
    Send("{e down}")
    Send("{b down}")
    Sleep 74
    Send("{b up}")
    Sleep 74
    Send("{e up}")
    Sleep 2
    Send("{g down}")
    Sleep 74
    Send("{g up}")
    Sleep 18
    Send("{u up}")
    Sleep 59
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{2 down}")
    Send("{n down}")
    Sleep 74
    Send("{2 up}")
    Send("{n up}")
    Sleep 76
    Send("{w down}")
    Send("{b down}")
    Sleep 74
    Send("{w up}")
    Send("{b up}")
    Sleep 76
    Send("{e down}")
    Send("{g down}")
    Sleep 74
    Send("{e up}")
    Send("{g up}")
    Sleep 18
    Send("{u up}")
    Sleep 59
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 74
    Send("{5 up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 76
    Send("{w down}")
    Send("{n down}")
    Sleep 74
    Send("{w up}")
    Send("{n up}")
    Sleep 76
    Send("{5 down}")
    Send("{b down}")
    Sleep 74
    Send("{5 up}")
    Send("{b up}")
    Sleep 76
    Send("{u down}")
    Send("{g down}")
    Sleep 74
    Send("{u up}")
    Send("{g up}")
    Sleep 18
    Send("{u up}")
    Sleep 59
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 74
    Send("{y up}")
    Send("{x up}")
    Send("{x up}")
    Sleep 76
    Send("{5 down}")
    Send("{s down}")
    Sleep 74
    Send("{5 up}")
    Send("{s up}")
    Sleep 76
    Send("{w down}")
    Send("{m down}")
    Sleep 74
    Send("{w up}")
    Send("{m up}")
    Sleep 76
    Send("{5 down}")
    Send("{n down}")
    Sleep 74
    Send("{5 up}")
    Send("{n up}")
    Sleep 18
    Send("{y up}")
    Send("{w up}")
    Sleep 59
    Send("{y down}")
    Send("{y down}")
    Send("{w down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 74
    Send("{x up}")
    Send("{x up}")
    Sleep 76
    Send("{s down}")
    Sleep 74
    Send("{s up}")
    Sleep 76
    Send("{m down}")
    Sleep 74
    Send("{m up}")
    Sleep 76
    Send("{n down}")
    Sleep 74
    Send("{n up}")
    Sleep 18
    Send("{y up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 59
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 72
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{2 down}")
    Send("{u down}")
    Send("{n down}")
    Sleep 72
    Send("{2 up}")
    Send("{u up}")
    Send("{n up}")
    Sleep 74
    Send("{w down}")
    Send("{u down}")
    Send("{b down}")
    Sleep 72
    Send("{w up}")
    Send("{u up}")
    Send("{b up}")
    Sleep 74
    Send("{e down}")
    Send("{u down}")
    Send("{g down}")
    Sleep 72
    Send("{e up}")
    Send("{u up}")
    Send("{g up}")
    Sleep 74
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 72
    Send("{5 up}")
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 74
    Send("{w down}")
    Send("{u down}")
    Send("{n down}")
    Sleep 72
    Send("{w up}")
    Send("{u up}")
    Send("{n up}")
    Sleep 74
    Send("{5 down}")
    Send("{u down}")
    Send("{b down}")
    Sleep 72
    Send("{b up}")
    Sleep 72
    Send("{5 up}")
    Send("{u up}")
    Sleep 2
    Send("{g down}")
    Sleep 72
    Send("{g up}")
    Sleep 74
    Send("{r down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 72
    Send("{r up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{2 down}")
    Send("{u down}")
    Send("{n down}")
    Sleep 72
    Send("{2 up}")
    Send("{n up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{r down}")
    Send("{u down}")
    Send("{b down}")
    Sleep 72
    Send("{b up}")
    Sleep 61
    Send("{u up}")
    Sleep 11
    Send("{r up}")
    Sleep 2
    Send("{g down}")
    Sleep 72
    Send("{g up}")
    Sleep 74
    Send("{e down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 72
    Send("{e up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{q down}")
    Send("{u down}")
    Send("{n down}")
    Sleep 72
    Send("{q up}")
    Send("{n up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{e down}")
    Send("{u down}")
    Send("{b down}")
    Sleep 72
    Send("{b up}")
    Sleep 61
    Send("{u up}")
    Sleep 11
    Send("{e up}")
    Sleep 2
    Send("{g down}")
    Sleep 72
    Send("{g up}")
    Sleep 74
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 72
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 61
    Send("{u up}")
    Sleep 14
    Send("{2 down}")
    Send("{u down}")
    Send("{n down}")
    Sleep 72
    Send("{2 up}")
    Send("{u up}")
    Send("{n up}")
    Sleep 74
    Send("{w down}")
    Send("{u down}")
    Send("{b down}")
    Sleep 72
    Send("{w up}")
    Send("{u up}")
    Send("{b up}")
    Sleep 74
    Send("{e down}")
    Send("{u down}")
    Send("{g down}")
    Sleep 72
    Send("{e up}")
    Send("{u up}")
    Send("{g up}")
    Sleep 74
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 70
    Send("{5 up}")
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 73
    Send("{w down}")
    Send("{u down}")
    Send("{n down}")
    Sleep 70
    Send("{w up}")
    Send("{u up}")
    Send("{n up}")
    Sleep 73
    Send("{5 down}")
    Send("{u down}")
    Send("{b down}")
    Sleep 69
    Send("{5 up}")
    Send("{u up}")
    Send("{b up}")
    Sleep 71
    Send("{u down}")
    Send("{u down}")
    Send("{g down}")
    Sleep 69
    Send("{u up}")
    Send("{u up}")
    Send("{g up}")
    Sleep 71
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 67
    Send("{5 up}")
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 69
    Send("{w down}")
    Send("{n down}")
    Sleep 67
    Send("{w up}")
    Send("{n up}")
    Sleep 69
    Send("{5 down}")
    Send("{b down}")
    Sleep 67
    Send("{5 up}")
    Send("{b up}")
    Sleep 69
    Send("{u down}")
    Send("{g down}")
    Sleep 67
    Send("{u up}")
    Send("{g up}")
    Sleep 69
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 67
    Send("{m up}")
    Send("{m up}")
    Sleep 69
    Send("{n down}")
    Sleep 67
    Send("{n up}")
    Sleep 69
    Send("{b down}")
    Sleep 67
    Send("{b up}")
    Sleep 69
    Send("{g down}")
    Sleep 67
    Send("{g up}")
    Sleep 16
    Send("{u up}")
    Sleep 53
    Send("{m down}")
    Send("{m down}")
    Sleep 79
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 95
    Send("{w up}")
    Send("{u up}")
    Sleep 484
    Send("{m down}")
    Send("{m down}")
    Sleep 79
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 95
    Send("{w up}")
    Send("{u up}")
    Sleep 484
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 57
    Send("{u up}")
    Sleep 59
    Send("{2 down}")
    Sleep 57
    Send("{2 up}")
    Sleep 36
    Send("{b up}")
    Send("{b up}")
    Sleep 23
    Send("{w down}")
    Send("{x down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 57
    Send("{w up}")
    Sleep 59
    Send("{e down}")
    Sleep 57
    Send("{e up}")
    Sleep 36
    Send("{x up}")
    Send("{b up}")
    Send("{m up}")
    Sleep 23
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 57
    Send("{5 up}")
    Sleep 59
    Send("{w down}")
    Sleep 57
    Send("{w up}")
    Sleep 36
    Send("{g up}")
    Send("{g up}")
    Sleep 23
    Send("{5 down}")
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 57
    Send("{5 up}")
    Sleep 59
    Send("{u down}")
    Sleep 57
    Send("{u up}")
    Sleep 36
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 23
    Send("{7 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 57
    Send("{7 up}")
    Sleep 59
    Send("{5 down}")
    Sleep 57
    Send("{5 up}")
    Sleep 36
    Send("{g up}")
    Send("{g up}")
    Sleep 23
    Send("{7 down}")
    Send("{s down}")
    Send("{g down}")
    Send("{j down}")
    Sleep 57
    Send("{7 up}")
    Sleep 59
    Send("{2 down}")
    Sleep 57
    Send("{2 up}")
    Sleep 36
    Send("{s up}")
    Send("{g up}")
    Send("{j up}")
    Sleep 23
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 186
    Send("{u up}")
    Sleep 23
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 23
    Send("{m down}")
    Send("{m down}")
    Sleep 79
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 95
    Send("{w up}")
    Send("{u up}")
    Sleep 484
    Send("{m down}")
    Send("{m down}")
    Sleep 79
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 95
    Send("{w up}")
    Send("{u up}")
    Sleep 484
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 57
    Send("{u up}")
    Sleep 59
    Send("{2 down}")
    Sleep 57
    Send("{2 up}")
    Sleep 36
    Send("{b up}")
    Send("{b up}")
    Sleep 23
    Send("{w down}")
    Send("{x down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 57
    Send("{w up}")
    Sleep 59
    Send("{e down}")
    Sleep 57
    Send("{e up}")
    Sleep 36
    Send("{x up}")
    Send("{b up}")
    Send("{m up}")
    Sleep 23
    Send("{5 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 57
    Send("{5 up}")
    Sleep 59
    Send("{w down}")
    Sleep 57
    Send("{w up}")
    Sleep 36
    Send("{g up}")
    Send("{g up}")
    Sleep 23
    Send("{5 down}")
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 57
    Send("{5 up}")
    Sleep 59
    Send("{u down}")
    Sleep 57
    Send("{u up}")
    Sleep 36
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 23
    Send("{7 down}")
    Send("{g down}")
    Send("{g down}")
    Sleep 57
    Send("{7 up}")
    Sleep 59
    Send("{5 down}")
    Sleep 57
    Send("{5 up}")
    Sleep 36
    Send("{g up}")
    Send("{g up}")
    Sleep 23
    Send("{7 down}")
    Send("{s down}")
    Send("{g down}")
    Send("{j down}")
    Sleep 57
    Send("{7 up}")
    Sleep 59
    Send("{2 down}")
    Sleep 57
    Send("{2 up}")
    Sleep 36
    Send("{s up}")
    Send("{g up}")
    Send("{j up}")
    Sleep 23
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 208
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 186
    Send("{u up}")
    Sleep 23
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 23
    Send("{m down}")
    Send("{m down}")
    Sleep 79
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 208
    Send("{w up}")
    Send("{u up}")
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 484
    Send("{m down}")
    Send("{m down}")
    Sleep 79
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 95
    Send("{w up}")
    Send("{u up}")
    Sleep 484
    Send("{m down}")
    Send("{m down}")
    Sleep 79
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 56
    Send("{6 down}")
    Sleep 58
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 7
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 56
    Send("{6 down}")
    Sleep 58
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 7
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 95
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{6 down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 14
    Send("{6 down}")
    Sleep 55
    Send("{y up}")
    Send("{7 down}")
    Sleep 3
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 7
    Send("{6 up}")
    Send("{y down}")
    Sleep 31
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Sleep 39
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 56
    Send("{6 down}")
    Sleep 58
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 7
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 56
    Send("{6 down}")
    Sleep 58
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 7
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{w up}")
    Send("{u up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{x down}")
    Send("{v down}")
    Send("{h down}")
    Send("{m down}")
    Sleep 114
    Send("{x up}")
    Send("{v up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 95
    Send("{w up}")
    Send("{u up}")
    Sleep 484
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Sleep 52
    Send("{m up}")
    Sleep 5
    Send("{m down}")
    Send("{m down}")
    Sleep 79
    Send("{6 down}")
    Sleep 41
    Send("{6 up}")
    Send("{y down}")
    Sleep 69
    Send("{y up}")
    Send("{7 down}")
    Sleep 18
    Send("{m up}")
    Send("{m up}")
    Sleep 23
    Send("{7 up}")
    Send("{w down}")
    Send("{u down}")
    Send("{m down}")
    Send("{x down}")
    Send("{g down}")
    Send("{m down}")
    Sleep 114
    Send("{m up}")
    Send("{x up}")
    Send("{g up}")
    Send("{m up}")
    Sleep 95
    Send("{w up}")
    Send("{u up}")
}
