#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{x down}")
    Sleep 372
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 268
    Send("{x up}")
    Sleep 89
    Send("{n down}")
    Send("{n down}")
    Sleep 134
    Send("{5 up}")
    Sleep 15
    Send("{n up}")
    Send("{w up}")
    Sleep 60
    Send("{n up}")
    Sleep 149
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 283
    Send("{n up}")
    Sleep 60
    Send("{n up}")
    Sleep 15
    Send("{x down}")
    Send("{m down}")
    Sleep 149
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 15
    Send("{n up}")
    Sleep 164
    Send("{5 down}")
    Sleep 15
    Send("{n down}")
    Send("{w down}")
    Sleep 179
    Send("{n down}")
    Sleep 30
    Send("{m up}")
    Sleep 30
    Send("{x up}")
    Sleep 119
    Send("{n down}")
    Sleep 179
    Send("{w up}")
    Send("{n up}")
    Send("{5 up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 193
    Send("{n up}")
    Sleep 164
    Send("{m down}")
    Sleep 119
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 208
    Send("{w down}")
    Send("{m down}")
    Send("{5 down}")
    Sleep 268
    Send("{m up}")
    Sleep 15
    Send("{n up}")
    Sleep 74
    Send("{g down}")
    Send("{m down}")
    Sleep 179
    Send("{w up}")
    Sleep 30
    Send("{5 up}")
    Send("{m up}")
    Sleep 149
    Send("{w down}")
    Send("{m down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 15
    Send("{m up}")
    Sleep 164
    Send("{m down}")
    Sleep 60
    Send("{g up}")
    Sleep 30
    Send("{n up}")
    Sleep 89
    Send("{m down}")
    Sleep 179
    Send("{m up}")
    Send("{w down}")
    Sleep 45
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Send("{m up}")
    Sleep 119
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 164
    Send("{m up}")
    Sleep 193
    Send("{m down}")
    Sleep 193
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Send("{m up}")
    Sleep 149
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{m up}")
    Sleep 89
    Send("{n down}")
    Sleep 149
    Send("{5 up}")
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Sleep 193
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 15
    Send("{w up}")
    Sleep 223
    Send("{n up}")
    Sleep 119
    Send("{c down}")
    Send("{e down}")
    Sleep 208
    Send("{e up}")
    Sleep 15
    Send("{2 up}")
    Sleep 15
    Send("{n up}")
    Sleep 30
    Send("{e up}")
    Sleep 89
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 268
    Send("{c up}")
    Sleep 89
    Send("{n down}")
    Send("{5 down}")
    Sleep 60
    Send("{e up}")
    Sleep 149
    Send("{n up}")
    Sleep 30
    Send("{e up}")
    Send("{2 up}")
    Sleep 119
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 164
    Send("{5 up}")
    Sleep 15
    Send("{e down}")
    Sleep 60
    Send("{n up}")
    Sleep 119
    Send("{c down}")
    Sleep 164
    Send("{c up}")
    Sleep 15
    Send("{e up}")
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 164
    Send("{n down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 179
    Send("{m down}")
    Sleep 45
    Send("{n up}")
    Sleep 45
    Send("{m up}")
    Sleep 60
    Send("{e up}")
    Sleep 30
    Send("{b down}")
    Send("{m down}")
    Sleep 119
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 164
    Send("{m up}")
    Sleep 45
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Send("{n down}")
    Sleep 149
    Send("{b up}")
    Sleep 208
    Send("{b down}")
    Send("{n up}")
    Send("{m down}")
    Sleep 119
    Send("{b up}")
    Sleep 60
    Send("{t up}")
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Sleep 164
    Send("{c down}")
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Sleep 15
    Send("{n down}")
    Sleep 45
    Send("{m up}")
    Sleep 104
    Send("{c up}")
    Sleep 179
    Send("{x down}")
    Sleep 15
    Send("{n up}")
    Send("{w down}")
    Sleep 179
    Send("{m up}")
    Send("{w up}")
    Sleep 30
    Send("{t up}")
    Sleep 134
    Send("{n down}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Sleep 89
    Send("{w up}")
    Sleep 89
    Send("{w down}")
    Sleep 89
    Send("{x up}")
    Sleep 89
    Send("{n down}")
    Sleep 179
    Send("{5 up}")
    Send("{n up}")
    Sleep 15
    Send("{w up}")
    Sleep 164
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{n up}")
    Sleep 89
    Send("{x down}")
    Sleep 238
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 89
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 208
    Send("{x up}")
    Sleep 134
    Send("{n down}")
    Sleep 223
    Send("{5 up}")
    Send("{w up}")
    Sleep 30
    Send("{n up}")
    Sleep 119
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{n up}")
    Sleep 74
    Send("{x down}")
    Sleep 15
    Send("{w up}")
    Sleep 238
    Send("{5 up}")
    Sleep 15
    Send("{n up}")
    Sleep 15
    Send("{w up}")
    Sleep 89
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 283
    Send("{x up}")
    Sleep 60
    Send("{n down}")
    Sleep 15
    Send("{n down}")
    Sleep 208
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 119
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 179
    Send("{m down}")
    Sleep 89
    Send("{n up}")
    Send("{n up}")
    Sleep 74
    Send("{x down}")
    Sleep 268
    Send("{5 up}")
    Send("{w up}")
    Sleep 15
    Send("{n up}")
    Sleep 89
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 89
    Send("{m up}")
    Sleep 119
    Send("{x up}")
    Sleep 149
    Send("{n down}")
    Sleep 193
    Send("{n up}")
    Sleep 15
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 15
    Send("{n up}")
    Sleep 119
    Send("{g down}")
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 193
    Send("{g up}")
    Sleep 164
    Send("{m down}")
    Send("{n up}")
    Send("{m down}")
    Sleep 238
    Send("{5 up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 119
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{m up}")
    Send("{w down}")
    Sleep 238
    Send("{m up}")
    Send("{w up}")
    Sleep 119
    Send("{g down}")
    Send("{w down}")
    Sleep 238
    Send("{5 up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 104
    Send("{5 down}")
    Sleep 15
    Send("{m down}")
    Send("{w down}")
    Send("{e down}")
    Sleep 74
    Send("{w up}")
    Sleep 119
    Send("{g up}")
    Sleep 164
    Send("{m down}")
    Send("{5 down}")
    Sleep 15
    Send("{e up}")
    Sleep 208
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Send("{m up}")
    Sleep 104
    Send("{w down}")
    Sleep 15
    Send("{m down}")
    Send("{5 down}")
    Sleep 119
    Send("{m up}")
    Sleep 238
    Send("{m down}")
    Sleep 238
    Send("{5 up}")
    Send("{m up}")
    Send("{w up}")
    Sleep 104
    Send("{w down}")
    Sleep 15
    Send("{m down}")
    Send("{5 down}")
    Sleep 164
    Send("{m up}")
    Sleep 134
    Send("{5 up}")
    Sleep 60
    Send("{n down}")
    Send("{e down}")
    Sleep 149
    Send("{5 up}")
    Send("{m up}")
    Send("{w up}")
    Sleep 119
    Send("{e up}")
    Sleep 89
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 268
    Send("{n up}")
    Send("{e up}")
    Sleep 89
    Send("{c down}")
    Send("{e down}")
    Sleep 268
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 30
    Send("{e up}")
    Sleep 15
    Send("{2 down}")
    Sleep 15
    Send("{n down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 253
    Send("{c up}")
    Sleep 104
    Send("{n down}")
    Send("{5 down}")
    Sleep 15
    Send("{e up}")
    Sleep 193
    Send("{e up}")
    Sleep 15
    Send("{2 up}")
    Sleep 15
    Send("{n up}")
    Sleep 119
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 179
    Send("{e down}")
    Sleep 30
    Send("{5 up}")
    Sleep 45
    Send("{n up}")
    Sleep 104
    Send("{c down}")
    Sleep 179
    Send("{c up}")
    Sleep 30
    Send("{e up}")
    Send("{2 up}")
    Sleep 30
    Send("{n up}")
    Sleep 104
    Send("{n down}")
    Sleep 15
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 179
    Send("{n up}")
    Sleep 179
    Send("{b down}")
    Send("{m down}")
    Sleep 30
    Send("{e up}")
    Sleep 30
    Send("{n up}")
    Sleep 30
    Send("{e up}")
    Send("{2 up}")
    Sleep 268
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 15
    Send("{m up}")
    Send("{w down}")
    Sleep 223
    Send("{w up}")
    Sleep 30
    Send("{b up}")
    Sleep 74
    Send("{g down}")
    Sleep 15
    Send("{w down}")
    Sleep 179
    Send("{g up}")
    Sleep 30
    Send("{t up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 149
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 15
    Send("{c down}")
    Send("{e down}")
    Sleep 15
    Send("{w up}")
    Sleep 134
    Send("{c up}")
    Sleep 15
    Send("{w down}")
    Sleep 60
    Send("{e up}")
    Sleep 119
    Send("{x down}")
    Sleep 119
    Send("{m up}")
    Sleep 30
    Send("{w up}")
    Sleep 15
    Send("{t up}")
    Sleep 179
    Send("{w down}")
    Sleep 15
    Send("{n down}")
    Send("{5 down}")
    Sleep 179
    Send("{w up}")
    Sleep 60
    Send("{x up}")
    Sleep 119
    Send("{n down}")
    Send("{w down}")
    Sleep 238
    Send("{5 up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 119
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{w up}")
    Send("{e down}")
    Sleep 179
    Send("{e up}")
    Send("{5 down}")
    Sleep 60
    Send("{n up}")
    Sleep 119
    Send("{x down}")
    Sleep 238
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 104
    Send("{w down}")
    Sleep 15
    Send("{n down}")
    Send("{5 down}")
    Sleep 193
    Send("{x up}")
    Sleep 164
    Send("{n down}")
    Sleep 208
    Send("{n up}")
    Sleep 15
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 119
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 313
    Send("{n up}")
    Sleep 45
    Send("{x down}")
    Sleep 208
    Send("{5 up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 149
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 193
    Send("{x up}")
    Send("{5 up}")
    Sleep 164
    Send("{g down}")
    Send("{e down}")
    Sleep 208
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 30
    Send("{g up}")
    Sleep 104
    Send("{5 down}")
    Sleep 15
    Send("{n down}")
    Send("{n down}")
    Send("{w down}")
    Send("{w down}")
    Sleep 30
    Send("{e up}")
    Sleep 134
    Send("{e down}")
    Sleep 15
    Send("{n up}")
    Send("{w up}")
    Sleep 179
    Send("{n down}")
    Sleep 179
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 149
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 208
    Send("{n up}")
    Sleep 149
    Send("{c down}")
    Sleep 208
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Send("{2 up}")
    Sleep 134
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 208
    Send("{c up}")
    Sleep 149
    Send("{n down}")
    Sleep 179
    Send("{e up}")
    Send("{2 up}")
    Send("{n up}")
    Sleep 164
    Send("{e down}")
    Sleep 15
    Send("{n down}")
    Send("{2 down}")
    Sleep 164
    Send("{e up}")
    Sleep 149
    Send("{n up}")
    Sleep 45
    Send("{c down}")
    Send("{5 down}")
    Sleep 179
    Send("{2 up}")
    Send("{n up}")
    Send("{e up}")
    Sleep 149
    Send("{5 up}")
    Sleep 15
    Send("{e down}")
    Sleep 15
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 179
    Send("{e up}")
    Send("{w down}")
    Sleep 30
    Send("{c up}")
    Sleep 149
    Send("{m down}")
    Sleep 119
    Send("{2 up}")
    Send("{n up}")
    Send("{e up}")
    Sleep 238
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 238
    Send("{m up}")
    Sleep 119
    Send("{g down}")
    Sleep 208
    Send("{5 up}")
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Sleep 134
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{g up}")
    Sleep 89
    Send("{m down}")
    Sleep 253
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Send("{m up}")
    Sleep 74
    Send("{5 down}")
    Sleep 15
    Send("{m down}")
    Send("{w down}")
    Sleep 208
    Send("{m up}")
    Sleep 30
    Send("{w up}")
    Sleep 119
    Send("{m down}")
    Send("{5 down}")
    Sleep 164
    Send("{m up}")
    Sleep 74
    Send("{w up}")
    Send("{m up}")
    Send("{5 up}")
    Sleep 104
    Send("{m down}")
    Sleep 15
    Send("{g down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Sleep 45
    Send("{5 up}")
    Sleep 134
    Send("{u down}")
    Sleep 15
    Send("{g up}")
    Sleep 30
    Send("{y up}")
    Sleep 134
    Send("{b down}")
    Sleep 119
    Send("{5 up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 238
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 238
    Send("{b up}")
    Sleep 119
    Send("{x down}")
    Sleep 179
    Send("{t up}")
    Sleep 30
    Send("{w up}")
    Send("{m up}")
    Sleep 134
    Send("{w down}")
    Sleep 15
    Send("{m down}")
    Send("{t down}")
    Sleep 313
    Send("{x up}")
    Sleep 45
    Send("{b down}")
    Sleep 223
    Send("{w up}")
    Sleep 15
    Send("{t up}")
    Send("{m up}")
    Sleep 119
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 104
    Send("{b up}")
    Sleep 164
    Send("{u up}")
    Sleep 89
    Send("{b down}")
    Send("{u down}")
    Sleep 164
    Send("{b up}")
    Sleep 45
    Send("{t up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 134
    Send("{m down}")
    Sleep 15
    Send("{w down}")
    Send("{t down}")
    Sleep 15
    Send("{c down}")
    Send("{u up}")
    Sleep 15
    Send("{5 down}")
    Sleep 149
    Send("{y down}")
    Sleep 30
    Send("{5 up}")
    Sleep 60
    Send("{c up}")
    Sleep 89
    Send("{x down}")
    Sleep 119
    Send("{w up}")
    Send("{m up}")
    Sleep 30
    Send("{t up}")
    Sleep 208
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 15
    Send("{5 down}")
    Sleep 15
    Send("{y up}")
    Sleep 208
    Send("{x up}")
    Sleep 119
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Sleep 30
    Send("{n up}")
    Sleep 30
    Send("{w up}")
    Sleep 179
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 268
    Send("{n up}")
    Sleep 89
    Send("{x down}")
    Sleep 149
    Send("{5 up}")
    Send("{w up}")
    Sleep 30
    Send("{n up}")
    Sleep 164
    Send("{n down}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{x up}")
    Sleep 89
    Send("{g down}")
    Send("{e down}")
    Sleep 74
    Send("{5 up}")
    Sleep 74
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 15
    Send("{g up}")
    Sleep 134
    Send("{e up}")
    Sleep 15
    Send("{5 down}")
    Sleep 15
    Send("{b down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 15
    Send("{w down}")
    Sleep 164
    Send("{e down}")
    Sleep 30
    Send("{w up}")
    Sleep 15
    Send("{b up}")
    Sleep 134
    Send("{n down}")
    Sleep 119
    Send("{w up}")
    Send("{n up}")
    Send("{5 up}")
    Sleep 238
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e up}")
    Send("{5 down}")
    Sleep 238
    Send("{n up}")
    Sleep 119
    Send("{c down}")
    Sleep 164
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 164
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 313
    Send("{c up}")
    Sleep 45
    Send("{n down}")
    Sleep 179
    Send("{2 up}")
    Sleep 15
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Sleep 149
    Send("{2 down}")
    Send("{e down}")
    Sleep 15
    Send("{n down}")
    Sleep 193
    Send("{n up}")
    Sleep 149
    Send("{c down}")
    Send("{e down}")
    Sleep 30
    Send("{5 up}")
    Sleep 60
    Send("{e up}")
    Sleep 30
    Send("{2 up}")
    Sleep 30
    Send("{n up}")
    Sleep 45
    Send("{c up}")
    Sleep 104
    Send("{e up}")
    Sleep 60
    Send("{g down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{w down}")
    Sleep 149
    Send("{w up}")
    Sleep 15
    Send("{w down}")
    Sleep 30
    Send("{g up}")
    Sleep 164
    Send("{b down}")
    Sleep 74
    Send("{n up}")
    Sleep 15
    Send("{e up}")
    Send("{2 up}")
    Sleep 268
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Sleep 238
    Send("{b up}")
    Sleep 119
    Send("{x down}")
    Sleep 149
    Send("{t up}")
    Sleep 30
    Send("{m up}")
    Send("{w up}")
    Sleep 179
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 238
    Send("{x up}")
    Sleep 119
    Send("{b down}")
    Sleep 179
    Send("{w up}")
    Send("{m up}")
    Sleep 15
    Send("{t up}")
    Sleep 149
    Send("{m down}")
    Sleep 15
    Send("{w down}")
    Send("{t down}")
    Sleep 253
    Send("{w up}")
    Sleep 60
    Send("{b up}")
    Sleep 45
    Send("{g down}")
    Send("{w down}")
    Sleep 149
    Send("{t up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 45
    Send("{g up}")
    Sleep 164
    Send("{c down}")
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 15
    Send("{w up}")
    Send("{e down}")
    Sleep 134
    Send("{e up}")
    Sleep 15
    Send("{w down}")
    Sleep 104
    Send("{c up}")
    Sleep 74
    Send("{x down}")
    Sleep 89
    Send("{m up}")
    Sleep 15
    Send("{t up}")
    Send("{w up}")
    Sleep 268
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 164
    Send("{x up}")
    Sleep 193
    Send("{n down}")
    Sleep 149
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 208
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{n up}")
    Sleep 89
    Send("{x down}")
    Sleep 208
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 149
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{x up}")
    Sleep 89
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Send("{n up}")
    Sleep 30
    Send("{w up}")
    Sleep 208
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 208
    Send("{n up}")
    Sleep 149
    Send("{x down}")
    Sleep 15
    Send("{w up}")
    Sleep 134
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 208
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 208
    Send("{x up}")
    Sleep 149
    Send("{n down}")
    Send("{n down}")
    Sleep 119
    Send("{w up}")
    Send("{n up}")
    Sleep 15
    Send("{5 up}")
    Sleep 104
    Send("{n up}")
    Sleep 119
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 238
    Send("{n up}")
    Sleep 60
    Send("{n up}")
    Sleep 60
    Send("{x down}")
    Send("{m down}")
    Sleep 149
    Send("{w up}")
    Sleep 30
    Send("{5 up}")
    Send("{n up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 179
    Send("{n down}")
    Sleep 89
    Send("{m up}")
    Sleep 74
    Send("{x up}")
    Sleep 15
    Send("{n down}")
    Sleep 149
    Send("{w up}")
    Sleep 30
    Send("{5 up}")
    Send("{n up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 238
    Send("{n up}")
    Sleep 119
    Send("{m down}")
    Sleep 89
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 15
    Send("{n up}")
    Sleep 253
    Send("{w down}")
    Send("{m down}")
    Send("{5 down}")
    Sleep 238
    Send("{m up}")
    Sleep 119
    Send("{g down}")
    Send("{m down}")
    Sleep 179
    Send("{5 up}")
    Send("{m up}")
    Send("{w up}")
    Sleep 179
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 15
    Send("{m up}")
    Sleep 164
    Send("{m down}")
    Sleep 60
    Send("{n up}")
    Sleep 30
    Send("{g up}")
    Sleep 89
    Send("{m down}")
    Sleep 179
    Send("{w up}")
    Send("{m up}")
    Sleep 30
    Send("{5 up}")
    Sleep 134
    Send("{m down}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Send("{w down}")
    Sleep 15
    Send("{m up}")
    Sleep 193
    Send("{m up}")
    Sleep 149
    Send("{x down}")
    Sleep 149
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Send("{m up}")
    Sleep 89
    Send("{x up}")
    Sleep 104
    Send("{m down}")
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 164
    Send("{m up}")
    Sleep 193
    Send("{n down}")
    Sleep 89
    Send("{5 up}")
    Send("{w up}")
    Send("{m up}")
    Send("{w up}")
    Sleep 268
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 238
    Send("{n up}")
    Sleep 119
    Send("{c down}")
    Send("{e down}")
    Sleep 179
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Sleep 15
    Send("{e up}")
    Sleep 15
    Send("{2 up}")
    Sleep 134
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 238
    Send("{c up}")
    Sleep 104
    Send("{n down}")
    Sleep 15
    Send("{5 down}")
    Sleep 60
    Send("{e up}")
    Sleep 119
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 149
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 179
    Send("{5 up}")
    Send("{e down}")
    Sleep 74
    Send("{n up}")
    Sleep 104
    Send("{c down}")
    Sleep 149
    Send("{e up}")
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 30
    Send("{c up}")
    Sleep 164
    Send("{n down}")
    Send("{e down}")
    Sleep 15
    Send("{n down}")
    Send("{2 down}")
    Sleep 149
    Send("{n up}")
    Sleep 15
    Send("{m down}")
    Sleep 30
    Send("{e up}")
    Sleep 60
    Send("{m up}")
    Sleep 89
    Send("{b down}")
    Sleep 15
    Send("{m down}")
    Sleep 45
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Send("{e up}")
    Sleep 238
    Send("{m up}")
    Sleep 15
    Send("{m down}")
    Sleep 15
    Send("{w down}")
    Send("{t down}")
    Send("{n down}")
    Sleep 238
    Send("{b up}")
    Sleep 119
    Send("{g down}")
    Send("{n up}")
    Send("{m down}")
    Sleep 164
    Send("{g up}")
    Sleep 15
    Send("{w up}")
    Sleep 30
    Send("{t up}")
    Send("{m up}")
    Sleep 149
    Send("{c down}")
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Send("{m up}")
    Send("{n down}")
    Sleep 164
    Send("{c up}")
    Sleep 193
    Send("{x down}")
    Send("{w down}")
    Sleep 15
    Send("{n up}")
    Sleep 104
    Send("{t up}")
    Sleep 30
    Send("{m up}")
    Send("{w up}")
    Sleep 208
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 119
    Send("{w up}")
    Sleep 60
    Send("{w down}")
    Sleep 89
    Send("{x up}")
    Sleep 89
    Send("{n down}")
    Sleep 223
    Send("{n up}")
    Sleep 15
    Send("{5 up}")
    Send("{w up}")
    Sleep 119
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 238
    Send("{n up}")
    Sleep 119
    Send("{x down}")
    Sleep 208
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 149
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 313
    Send("{x up}")
    Sleep 45
    Send("{n down}")
    Sleep 208
    Send("{5 up}")
    Sleep 15
    Send("{n up}")
    Sleep 15
    Send("{w up}")
    Sleep 119
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 164
    Send("{n up}")
    Sleep 193
    Send("{x down}")
    Sleep 208
    Send("{5 up}")
    Send("{w up}")
    Sleep 15
    Send("{n up}")
    Sleep 119
    Send("{w down}")
    Sleep 15
    Send("{n down}")
    Send("{5 down}")
    Sleep 208
    Send("{x up}")
    Sleep 74
    Send("{w up}")
    Sleep 60
    Send("{n down}")
    Sleep 15
    Send("{n down}")
    Sleep 208
    Send("{5 up}")
    Send("{n up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 149
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 238
    Send("{n up}")
    Sleep 89
    Send("{n up}")
    Sleep 30
    Send("{x down}")
    Send("{m down}")
    Sleep 179
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 164
    Send("{n down}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Sleep 179
    Send("{n down}")
    Sleep 15
    Send("{x up}")
    Sleep 74
    Send("{m up}")
    Sleep 74
    Send("{n down}")
    Sleep 193
    Send("{n up}")
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 179
    Send("{g down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 193
    Send("{g up}")
    Sleep 164
    Send("{m down}")
    Send("{m down}")
    Sleep 30
    Send("{n up}")
    Sleep 30
    Send("{n up}")
    Sleep 30
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Sleep 223
    Send("{w down}")
    Sleep 15
    Send("{m down}")
    Send("{5 down}")
    Send("{w down}")
    Sleep 15
    Send("{m up}")
    Sleep 253
    Send("{w up}")
    Sleep 74
    Send("{m up}")
    Sleep 15
    Send("{g down}")
    Send("{w down}")
    Sleep 179
    Send("{5 up}")
    Send("{m up}")
    Send("{w up}")
    Sleep 179
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{e down}")
    Sleep 60
    Send("{w up}")
    Sleep 149
    Send("{g up}")
    Sleep 134
    Send("{m down}")
    Sleep 15
    Send("{e up}")
    Send("{5 down}")
    Sleep 223
    Send("{5 up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 134
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{m up}")
    Sleep 89
    Send("{g down}")
    Sleep 149
    Send("{5 up}")
    Send("{m up}")
    Sleep 15
    Send("{w up}")
    Sleep 15
    Send("{g up}")
    Sleep 179
    Send("{m down}")
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 164
    Send("{m up}")
    Sleep 193
    Send("{n down}")
    Send("{e down}")
    Sleep 30
    Send("{5 up}")
    Sleep 60
    Send("{5 up}")
    Sleep 15
    Send("{m up}")
    Sleep 15
    Send("{w up}")
    Sleep 164
    Send("{e up}")
    Sleep 74
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 238
    Send("{e up}")
    Sleep 30
    Send("{n up}")
    Sleep 89
    Send("{c down}")
    Send("{e down}")
    Sleep 193
    Send("{e up}")
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 60
    Send("{e up}")
    Sleep 89
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 238
    Send("{c up}")
    Sleep 119
    Send("{n down}")
    Send("{5 down}")
    Sleep 60
    Send("{e up}")
    Sleep 89
    Send("{e up}")
    Sleep 30
    Send("{2 up}")
    Send("{n up}")
    Sleep 179
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 179
    Send("{e down}")
    Sleep 60
    Send("{5 up}")
    Sleep 30
    Send("{n up}")
    Sleep 89
    Send("{c down}")
    Sleep 149
    Send("{e up}")
    Sleep 15
    Send("{2 up}")
    Send("{n up}")
    Sleep 30
    Send("{c up}")
    Sleep 164
    Send("{n down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 164
    Send("{n up}")
    Sleep 179
    Send("{b down}")
    Sleep 15
    Send("{e up}")
    Send("{m down}")
    Sleep 104
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 30
    Send("{e up}")
    Sleep 208
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Send("{m up}")
    Send("{w down}")
    Sleep 268
    Send("{w up}")
    Sleep 89
    Send("{g down}")
    Send("{w down}")
    Sleep 15
    Send("{b up}")
    Sleep 164
    Send("{g up}")
    Send("{t up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 164
    Send("{c down}")
    Sleep 15
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Send("{e down}")
    Sleep 30
    Send("{w up}")
    Sleep 134
    Send("{c up}")
    Sleep 15
    Send("{w down}")
    Sleep 60
    Send("{e up}")
    Sleep 119
    Send("{x down}")
    Sleep 149
    Send("{t up}")
    Send("{m up}")
    Sleep 30
    Send("{w up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{w up}")
    Sleep 45
    Send("{x up}")
    Sleep 45
    Send("{n down}")
    Send("{w down}")
    Sleep 164
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Send("{n up}")
    Sleep 149
    Send("{w up}")
    Sleep 30
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{e down}")
    Sleep 179
    Send("{e up}")
    Send("{5 down}")
    Sleep 60
    Send("{n up}")
    Sleep 119
    Send("{x down}")
    Sleep 164
    Send("{5 up}")
    Send("{n up}")
    Sleep 15
    Send("{w up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 208
    Send("{x up}")
    Sleep 149
    Send("{n down}")
    Sleep 149
    Send("{n up}")
    Sleep 15
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 193
    Send("{n up}")
    Sleep 149
    Send("{x down}")
    Sleep 193
    Send("{n up}")
    Sleep 15
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 149
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 193
    Send("{5 up}")
    Sleep 60
    Send("{x up}")
    Sleep 104
    Send("{g down}")
    Send("{e down}")
    Sleep 164
    Send("{5 up}")
    Send("{n up}")
    Sleep 15
    Send("{w up}")
    Sleep 15
    Send("{g up}")
    Sleep 164
    Send("{b down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 15
    Send("{w down}")
    Sleep 15
    Send("{e up}")
    Sleep 149
    Send("{w up}")
    Send("{e down}")
    Sleep 89
    Send("{b up}")
    Sleep 89
    Send("{n down}")
    Sleep 74
    Send("{n up}")
    Sleep 15
    Send("{5 up}")
    Send("{w up}")
    Sleep 268
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 193
    Send("{n up}")
    Sleep 164
    Send("{c down}")
    Sleep 149
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 179
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 253
    Send("{c up}")
    Sleep 104
    Send("{n down}")
    Sleep 119
    Send("{e up}")
    Sleep 30
    Send("{2 up}")
    Send("{n up}")
    Sleep 208
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 134
    Send("{n up}")
    Sleep 45
    Send("{e up}")
    Sleep 164
    Send("{g down}")
    Sleep 15
    Send("{5 down}")
    Sleep 149
    Send("{g up}")
    Sleep 15
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 119
    Send("{5 up}")
    Sleep 30
    Send("{n down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 15
    Send("{e down}")
    Sleep 164
    Send("{n up}")
    Sleep 179
    Send("{m down}")
    Send("{w down}")
    Sleep 60
    Send("{e up}")
    Sleep 15
    Send("{e up}")
    Sleep 15
    Send("{2 up}")
    Send("{n up}")
    Sleep 268
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 238
    Send("{m up}")
    Sleep 119
    Send("{g down}")
    Sleep 134
    Send("{5 up}")
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Sleep 208
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 238
    Send("{g up}")
    Sleep 119
    Send("{m down}")
    Sleep 179
    Send("{5 up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 179
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 253
    Send("{m up}")
    Sleep 104
    Send("{g down}")
    Send("{5 down}")
    Sleep 60
    Send("{w up}")
    Sleep 119
    Send("{5 up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 15
    Send("{g up}")
    Sleep 164
    Send("{n down}")
    Send("{w down}")
    Send("{m down}")
    Send("{5 down}")
    Sleep 15
    Send("{y down}")
    Sleep 30
    Send("{5 up}")
    Sleep 119
    Send("{n up}")
    Sleep 15
    Send("{u down}")
    Sleep 45
    Send("{y up}")
    Sleep 134
    Send("{b down}")
    Sleep 104
    Send("{5 up}")
    Sleep 15
    Send("{m up}")
    Sleep 30
    Send("{w up}")
    Sleep 208
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 238
    Send("{b up}")
    Sleep 119
    Send("{x down}")
    Sleep 149
    Send("{t up}")
    Sleep 30
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Sleep 149
    Send("{w down}")
    Sleep 15
    Send("{m down}")
    Send("{t down}")
    Sleep 268
    Send("{x up}")
    Sleep 89
    Send("{b down}")
    Sleep 179
    Send("{t up}")
    Send("{m up}")
    Send("{w up}")
    Sleep 179
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Sleep 119
    Send("{b up}")
    Sleep 149
    Send("{u up}")
    Sleep 89
    Send("{b down}")
    Send("{u down}")
    Sleep 119
    Send("{b up}")
    Sleep 60
    Send("{t up}")
    Send("{m up}")
    Send("{w up}")
    Sleep 179
    Send("{c down}")
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 15
    Send("{u up}")
    Send("{5 down}")
    Sleep 74
    Send("{c up}")
    Sleep 89
    Send("{y down}")
    Sleep 30
    Send("{5 up}")
    Sleep 149
    Send("{x down}")
    Sleep 89
    Send("{t up}")
    Sleep 30
    Send("{w up}")
    Send("{m up}")
    Sleep 238
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{5 down}")
    Sleep 30
    Send("{y up}")
    Sleep 283
    Send("{x up}")
    Sleep 45
    Send("{n down}")
    Sleep 149
    Send("{5 up}")
    Send("{w up}")
    Sleep 15
    Send("{n up}")
    Sleep 193
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 208
    Send("{n up}")
    Sleep 149
    Send("{x down}")
    Sleep 119
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 193
    Send("{n down}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Sleep 253
    Send("{x up}")
    Sleep 104
    Send("{g down}")
    Send("{e down}")
    Sleep 60
    Send("{5 up}")
    Sleep 30
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 45
    Send("{g up}")
    Sleep 164
    Send("{e up}")
    Sleep 30
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 15
    Send("{b down}")
    Send("{w down}")
    Sleep 164
    Send("{e down}")
    Sleep 15
    Send("{b up}")
    Sleep 15
    Send("{w up}")
    Sleep 149
    Send("{n down}")
    Sleep 30
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 298
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Send("{e up}")
    Sleep 15
    Send("{5 down}")
    Sleep 223
    Send("{n up}")
    Sleep 119
    Send("{c down}")
    Sleep 119
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 208
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 268
    Send("{c up}")
    Sleep 89
    Send("{n down}")
    Sleep 179
    Send("{e up}")
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 149
    Send("{n down}")
    Sleep 15
    Send("{2 down}")
    Send("{e down}")
    Sleep 238
    Send("{n up}")
    Sleep 119
    Send("{c down}")
    Send("{e down}")
    Sleep 30
    Send("{5 up}")
    Sleep 89
    Send("{e up}")
    Sleep 30
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 60
    Send("{c up}")
    Sleep 60
    Send("{e up}")
    Sleep 60
    Send("{n down}")
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 15
    Send("{w down}")
    Sleep 104
    Send("{n up}")
    Sleep 30
    Send("{w up}")
    Sleep 15
    Send("{w down}")
    Sleep 193
    Send("{b down}")
    Sleep 89
    Send("{n up}")
    Send("{2 up}")
    Sleep 30
    Send("{e up}")
    Sleep 238
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 268
    Send("{b up}")
    Sleep 89
    Send("{x down}")
    Sleep 119
    Send("{t up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 238
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 238
    Send("{x up}")
    Sleep 119
    Send("{b down}")
    Sleep 134
    Send("{t up}")
    Sleep 15
    Send("{w up}")
    Send("{m up}")
    Sleep 193
    Send("{m down}")
    Sleep 15
    Send("{w down}")
    Send("{t down}")
    Sleep 253
    Send("{w up}")
    Sleep 15
    Send("{b up}")
    Sleep 89
    Send("{g down}")
    Send("{w down}")
    Sleep 149
    Send("{t up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 45
    Send("{g up}")
    Sleep 164
    Send("{c down}")
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 15
    Send("{w up}")
    Send("{e down}")
    Sleep 134
    Send("{e up}")
    Sleep 15
    Send("{c up}")
    Sleep 15
    Send("{w down}")
    Sleep 164
    Send("{x down}")
    Sleep 74
    Send("{m up}")
    Sleep 30
    Send("{t up}")
    Send("{w up}")
    Sleep 253
    Send("{w down}")
    Sleep 15
    Send("{n down}")
    Send("{5 down}")
    Sleep 193
    Send("{x up}")
    Sleep 164
    Send("{n down}")
    Sleep 60
    Send("{5 up}")
    Sleep 45
    Send("{n up}")
    Send("{w up}")
    Sleep 253
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 238
    Send("{n up}")
    Sleep 119
    Send("{x down}")
    Sleep 119
    Send("{5 up}")
    Sleep 30
    Send("{n up}")
    Sleep 30
    Send("{w up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{x up}")
    Sleep 89
    Send("{n down}")
    Sleep 149
    Send("{5 up}")
    Sleep 30
    Send("{n up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 164
    Send("{5 down}")
    Sleep 15
    Send("{j down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 164
    Send("{j up}")
    Sleep 193
    Send("{m down}")
    Sleep 30
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Send("{n up}")
    Sleep 298
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{w down}")
    Sleep 238
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Sleep 104
    Send("{g down}")
    Send("{w down}")
    Sleep 119
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Send("{m up}")
    Sleep 60
    Send("{g up}")
    Sleep 74
    Send("{w up}")
    Sleep 89
    Send("{m down}")
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 15
    Send("{w down}")
    Sleep 149
    Send("{m up}")
    Sleep 193
    Send("{n down}")
    Send("{2 down}")
    Sleep 30
    Send("{w up}")
    Sleep 30
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{m up}")
    Sleep 268
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 104
    Send("{n up}")
    Sleep 253
    Send("{n down}")
    Send("{2 up}")
    Send("{w down}")
    Sleep 149
    Send("{e up}")
    Sleep 30
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 164
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 15
    Send("{w up}")
    Sleep 223
    Send("{n up}")
    Sleep 119
    Send("{x down}")
    Send("{e up}")
    Send("{5 down}")
    Sleep 119
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 208
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 119
    Send("{5 up}")
    Sleep 60
    Send("{5 down}")
    Sleep 74
    Send("{x up}")
    Sleep 15
    Send("{5 up}")
    Sleep 89
    Send("{n down}")
    Send("{5 down}")
    Sleep 179
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 119
    Send("{5 up}")
    Sleep 60
    Send("{5 down}")
    Sleep 74
    Send("{n up}")
    Sleep 15
    Send("{5 up}")
    Sleep 89
    Send("{x down}")
    Send("{5 down}")
    Sleep 149
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 179
    Send("{5 up}")
    Sleep 15
    Send("{5 down}")
    Sleep 15
    Send("{n down}")
    Send("{w down}")
    Send("{w down}")
    Sleep 313
    Send("{x up}")
    Sleep 30
    Send("{c down}")
    Sleep 134
    Send("{n up}")
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 45
    Send("{c up}")
    Sleep 179
    Send("{g down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 119
    Send("{w up}")
    Sleep 60
    Send("{w down}")
    Sleep 15
    Send("{g up}")
    Sleep 134
    Send("{w up}")
    Sleep 15
    Send("{b down}")
    Sleep 15
    Send("{t down}")
    Sleep 119
    Send("{5 up}")
    Send("{n up}")
    Sleep 30
    Send("{w up}")
    Sleep 119
    Send("{t up}")
    Sleep 89
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Send("{t down}")
    Sleep 149
    Send("{b up}")
    Send("{t up}")
    Sleep 15
    Send("{t down}")
    Sleep 193
    Send("{b down}")
    Sleep 149
    Send("{t up}")
    Send("{w up}")
    Sleep 30
    Send("{m up}")
    Sleep 74
    Send("{t up}")
    Sleep 89
    Send("{m down}")
    Sleep 15
    Send("{w down}")
    Send("{t down}")
    Send("{t down}")
    Sleep 149
    Send("{t up}")
    Sleep 15
    Send("{b up}")
    Send("{t down}")
    Sleep 193
    Send("{x down}")
    Sleep 119
    Send("{w up}")
    Send("{m up}")
    Sleep 30
    Send("{t up}")
    Sleep 104
    Send("{t up}")
    Sleep 89
    Send("{5 down}")
    Sleep 15
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 89
    Send("{x up}")
    Sleep 268
    Send("{x down}")
    Send("{e down}")
    Sleep 30
    Send("{5 up}")
    Sleep 119
    Send("{w up}")
    Send("{n up}")
    Send("{5 up}")
    Sleep 89
    Send("{x up}")
    Sleep 119
    Send("{g down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 15
    Send("{e up}")
    Send("{w down}")
    Sleep 30
    Send("{g up}")
    Sleep 119
    Send("{n down}")
    Sleep 45
    Send("{n up}")
    Sleep 149
    Send("{n down}")
    Send("{w up}")
    Send("{e down}")
    Sleep 119
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 238
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 164
    Send("{n up}")
    Sleep 193
    Send("{c down}")
    Send("{5 down}")
    Sleep 30
    Send("{e up}")
    Sleep 134
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Sleep 45
    Send("{2 up}")
    Sleep 45
    Send("{5 up}")
    Sleep 74
    Send("{2 down}")
    Sleep 15
    Send("{n down}")
    Send("{e down}")
    Send("{5 down}")
    Sleep 134
    Send("{5 up}")
    Sleep 45
    Send("{e down}")
    Sleep 89
    Send("{c up}")
    Sleep 89
    Send("{n down}")
    Sleep 208
    Send("{e up}")
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 119
    Send("{2 down}")
    Sleep 15
    Send("{n down}")
    Send("{e down}")
    Sleep 193
    Send("{n up}")
    Sleep 164
    Send("{n down}")
    Sleep 119
    Send("{n up}")
    Sleep 30
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 179
    Send("{j down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 164
    Send("{j up}")
    Sleep 164
    Send("{e up}")
    Sleep 30
    Send("{m down}")
    Sleep 15
    Send("{5 down}")
    Sleep 45
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 208
    Send("{5 up}")
    Sleep 60
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{5 down}")
    Sleep 119
    Send("{m up}")
    Sleep 193
    Send("{5 up}")
    Sleep 45
    Send("{m down}")
    Send("{5 down}")
    Sleep 119
    Send("{5 up}")
    Sleep 60
    Send("{5 up}")
    Send("{w up}")
    Send("{m up}")
    Send("{5 down}")
    Sleep 179
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 208
    Send("{m up}")
    Sleep 89
    Send("{5 up}")
    Sleep 60
    Send("{z down}")
    Send("{e down}")
    Sleep 134
    Send("{5 up}")
    Send("{m up}")
    Sleep 15
    Send("{w up}")
    Sleep 193
    Send("{e up}")
    Sleep 15
    Send("{b down}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 283
    Send("{z up}")
    Sleep 15
    Send("{e up}")
    Sleep 60
    Send("{c down}")
    Send("{e down}")
    Sleep 89
    Send("{e up}")
    Sleep 74
    Send("{c up}")
    Sleep 15
    Send("{e up}")
    Send("{q up}")
    Send("{e down}")
    Sleep 15
    Send("{b up}")
    Sleep 164
    Send("{b down}")
    Send("{b down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 89
    Send("{b up}")
    Sleep 208
    Send("{e up}")
    Sleep 60
    Send("{b down}")
    Send("{w down}")
    Sleep 119
    Send("{e up}")
    Sleep 15
    Send("{q up}")
    Send("{b up}")
    Sleep 193
    Send("{w up}")
    Sleep 15
    Send("{b down}")
    Sleep 15
    Send("{m down}")
    Send("{w down}")
    Send("{w down}")
    Sleep 208
    Send("{b up}")
    Sleep 60
    Send("{w up}")
    Sleep 89
    Send("{g down}")
    Send("{w down}")
    Sleep 89
    Send("{w up}")
    Sleep 74
    Send("{g up}")
    Sleep 15
    Send("{w up}")
    Send("{m up}")
    Send("{b up}")
    Send("{w down}")
    Sleep 164
    Send("{b down}")
    Sleep 15
    Send("{c down}")
    Send("{m down}")
    Send("{w down}")
    Sleep 164
    Send("{c up}")
    Sleep 74
    Send("{w up}")
    Sleep 104
    Send("{x down}")
    Sleep 15
    Send("{w down}")
    Sleep 119
    Send("{w up}")
    Send("{m up}")
    Send("{b up}")
    Sleep 223
    Send("{w up}")
    Sleep 15
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Send("{w down}")
    Sleep 134
    Send("{x up}")
    Sleep 164
    Send("{w up}")
    Sleep 60
    Send("{x down}")
    Send("{w down}")
    Sleep 89
    Send("{w up}")
    Sleep 60
    Send("{5 up}")
    Send("{w up}")
    Sleep 15
    Send("{w down}")
    Sleep 15
    Send("{n up}")
    Sleep 179
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 193
    Send("{x up}")
    Sleep 134
    Send("{w up}")
    Sleep 30
    Send("{n down}")
    Send("{e down}")
    Sleep 149
    Send("{5 up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 119
    Send("{e up}")
    Sleep 74
    Send("{e down}")
    Sleep 15
    Send("{n down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 179
    Send("{e down}")
    Sleep 15
    Send("{n up}")
    Sleep 45
    Send("{5 up}")
    Sleep 119
    Send("{c down}")
    Sleep 179
    Send("{n up}")
    Send("{e up}")
    Sleep 45
    Send("{2 up}")
    Sleep 134
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 268
    Send("{c up}")
    Sleep 74
    Send("{n down}")
    Sleep 193
    Send("{e up}")
    Send("{2 up}")
    Sleep 15
    Send("{n up}")
    Sleep 164
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 238
    Send("{n up}")
    Send("{e up}")
    Sleep 119
    Send("{c down}")
    Send("{e down}")
    Sleep 45
    Send("{c up}")
    Sleep 104
    Send("{e up}")
    Sleep 30
    Send("{2 up}")
    Send("{n up}")
    Sleep 164
    Send("{2 down}")
    Send("{e up}")
    Sleep 15
    Send("{c down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 15
    Send("{5 down}")
    Sleep 208
    Send("{c up}")
    Sleep 134
    Send("{n down}")
    Send("{5 up}")
    Send("{t down}")
    Sleep 164
    Send("{2 up}")
    Sleep 15
    Send("{e up}")
    Send("{n up}")
    Sleep 179
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 208
    Send("{n up}")
    Sleep 134
    Send("{c down}")
    Sleep 134
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 208
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 193
    Send("{c up}")
    Sleep 164
    Send("{n down}")
    Sleep 208
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 119
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 179
    Send("{t up}")
    Sleep 179
    Send("{w down}")
    Sleep 357
    Send("{w up}")
    Send("{e down}")
    Sleep 179
    Send("{e up}")
    Send("{5 down}")
    Sleep 179
    Send("{x down}")
    Sleep 74
    Send("{n up}")
    Sleep 74
    Send("{n up}")
    Sleep 15
    Send("{e up}")
    Send("{2 up}")
    Sleep 193
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 193
    Send("{x up}")
    Sleep 164
    Send("{n down}")
    Sleep 164
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Send("{n up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 313
    Send("{n up}")
    Sleep 45
    Send("{x down}")
    Sleep 208
    Send("{5 up}")
    Send("{w up}")
    Sleep 30
    Send("{n up}")
    Sleep 119
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 193
    Send("{x up}")
    Send("{5 up}")
    Sleep 164
    Send("{g down}")
    Send("{e down}")
    Sleep 119
    Send("{5 up}")
    Send("{w up}")
    Sleep 30
    Send("{n up}")
    Sleep 74
    Send("{g up}")
    Sleep 134
    Send("{n down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 15
    Send("{w down}")
    Sleep 15
    Send("{e up}")
    Sleep 134
    Send("{n up}")
    Sleep 15
    Send("{w up}")
    Send("{e down}")
    Sleep 179
    Send("{n down}")
    Sleep 89
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 268
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 193
    Send("{n up}")
    Sleep 164
    Send("{c down}")
    Sleep 119
    Send("{e up}")
    Send("{2 up}")
    Send("{n up}")
    Sleep 238
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 208
    Send("{c up}")
    Sleep 149
    Send("{n down}")
    Sleep 119
    Send("{e up}")
    Send("{2 up}")
    Send("{n up}")
    Sleep 238
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 179
    Send("{e up}")
    Sleep 134
    Send("{n up}")
    Sleep 45
    Send("{c down}")
    Send("{5 down}")
    Sleep 149
    Send("{e up}")
    Send("{2 up}")
    Sleep 15
    Send("{n up}")
    Sleep 164
    Send("{5 up}")
    Sleep 30
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 179
    Send("{e up}")
    Send("{w down}")
    Sleep 30
    Send("{c up}")
    Sleep 149
    Send("{m down}")
    Sleep 60
    Send("{e up}")
    Sleep 30
    Send("{2 up}")
    Send("{n up}")
    Sleep 268
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 238
    Send("{m up}")
    Sleep 119
    Send("{g down}")
    Sleep 149
    Send("{5 up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 208
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{g up}")
    Sleep 89
    Send("{m down}")
    Sleep 179
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Send("{m up}")
    Sleep 164
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 208
    Send("{m up}")
    Sleep 30
    Send("{w up}")
    Sleep 119
    Send("{m down}")
    Send("{5 down}")
    Sleep 164
    Send("{m up}")
    Sleep 15
    Send("{5 up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 179
    Send("{g down}")
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 15
    Send("{y down}")
    Sleep 30
    Send("{5 up}")
    Sleep 134
    Send("{u down}")
    Sleep 15
    Send("{g up}")
    Sleep 30
    Send("{y up}")
    Sleep 134
    Send("{b down}")
    Sleep 119
    Send("{m up}")
    Sleep 15
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 208
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Sleep 238
    Send("{b up}")
    Sleep 119
    Send("{x down}")
    Sleep 149
    Send("{t up}")
    Sleep 15
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Sleep 164
    Send("{t down}")
    Sleep 15
    Send("{m down}")
    Send("{w down}")
    Sleep 313
    Send("{x up}")
    Sleep 45
    Send("{b down}")
    Sleep 208
    Send("{w up}")
    Send("{m up}")
    Send("{t up}")
    Sleep 149
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 104
    Send("{b up}")
    Sleep 164
    Send("{u up}")
    Sleep 89
    Send("{b down}")
    Send("{u down}")
    Sleep 164
    Send("{b up}")
    Sleep 15
    Send("{w up}")
    Sleep 15
    Send("{t up}")
    Sleep 15
    Send("{m up}")
    Sleep 149
    Send("{c down}")
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Sleep 15
    Send("{u up}")
    Send("{5 down}")
    Sleep 164
    Send("{y down}")
    Sleep 30
    Send("{5 up}")
    Sleep 60
    Send("{c up}")
    Sleep 89
    Send("{x down}")
    Sleep 119
    Send("{m up}")
    Sleep 30
    Send("{t up}")
    Send("{w up}")
    Sleep 208
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{5 down}")
    Sleep 30
    Send("{y up}")
    Sleep 208
    Send("{x up}")
    Sleep 119
    Send("{n down}")
    Sleep 149
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 283
    Send("{n up}")
    Sleep 74
    Send("{x down}")
    Sleep 179
    Send("{w up}")
    Send("{n up}")
    Sleep 30
    Send("{5 up}")
    Sleep 134
    Send("{n down}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Sleep 253
    Send("{x up}")
    Sleep 104
    Send("{g down}")
    Send("{e down}")
    Sleep 60
    Send("{5 up}")
    Sleep 89
    Send("{n up}")
    Sleep 30
    Send("{5 up}")
    Send("{w up}")
    Sleep 15
    Send("{g up}")
    Sleep 134
    Send("{e up}")
    Sleep 30
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 15
    Send("{b down}")
    Send("{w down}")
    Sleep 164
    Send("{e down}")
    Sleep 30
    Send("{w up}")
    Sleep 15
    Send("{b up}")
    Sleep 134
    Send("{n down}")
    Sleep 89
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 268
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Send("{e up}")
    Sleep 15
    Send("{5 down}")
    Sleep 223
    Send("{n up}")
    Sleep 119
    Send("{c down}")
    Sleep 179
    Send("{e up}")
    Send("{n up}")
    Send("{2 up}")
    Sleep 179
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 313
    Send("{c up}")
    Sleep 45
    Send("{n down}")
    Sleep 179
    Send("{e up}")
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 164
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 208
    Send("{n up}")
    Sleep 149
    Send("{c down}")
    Send("{e down}")
    Sleep 30
    Send("{5 up}")
    Sleep 149
    Send("{e up}")
    Send("{n up}")
    Sleep 15
    Send("{c up}")
    Send("{2 up}")
    Sleep 104
    Send("{e up}")
    Sleep 60
    Send("{g down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 15
    Send("{w down}")
    Sleep 134
    Send("{w up}")
    Sleep 15
    Send("{w down}")
    Sleep 45
    Send("{g up}")
    Sleep 164
    Send("{b down}")
    Sleep 104
    Send("{n up}")
    Sleep 30
    Send("{e up}")
    Send("{2 up}")
    Sleep 208
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 223
    Send("{b up}")
    Sleep 134
    Send("{x down}")
    Sleep 208
    Send("{t up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 149
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Sleep 238
    Send("{x up}")
    Sleep 119
    Send("{b down}")
    Sleep 268
    Send("{t up}")
    Send("{w up}")
    Sleep 30
    Send("{m up}")
    Sleep 45
    Send("{m down}")
    Sleep 15
    Send("{w down}")
    Send("{t down}")
    Sleep 253
    Send("{w up}")
    Sleep 60
    Send("{b up}")
    Sleep 45
    Send("{g down}")
    Send("{w down}")
    Sleep 193
    Send("{g up}")
    Sleep 15
    Send("{t up}")
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Sleep 134
    Send("{c down}")
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Sleep 15
    Send("{w up}")
    Send("{e down}")
    Sleep 134
    Send("{e up}")
    Sleep 30
    Send("{w down}")
    Sleep 89
    Send("{c up}")
    Sleep 89
    Send("{x down}")
    Sleep 193
    Send("{t up}")
    Sleep 15
    Send("{w up}")
    Sleep 30
    Send("{m up}")
    Sleep 119
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 164
    Send("{x up}")
    Sleep 193
    Send("{n down}")
    Sleep 149
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{n up}")
    Sleep 74
    Send("{x down}")
    Sleep 193
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 149
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 268
    Send("{x up}")
    Sleep 89
    Send("{n down}")
    Send("{w up}")
    Send("{w down}")
    Sleep 149
    Send("{5 up}")
    Sleep 30
    Send("{n up}")
    Send("{w up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{w up}")
    Send("{e down}")
    Sleep 179
    Send("{e up}")
    Send("{5 down}")
    Sleep 30
    Send("{n up}")
    Sleep 149
    Send("{x down}")
    Sleep 164
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Send("{n up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 208
    Send("{x up}")
    Sleep 149
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 238
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 313
    Send("{n up}")
    Sleep 45
    Send("{x down}")
    Sleep 149
    Send("{5 up}")
    Send("{n up}")
    Sleep 15
    Send("{w up}")
    Sleep 193
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 193
    Send("{x up}")
    Sleep 15
    Send("{5 up}")
    Sleep 149
    Send("{g down}")
    Send("{e down}")
    Sleep 119
    Send("{5 up}")
    Sleep 30
    Send("{n up}")
    Send("{w up}")
    Sleep 89
    Send("{g up}")
    Sleep 119
    Send("{n down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{w down}")
    Sleep 30
    Send("{e up}")
    Sleep 149
    Send("{n up}")
    Send("{w up}")
    Send("{e down}")
    Sleep 179
    Send("{n down}")
    Sleep 89
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 268
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 208
    Send("{n up}")
    Sleep 149
    Send("{c down}")
    Sleep 119
    Send("{e up}")
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 208
    Send("{2 down}")
    Sleep 15
    Send("{n down}")
    Send("{e down}")
    Sleep 208
    Send("{c up}")
    Sleep 149
    Send("{n down}")
    Sleep 89
    Send("{e up}")
    Sleep 30
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 223
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 179
    Send("{e up}")
    Sleep 134
    Send("{n up}")
    Sleep 30
    Send("{c down}")
    Sleep 15
    Send("{5 down}")
    Sleep 89
    Send("{e up}")
    Send("{2 up}")
    Send("{n up}")
    Sleep 238
    Send("{5 up}")
    Sleep 15
    Send("{n down}")
    Sleep 15
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 179
    Send("{e up}")
    Send("{w down}")
    Sleep 30
    Send("{c up}")
    Sleep 149
    Send("{m down}")
    Sleep 60
    Send("{n up}")
    Sleep 15
    Send("{e up}")
    Sleep 15
    Send("{2 up}")
    Sleep 268
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 238
    Send("{m up}")
    Sleep 119
    Send("{g down}")
    Sleep 119
    Send("{w up}")
    Send("{m up}")
    Sleep 30
    Send("{5 up}")
    Sleep 208
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{g up}")
    Sleep 89
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Sleep 15
    Send("{w up}")
    Sleep 30
    Send("{5 up}")
    Sleep 179
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 208
    Send("{m up}")
    Sleep 30
    Send("{w up}")
    Sleep 119
    Send("{m down}")
    Send("{5 down}")
    Sleep 119
    Send("{w up}")
    Send("{m up}")
    Sleep 15
    Send("{5 up}")
    Sleep 30
    Send("{m up}")
    Sleep 193
    Send("{g down}")
    Send("{m down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 15
    Send("{y down}")
    Sleep 30
    Send("{5 up}")
    Sleep 134
    Send("{u down}")
    Sleep 15
    Send("{g up}")
    Sleep 15
    Send("{y up}")
    Sleep 149
    Send("{b down}")
    Sleep 89
    Send("{m up}")
    Sleep 30
    Send("{5 up}")
    Send("{w up}")
    Sleep 238
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 238
    Send("{b up}")
    Sleep 119
    Send("{x down}")
    Sleep 134
    Send("{t up}")
    Sleep 45
    Send("{w up}")
    Send("{m up}")
    Sleep 179
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Sleep 313
    Send("{x up}")
    Sleep 45
    Send("{b down}")
    Sleep 179
    Send("{t up}")
    Send("{w up}")
    Sleep 30
    Send("{m up}")
    Sleep 149
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Sleep 104
    Send("{b up}")
    Sleep 164
    Send("{u up}")
    Sleep 74
    Send("{b down}")
    Sleep 15
    Send("{u down}")
    Sleep 164
    Send("{b up}")
    Sleep 45
    Send("{t up}")
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Sleep 134
    Send("{c down}")
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 15
    Send("{u up}")
    Send("{5 down}")
    Sleep 164
    Send("{y down}")
    Sleep 30
    Send("{5 up}")
    Sleep 60
    Send("{c up}")
    Sleep 89
    Send("{x down}")
    Sleep 119
    Send("{m up}")
    Sleep 30
    Send("{t up}")
    Send("{w up}")
    Sleep 208
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 15
    Send("{5 down}")
    Sleep 15
    Send("{y up}")
    Sleep 208
    Send("{x up}")
    Sleep 119
    Send("{n down}")
    Sleep 149
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{n up}")
    Sleep 74
    Send("{x down}")
    Sleep 179
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Send("{n up}")
    Sleep 179
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 253
    Send("{x up}")
    Sleep 104
    Send("{g down}")
    Send("{e down}")
    Sleep 60
    Send("{5 up}")
    Sleep 104
    Send("{5 up}")
    Send("{w up}")
    Sleep 15
    Send("{n up}")
    Sleep 15
    Send("{g up}")
    Sleep 134
    Send("{e up}")
    Sleep 15
    Send("{5 down}")
    Sleep 15
    Send("{b down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 15
    Send("{w down}")
    Sleep 164
    Send("{e down}")
    Sleep 30
    Send("{w up}")
    Sleep 15
    Send("{b up}")
    Sleep 134
    Send("{n down}")
    Sleep 74
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 253
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e up}")
    Send("{5 down}")
    Sleep 253
    Send("{n up}")
    Sleep 104
    Send("{c down}")
    Sleep 149
    Send("{e up}")
    Send("{2 up}")
    Send("{n up}")
    Sleep 208
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 298
    Send("{c up}")
    Sleep 60
    Send("{n down}")
    Sleep 89
    Send("{e up}")
    Sleep 30
    Send("{n up}")
    Send("{2 up}")
    Sleep 238
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 208
    Send("{n up}")
    Sleep 149
    Send("{c down}")
    Send("{e down}")
    Sleep 30
    Send("{5 up}")
    Sleep 89
    Send("{e up}")
    Send("{2 up}")
    Send("{n up}")
    Sleep 74
    Send("{c up}")
    Sleep 104
    Send("{e up}")
    Sleep 60
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 15
    Send("{g down}")
    Send("{w down}")
    Sleep 134
    Send("{w up}")
    Sleep 15
    Send("{w down}")
    Sleep 45
    Send("{g up}")
    Sleep 149
    Send("{b down}")
    Sleep 74
    Send("{n up}")
    Send("{2 up}")
    Sleep 45
    Send("{e up}")
    Sleep 238
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 223
    Send("{b up}")
    Sleep 134
    Send("{x down}")
    Sleep 149
    Send("{t up}")
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Sleep 193
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 253
    Send("{x up}")
    Sleep 104
    Send("{b down}")
    Sleep 149
    Send("{w up}")
    Sleep 30
    Send("{t up}")
    Send("{m up}")
    Sleep 164
    Send("{t down}")
    Sleep 15
    Send("{m down}")
    Send("{w down}")
    Sleep 253
    Send("{w up}")
    Sleep 60
    Send("{b up}")
    Sleep 45
    Send("{g down}")
    Send("{w down}")
    Sleep 164
    Send("{w up}")
    Sleep 15
    Send("{m up}")
    Send("{t up}")
    Sleep 15
    Send("{g up}")
    Sleep 164
    Send("{c down}")
    Send("{w down}")
    Send("{m down}")
    Send("{t down}")
    Send("{e down}")
    Sleep 15
    Send("{w up}")
    Sleep 134
    Send("{e up}")
    Sleep 15
    Send("{w down}")
    Sleep 104
    Send("{c up}")
    Sleep 74
    Send("{x down}")
    Sleep 134
    Send("{m up}")
    Send("{w up}")
    Sleep 15
    Send("{t up}")
    Sleep 208
    Send("{n down}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Sleep 164
    Send("{x up}")
    Sleep 193
    Send("{n down}")
    Sleep 149
    Send("{5 up}")
    Send("{n up}")
    Sleep 30
    Send("{w up}")
    Sleep 179
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{n up}")
    Sleep 89
    Send("{x down}")
    Sleep 164
    Send("{x up}")
    Sleep 30
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Send("{n up}")
    Sleep 134
    Send("{n down}")
    Sleep 15
    Send("{x down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 164
    Send("{x up}")
    Sleep 179
    Send("{w up}")
    Sleep 15
    Send("{s down}")
    Send("{e down}")
    Sleep 164
    Send("{s up}")
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Send("{n up}")
    Sleep 179
    Send("{w down}")
    Send("{5 down}")
    Send("{e up}")
    Sleep 15
    Send("{m down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 134
    Send("{m up}")
    Sleep 15
    Send("{e down}")
    Sleep 30
    Send("{w up}")
    Sleep 164
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Send("{w up}")
    Sleep 15
    Send("{n up}")
    Sleep 223
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 223
    Send("{n up}")
    Sleep 134
    Send("{c down}")
    Sleep 149
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 179
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 268
    Send("{c up}")
    Sleep 89
    Send("{n down}")
    Sleep 149
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Sleep 15
    Send("{n up}")
    Send("{2 up}")
    Sleep 164
    Send("{2 down}")
    Sleep 15
    Send("{n down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 119
    Send("{n up}")
    Sleep 15
    Send("{e up}")
    Sleep 223
    Send("{m down}")
    Send("{w down}")
    Sleep 149
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 15
    Send("{m up}")
    Sleep 164
    Send("{s down}")
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Send("{w up}")
    Send("{e down}")
    Sleep 164
    Send("{s up}")
    Send("{w down}")
    Sleep 45
    Send("{e up}")
    Sleep 149
    Send("{x down}")
    Sleep 89
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 238
    Send("{w down}")
    Send("{n down}")
    Send("{5 down}")
    Sleep 313
    Send("{x up}")
    Sleep 45
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Sleep 30
    Send("{n up}")
    Send("{w up}")
    Sleep 208
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 208
    Send("{n up}")
    Sleep 149
    Send("{x down}")
    Sleep 89
    Send("{x up}")
    Sleep 60
    Send("{5 up}")
    Sleep 15
    Send("{n up}")
    Sleep 15
    Send("{w up}")
    Sleep 179
    Send("{x down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 89
    Send("{x up}")
    Sleep 253
    Send("{w up}")
    Sleep 15
    Send("{s down}")
    Send("{e down}")
    Sleep 149
    Send("{s up}")
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 208
    Send("{m down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{e up}")
    Send("{w down}")
    Sleep 179
    Send("{m up}")
    Send("{e down}")
    Sleep 60
    Send("{w up}")
    Sleep 119
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 238
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 208
    Send("{n up}")
    Sleep 149
    Send("{c down}")
    Sleep 119
    Send("{e up}")
    Sleep 30
    Send("{2 up}")
    Send("{n up}")
    Sleep 208
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 238
    Send("{c up}")
    Sleep 119
    Send("{n down}")
    Sleep 45
    Send("{n up}")
    Sleep 134
    Send("{e up}")
    Send("{n up}")
    Sleep 30
    Send("{2 up}")
    Sleep 149
    Send("{n down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 119
    Send("{n up}")
    Sleep 238
    Send("{m down}")
    Send("{w down}")
    Sleep 30
    Send("{e up}")
    Sleep 89
    Send("{e up}")
    Sleep 30
    Send("{2 up}")
    Send("{n up}")
    Sleep 15
    Send("{m up}")
    Sleep 193
    Send("{s down}")
    Send("{2 down}")
    Send("{n down}")
    Send("{e down}")
    Send("{w up}")
    Send("{e down}")
    Sleep 119
    Send("{s up}")
    Sleep 60
    Send("{w down}")
    Sleep 60
    Send("{e up}")
    Sleep 119
    Send("{x down}")
    Sleep 149
    Send("{e up}")
    Sleep 15
    Send("{n up}")
    Send("{2 up}")
    Sleep 193
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 253
    Send("{x up}")
    Sleep 104
    Send("{n down}")
    Sleep 134
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Send("{n up}")
    Sleep 208
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 268
    Send("{n up}")
    Sleep 89
    Send("{x down}")
    Sleep 164
    Send("{x up}")
    Sleep 15
    Send("{5 up}")
    Sleep 30
    Send("{w up}")
    Send("{n up}")
    Sleep 134
    Send("{n down}")
    Sleep 15
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 74
    Send("{n up}")
    Sleep 104
    Send("{e up}")
    Send("{2 up}")
    Send("{n up}")
    Sleep 179
    Send("{x down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 179
    Send("{w up}")
    Sleep 298
    Send("{x up}")
    Sleep 179
    Send("{5 up}")
    Send("{n up}")
    Sleep 30
    Send("{w up}")
}
