#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{v down}")
    Sleep 210
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 211
    Send("{3 down}")
    Send("{t down}")
    Send("{7 down}")
    Send("{w down}")
    Sleep 1264
    Send("{3 up}")
    Send("{t up}")
    Send("{7 up}")
    Send("{w up}")
    Send("{v up}")
    Sleep 2
    Send("{e down}")
    Send("{6 down}")
    Send("{u down}")
    Send("{3 down}")
    Send("{g down}")
    Sleep 858
    Send("{e up}")
    Send("{6 up}")
    Send("{u up}")
    Send("{3 up}")
    Send("{g up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{q down}")
    Send("{e down}")
    Send("{b down}")
    Sleep 419
    Send("{q down}")
    Sleep 5
    Send("{r up}")
    Send("{y up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 57
    Send("{w down}")
    Sleep 55
    Send("{q up}")
    Sleep 6
    Send("{e down}")
    Sleep 55
    Send("{w up}")
    Sleep 6
    Send("{r down}")
    Sleep 55
    Send("{e up}")
    Sleep 6
    Send("{t down}")
    Sleep 55
    Send("{r up}")
    Sleep 6
    Send("{y down}")
    Sleep 56
    Send("{t up}")
    Sleep 6
    Send("{u down}")
    Sleep 1
    Send("{b up}")
    Sleep 54
    Send("{y up}")
    Sleep 9
    Send("{q down}")
    Send("{z down}")
    Sleep 5
    Send("{u up}")
    Sleep 93
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{3 down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{3 up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{t down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{t up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{3 down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{3 up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{t down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{t up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{3 down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{3 up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{t down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{t up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{3 down}")
    Sleep 96
    Send("{v up}")
    Sleep 6
    Send("{3 up}")
    Sleep 7
    Send("{g down}")
    Sleep 202
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 205
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 862
    Send("{z up}")
    Sleep 845
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 92
    Send("{t down}")
    Sleep 53
    Send("{t up}")
    Send("{6 down}")
    Sleep 53
    Send("{z up}")
    Sleep 0
    Send("{6 up}")
    Sleep 12
    Send("{y down}")
    Send("{q down}")
    Sleep 210
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{e up}")
    Send("{t up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 210
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 12
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{q up}")
    Send("{e up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 105
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 97
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{y up}")
    Send("{z up}")
    Sleep 12
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{g down}")
    Sleep 199
    Send("{t up}")
    Send("{g up}")
    Sleep 13
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{b down}")
    Sleep 98
    Send("{r up}")
    Sleep 6
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{t up}")
    Sleep 6
    Send("{7 up}")
    Sleep 2
    Send("{z down}")
    Sleep 122
    Send("{t down}")
    Send("{7 down}")
    Sleep 91
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{t up}")
    Send("{7 up}")
    Sleep 2
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 13
    Send("{y down}")
    Send("{q down}")
    Sleep 210
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{e up}")
    Send("{t up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 210
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 12
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{q up}")
    Send("{e up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 105
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 97
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{y up}")
    Send("{z up}")
    Sleep 12
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{g down}")
    Sleep 199
    Send("{t up}")
    Send("{g up}")
    Sleep 13
    Send("{7 up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Send("{b down}")
    Sleep 98
    Send("{y up}")
    Sleep 6
    Send("{q up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{7 up}")
    Sleep 6
    Send("{w up}")
    Sleep 2
    Send("{z down}")
    Sleep 122
    Send("{q down}")
    Send("{e down}")
    Sleep 91
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 8
    Send("{q down}")
    Sleep 5
    Send("{q up}")
    Send("{e up}")
    Sleep 0
    Send("{g down}")
    Sleep 26
    Send("{u down}")
    Sleep 27
    Send("{q up}")
    Sleep 3
    Send("{y down}")
    Sleep 27
    Send("{u up}")
    Sleep 3
    Send("{t down}")
    Sleep 27
    Send("{y up}")
    Sleep 3
    Send("{r down}")
    Sleep 27
    Send("{t up}")
    Sleep 3
    Send("{e down}")
    Sleep 27
    Send("{r up}")
    Sleep 3
    Send("{w down}")
    Sleep 20
    Send("{g up}")
    Sleep 7
    Send("{e up}")
    Sleep 3
    Send("{q down}")
    Sleep 3
    Send("{b down}")
    Sleep 25
    Send("{w up}")
    Sleep 3
    Send("{u down}")
    Sleep 28
    Send("{q up}")
    Sleep 3
    Send("{y down}")
    Sleep 28
    Send("{u up}")
    Sleep 3
    Send("{t down}")
    Sleep 28
    Send("{y up}")
    Sleep 3
    Send("{r down}")
    Sleep 28
    Send("{t up}")
    Sleep 3
    Send("{e down}")
    Sleep 28
    Send("{r up}")
    Sleep 3
    Send("{w down}")
    Sleep 19
    Send("{b up}")
    Sleep 9
    Send("{e up}")
    Sleep 6
    Send("{q down}")
    Send("{z down}")
    Sleep 1
    Send("{w up}")
    Sleep 96
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{3 down}")
    Send("{d down}")
    Sleep 84
    Send("{3 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{3 down}")
    Send("{c down}")
    Sleep 84
    Send("{3 up}")
    Sleep 116
    Send("{c up}")
    Sleep 13
    Send("{3 down}")
    Send("{v down}")
    Sleep 82
    Send("{3 up}")
    Sleep 116
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{g down}")
    Sleep 83
    Send("{3 up}")
    Sleep 117
    Send("{g up}")
    Sleep 13
    Send("{w down}")
    Send("{b down}")
    Sleep 98
    Send("{w up}")
    Sleep 7
    Send("{3 down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{3 up}")
    Sleep 8
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 101
    Send("{3 up}")
    Sleep 6
    Send("{t up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 91
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{3 down}")
    Send("{d down}")
    Sleep 84
    Send("{3 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{3 down}")
    Send("{c down}")
    Sleep 84
    Send("{3 up}")
    Sleep 116
    Send("{c up}")
    Sleep 13
    Send("{3 down}")
    Send("{v down}")
    Sleep 82
    Send("{3 up}")
    Sleep 116
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{g down}")
    Sleep 83
    Send("{3 up}")
    Sleep 117
    Send("{g up}")
    Sleep 13
    Send("{r down}")
    Send("{b down}")
    Sleep 98
    Send("{r up}")
    Sleep 7
    Send("{3 down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{3 up}")
    Sleep 8
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 101
    Send("{3 up}")
    Sleep 6
    Send("{t up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 91
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{3 down}")
    Send("{d down}")
    Sleep 84
    Send("{3 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{3 down}")
    Send("{c down}")
    Sleep 84
    Send("{3 up}")
    Sleep 116
    Send("{c up}")
    Sleep 13
    Send("{3 down}")
    Send("{v down}")
    Sleep 82
    Send("{3 up}")
    Sleep 116
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{g down}")
    Sleep 83
    Send("{3 up}")
    Sleep 117
    Send("{g up}")
    Sleep 13
    Send("{w down}")
    Send("{b down}")
    Sleep 98
    Send("{w up}")
    Sleep 7
    Send("{3 down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{3 up}")
    Sleep 8
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 101
    Send("{3 up}")
    Sleep 6
    Send("{t up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 91
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{3 down}")
    Send("{d down}")
    Sleep 84
    Send("{3 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{3 down}")
    Send("{c down}")
    Sleep 84
    Send("{3 up}")
    Sleep 116
    Send("{c up}")
    Sleep 13
    Send("{3 down}")
    Send("{v down}")
    Sleep 82
    Send("{3 up}")
    Sleep 116
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{g down}")
    Sleep 83
    Send("{3 up}")
    Sleep 117
    Send("{g up}")
    Sleep 13
    Send("{r down}")
    Send("{b down}")
    Sleep 98
    Send("{r up}")
    Sleep 7
    Send("{t down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{t up}")
    Sleep 8
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 200
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 200
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 102
    Send("{3 up}")
    Sleep 6
    Send("{t up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 93
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 205
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{v down}")
    Sleep 217
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{r down}")
    Send("{y down}")
    Sleep 101
    Send("{r up}")
    Sleep 6
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Sleep 103
    Send("{h down}")
    Sleep 90
    Send("{t up}")
    Sleep 12
    Send("{7 up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 96
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 13
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 197
    Send("{y up}")
    Sleep 12
    Send("{q up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{h down}")
    Sleep 199
    Send("{7 up}")
    Send("{h up}")
    Sleep 12
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 2
    Send("{q down}")
    Send("{3 down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 12
    Send("{q up}")
    Send("{3 up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 103
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 95
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 223
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 13
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{r down}")
    Send("{y down}")
    Sleep 101
    Send("{r up}")
    Sleep 6
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Sleep 103
    Send("{h down}")
    Sleep 90
    Send("{t up}")
    Sleep 12
    Send("{7 up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 96
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 13
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 197
    Send("{y up}")
    Sleep 12
    Send("{q up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{h down}")
    Sleep 199
    Send("{7 up}")
    Send("{h up}")
    Sleep 12
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 2
    Send("{q down}")
    Send("{3 down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 12
    Send("{q up}")
    Send("{3 up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 12
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{q down}")
    Send("{3 down}")
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{q up}")
    Send("{3 up}")
    Sleep 2
    Send("{3 down}")
    Send("{t down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 12
    Send("{3 up}")
    Send("{t up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 82
    Send("{w up}")
    Send("{r up}")
    Sleep 128
    Send("{r down}")
    Send("{y down}")
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{r up}")
    Send("{n up}")
    Sleep 12
    Send("{y up}")
    Sleep 0
    Send("{3 down}")
    Send("{t down}")
    Send("{j down}")
    Sleep 82
    Send("{3 up}")
    Send("{t up}")
    Sleep 115
    Send("{j up}")
    Sleep 13
    Send("{t down}")
    Send("{7 down}")
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{t up}")
    Send("{7 up}")
    Sleep 2
    Send("{r down}")
    Send("{y down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 103
    Send("{r up}")
    Send("{y up}")
    Sleep 0
    Send("{3 down}")
    Send("{t down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{3 up}")
    Sleep 6
    Send("{t up}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{q down}")
    Send("{3 down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{q up}")
    Sleep 6
    Send("{3 up}")
    Sleep 0
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{7 down}")
    Send("{w down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 103
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{y up}")
    Sleep 6
    Send("{q up}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{t down}")
    Send("{7 down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{r up}")
    Sleep 6
    Send("{y up}")
    Sleep 0
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{3 down}")
    Send("{t down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 223
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 13
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 223
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 13
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{3 up}")
    Send("{t up}")
    Sleep 2
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{y up}")
    Send("{q up}")
    Sleep 7
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{q down}")
    Send("{3 down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{q up}")
    Send("{3 up}")
    Sleep 7
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{y up}")
    Send("{q up}")
    Sleep 7
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{q down}")
    Send("{3 down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{q up}")
    Send("{3 up}")
    Sleep 7
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 17
    Send("{v down}")
    Sleep 210
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 211
    Send("{3 down}")
    Send("{t down}")
    Send("{7 down}")
    Send("{w down}")
    Sleep 1264
    Send("{3 up}")
    Send("{t up}")
    Send("{7 up}")
    Send("{w up}")
    Send("{v up}")
    Sleep 2
    Send("{e down}")
    Send("{6 down}")
    Send("{u down}")
    Send("{3 down}")
    Send("{g down}")
    Sleep 858
    Send("{e up}")
    Send("{6 up}")
    Send("{u up}")
    Send("{3 up}")
    Send("{g up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{q down}")
    Send("{e down}")
    Send("{b down}")
    Sleep 419
    Send("{q down}")
    Sleep 5
    Send("{r up}")
    Send("{y up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 57
    Send("{w down}")
    Sleep 55
    Send("{q up}")
    Sleep 6
    Send("{e down}")
    Sleep 55
    Send("{w up}")
    Sleep 6
    Send("{r down}")
    Sleep 55
    Send("{e up}")
    Sleep 6
    Send("{t down}")
    Sleep 55
    Send("{r up}")
    Sleep 6
    Send("{y down}")
    Sleep 56
    Send("{t up}")
    Sleep 6
    Send("{u down}")
    Sleep 1
    Send("{b up}")
    Sleep 54
    Send("{y up}")
    Sleep 9
    Send("{q down}")
    Send("{z down}")
    Sleep 5
    Send("{u up}")
    Sleep 93
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{3 down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{3 up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{t down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{t up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{3 down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{3 up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{t down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{t up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{3 down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{3 up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{t down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{t up}")
    Sleep 7
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Send("{z down}")
    Sleep 83
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{q down}")
    Sleep 82
    Send("{q up}")
    Sleep 128
    Send("{7 down}")
    Send("{d down}")
    Sleep 84
    Send("{7 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{q down}")
    Send("{c down}")
    Sleep 103
    Send("{q up}")
    Sleep 7
    Send("{7 down}")
    Sleep 78
    Send("{7 up}")
    Sleep 12
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 104
    Send("{3 down}")
    Sleep 96
    Send("{v up}")
    Sleep 6
    Send("{3 up}")
    Sleep 7
    Send("{g down}")
    Sleep 202
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 205
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 862
    Send("{z up}")
    Sleep 845
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 92
    Send("{t down}")
    Sleep 53
    Send("{t up}")
    Send("{6 down}")
    Sleep 53
    Send("{z up}")
    Sleep 0
    Send("{6 up}")
    Sleep 12
    Send("{y down}")
    Send("{q down}")
    Sleep 210
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{e up}")
    Send("{t up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 210
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 12
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{q up}")
    Send("{e up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 105
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 97
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{y up}")
    Send("{z up}")
    Sleep 12
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{g down}")
    Sleep 199
    Send("{t up}")
    Send("{g up}")
    Sleep 13
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{b down}")
    Sleep 98
    Send("{r up}")
    Sleep 6
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{t up}")
    Sleep 6
    Send("{7 up}")
    Sleep 2
    Send("{z down}")
    Sleep 122
    Send("{t down}")
    Send("{7 down}")
    Sleep 91
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{t up}")
    Send("{7 up}")
    Sleep 2
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 13
    Send("{y down}")
    Send("{q down}")
    Sleep 210
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{e up}")
    Send("{t up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 210
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 12
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{q up}")
    Send("{e up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{g down}")
    Sleep 199
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 105
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 97
    Send("{b up}")
    Sleep 15
    Send("{z down}")
    Sleep 212
    Send("{y up}")
    Send("{z up}")
    Sleep 12
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{g down}")
    Sleep 199
    Send("{t up}")
    Send("{g up}")
    Sleep 13
    Send("{7 up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Send("{b down}")
    Sleep 98
    Send("{y up}")
    Sleep 6
    Send("{q up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{7 up}")
    Sleep 6
    Send("{w up}")
    Sleep 2
    Send("{z down}")
    Sleep 122
    Send("{q down}")
    Send("{e down}")
    Sleep 91
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 8
    Send("{q down}")
    Sleep 5
    Send("{q up}")
    Send("{e up}")
    Sleep 0
    Send("{g down}")
    Sleep 26
    Send("{u down}")
    Sleep 27
    Send("{q up}")
    Sleep 3
    Send("{y down}")
    Sleep 27
    Send("{u up}")
    Sleep 3
    Send("{t down}")
    Sleep 27
    Send("{y up}")
    Sleep 3
    Send("{r down}")
    Sleep 27
    Send("{t up}")
    Sleep 3
    Send("{e down}")
    Sleep 27
    Send("{r up}")
    Sleep 3
    Send("{w down}")
    Sleep 20
    Send("{g up}")
    Sleep 7
    Send("{e up}")
    Sleep 3
    Send("{q down}")
    Sleep 3
    Send("{b down}")
    Sleep 25
    Send("{w up}")
    Sleep 3
    Send("{u down}")
    Sleep 28
    Send("{q up}")
    Sleep 3
    Send("{y down}")
    Sleep 28
    Send("{u up}")
    Sleep 3
    Send("{t down}")
    Sleep 28
    Send("{y up}")
    Sleep 3
    Send("{r down}")
    Sleep 28
    Send("{t up}")
    Sleep 3
    Send("{e down}")
    Sleep 28
    Send("{r up}")
    Sleep 3
    Send("{w down}")
    Sleep 19
    Send("{b up}")
    Sleep 9
    Send("{e up}")
    Sleep 6
    Send("{q down}")
    Send("{z down}")
    Sleep 1
    Send("{w up}")
    Sleep 96
    Send("{q up}")
    Sleep 115
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{3 down}")
    Send("{d down}")
    Sleep 84
    Send("{3 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{3 down}")
    Send("{c down}")
    Sleep 84
    Send("{3 up}")
    Sleep 116
    Send("{c up}")
    Sleep 13
    Send("{3 down}")
    Send("{v down}")
    Sleep 82
    Send("{3 up}")
    Sleep 116
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{g down}")
    Sleep 83
    Send("{3 up}")
    Sleep 117
    Send("{g up}")
    Sleep 13
    Send("{w down}")
    Send("{b down}")
    Sleep 98
    Send("{w up}")
    Sleep 7
    Send("{3 down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{3 up}")
    Sleep 8
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 101
    Send("{3 up}")
    Sleep 6
    Send("{t up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 91
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{3 down}")
    Send("{d down}")
    Sleep 84
    Send("{3 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{3 down}")
    Send("{c down}")
    Sleep 84
    Send("{3 up}")
    Sleep 116
    Send("{c up}")
    Sleep 13
    Send("{3 down}")
    Send("{v down}")
    Sleep 82
    Send("{3 up}")
    Sleep 116
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{g down}")
    Sleep 83
    Send("{3 up}")
    Sleep 117
    Send("{g up}")
    Sleep 13
    Send("{r down}")
    Send("{b down}")
    Sleep 98
    Send("{r up}")
    Sleep 7
    Send("{3 down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{3 up}")
    Sleep 8
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 101
    Send("{3 up}")
    Sleep 6
    Send("{t up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 91
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{3 down}")
    Send("{d down}")
    Sleep 84
    Send("{3 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{3 down}")
    Send("{c down}")
    Sleep 84
    Send("{3 up}")
    Sleep 116
    Send("{c up}")
    Sleep 13
    Send("{3 down}")
    Send("{v down}")
    Sleep 82
    Send("{3 up}")
    Sleep 116
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{g down}")
    Sleep 83
    Send("{3 up}")
    Sleep 117
    Send("{g up}")
    Sleep 13
    Send("{w down}")
    Send("{b down}")
    Sleep 98
    Send("{w up}")
    Sleep 7
    Send("{3 down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{3 up}")
    Sleep 8
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 199
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 199
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 101
    Send("{3 up}")
    Sleep 6
    Send("{t up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 91
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 202
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{3 down}")
    Send("{d down}")
    Sleep 84
    Send("{3 up}")
    Sleep 115
    Send("{d up}")
    Sleep 13
    Send("{3 down}")
    Send("{c down}")
    Sleep 84
    Send("{3 up}")
    Sleep 116
    Send("{c up}")
    Sleep 13
    Send("{3 down}")
    Send("{v down}")
    Sleep 82
    Send("{3 up}")
    Sleep 116
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{g down}")
    Sleep 83
    Send("{3 up}")
    Sleep 117
    Send("{g up}")
    Sleep 13
    Send("{r down}")
    Send("{b down}")
    Sleep 98
    Send("{r up}")
    Sleep 7
    Send("{t down}")
    Sleep 97
    Send("{b up}")
    Sleep 6
    Send("{t up}")
    Sleep 8
    Send("{z down}")
    Sleep 212
    Send("{z up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 223
    Send("{d down}")
    Sleep 199
    Send("{d up}")
    Sleep 13
    Send("{c down}")
    Sleep 200
    Send("{c up}")
    Sleep 13
    Send("{v down}")
    Sleep 200
    Send("{v up}")
    Sleep 13
    Send("{3 down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 102
    Send("{3 up}")
    Sleep 6
    Send("{t up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 93
    Send("{g up}")
    Sleep 13
    Send("{b down}")
    Sleep 205
    Send("{b up}")
    Sleep 13
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{v down}")
    Sleep 217
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{r down}")
    Send("{y down}")
    Sleep 101
    Send("{r up}")
    Sleep 6
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Sleep 103
    Send("{h down}")
    Sleep 90
    Send("{t up}")
    Sleep 12
    Send("{7 up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 96
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 13
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 197
    Send("{y up}")
    Sleep 12
    Send("{q up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{h down}")
    Sleep 199
    Send("{7 up}")
    Send("{h up}")
    Sleep 12
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 2
    Send("{q down}")
    Send("{3 down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 12
    Send("{q up}")
    Send("{3 up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 103
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 95
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 223
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 13
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{r up}")
    Send("{y up}")
    Sleep 2
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{r down}")
    Send("{y down}")
    Sleep 101
    Send("{r up}")
    Sleep 6
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Sleep 103
    Send("{h down}")
    Sleep 90
    Send("{t up}")
    Sleep 12
    Send("{7 up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 96
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 13
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 197
    Send("{y up}")
    Sleep 12
    Send("{q up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{h down}")
    Sleep 199
    Send("{7 up}")
    Send("{h up}")
    Sleep 12
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 12
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 2
    Send("{q down}")
    Send("{3 down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 12
    Send("{q up}")
    Send("{3 up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 12
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{q down}")
    Send("{3 down}")
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{q up}")
    Send("{3 up}")
    Sleep 2
    Send("{3 down}")
    Send("{t down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 12
    Send("{3 up}")
    Send("{t up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 82
    Send("{w up}")
    Send("{r up}")
    Sleep 128
    Send("{r down}")
    Send("{y down}")
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{r up}")
    Send("{n up}")
    Sleep 12
    Send("{y up}")
    Sleep 0
    Send("{3 down}")
    Send("{t down}")
    Send("{j down}")
    Sleep 82
    Send("{3 up}")
    Send("{t up}")
    Sleep 115
    Send("{j up}")
    Sleep 13
    Send("{t down}")
    Send("{7 down}")
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{t up}")
    Send("{7 up}")
    Sleep 2
    Send("{r down}")
    Send("{y down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 103
    Send("{r up}")
    Send("{y up}")
    Sleep 0
    Send("{3 down}")
    Send("{t down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{3 up}")
    Sleep 6
    Send("{t up}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{q down}")
    Send("{3 down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{q up}")
    Sleep 6
    Send("{3 up}")
    Sleep 0
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{7 down}")
    Send("{w down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 103
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 95
    Send("{v up}")
    Sleep 6
    Send("{y up}")
    Sleep 6
    Send("{q up}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{t down}")
    Send("{7 down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{t up}")
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{r up}")
    Sleep 6
    Send("{y up}")
    Sleep 0
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{3 down}")
    Send("{t down}")
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 223
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 13
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 223
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 13
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 13
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 12
    Send("{3 up}")
    Send("{t up}")
    Sleep 2
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{y up}")
    Send("{q up}")
    Sleep 7
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{q down}")
    Send("{3 down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{q up}")
    Send("{3 up}")
    Sleep 7
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{y up}")
    Send("{q up}")
    Sleep 7
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 212
    Send("{v up}")
    Sleep 13
    Send("{v down}")
    Sleep 198
    Send("{v up}")
    Sleep 13
    Send("{7 down}")
    Send("{w down}")
    Sleep 210
    Send("{h down}")
    Sleep 199
    Send("{h up}")
    Sleep 12
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 13
    Send("{j down}")
    Sleep 103
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{q down}")
    Send("{3 down}")
    Sleep 94
    Send("{j up}")
    Sleep 6
    Send("{q up}")
    Send("{3 up}")
    Sleep 7
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 13
    Send("{z down}")
    Sleep 198
    Send("{z up}")
}
