#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{2 down}")
    Sleep 111
    Send("{w up}")
    Send("{5 up}")
    Send("{y up}")
    Send("{2 up}")
    Send("{2 up}")
    Sleep 150
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{2 down}")
    Sleep 98
    Send("{w up}")
    Send("{2 up}")
    Send("{2 up}")
    Sleep 15
    Send("{5 up}")
    Send("{y up}")
    Sleep 261
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{2 down}")
    Sleep 113
    Send("{w up}")
    Send("{5 up}")
    Send("{y up}")
    Sleep 7
    Send("{2 up}")
    Sleep 7
    Send("{2 up}")
    Sleep 114
    Send("{e down}")
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{w down}")
    Sleep 120
    Send("{e up}")
    Send("{t up}")
    Send("{u up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{w up}")
    Sleep 122
    Send("{e down}")
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{w down}")
    Sleep 113
    Send("{e up}")
    Send("{t up}")
    Send("{u up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{w up}")
    Sleep 240
    Send("{e down}")
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{w down}")
    Sleep 96
    Send("{e up}")
    Send("{t up}")
    Send("{u up}")
    Send("{w up}")
    Send("{w up}")
    Sleep 150
    Send("{e down}")
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{w down}")
    Sleep 83
    Send("{t up}")
    Sleep 15
    Send("{e up}")
    Send("{u up}")
    Send("{w up}")
    Send("{w up}")
    Sleep 152
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 114
    Send("{5 up}")
    Send("{y up}")
    Send("{2 up}")
    Send("{e up}")
    Send("{e up}")
    Sleep 150
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 83
    Send("{y up}")
    Send("{2 up}")
    Sleep 15
    Send("{5 up}")
    Send("{e up}")
    Send("{e up}")
    Sleep 276
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 113
    Send("{5 up}")
    Send("{y up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 7
    Send("{e up}")
    Sleep 122
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 120
    Send("{t up}")
    Send("{u up}")
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 129
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Sleep 113
    Send("{t up}")
    Send("{u up}")
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{y down}")
    Sleep 14
    Send("{y up}")
    Sleep 107
    Send("{y down}")
    Sleep 14
    Send("{y up}")
    Sleep 87
    Send("{y up}")
    Sleep 24
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 96
    Send("{t up}")
    Send("{u up}")
    Send("{w up}")
    Send("{5 up}")
    Sleep 150
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 83
    Send("{u up}")
    Sleep 15
    Send("{t up}")
    Send("{w up}")
    Send("{5 up}")
    Sleep 152
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{2 down}")
    Sleep 114
    Send("{w up}")
    Send("{5 up}")
    Send("{y up}")
    Send("{2 up}")
    Send("{2 up}")
    Sleep 150
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{2 down}")
    Sleep 83
    Send("{5 up}")
    Send("{y up}")
    Sleep 15
    Send("{w up}")
    Send("{2 up}")
    Send("{2 up}")
    Sleep 276
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{2 down}")
    Sleep 113
    Send("{w up}")
    Send("{5 up}")
    Send("{y up}")
    Send("{2 up}")
    Sleep 7
    Send("{2 up}")
    Sleep 122
    Send("{e down}")
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Sleep 120
    Send("{e up}")
    Send("{t up}")
    Send("{u up}")
    Sleep 7
    Send("{w up}")
    Sleep 129
    Send("{e down}")
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{y down}")
    Sleep 113
    Send("{e up}")
    Send("{t up}")
    Send("{u up}")
    Sleep 7
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Sleep 14
    Send("{y up}")
    Sleep 107
    Send("{y down}")
    Sleep 14
    Send("{y up}")
    Sleep 87
    Send("{y up}")
    Sleep 24
    Send("{e down}")
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Sleep 96
    Send("{e up}")
    Send("{t up}")
    Send("{u up}")
    Send("{w up}")
    Sleep 150
    Send("{e down}")
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Sleep 83
    Send("{t up}")
    Sleep 15
    Send("{e up}")
    Send("{u up}")
    Send("{w up}")
    Sleep 152
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 114
    Send("{5 up}")
    Send("{y up}")
    Send("{2 up}")
    Send("{e up}")
    Send("{e up}")
    Sleep 150
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 83
    Send("{y up}")
    Send("{2 up}")
    Sleep 15
    Send("{5 up}")
    Send("{e up}")
    Send("{e up}")
    Sleep 276
    Send("{5 down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 113
    Send("{5 up}")
    Send("{y up}")
    Send("{2 up}")
    Sleep 7
    Send("{e up}")
    Sleep 7
    Send("{e up}")
    Sleep 114
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{5 down}")
    Sleep 120
    Send("{t up}")
    Send("{u up}")
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 7
    Send("{5 up}")
    Sleep 122
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{5 down}")
    Sleep 113
    Send("{t up}")
    Send("{u up}")
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 7
    Send("{5 up}")
    Sleep 240
    Send("{t down}")
    Send("{u down}")
    Send("{w down}")
    Send("{y down}")
    Send("{5 down}")
    Sleep 82
    Send("{u up}")
    Sleep 15
    Send("{t up}")
    Send("{w up}")
    Send("{y up}")
    Send("{5 up}")
    Sleep 150
    Send("{y down}")
    Send("{y down}")
    Sleep 97
    Send("{y up}")
    Send("{y up}")
    Sleep 152
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 250
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Send("{x up}")
    Sleep 0
    Send("{5 down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 126
    Send("{w down}")
    Send("{5 down}")
    Sleep 105
    Send("{n up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{x down}")
    Sleep 121
    Send("{5 down}")
    Send("{y down}")
    Sleep 113
    Send("{x up}")
    Sleep 15
    Send("{x down}")
    Sleep 370
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 118
    Send("{n up}")
    Sleep 7
    Send("{5 up}")
    Send("{y up}")
    Sleep 0
    Send("{y down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 96
    Send("{x up}")
    Sleep 21
    Send("{y up}")
    Sleep 8
    Send("{u down}")
    Sleep 106
    Send("{5 up}")
    Sleep 7
    Send("{u up}")
    Sleep 8
    Send("{n down}")
    Sleep 232
    Send("{n up}")
    Sleep 17
    Send("{t down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 264
    Send("{t up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 121
    Send("{t up}")
    Send("{u up}")
    Send("{z up}")
    Sleep 0
    Send("{t down}")
    Send("{q down}")
    Send("{b down}")
    Sleep 126
    Send("{q up}")
    Sleep 7
    Send("{t up}")
    Sleep 119
    Send("{t down}")
    Send("{u down}")
    Sleep 105
    Send("{b up}")
    Sleep 15
    Send("{u up}")
    Sleep 0
    Send("{z down}")
    Sleep 7
    Send("{t up}")
    Sleep 114
    Send("{t down}")
    Send("{q down}")
    Sleep 113
    Send("{z up}")
    Sleep 15
    Send("{z down}")
    Sleep 249
    Send("{t up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 97
    Send("{t up}")
    Send("{u up}")
    Sleep 25
    Send("{z up}")
    Sleep 0
    Send("{b down}")
    Sleep 119
    Send("{b up}")
    Sleep 8
    Send("{q down}")
    Send("{e down}")
    Send("{y down}")
    Send("{z down}")
    Sleep 97
    Send("{q up}")
    Send("{e up}")
    Send("{y up}")
    Send("{z up}")
    Sleep 152
    Send("{e down}")
    Send("{t down}")
    Send("{b down}")
    Sleep 99
    Send("{e up}")
    Send("{t up}")
    Sleep 138
    Send("{b up}")
    Sleep 17
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 250
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Send("{x up}")
    Sleep 0
    Send("{5 down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 126
    Send("{w down}")
    Send("{5 down}")
    Sleep 105
    Send("{n up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{x down}")
    Sleep 121
    Send("{5 down}")
    Send("{y down}")
    Sleep 113
    Send("{x up}")
    Sleep 7
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{x down}")
    Sleep 250
    Send("{y down}")
    Send("{w down}")
    Sleep 122
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 120
    Send("{n up}")
    Sleep 8
    Send("{x down}")
    Sleep 99
    Send("{x up}")
    Sleep 139
    Send("{y up}")
    Sleep 15
    Send("{w up}")
    Sleep 1
    Send("{e down}")
    Send("{x down}")
    Sleep 101
    Send("{e up}")
    Sleep 158
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Send("{b down}")
    Sleep 13
    Send("{x up}")
    Sleep 241
    Send("{7 up}")
    Sleep 15
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{x down}")
    Sleep 119
    Send("{w up}")
    Sleep 134
    Send("{7 down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{7 up}")
    Sleep 8
    Send("{b down}")
    Sleep 121
    Send("{7 down}")
    Send("{w down}")
    Sleep 113
    Send("{b up}")
    Sleep 144
    Send("{z down}")
    Sleep 113
    Send("{z up}")
    Sleep 128
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{z down}")
    Sleep 118
    Send("{z up}")
    Sleep 133
    Send("{z down}")
    Sleep 106
    Send("{r up}")
    Sleep 7
    Send("{z up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 97
    Send("{e up}")
    Send("{t up}")
    Sleep 135
    Send("{z up}")
    Sleep 17
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 250
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Send("{x up}")
    Sleep 0
    Send("{5 down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 126
    Send("{w down}")
    Send("{5 down}")
    Sleep 105
    Send("{n up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{x down}")
    Sleep 121
    Send("{5 down}")
    Send("{y down}")
    Sleep 113
    Send("{x up}")
    Sleep 15
    Send("{x down}")
    Sleep 370
    Send("{5 up}")
    Send("{y up}")
    Send("{x up}")
    Sleep 0
    Send("{w down}")
    Send("{n down}")
    Sleep 118
    Send("{w up}")
    Send("{n up}")
    Sleep 8
    Send("{y down}")
    Send("{x down}")
    Sleep 96
    Send("{y up}")
    Send("{x up}")
    Sleep 150
    Send("{u down}")
    Send("{n down}")
    Sleep 97
    Send("{u up}")
    Sleep 135
    Send("{n up}")
    Sleep 17
    Send("{t down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 264
    Send("{t up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 114
    Send("{t up}")
    Sleep 7
    Send("{u up}")
    Send("{z up}")
    Sleep 0
    Send("{q down}")
    Send("{b down}")
    Sleep 119
    Send("{q up}")
    Sleep 134
    Send("{t down}")
    Send("{u down}")
    Sleep 105
    Send("{b up}")
    Sleep 7
    Send("{t up}")
    Sleep 7
    Send("{u up}")
    Sleep 0
    Send("{z down}")
    Sleep 121
    Send("{t down}")
    Send("{q down}")
    Sleep 113
    Send("{z up}")
    Sleep 15
    Send("{z down}")
    Sleep 234
    Send("{t up}")
    Sleep 15
    Send("{q up}")
    Sleep 0
    Send("{w down}")
    Sleep 97
    Send("{w up}")
    Sleep 25
    Send("{z up}")
    Sleep 0
    Send("{b down}")
    Sleep 126
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{b down}")
    Sleep 97
    Send("{w up}")
    Send("{r up}")
    Sleep 137
    Send("{b up}")
    Sleep 15
    Send("{q down}")
    Send("{e down}")
    Send("{z down}")
    Sleep 99
    Send("{q up}")
    Send("{e up}")
    Sleep 138
    Send("{z up}")
    Sleep 17
    Send("{u down}")
    Send("{w down}")
    Send("{b down}")
    Sleep 264
    Send("{u up}")
    Send("{w up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 98
    Send("{u up}")
    Sleep 23
    Send("{b up}")
    Sleep 0
    Send("{x down}")
    Sleep 19
    Send("{t up}")
    Sleep 234
    Send("{w down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{w up}")
    Sleep 8
    Send("{b down}")
    Sleep 121
    Send("{w down}")
    Send("{r down}")
    Sleep 113
    Send("{b up}")
    Sleep 15
    Send("{b down}")
    Sleep 121
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 113
    Send("{e up}")
    Sleep 8
    Send("{w down}")
    Sleep 121
    Send("{b up}")
    Sleep 0
    Send("{x down}")
    Sleep 125
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 231
    Send("{w up}")
    Send("{x up}")
    Sleep 15
    Send("{e down}")
    Send("{b down}")
    Sleep 97
    Send("{e up}")
    Sleep 135
    Send("{b up}")
    Sleep 17
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{j down}")
    Sleep 250
    Send("{w up}")
    Sleep 15
    Send("{r up}")
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Sleep 114
    Send("{t up}")
    Sleep 7
    Send("{j up}")
    Sleep 0
    Send("{r down}")
    Send("{v down}")
    Sleep 119
    Send("{r up}")
    Sleep 134
    Send("{t down}")
    Sleep 105
    Send("{v up}")
    Sleep 7
    Send("{t up}")
    Sleep 8
    Send("{j down}")
    Sleep 121
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 113
    Send("{j up}")
    Sleep 144
    Send("{z down}")
    Sleep 114
    Send("{z up}")
    Sleep 131
    Send("{z down}")
    Sleep 120
    Send("{z up}")
    Sleep 7
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 1
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 129
    Send("{z down}")
    Sleep 117
    Send("{z up}")
    Sleep 8
    Send("{z down}")
    Sleep 241
    Send("{z up}")
    Sleep 15
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 3
    Send("{q down}")
    Send("{e down}")
    Send("{v down}")
    Sleep 254
    Send("{q up}")
    Sleep 15
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 114
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Send("{v up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 119
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Sleep 126
    Send("{q down}")
    Send("{e down}")
    Sleep 105
    Send("{z up}")
    Sleep 7
    Send("{q up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{z down}")
    Sleep 121
    Send("{t down}")
    Send("{q down}")
    Sleep 113
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 370
    Send("{v up}")
    Sleep 0
    Send("{z down}")
    Sleep 357
    Send("{z up}")
    Sleep 15
    Send("{t up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{q down}")
    Send("{v down}")
    Sleep 97
    Send("{t up}")
    Send("{q up}")
    Sleep 135
    Send("{v up}")
    Sleep 17
    Send("{u down}")
    Send("{e down}")
    Send("{m down}")
    Sleep 264
    Send("{u up}")
    Send("{e up}")
    Sleep 0
    Send("{u down}")
    Send("{w down}")
    Sleep 121
    Send("{u up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 0
    Send("{u down}")
    Send("{e down}")
    Send("{v down}")
    Sleep 126
    Send("{e up}")
    Sleep 7
    Send("{u up}")
    Sleep 119
    Send("{u down}")
    Send("{w down}")
    Sleep 105
    Send("{v up}")
    Sleep 15
    Send("{w up}")
    Sleep 0
    Send("{m down}")
    Sleep 7
    Send("{u up}")
    Sleep 114
    Send("{u down}")
    Send("{r down}")
    Sleep 113
    Send("{m up}")
    Sleep 15
    Send("{m down}")
    Sleep 99
    Send("{r up}")
    Sleep 16
    Send("{e down}")
    Sleep 62
    Send("{e up}")
    Send("{3 down}")
    Sleep 57
    Send("{u up}")
    Sleep 6
    Send("{3 up}")
    Sleep 4
    Send("{u down}")
    Send("{w down}")
    Sleep 126
    Send("{m up}")
    Sleep 0
    Send("{v down}")
    Sleep 357
    Send("{v up}")
    Sleep 15
    Send("{m down}")
    Sleep 232
    Send("{m up}")
    Sleep 15
    Send("{u up}")
    Send("{w up}")
    Sleep 2
    Send("{7 down}")
    Send("{w down}")
    Send("{j down}")
    Sleep 250
    Send("{7 up}")
    Sleep 15
    Send("{w up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Sleep 114
    Send("{q up}")
    Sleep 7
    Send("{e up}")
    Send("{j up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{v down}")
    Sleep 119
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Sleep 126
    Send("{7 down}")
    Send("{w down}")
    Sleep 105
    Send("{v up}")
    Sleep 7
    Send("{7 up}")
    Sleep 7
    Send("{w up}")
    Sleep 0
    Send("{j down}")
    Sleep 121
    Send("{w down}")
    Send("{r down}")
    Sleep 113
    Send("{j up}")
    Sleep 15
    Send("{j down}")
    Sleep 370
    Send("{w up}")
    Send("{r up}")
    Send("{j up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{v down}")
    Sleep 118
    Send("{r up}")
    Send("{v up}")
    Sleep 7
    Send("{y up}")
    Sleep 126
    Send("{e down}")
    Send("{t down}")
    Sleep 113
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{n down}")
    Sleep 232
    Send("{n up}")
    Sleep 17
    Send("{q down}")
    Send("{y down}")
    Send("{b down}")
    Sleep 264
    Send("{q up}")
    Send("{y up}")
    Sleep 0
    Send("{q down}")
    Send("{t down}")
    Sleep 121
    Send("{q up}")
    Send("{t up}")
    Send("{b up}")
    Sleep 0
    Send("{q down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 119
    Send("{q up}")
    Sleep 7
    Send("{y up}")
    Sleep 126
    Send("{w down}")
    Send("{t down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{b down}")
    Sleep 121
    Send("{q down}")
    Send("{e down}")
    Sleep 113
    Send("{b up}")
    Sleep 144
    Send("{z down}")
    Sleep 105
    Send("{q up}")
    Sleep 15
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 96
    Send("{w up}")
    Send("{r up}")
    Sleep 150
    Send("{z up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 96
    Send("{e up}")
    Send("{t up}")
    Send("{z up}")
    Sleep 150
    Send("{t down}")
    Send("{q down}")
    Send("{j down}")
    Sleep 97
    Send("{t up}")
    Send("{q up}")
    Send("{j up}")
    Sleep 152
    Send("{q down}")
    Send("{e down}")
    Send("{n down}")
    Sleep 250
    Send("{q up}")
    Sleep 15
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 114
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{c down}")
    Sleep 119
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Sleep 126
    Send("{q down}")
    Send("{e down}")
    Sleep 105
    Send("{c up}")
    Sleep 7
    Send("{q up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{n down}")
    Sleep 121
    Send("{e down}")
    Send("{t down}")
    Sleep 113
    Send("{n up}")
    Sleep 15
    Send("{n down}")
    Sleep 370
    Send("{n up}")
    Sleep 0
    Send("{c down}")
    Sleep 125
    Send("{e up}")
    Send("{t up}")
    Sleep 0
    Send("{t down}")
    Sleep 96
    Send("{t up}")
    Sleep 135
    Send("{c up}")
    Sleep 15
    Send("{y down}")
    Send("{n down}")
    Sleep 97
    Send("{y up}")
    Sleep 135
    Send("{n up}")
    Sleep 17
    Send("{r down}")
    Send("{u down}")
    Send("{h down}")
    Sleep 264
    Send("{r up}")
    Send("{u up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 121
    Send("{r up}")
    Send("{y up}")
    Send("{h up}")
    Sleep 0
    Send("{r down}")
    Send("{u down}")
    Send("{x down}")
    Sleep 119
    Send("{r up}")
    Sleep 7
    Send("{u up}")
    Sleep 126
    Send("{w down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{w up}")
    Sleep 8
    Send("{x down}")
    Sleep 121
    Send("{u down}")
    Send("{r down}")
    Sleep 113
    Send("{x up}")
    Sleep 15
    Send("{h down}")
    Sleep 121
    Send("{u up}")
    Sleep 7
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 114
    Send("{e up}")
    Sleep 130
    Send("{h up}")
    Sleep 0
    Send("{x down}")
    Sleep 128
    Send("{w down}")
    Sleep 99
    Send("{w up}")
    Sleep 139
    Send("{x up}")
    Sleep 16
    Send("{u down}")
    Send("{x down}")
    Sleep 101
    Send("{u up}")
    Sleep 140
    Send("{x up}")
    Sleep 18
    Send("{w down}")
    Send("{5 down}")
    Send("{b down}")
    Sleep 254
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{x down}")
    Sleep 119
    Send("{w up}")
    Sleep 134
    Send("{u down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{u up}")
    Sleep 8
    Send("{b down}")
    Sleep 121
    Send("{y down}")
    Send("{w down}")
    Sleep 113
    Send("{b up}")
    Sleep 15
    Send("{g down}")
    Sleep 370
    Send("{g up}")
    Sleep 0
    Send("{s down}")
    Sleep 125
    Send("{y up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Sleep 96
    Send("{y up}")
    Send("{w up}")
    Sleep 135
    Send("{s up}")
    Sleep 15
    Send("{e down}")
    Send("{g down}")
    Sleep 97
    Send("{e up}")
    Sleep 135
    Send("{g up}")
    Sleep 17
    Send("{w down}")
    Send("{r down}")
    Send("{b down}")
    Sleep 250
    Send("{w up}")
    Sleep 15
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{b up}")
    Sleep 0
    Send("{r down}")
    Send("{x down}")
    Sleep 119
    Send("{r up}")
    Sleep 134
    Send("{w down}")
    Send("{t down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{b down}")
    Sleep 121
    Send("{y down}")
    Send("{y down}")
    Sleep 113
    Send("{b up}")
    Sleep 144
    Send("{n down}")
    Sleep 106
    Send("{y up}")
    Sleep 15
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Sleep 97
    Send("{t up}")
    Sleep 152
    Send("{n up}")
    Sleep 1
    Send("{r down}")
    Send("{n down}")
    Sleep 99
    Send("{r up}")
    Send("{n up}")
    Sleep 155
    Send("{e down}")
    Send("{n down}")
    Sleep 101
    Send("{e up}")
    Send("{n up}")
    Sleep 158
    Send("{x down}")
    Sleep 269
    Send("{y down}")
    Sleep 121
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 126
    Send("{w down}")
    Sleep 29
    Send("{y up}")
    Sleep 109
    Send("{w up}")
    Sleep 93
    Send("{n up}")
    Sleep 15
    Send("{5 down}")
    Send("{x down}")
    Sleep 99
    Send("{5 up}")
    Sleep 135
    Send("{x up}")
    Sleep 15
    Send("{2 down}")
    Send("{e down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 234
    Send("{2 up}")
    Send("{e up}")
    Sleep 15
    Send("{t up}")
    Sleep 0
    Send("{5 down}")
    Sleep 113
    Send("{5 up}")
    Sleep 7
    Send("{g up}")
    Sleep 0
    Send("{t down}")
    Send("{s down}")
    Sleep 118
    Send("{t up}")
    Sleep 133
    Send("{y down}")
    Sleep 106
    Send("{s up}")
    Sleep 7
    Send("{y up}")
    Sleep 8
    Send("{g down}")
    Sleep 121
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Sleep 111
    Send("{g up}")
    Sleep 17
    Send("{b down}")
    Sleep 386
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 119
    Send("{b up}")
    Sleep 7
    Send("{w up}")
    Send("{5 up}")
    Send("{y up}")
    Sleep 0
    Send("{w down}")
    Send("{x down}")
    Sleep 96
    Send("{w up}")
    Send("{x up}")
    Sleep 150
    Send("{e down}")
    Send("{b down}")
    Sleep 234
    Send("{e up}")
    Send("{b up}")
    Sleep 15
    Send("{u down}")
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 234
    Send("{u up}")
    Send("{w up}")
    Sleep 15
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 113
    Send("{e up}")
    Sleep 7
    Send("{n up}")
    Sleep 0
    Send("{u down}")
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 118
    Send("{u up}")
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Sleep 126
    Send("{u down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 106
    Send("{n up}")
    Sleep 7
    Send("{u up}")
    Send("{w up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{b down}")
    Sleep 121
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 111
    Send("{b up}")
    Sleep 17
    Send("{g down}")
    Sleep 512
    Send("{y up}")
    Send("{2 up}")
    Send("{e up}")
    Send("{g up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Send("{s down}")
    Sleep 96
    Send("{y up}")
    Send("{w up}")
    Sleep 135
    Send("{s up}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Send("{g down}")
    Sleep 99
    Send("{w up}")
    Send("{5 up}")
    Sleep 135
    Send("{g up}")
    Sleep 15
    Send("{q down}")
    Send("{t down}")
    Send("{m down}")
    Sleep 234
    Send("{q up}")
    Sleep 15
    Send("{t up}")
    Sleep 0
    Send("{u down}")
    Send("{5 down}")
    Sleep 114
    Send("{u up}")
    Sleep 7
    Send("{5 up}")
    Send("{m up}")
    Sleep 0
    Send("{q down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 119
    Send("{q up}")
    Sleep 7
    Send("{t up}")
    Sleep 128
    Send("{w down}")
    Send("{y down}")
    Sleep 107
    Send("{g up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{m down}")
    Sleep 123
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Sleep 114
    Send("{m up}")
    Sleep 17
    Send("{c down}")
    Sleep 386
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 119
    Send("{c up}")
    Sleep 7
    Send("{w up}")
    Send("{5 up}")
    Send("{y up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Send("{g down}")
    Sleep 96
    Send("{w up}")
    Send("{w up}")
    Sleep 135
    Send("{g up}")
    Sleep 15
    Send("{e down}")
    Send("{e down}")
    Send("{b down}")
    Sleep 99
    Send("{e up}")
    Send("{e up}")
    Sleep 135
    Send("{b up}")
    Sleep 15
    Send("{r down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 235
    Send("{r up}")
    Sleep 15
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Sleep 115
    Send("{e up}")
    Sleep 7
    Send("{e up}")
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 120
    Send("{w up}")
    Sleep 7
    Send("{w up}")
    Sleep 129
    Send("{e down}")
    Send("{t down}")
    Send("{u down}")
    Send("{e down}")
    Sleep 109
    Send("{n up}")
    Sleep 16
    Send("{n down}")
    Sleep 110
    Send("{e up}")
    Send("{t up}")
    Sleep 15
    Send("{u up}")
    Send("{e up}")
    Sleep 1
    Send("{w down}")
    Send("{w down}")
    Sleep 116
    Send("{n up}")
    Sleep 18
    Send("{x down}")
    Sleep 254
    Send("{w up}")
    Sleep 15
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Sleep 98
    Send("{y up}")
    Sleep 23
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 126
    Send("{w down}")
    Sleep 96
    Send("{w up}")
    Sleep 135
    Send("{n up}")
    Sleep 15
    Send("{5 down}")
    Send("{x down}")
    Sleep 99
    Send("{5 up}")
    Sleep 135
    Send("{x up}")
    Sleep 15
    Send("{t down}")
    Send("{g down}")
    Sleep 234
    Send("{t up}")
    Sleep 15
    Send("{5 down}")
    Sleep 113
    Send("{5 up}")
    Sleep 7
    Send("{g up}")
    Sleep 0
    Send("{t down}")
    Send("{s down}")
    Sleep 118
    Send("{t up}")
    Sleep 133
    Send("{5 down}")
    Send("{y down}")
    Sleep 106
    Send("{s up}")
    Sleep 7
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{g down}")
    Sleep 121
    Send("{5 down}")
    Send("{y down}")
    Sleep 111
    Send("{g up}")
    Sleep 17
    Send("{b down}")
    Sleep 250
    Send("{5 up}")
    Sleep 15
    Send("{y up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Sleep 121
    Send("{b up}")
    Sleep 0
    Send("{x down}")
    Sleep 111
    Send("{y up}")
    Sleep 15
    Send("{w up}")
    Sleep 126
    Send("{y down}")
    Send("{w down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{y up}")
    Sleep 7
    Send("{w up}")
    Sleep 0
    Send("{b down}")
    Sleep 121
    Send("{w down}")
    Sleep 113
    Send("{b up}")
    Sleep 7
    Send("{w up}")
    Sleep 8
    Send("{r down}")
    Send("{n down}")
    Sleep 234
    Send("{r up}")
    Sleep 15
    Send("{e down}")
    Sleep 113
    Send("{e up}")
    Sleep 7
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Send("{n down}")
    Sleep 118
    Send("{w up}")
    Send("{n up}")
    Sleep 8
    Send("{n down}")
    Sleep 125
    Send("{u down}")
    Send("{e down}")
    Sleep 106
    Send("{n up}")
    Sleep 7
    Send("{u up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{b down}")
    Sleep 121
    Send("{y down}")
    Send("{w down}")
    Sleep 111
    Send("{b up}")
    Sleep 17
    Send("{g down}")
    Sleep 250
    Send("{y up}")
    Sleep 15
    Send("{w up}")
    Sleep 122
    Send("{g up}")
    Sleep 0
    Send("{y down}")
    Send("{g down}")
    Sleep 119
    Send("{y up}")
    Send("{g up}")
    Sleep 8
    Send("{w down}")
    Send("{x down}")
    Sleep 96
    Send("{w up}")
    Send("{x up}")
    Sleep 150
    Send("{5 down}")
    Send("{g down}")
    Sleep 99
    Send("{5 up}")
    Send("{g up}")
    Sleep 150
    Send("{w down}")
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Sleep 234
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Send("{u up}")
    Sleep 0
    Send("{5 down}")
    Sleep 114
    Send("{5 up}")
    Sleep 7
    Send("{m up}")
    Sleep 0
    Send("{t down}")
    Send("{g down}")
    Sleep 119
    Send("{t up}")
    Sleep 135
    Send("{y down}")
    Sleep 107
    Send("{g up}")
    Sleep 7
    Send("{y up}")
    Sleep 8
    Send("{m down}")
    Sleep 123
    Send("{y down}")
    Send("{5 down}")
    Sleep 114
    Send("{m up}")
    Sleep 17
    Send("{c down}")
    Sleep 264
    Send("{5 up}")
    Sleep 0
    Send("{w down}")
    Sleep 121
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 111
    Send("{y up}")
    Sleep 7
    Send("{c up}")
    Sleep 7
    Send("{w up}")
    Sleep 0
    Send("{g down}")
    Sleep 231
    Send("{g up}")
    Sleep 15
    Send("{w down}")
    Send("{b down}")
    Sleep 99
    Send("{w up}")
    Sleep 135
    Send("{b up}")
    Sleep 15
    Send("{w down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 234
    Send("{w up}")
    Sleep 15
    Send("{y up}")
    Send("{n up}")
    Sleep 0
    Send("{u down}")
    Send("{t down}")
    Send("{n down}")
    Sleep 114
    Send("{u up}")
    Send("{n up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{y down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 119
    Send("{y up}")
    Sleep 7
    Send("{5 up}")
    Sleep 120
    Send("{n up}")
    Sleep 8
    Send("{e down}")
    Send("{t down}")
    Send("{n down}")
    Sleep 115
    Send("{e up}")
    Send("{n up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{n down}")
    Sleep 123
    Send("{w down}")
    Send("{5 down}")
    Sleep 114
    Send("{n up}")
    Sleep 17
    Send("{x down}")
    Sleep 386
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 79
    Send("{w up}")
    Send("{5 up}")
    Sleep 47
    Send("{w down}")
    Send("{5 down}")
    Sleep 96
    Send("{w up}")
    Send("{5 up}")
    Sleep 135
    Send("{n up}")
    Sleep 15
    Send("{2 down}")
    Send("{e down}")
    Send("{x down}")
    Sleep 113
    Send("{2 up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 113
    Send("{x up}")
    Sleep 7
    Send("{t up}")
    Sleep 7
    Send("{u up}")
    Sleep 0
    Send("{x down}")
    Sleep 129
    Send("{t down}")
    Send("{u down}")
    Sleep 121
    Send("{u up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Sleep 14
    Send("{t up}")
    Sleep 83
    Send("{5 up}")
    Sleep 25
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 18
    Send("{w up}")
    Sleep 109
    Send("{n up}")
    Sleep 1
    Send("{t down}")
    Send("{u down}")
    Send("{n down}")
    Sleep 99
    Send("{t up}")
    Send("{u up}")
    Sleep 139
    Send("{n up}")
    Sleep 16
    Send("{w down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 85
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 140
    Send("{n up}")
    Sleep 18
    Send("{y down}")
    Send("{2 down}")
    Send("{x down}")
    Sleep 119
    Send("{y up}")
    Send("{2 up}")
    Sleep 151
    Send("{w down}")
    Send("{5 down}")
    Sleep 98
    Send("{w up}")
    Send("{5 up}")
    Sleep 23
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 126
    Send("{y down}")
    Send("{2 down}")
    Sleep 96
    Send("{y up}")
    Send("{2 up}")
    Sleep 135
    Send("{n up}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 113
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 113
    Send("{x up}")
    Sleep 7
    Send("{t up}")
    Sleep 7
    Send("{u up}")
    Sleep 0
    Send("{x down}")
    Sleep 128
    Send("{t down}")
    Send("{u down}")
    Sleep 120
    Send("{u up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 14
    Send("{t up}")
    Sleep 82
    Send("{5 up}")
    Sleep 24
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 18
    Send("{w up}")
    Sleep 100
    Send("{n up}")
    Sleep 8
    Send("{w down}")
    Send("{t down}")
    Send("{u down}")
    Sleep 29
    Send("{y up}")
    Sleep 67
    Send("{t up}")
    Send("{u up}")
    Sleep 29
    Send("{n down}")
    Sleep 113
    Send("{n up}")
    Sleep 8
    Send("{u down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 29
    Send("{w up}")
    Sleep 53
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 16
    Send("{n up}")
    Sleep 8
    Send("{n down}")
    Sleep 89
    Send("{u up}")
    Sleep 29
    Send("{n up}")
    Sleep 10
    Send("{e down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 386
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 358
    Send("{n up}")
    Sleep 4
    Send("{6 down}")
    Sleep 11
    Send("{x down}")
    Sleep 51
    Send("{6 up}")
    Send("{t down}")
    Sleep 47
    Send("{y up}")
    Sleep 15
    Send("{t up}")
    Send("{5 down}")
    Sleep 62
    Send("{5 up}")
    Send("{r down}")
    Sleep 58
    Send("{x up}")
    Sleep 5
    Send("{r up}")
    Sleep 4
    Send("{2 down}")
    Send("{e down}")
    Sleep 6
    Send("{e up}")
    Sleep 0
    Send("{x down}")
    Sleep 370
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 118
    Send("{n up}")
    Sleep 254
    Send("{n down}")
    Sleep 97
    Send("{e up}")
    Sleep 25
    Send("{3 down}")
    Sleep 62
    Send("{3 up}")
    Send("{w down}")
    Sleep 47
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 0
    Send("{w up}")
    Sleep 2
    Send("{y down}")
    Send("{2 down}")
    Send("{x down}")
    Sleep 386
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 358
    Send("{n up}")
    Sleep 15
    Send("{x down}")
    Sleep 51
    Send("{q down}")
    Sleep 47
    Send("{2 up}")
    Sleep 15
    Send("{q up}")
    Send("{u down}")
    Sleep 62
    Send("{u up}")
    Send("{7 down}")
    Sleep 58
    Send("{x up}")
    Sleep 5
    Send("{7 up}")
    Sleep 4
    Send("{e down}")
    Send("{y down}")
    Sleep 6
    Send("{y up}")
    Sleep 0
    Send("{x down}")
    Sleep 370
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 118
    Send("{n up}")
    Sleep 133
    Send("{n down}")
    Sleep 113
    Send("{n up}")
    Sleep 8
    Send("{n down}")
    Sleep 232
    Send("{n up}")
    Sleep 15
    Send("{e up}")
    Send("{y up}")
    Sleep 2
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 250
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Send("{x up}")
    Sleep 0
    Send("{5 down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 126
    Send("{w down}")
    Send("{5 down}")
    Sleep 105
    Send("{n up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{x down}")
    Sleep 121
    Send("{5 down}")
    Send("{y down}")
    Sleep 113
    Send("{x up}")
    Sleep 15
    Send("{x down}")
    Sleep 370
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 118
    Send("{n up}")
    Sleep 7
    Send("{5 up}")
    Send("{y up}")
    Sleep 0
    Send("{y down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 96
    Send("{x up}")
    Sleep 21
    Send("{y up}")
    Sleep 8
    Send("{u down}")
    Sleep 106
    Send("{5 up}")
    Sleep 7
    Send("{u up}")
    Sleep 8
    Send("{n down}")
    Sleep 232
    Send("{n up}")
    Sleep 17
    Send("{t down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 264
    Send("{t up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 121
    Send("{t up}")
    Send("{u up}")
    Send("{z up}")
    Sleep 0
    Send("{t down}")
    Send("{q down}")
    Send("{b down}")
    Sleep 126
    Send("{q up}")
    Sleep 7
    Send("{t up}")
    Sleep 119
    Send("{t down}")
    Send("{u down}")
    Sleep 105
    Send("{b up}")
    Sleep 15
    Send("{u up}")
    Sleep 0
    Send("{z down}")
    Sleep 7
    Send("{t up}")
    Sleep 114
    Send("{t down}")
    Send("{q down}")
    Sleep 113
    Send("{z up}")
    Sleep 15
    Send("{z down}")
    Sleep 249
    Send("{t up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 97
    Send("{t up}")
    Send("{u up}")
    Sleep 25
    Send("{z up}")
    Sleep 0
    Send("{b down}")
    Sleep 119
    Send("{b up}")
    Sleep 8
    Send("{q down}")
    Send("{e down}")
    Send("{y down}")
    Send("{z down}")
    Sleep 97
    Send("{q up}")
    Send("{e up}")
    Send("{y up}")
    Send("{z up}")
    Sleep 152
    Send("{e down}")
    Send("{t down}")
    Send("{b down}")
    Sleep 99
    Send("{e up}")
    Send("{t up}")
    Sleep 138
    Send("{b up}")
    Sleep 17
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 250
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Send("{x up}")
    Sleep 0
    Send("{5 down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 126
    Send("{w down}")
    Send("{5 down}")
    Sleep 105
    Send("{n up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{x down}")
    Sleep 121
    Send("{5 down}")
    Send("{y down}")
    Sleep 113
    Send("{x up}")
    Sleep 7
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{x down}")
    Sleep 250
    Send("{y down}")
    Send("{w down}")
    Sleep 122
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 120
    Send("{n up}")
    Sleep 8
    Send("{x down}")
    Sleep 99
    Send("{x up}")
    Sleep 139
    Send("{y up}")
    Sleep 15
    Send("{w up}")
    Sleep 1
    Send("{e down}")
    Send("{x down}")
    Sleep 101
    Send("{e up}")
    Sleep 158
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Send("{b down}")
    Sleep 13
    Send("{x up}")
    Sleep 241
    Send("{7 up}")
    Sleep 15
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{x down}")
    Sleep 119
    Send("{w up}")
    Sleep 134
    Send("{7 down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{7 up}")
    Sleep 8
    Send("{b down}")
    Sleep 121
    Send("{7 down}")
    Send("{w down}")
    Sleep 113
    Send("{b up}")
    Sleep 144
    Send("{z down}")
    Sleep 113
    Send("{z up}")
    Sleep 128
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{z down}")
    Sleep 118
    Send("{z up}")
    Sleep 133
    Send("{z down}")
    Sleep 106
    Send("{r up}")
    Sleep 7
    Send("{z up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 97
    Send("{e up}")
    Send("{t up}")
    Sleep 135
    Send("{z up}")
    Sleep 17
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 250
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Send("{x up}")
    Sleep 0
    Send("{5 down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 119
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 126
    Send("{w down}")
    Send("{5 down}")
    Sleep 105
    Send("{n up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{x down}")
    Sleep 121
    Send("{5 down}")
    Send("{y down}")
    Sleep 113
    Send("{x up}")
    Sleep 15
    Send("{x down}")
    Sleep 370
    Send("{5 up}")
    Send("{y up}")
    Send("{x up}")
    Sleep 0
    Send("{w down}")
    Send("{n down}")
    Sleep 118
    Send("{w up}")
    Send("{n up}")
    Sleep 8
    Send("{y down}")
    Send("{x down}")
    Sleep 96
    Send("{y up}")
    Send("{x up}")
    Sleep 150
    Send("{u down}")
    Send("{n down}")
    Sleep 97
    Send("{u up}")
    Sleep 135
    Send("{n up}")
    Sleep 17
    Send("{t down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 264
    Send("{t up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 114
    Send("{t up}")
    Sleep 7
    Send("{u up}")
    Send("{z up}")
    Sleep 0
    Send("{q down}")
    Send("{b down}")
    Sleep 119
    Send("{q up}")
    Sleep 134
    Send("{t down}")
    Send("{u down}")
    Sleep 105
    Send("{b up}")
    Sleep 7
    Send("{t up}")
    Sleep 7
    Send("{u up}")
    Sleep 0
    Send("{z down}")
    Sleep 121
    Send("{t down}")
    Send("{q down}")
    Sleep 113
    Send("{z up}")
    Sleep 15
    Send("{z down}")
    Sleep 234
    Send("{t up}")
    Sleep 15
    Send("{q up}")
    Sleep 0
    Send("{w down}")
    Sleep 97
    Send("{w up}")
    Sleep 25
    Send("{z up}")
    Sleep 0
    Send("{b down}")
    Sleep 126
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{b down}")
    Sleep 97
    Send("{w up}")
    Send("{r up}")
    Sleep 137
    Send("{b up}")
    Sleep 15
    Send("{q down}")
    Send("{e down}")
    Send("{z down}")
    Sleep 99
    Send("{q up}")
    Send("{e up}")
    Sleep 138
    Send("{z up}")
    Sleep 17
    Send("{u down}")
    Send("{w down}")
    Send("{b down}")
    Sleep 264
    Send("{u up}")
    Send("{w up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 98
    Send("{u up}")
    Sleep 23
    Send("{b up}")
    Sleep 0
    Send("{x down}")
    Sleep 19
    Send("{t up}")
    Sleep 234
    Send("{w down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{w up}")
    Sleep 8
    Send("{b down}")
    Sleep 121
    Send("{w down}")
    Send("{r down}")
    Sleep 113
    Send("{b up}")
    Sleep 15
    Send("{b down}")
    Sleep 121
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 113
    Send("{e up}")
    Sleep 8
    Send("{w down}")
    Sleep 121
    Send("{b up}")
    Sleep 0
    Send("{x down}")
    Sleep 125
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 231
    Send("{w up}")
    Send("{x up}")
    Sleep 15
    Send("{e down}")
    Send("{b down}")
    Sleep 97
    Send("{e up}")
    Sleep 135
    Send("{b up}")
    Sleep 17
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{j down}")
    Sleep 250
    Send("{w up}")
    Sleep 15
    Send("{r up}")
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Sleep 114
    Send("{t up}")
    Sleep 7
    Send("{j up}")
    Sleep 0
    Send("{r down}")
    Send("{v down}")
    Sleep 119
    Send("{r up}")
    Sleep 134
    Send("{t down}")
    Sleep 105
    Send("{v up}")
    Sleep 7
    Send("{t up}")
    Sleep 8
    Send("{j down}")
    Sleep 121
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 113
    Send("{j up}")
    Sleep 144
    Send("{z down}")
    Sleep 114
    Send("{z up}")
    Sleep 131
    Send("{z down}")
    Sleep 120
    Send("{z up}")
    Sleep 7
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 1
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 129
    Send("{z down}")
    Sleep 117
    Send("{z up}")
    Sleep 8
    Send("{z down}")
    Sleep 241
    Send("{z up}")
    Sleep 15
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 3
    Send("{q down}")
    Send("{e down}")
    Send("{v down}")
    Sleep 254
    Send("{q up}")
    Sleep 15
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 114
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Send("{v up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 119
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Sleep 126
    Send("{q down}")
    Send("{e down}")
    Sleep 105
    Send("{z up}")
    Sleep 7
    Send("{q up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{z down}")
    Sleep 121
    Send("{t down}")
    Send("{q down}")
    Sleep 113
    Send("{z up}")
    Sleep 15
    Send("{v down}")
    Sleep 370
    Send("{v up}")
    Sleep 0
    Send("{z down}")
    Sleep 357
    Send("{z up}")
    Sleep 15
    Send("{t up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{q down}")
    Send("{v down}")
    Sleep 97
    Send("{t up}")
    Send("{q up}")
    Sleep 135
    Send("{v up}")
    Sleep 17
    Send("{u down}")
    Send("{e down}")
    Send("{m down}")
    Sleep 264
    Send("{u up}")
    Send("{e up}")
    Sleep 0
    Send("{u down}")
    Send("{w down}")
    Sleep 121
    Send("{u up}")
    Send("{w up}")
    Send("{m up}")
    Sleep 0
    Send("{u down}")
    Send("{e down}")
    Send("{v down}")
    Sleep 126
    Send("{e up}")
    Sleep 7
    Send("{u up}")
    Sleep 119
    Send("{u down}")
    Send("{w down}")
    Sleep 105
    Send("{v up}")
    Sleep 15
    Send("{w up}")
    Sleep 0
    Send("{m down}")
    Sleep 7
    Send("{u up}")
    Sleep 114
    Send("{u down}")
    Send("{r down}")
    Sleep 113
    Send("{m up}")
    Sleep 15
    Send("{m down}")
    Sleep 99
    Send("{r up}")
    Sleep 16
    Send("{e down}")
    Sleep 62
    Send("{e up}")
    Send("{3 down}")
    Sleep 57
    Send("{u up}")
    Sleep 6
    Send("{3 up}")
    Sleep 4
    Send("{u down}")
    Send("{w down}")
    Sleep 126
    Send("{m up}")
    Sleep 0
    Send("{v down}")
    Sleep 357
    Send("{v up}")
    Sleep 15
    Send("{m down}")
    Sleep 232
    Send("{m up}")
    Sleep 15
    Send("{u up}")
    Send("{w up}")
    Sleep 2
    Send("{7 down}")
    Send("{w down}")
    Send("{j down}")
    Sleep 250
    Send("{7 up}")
    Sleep 15
    Send("{w up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Sleep 114
    Send("{q up}")
    Sleep 7
    Send("{e up}")
    Send("{j up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{v down}")
    Sleep 119
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Sleep 126
    Send("{7 down}")
    Send("{w down}")
    Sleep 105
    Send("{v up}")
    Sleep 7
    Send("{7 up}")
    Sleep 7
    Send("{w up}")
    Sleep 0
    Send("{j down}")
    Sleep 121
    Send("{w down}")
    Send("{r down}")
    Sleep 113
    Send("{j up}")
    Sleep 15
    Send("{j down}")
    Sleep 370
    Send("{w up}")
    Send("{r up}")
    Send("{j up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{v down}")
    Sleep 118
    Send("{r up}")
    Send("{v up}")
    Sleep 7
    Send("{y up}")
    Sleep 126
    Send("{e down}")
    Send("{t down}")
    Sleep 113
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{n down}")
    Sleep 232
    Send("{n up}")
    Sleep 17
    Send("{q down}")
    Send("{y down}")
    Send("{b down}")
    Sleep 264
    Send("{q up}")
    Send("{y up}")
    Sleep 0
    Send("{q down}")
    Send("{t down}")
    Sleep 121
    Send("{q up}")
    Send("{t up}")
    Send("{b up}")
    Sleep 0
    Send("{q down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 119
    Send("{q up}")
    Sleep 7
    Send("{y up}")
    Sleep 126
    Send("{w down}")
    Send("{t down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{b down}")
    Sleep 121
    Send("{q down}")
    Send("{e down}")
    Sleep 113
    Send("{b up}")
    Sleep 144
    Send("{z down}")
    Sleep 105
    Send("{q up}")
    Sleep 15
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 96
    Send("{w up}")
    Send("{r up}")
    Sleep 150
    Send("{z up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 96
    Send("{e up}")
    Send("{t up}")
    Send("{z up}")
    Sleep 150
    Send("{t down}")
    Send("{q down}")
    Send("{j down}")
    Sleep 97
    Send("{t up}")
    Send("{q up}")
    Send("{j up}")
    Sleep 152
    Send("{q down}")
    Send("{e down}")
    Send("{n down}")
    Sleep 250
    Send("{q up}")
    Sleep 15
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Sleep 114
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{c down}")
    Sleep 119
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Sleep 126
    Send("{q down}")
    Send("{e down}")
    Sleep 105
    Send("{c up}")
    Sleep 7
    Send("{q up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{n down}")
    Sleep 121
    Send("{e down}")
    Send("{t down}")
    Sleep 113
    Send("{n up}")
    Sleep 15
    Send("{n down}")
    Sleep 370
    Send("{n up}")
    Sleep 0
    Send("{c down}")
    Sleep 125
    Send("{e up}")
    Send("{t up}")
    Sleep 0
    Send("{t down}")
    Sleep 96
    Send("{t up}")
    Sleep 135
    Send("{c up}")
    Sleep 15
    Send("{y down}")
    Send("{n down}")
    Sleep 97
    Send("{y up}")
    Sleep 135
    Send("{n up}")
    Sleep 17
    Send("{r down}")
    Send("{u down}")
    Send("{h down}")
    Sleep 264
    Send("{r up}")
    Send("{u up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Sleep 121
    Send("{r up}")
    Send("{y up}")
    Send("{h up}")
    Sleep 0
    Send("{r down}")
    Send("{u down}")
    Send("{x down}")
    Sleep 119
    Send("{r up}")
    Sleep 7
    Send("{u up}")
    Sleep 126
    Send("{w down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{w up}")
    Sleep 8
    Send("{x down}")
    Sleep 121
    Send("{u down}")
    Send("{r down}")
    Sleep 113
    Send("{x up}")
    Sleep 15
    Send("{h down}")
    Sleep 121
    Send("{u up}")
    Sleep 7
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 114
    Send("{e up}")
    Sleep 130
    Send("{h up}")
    Sleep 0
    Send("{x down}")
    Sleep 128
    Send("{w down}")
    Sleep 99
    Send("{w up}")
    Sleep 139
    Send("{x up}")
    Sleep 16
    Send("{u down}")
    Send("{x down}")
    Sleep 101
    Send("{u up}")
    Sleep 140
    Send("{x up}")
    Sleep 18
    Send("{w down}")
    Send("{5 down}")
    Send("{b down}")
    Sleep 254
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{x down}")
    Sleep 119
    Send("{w up}")
    Sleep 134
    Send("{u down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{u up}")
    Sleep 8
    Send("{b down}")
    Sleep 121
    Send("{y down}")
    Send("{w down}")
    Sleep 113
    Send("{b up}")
    Sleep 15
    Send("{g down}")
    Sleep 370
    Send("{g up}")
    Sleep 0
    Send("{s down}")
    Sleep 125
    Send("{y up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Sleep 96
    Send("{y up}")
    Send("{w up}")
    Sleep 135
    Send("{s up}")
    Sleep 15
    Send("{e down}")
    Send("{g down}")
    Sleep 97
    Send("{e up}")
    Sleep 135
    Send("{g up}")
    Sleep 17
    Send("{w down}")
    Send("{r down}")
    Send("{b down}")
    Sleep 250
    Send("{w up}")
    Sleep 15
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 114
    Send("{e up}")
    Sleep 7
    Send("{b up}")
    Sleep 0
    Send("{r down}")
    Send("{x down}")
    Sleep 119
    Send("{r up}")
    Sleep 134
    Send("{w down}")
    Send("{t down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{b down}")
    Sleep 121
    Send("{y down}")
    Send("{y down}")
    Sleep 113
    Send("{b up}")
    Sleep 144
    Send("{n down}")
    Sleep 106
    Send("{y up}")
    Sleep 15
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Sleep 97
    Send("{t up}")
    Sleep 152
    Send("{n up}")
    Sleep 1
    Send("{r down}")
    Send("{n down}")
    Sleep 99
    Send("{r up}")
    Send("{n up}")
    Sleep 155
    Send("{e down}")
    Send("{n down}")
    Sleep 101
    Send("{e up}")
    Send("{n up}")
    Sleep 158
    Send("{x down}")
    Sleep 269
    Send("{y down}")
    Sleep 121
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 126
    Send("{w down}")
    Sleep 29
    Send("{y up}")
    Sleep 109
    Send("{w up}")
    Sleep 93
    Send("{n up}")
    Sleep 15
    Send("{5 down}")
    Send("{x down}")
    Sleep 99
    Send("{5 up}")
    Sleep 135
    Send("{x up}")
    Sleep 15
    Send("{2 down}")
    Send("{e down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 234
    Send("{2 up}")
    Send("{e up}")
    Sleep 15
    Send("{t up}")
    Sleep 0
    Send("{5 down}")
    Sleep 113
    Send("{5 up}")
    Sleep 7
    Send("{g up}")
    Sleep 0
    Send("{t down}")
    Send("{s down}")
    Sleep 118
    Send("{t up}")
    Sleep 133
    Send("{y down}")
    Sleep 106
    Send("{s up}")
    Sleep 7
    Send("{y up}")
    Sleep 8
    Send("{g down}")
    Sleep 121
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Sleep 111
    Send("{g up}")
    Sleep 17
    Send("{b down}")
    Sleep 386
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 119
    Send("{b up}")
    Sleep 7
    Send("{w up}")
    Send("{5 up}")
    Send("{y up}")
    Sleep 0
    Send("{w down}")
    Send("{x down}")
    Sleep 96
    Send("{w up}")
    Send("{x up}")
    Sleep 150
    Send("{e down}")
    Send("{b down}")
    Sleep 234
    Send("{e up}")
    Send("{b up}")
    Sleep 15
    Send("{u down}")
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 234
    Send("{u up}")
    Send("{w up}")
    Sleep 15
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 113
    Send("{e up}")
    Sleep 7
    Send("{n up}")
    Sleep 0
    Send("{u down}")
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 118
    Send("{u up}")
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Sleep 126
    Send("{u down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 106
    Send("{n up}")
    Sleep 7
    Send("{u up}")
    Send("{w up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{b down}")
    Sleep 121
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 111
    Send("{b up}")
    Sleep 17
    Send("{g down}")
    Sleep 512
    Send("{y up}")
    Send("{2 up}")
    Send("{e up}")
    Send("{g up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Send("{s down}")
    Sleep 96
    Send("{y up}")
    Send("{w up}")
    Sleep 135
    Send("{s up}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Send("{g down}")
    Sleep 99
    Send("{w up}")
    Send("{5 up}")
    Sleep 135
    Send("{g up}")
    Sleep 15
    Send("{q down}")
    Send("{t down}")
    Send("{m down}")
    Sleep 234
    Send("{q up}")
    Sleep 15
    Send("{t up}")
    Sleep 0
    Send("{u down}")
    Send("{5 down}")
    Sleep 114
    Send("{u up}")
    Sleep 7
    Send("{5 up}")
    Send("{m up}")
    Sleep 0
    Send("{q down}")
    Send("{t down}")
    Send("{g down}")
    Sleep 119
    Send("{q up}")
    Sleep 7
    Send("{t up}")
    Sleep 128
    Send("{w down}")
    Send("{y down}")
    Sleep 107
    Send("{g up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{m down}")
    Sleep 123
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Sleep 114
    Send("{m up}")
    Sleep 17
    Send("{c down}")
    Sleep 386
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 119
    Send("{c up}")
    Sleep 7
    Send("{w up}")
    Send("{5 up}")
    Send("{y up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Send("{g down}")
    Sleep 96
    Send("{w up}")
    Send("{w up}")
    Sleep 135
    Send("{g up}")
    Sleep 15
    Send("{e down}")
    Send("{e down}")
    Send("{b down}")
    Sleep 99
    Send("{e up}")
    Send("{e up}")
    Sleep 135
    Send("{b up}")
    Sleep 15
    Send("{r down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 235
    Send("{r up}")
    Sleep 15
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Sleep 115
    Send("{e up}")
    Sleep 7
    Send("{e up}")
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 120
    Send("{w up}")
    Sleep 7
    Send("{w up}")
    Sleep 129
    Send("{e down}")
    Send("{t down}")
    Send("{u down}")
    Send("{e down}")
    Sleep 109
    Send("{n up}")
    Sleep 16
    Send("{n down}")
    Sleep 110
    Send("{e up}")
    Send("{t up}")
    Sleep 15
    Send("{u up}")
    Send("{e up}")
    Sleep 1
    Send("{w down}")
    Send("{w down}")
    Sleep 116
    Send("{n up}")
    Sleep 18
    Send("{x down}")
    Sleep 254
    Send("{w up}")
    Sleep 15
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Sleep 98
    Send("{y up}")
    Sleep 23
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 126
    Send("{w down}")
    Sleep 96
    Send("{w up}")
    Sleep 135
    Send("{n up}")
    Sleep 15
    Send("{5 down}")
    Send("{x down}")
    Sleep 99
    Send("{5 up}")
    Sleep 135
    Send("{x up}")
    Sleep 15
    Send("{t down}")
    Send("{g down}")
    Sleep 234
    Send("{t up}")
    Sleep 15
    Send("{5 down}")
    Sleep 113
    Send("{5 up}")
    Sleep 7
    Send("{g up}")
    Sleep 0
    Send("{t down}")
    Send("{s down}")
    Sleep 118
    Send("{t up}")
    Sleep 133
    Send("{5 down}")
    Send("{y down}")
    Sleep 106
    Send("{s up}")
    Sleep 7
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{g down}")
    Sleep 121
    Send("{5 down}")
    Send("{y down}")
    Sleep 111
    Send("{g up}")
    Sleep 17
    Send("{b down}")
    Sleep 250
    Send("{5 up}")
    Sleep 15
    Send("{y up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Sleep 121
    Send("{b up}")
    Sleep 0
    Send("{x down}")
    Sleep 111
    Send("{y up}")
    Sleep 15
    Send("{w up}")
    Sleep 126
    Send("{y down}")
    Send("{w down}")
    Sleep 105
    Send("{x up}")
    Sleep 7
    Send("{y up}")
    Sleep 7
    Send("{w up}")
    Sleep 0
    Send("{b down}")
    Sleep 121
    Send("{w down}")
    Sleep 113
    Send("{b up}")
    Sleep 7
    Send("{w up}")
    Sleep 8
    Send("{r down}")
    Send("{n down}")
    Sleep 234
    Send("{r up}")
    Sleep 15
    Send("{e down}")
    Sleep 113
    Send("{e up}")
    Sleep 7
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Send("{n down}")
    Sleep 118
    Send("{w up}")
    Send("{n up}")
    Sleep 8
    Send("{n down}")
    Sleep 125
    Send("{u down}")
    Send("{e down}")
    Sleep 106
    Send("{n up}")
    Sleep 7
    Send("{u up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{b down}")
    Sleep 121
    Send("{y down}")
    Send("{w down}")
    Sleep 111
    Send("{b up}")
    Sleep 17
    Send("{g down}")
    Sleep 250
    Send("{y up}")
    Sleep 15
    Send("{w up}")
    Sleep 122
    Send("{g up}")
    Sleep 0
    Send("{y down}")
    Send("{g down}")
    Sleep 119
    Send("{y up}")
    Send("{g up}")
    Sleep 8
    Send("{w down}")
    Send("{x down}")
    Sleep 96
    Send("{w up}")
    Send("{x up}")
    Sleep 150
    Send("{5 down}")
    Send("{g down}")
    Sleep 99
    Send("{5 up}")
    Send("{g up}")
    Sleep 150
    Send("{w down}")
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Sleep 234
    Send("{w up}")
    Sleep 15
    Send("{5 up}")
    Send("{u up}")
    Sleep 0
    Send("{5 down}")
    Sleep 114
    Send("{5 up}")
    Sleep 7
    Send("{m up}")
    Sleep 0
    Send("{t down}")
    Send("{g down}")
    Sleep 119
    Send("{t up}")
    Sleep 135
    Send("{y down}")
    Sleep 107
    Send("{g up}")
    Sleep 7
    Send("{y up}")
    Sleep 8
    Send("{m down}")
    Sleep 123
    Send("{y down}")
    Send("{5 down}")
    Sleep 114
    Send("{m up}")
    Sleep 17
    Send("{c down}")
    Sleep 264
    Send("{5 up}")
    Sleep 0
    Send("{w down}")
    Sleep 121
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 111
    Send("{y up}")
    Sleep 7
    Send("{c up}")
    Sleep 7
    Send("{w up}")
    Sleep 0
    Send("{g down}")
    Sleep 231
    Send("{g up}")
    Sleep 15
    Send("{w down}")
    Send("{b down}")
    Sleep 99
    Send("{w up}")
    Sleep 135
    Send("{b up}")
    Sleep 15
    Send("{w down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 234
    Send("{w up}")
    Sleep 15
    Send("{y up}")
    Send("{n up}")
    Sleep 0
    Send("{u down}")
    Send("{t down}")
    Send("{n down}")
    Sleep 114
    Send("{u up}")
    Send("{n up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{y down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 119
    Send("{y up}")
    Sleep 7
    Send("{5 up}")
    Sleep 120
    Send("{n up}")
    Sleep 8
    Send("{e down}")
    Send("{t down}")
    Send("{n down}")
    Sleep 115
    Send("{e up}")
    Send("{n up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{n down}")
    Sleep 123
    Send("{w down}")
    Send("{5 down}")
    Sleep 114
    Send("{n up}")
    Sleep 17
    Send("{x down}")
    Sleep 386
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 79
    Send("{w up}")
    Send("{5 up}")
    Sleep 47
    Send("{w down}")
    Send("{5 down}")
    Sleep 96
    Send("{w up}")
    Send("{5 up}")
    Sleep 135
    Send("{n up}")
    Sleep 15
    Send("{2 down}")
    Send("{e down}")
    Send("{x down}")
    Sleep 113
    Send("{2 up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 113
    Send("{x up}")
    Sleep 7
    Send("{t up}")
    Sleep 7
    Send("{u up}")
    Sleep 0
    Send("{x down}")
    Sleep 129
    Send("{t down}")
    Send("{u down}")
    Sleep 121
    Send("{u up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Sleep 14
    Send("{t up}")
    Sleep 83
    Send("{5 up}")
    Sleep 25
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 18
    Send("{w up}")
    Sleep 109
    Send("{n up}")
    Sleep 1
    Send("{t down}")
    Send("{u down}")
    Send("{n down}")
    Sleep 99
    Send("{t up}")
    Send("{u up}")
    Sleep 139
    Send("{n up}")
    Sleep 16
    Send("{w down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 85
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 140
    Send("{n up}")
    Sleep 18
    Send("{y down}")
    Send("{2 down}")
    Send("{x down}")
    Sleep 119
    Send("{y up}")
    Send("{2 up}")
    Sleep 151
    Send("{w down}")
    Send("{5 down}")
    Sleep 98
    Send("{w up}")
    Send("{5 up}")
    Sleep 23
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 126
    Send("{y down}")
    Send("{2 down}")
    Sleep 96
    Send("{y up}")
    Send("{2 up}")
    Sleep 135
    Send("{n up}")
    Sleep 15
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 113
    Send("{w up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Sleep 113
    Send("{x up}")
    Sleep 7
    Send("{t up}")
    Sleep 7
    Send("{u up}")
    Sleep 0
    Send("{x down}")
    Sleep 128
    Send("{t down}")
    Send("{u down}")
    Sleep 120
    Send("{u up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 14
    Send("{t up}")
    Sleep 82
    Send("{5 up}")
    Sleep 24
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 18
    Send("{w up}")
    Sleep 100
    Send("{n up}")
    Sleep 8
    Send("{w down}")
    Send("{t down}")
    Send("{u down}")
    Sleep 29
    Send("{y up}")
    Sleep 67
    Send("{t up}")
    Send("{u up}")
    Sleep 29
    Send("{n down}")
    Sleep 113
    Send("{n up}")
    Sleep 8
    Send("{u down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 29
    Send("{w up}")
    Sleep 53
    Send("{5 up}")
    Sleep 15
    Send("{w up}")
    Sleep 16
    Send("{n up}")
    Sleep 8
    Send("{n down}")
    Sleep 89
    Send("{u up}")
    Sleep 29
    Send("{n up}")
    Sleep 10
    Send("{e down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 386
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 358
    Send("{n up}")
    Sleep 4
    Send("{6 down}")
    Sleep 11
    Send("{x down}")
    Sleep 51
    Send("{6 up}")
    Send("{t down}")
    Sleep 47
    Send("{y up}")
    Sleep 15
    Send("{t up}")
    Send("{5 down}")
    Sleep 62
    Send("{5 up}")
    Send("{r down}")
    Sleep 58
    Send("{x up}")
    Sleep 5
    Send("{r up}")
    Sleep 4
    Send("{2 down}")
    Send("{e down}")
    Sleep 6
    Send("{e up}")
    Sleep 0
    Send("{x down}")
    Sleep 370
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 118
    Send("{n up}")
    Sleep 254
    Send("{n down}")
    Sleep 97
    Send("{e up}")
    Sleep 25
    Send("{3 down}")
    Sleep 62
    Send("{3 up}")
    Send("{w down}")
    Sleep 47
    Send("{n up}")
    Sleep 15
    Send("{2 up}")
    Sleep 0
    Send("{w up}")
    Sleep 2
    Send("{y down}")
    Send("{2 down}")
    Send("{x down}")
    Sleep 386
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 358
    Send("{n up}")
    Sleep 15
    Send("{x down}")
    Sleep 51
    Send("{q down}")
    Sleep 47
    Send("{2 up}")
    Sleep 15
    Send("{q up}")
    Send("{u down}")
    Sleep 62
    Send("{u up}")
    Send("{7 down}")
    Sleep 58
    Send("{x up}")
    Sleep 5
    Send("{7 up}")
    Sleep 4
    Send("{e down}")
    Send("{y down}")
    Sleep 6
    Send("{y up}")
    Sleep 0
    Send("{x down}")
    Sleep 370
    Send("{x up}")
    Sleep 0
    Send("{n down}")
    Sleep 118
    Send("{n up}")
    Sleep 133
    Send("{n down}")
    Sleep 113
    Send("{n up}")
    Sleep 8
    Send("{n down}")
    Sleep 232
    Send("{n up}")
    Sleep 15
    Send("{e up}")
    Send("{y up}")
}
