#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()

Hotkey "Esc", (*) => ExitApp()

PlaySong() {
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 72
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 250
    Send("{w up}")
    Sleep 50
    Send("{w down}")
    Sleep 47
    Send("{w up}")
    Sleep 3
    Send("{w down}")
    Sleep 147
    Send("{w up}")
    Sleep 3
    Send("{n down}")
    Sleep 147
    Send("{n up}")
    Sleep 3
    Send("{q down}")
    Sleep 47
    Send("{q up}")
    Sleep 3
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Send("{x up}")
    Sleep 50
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 50
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Send("{x up}")
    Sleep 47
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 3
    Send("{n down}")
    Send("{q down}")
    Send("{e down}")
    Send("{z down}")
    Sleep 147
    Send("{n up}")
    Send("{q up}")
    Send("{e up}")
    Send("{z up}")
    Sleep 3
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 100
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 47
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 3
    Send("{w down}")
    Send("{t down}")
    Sleep 147
    Send("{w up}")
    Send("{t up}")
    Sleep 3
    Send("{n down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 250
    Send("{n up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{n down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 100
    Send("{n up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{n down}")
    Send("{w down}")
    Sleep 47
    Send("{n up}")
    Send("{w up}")
    Sleep 3
    Send("{b down}")
    Send("{q down}")
    Sleep 147
    Send("{b up}")
    Send("{q up}")
    Sleep 3
    Send("{n down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 147
    Send("{n up}")
    Send("{q up}")
    Sleep 3
    Send("{n down}")
    Send("{w down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{n up}")
    Send("{w up}")
    Send("{x up}")
    Send("{x down}")
    Sleep 150
    Send("{n down}")
    Send("{x up}")
    Sleep 47
    Send("{n up}")
    Sleep 3
    Send("{q down}")
    Send("{x down}")
    Sleep 147
    Send("{q up}")
    Send("{x up}")
    Sleep 3
    Send("{v down}")
    Send("{j down}")
    Send("{w down}")
    Sleep 250
    Send("{v up}")
    Send("{j up}")
    Send("{w up}")
    Sleep 50
    Send("{v down}")
    Send("{j down}")
    Send("{w down}")
    Sleep 100
    Send("{v up}")
    Send("{j up}")
    Send("{w up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Sleep 47
    Send("{j up}")
    Send("{w up}")
    Sleep 3
    Send("{j down}")
    Send("{e down}")
    Sleep 147
    Send("{j up}")
    Send("{e up}")
    Sleep 3
    Send("{n down}")
    Send("{q down}")
    Send("{r down}")
    Sleep 250
    Send("{n up}")
    Send("{q up}")
    Send("{r up}")
    Sleep 50
    Send("{n down}")
    Send("{q down}")
    Send("{r down}")
    Sleep 100
    Send("{n up}")
    Send("{q up}")
    Send("{r up}")
    Sleep 50
    Send("{q down}")
    Send("{r down}")
    Sleep 47
    Send("{q up}")
    Send("{r up}")
    Sleep 3
    Send("{q down}")
    Send("{t down}")
    Sleep 147
    Send("{q up}")
    Send("{t up}")
    Sleep 3
    Send("{q down}")
    Send("{e down}")
    Send("{z down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Send("{z up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Send("{z down}")
    Send("{z up}")
    Sleep 100
    Send("{q up}")
    Send("{e up}")
    Sleep 50
    Send("{n down}")
    Send("{w down}")
    Sleep 47
    Send("{n up}")
    Send("{w up}")
    Sleep 3
    Send("{q down}")
    Sleep 147
    Send("{q up}")
    Sleep 3
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 150
    Send("{n down}")
    Send("{x up}")
    Sleep 47
    Send("{n up}")
    Sleep 3
    Send("{q down}")
    Send("{x down}")
    Sleep 147
    Send("{q up}")
    Send("{x up}")
    Sleep 3
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Send("{x up}")
    Sleep 50
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Sleep 50
    Send("{n down}")
    Send("{w down}")
    Send("{x up}")
    Sleep 47
    Send("{n up}")
    Send("{w up}")
    Sleep 3
    Send("{n down}")
    Send("{r down}")
    Send("{x down}")
    Sleep 147
    Send("{n up}")
    Send("{r up}")
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 250
    Send("{j up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 100
    Send("{j up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 50
    Send("{w down}")
    Send("{t down}")
    Sleep 47
    Send("{w up}")
    Send("{t up}")
    Sleep 3
    Send("{w down}")
    Send("{y down}")
    Sleep 147
    Send("{w up}")
    Send("{y up}")
    Sleep 3
    Send("{w down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 250
    Send("{w up}")
    Send("{t up}")
    Send("{7 up}")
    Sleep 50
    Send("{w down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 100
    Send("{w up}")
    Send("{t up}")
    Send("{7 up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Sleep 47
    Send("{r up}")
    Send("{y up}")
    Sleep 3
    Send("{e down}")
    Send("{t down}")
    Sleep 147
    Send("{e up}")
    Send("{t up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 147
    Send("{r up}")
    Send("{y up}")
    Sleep 3
    Send("{w down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{w up}")
    Send("{x up}")
    Send("{x down}")
    Sleep 150
    Send("{w down}")
    Send("{x up}")
    Sleep 47
    Send("{w up}")
    Sleep 3
    Send("{e down}")
    Send("{x down}")
    Sleep 147
    Send("{e up}")
    Send("{x up}")
    Sleep 3
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 250
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 100
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 50
    Send("{j down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 100
    Send("{j up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 147
    Send("{r up}")
    Send("{y up}")
    Sleep 3
    Send("{w down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{w up}")
    Send("{x up}")
    Send("{x down}")
    Sleep 150
    Send("{w down}")
    Send("{x up}")
    Sleep 47
    Send("{w up}")
    Sleep 3
    Send("{r down}")
    Send("{x down}")
    Sleep 147
    Send("{r up}")
    Send("{x up}")
    Sleep 3
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 250
    Send("{n up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 50
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 100
    Send("{n up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Sleep 47
    Send("{w up}")
    Send("{r up}")
    Sleep 3
    Send("{m down}")
    Send("{w down}")
    Sleep 147
    Send("{m up}")
    Send("{w up}")
    Sleep 3
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 147
    Send("{n up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 150
    Send("{y down}")
    Sleep 47
    Send("{y up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{r up}")
    Send("{y up}")
    Send("{x up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Send("{x up}")
    Sleep 47
    Send("{r up}")
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Send("{z down}")
    Sleep 147
    Send("{y up}")
    Send("{z up}")
    Sleep 3
    Send("{7 down}")
    Sleep 250
    Send("{7 up}")
    Sleep 50
    Send("{7 down}")
    Sleep 100
    Send("{7 up}")
    Sleep 50
    Send("{7 down}")
    Sleep 47
    Send("{7 up}")
    Sleep 3
    Send("{y down}")
    Sleep 250
    Send("{y up}")
    Sleep 50
    Send("{y down}")
    Sleep 100
    Send("{y up}")
    Sleep 50
    Send("{y down}")
    Sleep 47
    Send("{y up}")
    Sleep 3
    Send("{t down}")
    Sleep 147
    Send("{t up}")
    Sleep 3
    Send("{y down}")
    Send("{x down}")
    Sleep 147
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{y up}")
    Send("{x up}")
    Send("{x down}")
    Sleep 150
    Send("{y down}")
    Send("{x up}")
    Sleep 47
    Send("{y up}")
    Send("{x down}")
    Send("{x up}")
    Sleep 3
    Send("{r down}")
    Send("{7 down}")
    Sleep 250
    Send("{r up}")
    Send("{7 up}")
    Sleep 50
    Send("{r down}")
    Send("{7 down}")
    Sleep 100
    Send("{r up}")
    Send("{7 up}")
    Sleep 50
    Send("{7 down}")
    Sleep 47
    Send("{7 up}")
    Sleep 3
    Send("{7 down}")
    Sleep 147
    Send("{7 up}")
    Sleep 3
    Send("{y down}")
    Sleep 250
    Send("{y up}")
    Sleep 50
    Send("{y down}")
    Sleep 100
    Send("{y up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Sleep 50
    Send("{y down}")
    Sleep 47
    Send("{y up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{r up}")
    Send("{y up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 150
    Send("{y down}")
    Send("{x up}")
    Sleep 47
    Send("{y up}")
    Send("{x down}")
    Send("{x up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{r up}")
    Send("{y up}")
    Send("{x up}")
    Sleep 50
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{y down}")
    Send("{x up}")
    Sleep 47
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Send("{x down}")
    Sleep 147
    Send("{y up}")
    Send("{x up}")
    Sleep 3
    Send("{7 down}")
    Sleep 250
    Send("{7 up}")
    Sleep 50
    Send("{7 down}")
    Sleep 100
    Send("{7 up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Sleep 3
    Send("{7 down}")
    Sleep 250
    Send("{7 up}")
    Sleep 50
    Send("{7 down}")
    Sleep 100
    Send("{7 up}")
    Sleep 50
    Send("{7 down}")
    Sleep 100
    Send("{7 up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Sleep 3
    Send("{y down}")
    Sleep 250
    Send("{y up}")
    Sleep 50
    Send("{y down}")
    Sleep 100
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{y up}")
    Send("{x up}")
    Sleep 50
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{y up}")
    Send("{x up}")
    Sleep 50
    Send("{y down}")
    Send("{z down}")
    Sleep 250
    Send("{y up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Sleep 3
    Send("{7 down}")
    Sleep 250
    Send("{7 up}")
    Sleep 150
    Send("{y down}")
    Sleep 47
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Sleep 147
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Sleep 147
    Send("{y up}")
    Sleep 150
    Send("{7 down}")
    Sleep 47
    Send("{7 up}")
    Sleep 3
    Send("{7 down}")
    Sleep 147
    Send("{7 up}")
    Sleep 3
    Send("{7 down}")
    Sleep 147
    Send("{7 up}")
    Sleep 3
    Send("{2 down}")
    Send("{e down}")
    Sleep 147
    Send("{2 up}")
    Send("{e up}")
    Sleep 3
    Send("{2 down}")
    Send("{e down}")
    Sleep 100
    Send("{2 up}")
    Send("{e up}")
    Sleep 3
    Send("{b down}")
    Send("{w down}")
    Sleep 100
    Send("{b up}")
    Send("{w up}")
    Sleep 3
    Send("{n down}")
    Send("{2 down}")
    Send("{r down}")
    Sleep 100
    Send("{n up}")
    Send("{2 up}")
    Send("{r up}")
    Sleep 150
    Send("{r down}")
    Sleep 47
    Send("{r up}")
    Sleep 3
    Send("{t down}")
    Sleep 147
    Send("{t up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Send("{x up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Send("{x up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{7 down}")
    Send("{x down}")
    Sleep 147
    Send("{w up}")
    Send("{r up}")
    Send("{7 up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{x up}")
    Sleep 47
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Sleep 3
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Send("{z up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Sleep 100
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 50
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Send("{z up}")
    Send("{z down}")
    Sleep 100
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Send("{z up}")
    Sleep 3
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Send("{v down}")
    Sleep 147
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 3
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Send("{v up}")
    Sleep 47
    Send("{q up}")
    Send("{r up}")
    Send("{y up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Send("{x up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 50
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Send("{x up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{7 down}")
    Send("{x down}")
    Sleep 147
    Send("{w up}")
    Send("{r up}")
    Send("{7 up}")
    Sleep 3
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{x up}")
    Sleep 47
    Send("{w up}")
    Send("{r up}")
    Send("{y up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Sleep 3
    Send("{2 down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 250
    Send("{2 up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 50
    Send("{2 down}")
    Send("{r down}")
    Sleep 100
    Send("{2 up}")
    Send("{r up}")
    Sleep 50
    Send("{n down}")
    Send("{e down}")
    Sleep 100
    Send("{n up}")
    Send("{e up}")
    Sleep 3
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 150
    Send("{w down}")
    Send("{x up}")
    Sleep 47
    Send("{w up}")
    Sleep 3
    Send("{e down}")
    Send("{x down}")
    Sleep 147
    Send("{e up}")
    Send("{x up}")
    Sleep 3
    Send("{n down}")
    Send("{w down}")
    Send("{r down}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 75
    Send("{n up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 75
    Send("{t down}")
    Send("{x up}")
    Sleep 47
    Send("{t up}")
    Sleep 3
    Send("{y down}")
    Send("{x down}")
    Sleep 147
    Send("{y up}")
    Send("{x up}")
    Sleep 3
    Send("{q down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 250
    Send("{q up}")
    Send("{t up}")
    Send("{z up}")
    Sleep 50
    Send("{q down}")
    Send("{r down}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Sleep 100
    Send("{q up}")
    Send("{r up}")
    Send("{z up}")
    Sleep 3
    Send("{q down}")
    Send("{e down}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Sleep 100
    Send("{q up}")
    Send("{e up}")
    Send("{z up}")
    Sleep 3
    Send("{n down}")
    Send("{q down}")
    Send("{r down}")
    Send("{v down}")
    Sleep 250
    Send("{n up}")
    Send("{q up}")
    Send("{r up}")
    Send("{v up}")
    Sleep 50
    Send("{n down}")
    Send("{q down}")
    Send("{t down}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Sleep 100
    Send("{n up}")
    Send("{q up}")
    Send("{t up}")
    Send("{v up}")
    Sleep 3
    Send("{n down}")
    Send("{q down}")
    Send("{y down}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Sleep 100
    Send("{n up}")
    Send("{q up}")
    Send("{y up}")
    Send("{v up}")
    Sleep 3
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 250
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Sleep 3
    Send("{r down}")
    Send("{z down}")
    Sleep 147
    Send("{r up}")
    Send("{z up}")
    Sleep 3
    Send("{t down}")
    Send("{z down}")
    Sleep 147
    Send("{t up}")
    Send("{z up}")
    Sleep 3
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Send("{v down}")
    Sleep 250
    Send("{q up}")
    Send("{r up}")
    Send("{y up}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Sleep 3
    Send("{t down}")
    Send("{v down}")
    Sleep 147
    Send("{t up}")
    Send("{v up}")
    Sleep 3
    Send("{r down}")
    Send("{v down}")
    Sleep 147
    Send("{r up}")
    Send("{v up}")
    Sleep 3
    Send("{2 down}")
    Send("{e down}")
    Sleep 250
    Send("{2 up}")
    Send("{e up}")
    Sleep 50
    Send("{2 down}")
    Send("{r down}")
    Sleep 100
    Send("{2 up}")
    Send("{r up}")
    Sleep 3
    Send("{2 down}")
    Send("{e down}")
    Sleep 100
    Send("{2 up}")
    Send("{e up}")
    Sleep 3
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 250
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 150
    Send("{e down}")
    Send("{x up}")
    Sleep 47
    Send("{e up}")
    Sleep 3
    Send("{q down}")
    Send("{x down}")
    Sleep 147
    Send("{q up}")
    Send("{x up}")
    Sleep 3
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 147
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Sleep 3
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{y up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Sleep 3
    Send("{r down}")
    Send("{7 down}")
    Sleep 250
    Send("{r up}")
    Send("{7 up}")
    Sleep 3
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{y up}")
    Send("{x up}")
    Sleep 50
    Send("{y down}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{y up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Sleep 3
    Send("{7 down}")
    Sleep 250
    Send("{7 up}")
    Sleep 50
    Send("{7 down}")
    Sleep 100
    Send("{7 up}")
    Sleep 3
    Send("{7 down}")
    Sleep 100
    Send("{7 up}")
    Sleep 3
    Send("{y down}")
    Sleep 250
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Sleep 250
    Send("{y up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Sleep 3
    Send("{7 down}")
    Sleep 250
    Send("{7 up}")
    Sleep 3
    Send("{y down}")
    Sleep 250
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Sleep 250
    Send("{y up}")
    Sleep 50
    Send("{y down}")
    Sleep 100
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Sleep 100
    Send("{y up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Sleep 100
    Send("{r up}")
    Send("{y up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{v down}")
    Send("{v up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Send("{z down}")
    Send("{z up}")
    Sleep 3
    Send("{7 down}")
    Sleep 250
    Send("{7 up}")
    Sleep 3
    Send("{y down}")
    Sleep 250
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Sleep 250
    Send("{y up}")
    Sleep 50
    Send("{y down}")
    Sleep 100
    Send("{y up}")
    Sleep 3
    Send("{y down}")
    Sleep 100
    Send("{y up}")
    Sleep 3
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 400
    Send("{r up}")
    Send("{y up}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Send("{x down}")
    Send("{x up}")
    Sleep 3
    Send("{w down}")
    Sleep 1125
    Send("{w up}")
}
