#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{n down}")
    Sleep 750
    Send("{n up}")
    Send("{c down}")
    Send("{z down}")
    Sleep 94
    Send("{z up}")
    Send("{c up}")
    Sleep 656
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 656
    Send("{c down}")
    Send("{z down}")
    Sleep 94
    Send("{z up}")
    Send("{c up}")
    Sleep 516
    Send("{c down}")
    Sleep 47
    Send("{c up}")
    Send("{g down}")
    Sleep 47
    Send("{g up}")
    Send("{h down}")
    Sleep 47
    Send("{h up}")
    Send("{n down}")
    Sleep 750
    Send("{n up}")
    Send("{c down}")
    Send("{z down}")
    Sleep 94
    Send("{z up}")
    Send("{c up}")
    Sleep 656
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 656
    Send("{c down}")
    Send("{z down}")
    Sleep 94
    Send("{z up}")
    Send("{c up}")
    Sleep 656
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 234
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 234
    Send("{n up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 234
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 234
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 234
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 234
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 234
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 234
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 234
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 234
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 234
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 234
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 234
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 234
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 234
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 234
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 188
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 188
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 188
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 188
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{c up}")
    Sleep 188
    Send("{e up}")
    Send("{r down}")
    Sleep 281
    Send("{r up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{c up}")
    Send("{z up}")
    Sleep 188
    Send("{e up}")
    Send("{3 down}")
    Sleep 281
    Send("{3 up}")
    Send("{e down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{e up}")
    Sleep 469
    Send("{c down}")
    Send("{z down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 469
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{c up}")
    Sleep 469
    Send("{c down}")
    Send("{z down}")
    Sleep 94
    Send("{z up}")
    Send("{c up}")
    Sleep 94
    Send("{q up}")
    Sleep 375
    Send("{h down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{h up}")
    Sleep 141
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Sleep 141
    Send("{c down}")
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{x up}")
    Send("{c up}")
    Sleep 141
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Sleep 141
    Send("{c down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c up}")
    Sleep 141
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Sleep 141
    Send("{c down}")
    Send("{x down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{x up}")
    Send("{c up}")
    Sleep 141
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Sleep 141
    Send("{q down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{q up}")
    Sleep 141
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Sleep 141
    Send("{q down}")
    Send("{c down}")
    Send("{z down}")
    Sleep 94
    Send("{z up}")
    Send("{c up}")
    Send("{q up}")
    Sleep 141
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Sleep 141
    Send("{q down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{q up}")
    Sleep 141
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Sleep 141
    Send("{y down}")
    Send("{c down}")
    Send("{z down}")
    Sleep 94
    Send("{z up}")
    Send("{c up}")
    Send("{y up}")
    Sleep 141
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Sleep 141
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Sleep 141
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Sleep 141
    Send("{d down}")
    Send("{n down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n up}")
    Send("{d up}")
    Sleep 141
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Sleep 141
    Send("{g down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{g up}")
    Sleep 375
    Send("{d down}")
    Send("{n down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n up}")
    Send("{d up}")
    Sleep 375
    Send("{6 down}")
    Send("{h down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{h up}")
    Send("{6 up}")
    Sleep 844
    Send("{c down}")
    Sleep 750
    Send("{c up}")
    Send("{g down}")
    Sleep 47
    Send("{g up}")
    Send("{h down}")
    Sleep 47
    Send("{h up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{n up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 94
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 94
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 94
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 94
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 94
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 94
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 94
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 94
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 94
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Sleep 94
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 281
    Send("{z down}")
    Send("{c down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 94
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Sleep 94
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{c up}")
    Send("{z up}")
    Sleep 281
    Send("{q up}")
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{x up}")
    Sleep 47
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Sleep 47
    Send("{v down}")
    Send("{n down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n up}")
    Send("{v up}")
    Sleep 47
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Sleep 47
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Sleep 47
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Sleep 47
    Send("{c down}")
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Send("{c up}")
    Sleep 47
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Sleep 47
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Sleep 47
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Sleep 47
    Send("{x down}")
    Send("{v down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{v up}")
    Send("{x up}")
    Sleep 47
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Sleep 47
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Sleep 47
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{q down}")
    Sleep 47
    Send("{z down}")
    Send("{c down}")
    Sleep 47
    Send("{q up}")
    Send("{y down}")
    Sleep 47
    Send("{c up}")
    Send("{z up}")
    Sleep 47
    Send("{y up}")
    Sleep 141
    Send("{r down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{r up}")
    Sleep 47
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Sleep 47
    Send("{g down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{g up}")
    Sleep 47
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Sleep 47
    Send("{h down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{h up}")
    Sleep 47
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Sleep 47
    Send("{c down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{c up}")
    Sleep 47
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Sleep 47
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Sleep 469
    Send("{c down}")
    Sleep 469
    Send("{c up}")
    Send("{g down}")
    Sleep 47
    Send("{g up}")
    Send("{h down}")
    Sleep 47
    Send("{h up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 94
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{c up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{z up}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{m up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c down}")
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{x up}")
    Send("{c up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{x down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{x up}")
    Send("{c up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{c down}")
    Send("{z down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{z up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{u down}")
    Send("{d down}")
    Send("{g down}")
    Sleep 94
    Send("{g up}")
    Send("{d up}")
    Send("{u up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{g down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{g up}")
    Sleep 94
    Send("{d down}")
    Send("{g down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{g up}")
    Send("{d up}")
    Sleep 94
    Send("{c down}")
    Send("{h down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{h up}")
    Send("{c up}")
    Sleep 281
    Send("{c down}")
    Sleep 281
    Send("{c up}")
    Sleep 94
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 94
    Send("{c down}")
    Send("{z down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{z up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{c down}")
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 94
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{x up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n down}")
    Send("{v down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{v up}")
    Send("{n up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n down}")
    Send("{c down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{c up}")
    Send("{n up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{h down}")
    Send("{x down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{x up}")
    Send("{h up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n down}")
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Send("{n up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{m down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{m up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{u down}")
    Send("{c down}")
    Sleep 94
    Send("{u up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{c up}")
    Send("{y down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{y up}")
    Sleep 281
    Send("{n down}")
    Sleep 281
    Send("{n up}")
    Send("{m down}")
    Sleep 47
    Send("{m up}")
    Send("{s down}")
    Sleep 47
    Send("{s up}")
    Send("{x down}")
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{x up}")
    Send("{x up}")
    Sleep 94
    Send("{n down}")
    Send("{v down}")
    Sleep 94
    Send("{v up}")
    Send("{n up}")
    Send("{w up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{n down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n up}")
    Sleep 94
    Send("{v down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{v up}")
    Sleep 94
    Send("{x down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{x up}")
    Sleep 94
    Send("{v down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{v up}")
    Sleep 94
    Send("{n down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n up}")
    Sleep 94
    Send("{v down}")
    Send("{n down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{n up}")
    Send("{v up}")
    Sleep 94
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{z up}")
    Sleep 94
    Send("{n down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{n up}")
    Send("{e up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Sleep 94
    Send("{n down}")
    Send("{c down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c up}")
    Send("{n up}")
    Sleep 94
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{z up}")
    Sleep 94
    Send("{n down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{n up}")
    Sleep 94
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{e up}")
    Sleep 94
    Send("{n down}")
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c up}")
    Send("{n up}")
    Sleep 94
    Send("{c down}")
    Send("{u down}")
    Sleep 94
    Send("{c up}")
    Sleep 94
    Send("{m down}")
    Send("{h down}")
    Sleep 94
    Send("{h up}")
    Send("{m up}")
    Send("{u up}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Sleep 94
    Send("{m down}")
    Send("{h down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 94
    Send("{c down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c up}")
    Sleep 94
    Send("{m down}")
    Send("{h down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 94
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Sleep 94
    Send("{m down}")
    Send("{h down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{h up}")
    Send("{m up}")
    Sleep 94
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Sleep 94
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Sleep 94
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Sleep 94
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Sleep 94
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Sleep 94
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Sleep 94
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{x up}")
    Sleep 94
    Send("{n down}")
    Send("{v down}")
    Sleep 94
    Send("{v up}")
    Send("{n up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{n down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n up}")
    Sleep 94
    Send("{n down}")
    Send("{v down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{v up}")
    Send("{n up}")
    Sleep 94
    Send("{x down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{x up}")
    Sleep 94
    Send("{n down}")
    Send("{v down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{v up}")
    Send("{n up}")
    Sleep 94
    Send("{n down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n up}")
    Sleep 94
    Send("{n down}")
    Send("{v down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{v up}")
    Send("{n up}")
    Sleep 94
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{z up}")
    Sleep 94
    Send("{n down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{n up}")
    Send("{e up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Sleep 94
    Send("{n down}")
    Send("{c down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c up}")
    Send("{n up}")
    Sleep 94
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Sleep 94
    Send("{n down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{n up}")
    Sleep 94
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{n up}")
    Sleep 94
    Send("{n down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{n up}")
    Sleep 94
    Send("{y up}")
    Send("{x down}")
    Sleep 94
    Send("{x up}")
    Sleep 94
    Send("{n down}")
    Send("{v down}")
    Send("{w down}")
    Sleep 94
    Send("{v up}")
    Send("{n up}")
    Sleep 94
    Send("{m down}")
    Sleep 94
    Send("{m up}")
    Sleep 94
    Send("{w up}")
    Send("{n down}")
    Send("{v down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{v up}")
    Send("{n up}")
    Sleep 94
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Sleep 94
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{x up}")
    Sleep 94
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Sleep 94
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Sleep 469
    Send("{c down}")
    Send("{e down}")
    Send("{6 down}")
    Send("{e down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{e up}")
    Send("{6 up}")
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{n down}")
    Send("{y down}")
    Send("{q down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{y up}")
    Send("{q up}")
    Send("{y up}")
    Send("{n up}")
    Sleep 281
    Send("{c down}")
    Sleep 281
    Send("{c up}")
    Send("{g down}")
    Sleep 47
    Send("{g up}")
    Send("{h down}")
    Sleep 47
    Send("{h up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 94
    Send("{c down}")
    Send("{z down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{z up}")
    Send("{c up}")
    Sleep 94
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{c up}")
    Sleep 94
    Send("{c down}")
    Send("{z down}")
    Sleep 94
    Send("{z up}")
    Send("{c up}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{m up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c down}")
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{x up}")
    Send("{c up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{x down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{x up}")
    Send("{c up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{c down}")
    Send("{z down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{z up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{d down}")
    Send("{g down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{g up}")
    Send("{d up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{g down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{g up}")
    Sleep 94
    Send("{d down}")
    Send("{g down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{g up}")
    Send("{d up}")
    Sleep 94
    Send("{c down}")
    Send("{h down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{h up}")
    Send("{c up}")
    Sleep 281
    Send("{c down}")
    Sleep 375
    Send("{c up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{c up}")
    Send("{z up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 94
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{z up}")
    Sleep 94
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{x up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{v down}")
    Send("{n down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n up}")
    Send("{v up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{c down}")
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{x down}")
    Send("{h down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{h up}")
    Send("{x up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z down}")
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Send("{z up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{m down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{m up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{u down}")
    Send("{c down}")
    Sleep 94
    Send("{u up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{c up}")
    Send("{y down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{y up}")
    Sleep 750
    Send("{n down}")
    Sleep 750
    Send("{n up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{z up}")
    Sleep 656
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 656
    Send("{z down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{z up}")
    Sleep 516
    Send("{c down}")
    Sleep 47
    Send("{c up}")
    Send("{g down}")
    Sleep 47
    Send("{g up}")
    Send("{h down}")
    Sleep 47
    Send("{h up}")
    Send("{n down}")
    Sleep 656
    Send("{n up}")
    Send("{z down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{z up}")
    Sleep 562
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 562
    Send("{z down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{z up}")
    Sleep 469
    Send("{n down}")
    Sleep 469
    Send("{n up}")
    Send("{z down}")
    Send("{c down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 375
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 375
    Send("{z down}")
    Send("{c down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 234
    Send("{c down}")
    Sleep 47
    Send("{c up}")
    Send("{g down}")
    Sleep 47
    Send("{g up}")
    Send("{h down}")
    Sleep 47
    Send("{h up}")
    Send("{n down}")
    Sleep 375
    Send("{n up}")
    Send("{z down}")
    Send("{c down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 281
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 281
    Send("{z down}")
    Send("{c down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 281
    Send("{n down}")
    Sleep 281
    Send("{n up}")
    Send("{c down}")
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Send("{c up}")
    Sleep 188
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 188
    Send("{c down}")
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Send("{c up}")
    Sleep 188
    Send("{n down}")
    Sleep 281
    Send("{n up}")
    Send("{n down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{q up}")
    Send("{n up}")
    Sleep 188
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 188
    Send("{n down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{q up}")
    Send("{n up}")
    Sleep 188
    Send("{n down}")
    Sleep 281
    Send("{n up}")
    Send("{q down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{q up}")
    Sleep 94
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 94
    Send("{e down}")
    Send("{y down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{y up}")
    Send("{e up}")
    Sleep 94
    Send("{n down}")
    Sleep 188
    Send("{n up}")
    Send("{y down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{q up}")
    Send("{y up}")
    Sleep 94
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 94
    Send("{q down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{q up}")
    Sleep 94
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 94
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{c up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{z up}")
    Send("{q up}")
    Sleep 94
    Send("{m down}")
    Send("{e down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{e up}")
    Send("{m up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c down}")
    Send("{x down}")
    Send("{e down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{e up}")
    Send("{x up}")
    Send("{c up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c down}")
    Send("{e down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{e up}")
    Send("{c up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c down}")
    Send("{x down}")
    Send("{e down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{e up}")
    Send("{x up}")
    Send("{c up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{z down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{z up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{3 down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{3 up}")
    Send("{m up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{d down}")
    Send("{g down}")
    Send("{3 down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{3 up}")
    Send("{g up}")
    Send("{d up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{g down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{g up}")
    Sleep 94
    Send("{d down}")
    Send("{g down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{g up}")
    Send("{d up}")
    Sleep 94
    Send("{c down}")
    Send("{h down}")
    Send("{e down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{e up}")
    Send("{h up}")
    Send("{c up}")
    Sleep 281
    Send("{c down}")
    Sleep 375
    Send("{c up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{z down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{c up}")
    Send("{z up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 94
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c up}")
    Sleep 94
    Send("{z down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{z up}")
    Sleep 94
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{x up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{v down}")
    Send("{n down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n up}")
    Send("{v up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{c down}")
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{x down}")
    Send("{h down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{h up}")
    Send("{x up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z down}")
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Send("{z up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{m down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{m up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{u down}")
    Send("{c down}")
    Sleep 94
    Send("{u up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{c up}")
    Send("{y down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{y up}")
    Sleep 281
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Sleep 281
    Send("{w down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Sleep 94
    Send("{r down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{r up}")
    Send("{w up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Sleep 94
    Send("{r down}")
    Send("{y down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{y up}")
    Send("{r up}")
    Sleep 94
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Sleep 94
    Send("{r down}")
    Send("{y down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{y up}")
    Send("{r up}")
    Sleep 94
    Send("{w down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{w up}")
    Sleep 94
    Send("{r down}")
    Send("{y down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{y up}")
    Send("{r up}")
    Sleep 94
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{n up}")
    Sleep 94
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{e up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Sleep 94
    Send("{q down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{y up}")
    Send("{q up}")
    Sleep 94
    Send("{e down}")
    Sleep 188
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Sleep 94
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Sleep 94
    Send("{e up}")
    Send("{q down}")
    Send("{y down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{y up}")
    Send("{q up}")
    Sleep 94
    Send("{h down}")
    Send("{u down}")
    Sleep 94
    Send("{h up}")
    Sleep 94
    Send("{m down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{m up}")
    Send("{u up}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Sleep 94
    Send("{m down}")
    Send("{e down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{e up}")
    Send("{m up}")
    Sleep 94
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Sleep 94
    Send("{m down}")
    Send("{e down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{e up}")
    Send("{m up}")
    Sleep 94
    Send("{h down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{h up}")
    Sleep 94
    Send("{m down}")
    Send("{e down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{e up}")
    Send("{m up}")
    Sleep 94
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Sleep 94
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Sleep 94
    Send("{q down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{q up}")
    Sleep 94
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Sleep 94
    Send("{y down}")
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Send("{y up}")
    Sleep 94
    Send("{e down}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{e up}")
    Sleep 94
    Send("{q down}")
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Send("{q up}")
    Sleep 94
    Send("{n down}")
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 94
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{x up}")
    Sleep 94
    Send("{v down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{v up}")
    Send("{w up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{n down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n up}")
    Sleep 94
    Send("{v down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{v up}")
    Sleep 94
    Send("{x down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{x up}")
    Sleep 94
    Send("{v down}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{v up}")
    Sleep 94
    Send("{n down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n up}")
    Sleep 94
    Send("{v down}")
    Send("{n down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{n up}")
    Send("{v up}")
    Sleep 94
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{z up}")
    Sleep 94
    Send("{c down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{c up}")
    Send("{e up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n up}")
    Sleep 94
    Send("{c down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n up}")
    Send("{c up}")
    Sleep 94
    Send("{z down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{z up}")
    Sleep 94
    Send("{c down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{c up}")
    Sleep 94
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{n up}")
    Sleep 94
    Send("{c down}")
    Send("{n down}")
    Sleep 94
    Send("{n up}")
    Send("{c up}")
    Sleep 94
    Send("{y up}")
    Send("{x down}")
    Sleep 94
    Send("{x up}")
    Sleep 94
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 94
    Send("{n up}")
    Send("{v up}")
    Sleep 94
    Send("{m down}")
    Sleep 94
    Send("{m up}")
    Sleep 94
    Send("{w up}")
    Send("{v down}")
    Send("{n down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{n up}")
    Send("{v up}")
    Sleep 94
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{z down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{z up}")
    Sleep 94
    Send("{x down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{x up}")
    Sleep 94
    Send("{m down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{m up}")
    Sleep 94
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Sleep 469
    Send("{6 down}")
    Send("{e down}")
    Send("{e down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{c up}")
    Send("{e up}")
    Send("{e up}")
    Send("{6 up}")
    Sleep 94
    Send("{n down}")
    Send("{n down}")
    Send("{y down}")
    Send("{y down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{y up}")
    Send("{y up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 281
    Send("{c down}")
    Send("{c down}")
    Sleep 375
    Send("{c up}")
    Send("{c up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 94
    Send("{q down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{q up}")
    Sleep 94
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{c up}")
    Sleep 94
    Send("{q down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{q up}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{6 down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{6 up}")
    Send("{m up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{w down}")
    Send("{e down}")
    Send("{6 down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{6 up}")
    Send("{e up}")
    Send("{w up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{c down}")
    Send("{6 down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{6 up}")
    Send("{c up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{w down}")
    Send("{e down}")
    Send("{6 down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{6 up}")
    Send("{e up}")
    Send("{w up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{n down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{c up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{3 down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{3 up}")
    Send("{m up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{3 down}")
    Send("{5 down}")
    Send("{3 down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{3 up}")
    Send("{5 up}")
    Send("{3 up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{g down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{g up}")
    Sleep 94
    Send("{3 down}")
    Send("{5 down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{5 up}")
    Send("{3 up}")
    Sleep 94
    Send("{e down}")
    Send("{c down}")
    Send("{6 down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{6 up}")
    Send("{c up}")
    Send("{e up}")
    Sleep 281
    Send("{c down}")
    Send("{c down}")
    Sleep 94
    Send("{c up}")
    Send("{c up}")
    Sleep 281
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{q down}")
    Send("{e down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e up}")
    Send("{q up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{c down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{c up}")
    Sleep 94
    Send("{q down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{q up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{n down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{n up}")
    Sleep 94
    Send("{q down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e up}")
    Send("{q up}")
    Sleep 94
    Send("{c down}")
    Send("{q down}")
    Sleep 94
    Send("{c up}")
    Sleep 94
    Send("{q down}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{q up}")
    Sleep 94
    Send("{q up}")
    Send("{w down}")
    Send("{r down}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{r up}")
    Send("{w up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{y down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{y up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{q down}")
    Send("{e down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{e up}")
    Send("{q up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{y down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{y up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{m down}")
    Send("{w down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{w up}")
    Send("{m up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{e down}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{e up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n down}")
    Send("{q down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q up}")
    Send("{n up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{e down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{e up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{h down}")
    Send("{e down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{e up}")
    Send("{h up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{w down}")
    Sleep 94
    Send("{w up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{c down}")
    Send("{c down}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{c up}")
    Send("{c up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{6 down}")
    Sleep 94
    Send("{6 up}")
    Send("{u down}")
    Sleep 94
    Send("{u up}")
    Send("{n down}")
    Send("{n down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 281
    Send("{c down}")
    Send("{c down}")
    Sleep 375
    Send("{c up}")
    Send("{c up}")
    Send("{j down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{j up}")
    Send("{7 down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{7 down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 up}")
    Send("{v down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{v up}")
    Send("{7 down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{7 down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 up}")
    Send("{j down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{j up}")
    Send("{7 down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{7 down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 up}")
    Send("{v down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{v up}")
    Send("{7 down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{7 down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 up}")
    Send("{j down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{j up}")
    Send("{7 down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{7 down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 up}")
    Send("{v down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{v up}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{j down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{j up}")
    Sleep 94
    Send("{2 down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{r up}")
    Send("{2 up}")
    Sleep 94
    Send("{v down}")
    Send("{2 down}")
    Sleep 94
    Send("{v up}")
    Sleep 94
    Send("{2 down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{2 up}")
    Sleep 94
    Send("{2 up}")
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{r up}")
    Send("{q up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{3 down}")
    Send("{r down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{r up}")
    Send("{r up}")
    Send("{3 up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{v down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{r up}")
    Send("{v up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{3 down}")
    Send("{r down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{r up}")
    Send("{r up}")
    Send("{3 up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{j down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{r up}")
    Send("{j up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{v down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{r up}")
    Send("{v up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{e down}")
    Send("{q down}")
    Send("{t down}")
    Sleep 94
    Send("{t up}")
    Send("{q up}")
    Send("{e up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{e down}")
    Send("{e down}")
    Send("{t down}")
    Send("{t down}")
    Sleep 94
    Send("{t up}")
    Send("{t up}")
    Send("{e up}")
    Send("{e up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{b down}")
    Send("{t down}")
    Sleep 94
    Send("{t up}")
    Send("{b up}")
    Sleep 94
    Send("{e down}")
    Send("{t down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{t up}")
    Send("{e up}")
    Sleep 94
    Send("{v down}")
    Send("{r down}")
    Send("{y down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{y up}")
    Send("{r up}")
    Send("{v up}")
    Sleep 281
    Send("{v down}")
    Send("{v down}")
    Sleep 94
    Send("{v up}")
    Send("{v up}")
    Sleep 281
    Send("{j down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{j up}")
    Send("{2 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{2 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 up}")
    Send("{v down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{v up}")
    Send("{2 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{2 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 up}")
    Send("{j down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{j up}")
    Send("{2 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{2 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 up}")
    Send("{v down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{v up}")
    Send("{2 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{2 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 up}")
    Send("{j down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{j up}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{e down}")
    Sleep 94
    Send("{e up}")
    Send("{v down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{v up}")
    Sleep 94
    Send("{2 down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{j down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{j up}")
    Sleep 94
    Send("{2 down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{r up}")
    Send("{2 up}")
    Sleep 94
    Send("{v down}")
    Send("{2 down}")
    Sleep 94
    Send("{v up}")
    Sleep 94
    Send("{2 down}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{2 up}")
    Sleep 94
    Send("{2 up}")
    Send("{3 down}")
    Send("{r down}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{r up}")
    Send("{3 up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{7 up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{7 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{7 up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{q down}")
    Send("{3 down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{3 up}")
    Send("{q up}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{r down}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{r up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{j down}")
    Send("{2 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 up}")
    Send("{j up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{r down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{r up}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{n down}")
    Send("{r down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{r up}")
    Send("{n up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{v down}")
    Send("{v down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{v up}")
    Send("{v up}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{j down}")
    Send("{j down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{j up}")
    Send("{j up}")
    Sleep 281
    Send("{j down}")
    Send("{j down}")
    Sleep 375
    Send("{j up}")
    Send("{j up}")
    Send("{3 down}")
    Send("{5 down}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{5 up}")
    Send("{3 up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{2 down}")
    Send("{r down}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{r up}")
    Send("{2 up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{q down}")
    Send("{3 down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{3 up}")
    Send("{q up}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{j down}")
    Send("{2 down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{2 up}")
    Send("{j up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{n down}")
    Send("{q down}")
    Send("{5 down}")
    Sleep 94
    Send("{5 up}")
    Send("{q up}")
    Send("{n up}")
    Send("{r down}")
    Sleep 94
    Send("{r up}")
    Send("{3 down}")
    Sleep 94
    Send("{3 up}")
    Send("{2 down}")
    Sleep 94
    Send("{2 up}")
    Send("{v down}")
    Send("{v down}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{v up}")
    Send("{v up}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{y down}")
    Sleep 94
    Send("{y up}")
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Send("{j down}")
    Send("{j down}")
    Send("{7 down}")
    Sleep 94
    Send("{7 up}")
    Send("{j up}")
    Send("{j up}")
    Sleep 281
    Send("{j down}")
    Send("{3 down}")
    Send("{7 down}")
    Send("{7 down}")
    Sleep 469
    Send("{7 up}")
    Send("{7 up}")
    Send("{3 up}")
    Send("{j up}")
}
