#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{g down}")
    Sleep 463
    Send("{g up}")
    Sleep 93
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 330
    Send("{j up}")
    Sleep 93
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Sleep 550
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{g up}")
    Sleep 284
    Send("{g down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 550
    Send("{d up}")
    Sleep 6
    Send("{s down}")
    Sleep 278
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 330
    Send("{s up}")
    Sleep 370
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 145
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Sleep 550
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 417
    Send("{2 up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 550
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Sleep 550
    Send("{h up}")
    Sleep 6
    Send("{d down}")
    Sleep 278
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 330
    Send("{d up}")
    Sleep 370
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 145
    Send("{g down}")
    Sleep 411
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{g up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{g up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 284
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 145
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{2 up}")
    Sleep 6
    Send("{m down}")
    Sleep 133
    Send("{m up}")
    Sleep 6
    Send("{m down}")
    Sleep 133
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{j up}")
    Sleep 145
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Sleep 6
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 145
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{3 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{3 up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{3 down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{3 up}")
    Sleep 6
    Send("{j down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{j up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Sleep 6
    Send("{m down}")
    Sleep 272
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 139
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{h up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{g up}")
    Sleep 284
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 6
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{g up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 145
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 284
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{g up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Sleep 6
    Send("{d down}")
    Sleep 272
    Send("{d up}")
    Sleep 6
    Send("{d down}")
    Sleep 278
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 52
    Send("{d up}")
    Sleep 93
    Send("{d down}")
    Sleep 411
    Send("{d up}")
    Sleep 6
    Send("{v down}")
    Sleep 133
    Send("{v up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{m down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 139
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{h down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 185
    Send("{h up}")
    Sleep 87
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{h down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{h up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{g down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{g up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{h down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{h up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{d down}")
    Sleep 1661
    Send("{d up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 145
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{g up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{s down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{s up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 6
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{m down}")
    Sleep 139
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{m up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Sleep 139
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{g up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 145
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{g up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{h up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 272
    Send("{d up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Sleep 6
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 6
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{2 up}")
    Sleep 6
    Send("{3 down}")
    Sleep 272
    Send("{3 up}")
    Sleep 145
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{j down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{j up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{g up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{m down}")
    Sleep 272
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{j down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{j up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{d down}")
    Sleep 272
    Send("{d up}")
    Sleep 6
    Send("{d down}")
    Sleep 272
    Send("{d up}")
    Sleep 6
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 6
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{3 down}")
    Sleep 272
    Send("{3 up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 139
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Sleep 284
    Send("{j down}")
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{j up}")
    Send("{2 up}")
    Send("{5 up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 145
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{3 up}")
    Send("{6 up}")
    Sleep 145
    Send("{g down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{g up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{j down}")
    Send("{3 down}")
    Send("{6 down}")
    Sleep 133
    Send("{j up}")
    Send("{3 up}")
    Send("{6 up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 272
    Send("{d up}")
    Sleep 6
    Send("{d down}")
    Sleep 278
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Sleep 52
    Send("{d up}")
    Sleep 93
    Send("{d down}")
    Sleep 278
    Send("{2 down}")
    Send("{5 down}")
    Sleep 133
    Send("{2 up}")
    Send("{5 up}")
    Send("{d up}")
    Sleep 6
    Send("{v down}")
    Sleep 133
    Send("{v up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{m down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 139
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{h down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 185
    Send("{h up}")
    Sleep 87
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{h down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{h up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{g down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{g up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{h down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{h up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{d down}")
    Sleep 1800
    Send("{d up}")
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 145
    Send("{2 down}")
    Send("{2 down}")
    Send("{s down}")
    Sleep 272
    Send("{s up}")
    Sleep 191
    Send("{2 up}")
    Send("{2 up}")
    Sleep 93
    Send("{7 down}")
    Send("{7 down}")
    Sleep 463
    Send("{7 up}")
    Send("{7 up}")
    Sleep 93
    Send("{6 down}")
    Send("{6 down}")
    Sleep 272
    Send("{6 up}")
    Send("{6 up}")
    Sleep 6
    Send("{5 down}")
    Send("{5 down}")
    Sleep 272
    Send("{5 up}")
    Send("{5 up}")
    Sleep 284
    Send("{7 down}")
    Send("{7 down}")
    Sleep 550
    Send("{7 up}")
    Send("{7 up}")
    Sleep 6
    Send("{u down}")
    Send("{u down}")
    Sleep 272
    Send("{u up}")
    Send("{u up}")
    Sleep 6
    Send("{7 down}")
    Send("{7 down}")
    Sleep 463
    Send("{7 up}")
    Send("{7 up}")
    Sleep 93
    Send("{6 down}")
    Send("{6 down}")
    Sleep 272
    Send("{6 up}")
    Send("{6 up}")
    Sleep 6
    Send("{5 down}")
    Send("{5 down}")
    Sleep 272
    Send("{5 up}")
    Send("{5 up}")
    Sleep 6
    Send("{3 down}")
    Send("{3 down}")
    Sleep 272
    Send("{3 up}")
    Send("{3 up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Sleep 463
    Send("{2 up}")
    Send("{2 up}")
    Sleep 93
    Send("{7 down}")
    Send("{7 down}")
    Sleep 463
    Send("{7 up}")
    Send("{7 up}")
    Sleep 93
    Send("{6 down}")
    Send("{6 down}")
    Sleep 272
    Send("{6 up}")
    Send("{6 up}")
    Sleep 6
    Send("{5 down}")
    Send("{5 down}")
    Sleep 272
    Send("{5 up}")
    Send("{5 up}")
    Sleep 284
    Send("{7 down}")
    Send("{7 down}")
    Sleep 550
    Send("{7 up}")
    Send("{7 up}")
    Sleep 6
    Send("{u down}")
    Send("{u down}")
    Sleep 272
    Send("{u up}")
    Send("{u up}")
    Sleep 6
    Send("{7 down}")
    Send("{7 down}")
    Sleep 463
    Send("{7 up}")
    Send("{7 up}")
    Sleep 93
    Send("{6 down}")
    Send("{6 down}")
    Sleep 272
    Send("{6 up}")
    Send("{6 up}")
    Sleep 6
    Send("{5 down}")
    Send("{5 down}")
    Sleep 272
    Send("{5 up}")
    Send("{5 up}")
    Sleep 6
    Send("{3 down}")
    Send("{3 down}")
    Sleep 272
    Send("{3 up}")
    Send("{3 up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Sleep 463
    Send("{2 up}")
    Send("{2 up}")
    Sleep 93
    Send("{7 down}")
    Send("{7 down}")
    Sleep 463
    Send("{7 up}")
    Send("{7 up}")
    Sleep 93
    Send("{6 down}")
    Send("{6 down}")
    Sleep 272
    Send("{6 up}")
    Send("{6 up}")
    Sleep 6
    Send("{5 down}")
    Send("{5 down}")
    Sleep 272
    Send("{5 up}")
    Send("{5 up}")
    Sleep 284
    Send("{7 down}")
    Send("{7 down}")
    Sleep 550
    Send("{7 up}")
    Send("{7 up}")
    Sleep 6
    Send("{u down}")
    Send("{u down}")
    Sleep 272
    Send("{u up}")
    Send("{u up}")
    Sleep 6
    Send("{7 down}")
    Send("{7 down}")
    Sleep 463
    Send("{7 up}")
    Send("{7 up}")
    Sleep 93
    Send("{6 down}")
    Send("{6 down}")
    Sleep 272
    Send("{6 up}")
    Send("{6 up}")
    Sleep 6
    Send("{5 down}")
    Send("{5 down}")
    Sleep 272
    Send("{5 up}")
    Send("{5 up}")
    Sleep 6
    Send("{3 down}")
    Send("{3 down}")
    Sleep 272
    Send("{3 up}")
    Send("{3 up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Sleep 463
    Send("{2 up}")
    Send("{2 up}")
    Sleep 93
    Send("{7 down}")
    Send("{7 down}")
    Sleep 463
    Send("{7 up}")
    Send("{7 up}")
    Sleep 93
    Send("{6 down}")
    Send("{6 down}")
    Sleep 272
    Send("{6 up}")
    Send("{6 up}")
    Sleep 6
    Send("{5 down}")
    Send("{5 down}")
    Sleep 272
    Send("{5 up}")
    Send("{5 up}")
    Sleep 284
    Send("{7 down}")
    Send("{7 down}")
    Sleep 550
    Send("{7 up}")
    Send("{7 up}")
    Sleep 6
    Send("{u down}")
    Send("{u down}")
    Sleep 272
    Send("{u up}")
    Send("{u up}")
    Sleep 6
    Send("{7 down}")
    Send("{7 down}")
    Sleep 463
    Send("{7 up}")
    Send("{7 up}")
    Sleep 93
    Send("{6 down}")
    Send("{6 down}")
    Sleep 272
    Send("{6 up}")
    Send("{6 up}")
    Sleep 6
    Send("{5 down}")
    Send("{5 down}")
    Sleep 272
    Send("{5 up}")
    Send("{5 up}")
    Sleep 6
    Send("{d down}")
    Send("{3 down}")
    Send("{3 down}")
    Sleep 272
    Send("{3 up}")
    Send("{3 up}")
    Sleep 6
    Send("{2 down}")
    Send("{2 down}")
    Sleep 133
    Send("{d up}")
    Sleep 6
    Send("{v down}")
    Sleep 133
    Send("{v up}")
    Send("{2 up}")
    Send("{2 up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{s down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{s up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{m down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{2 up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{3 down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{3 up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{5 down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 133
    Send("{5 up}")
    Sleep 139
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{h down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 185
    Send("{h up}")
    Sleep 87
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{g down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{c down}")
    Send("{m down}")
    Sleep 185
    Send("{g up}")
    Sleep 87
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 272
    Send("{2 up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{z up}")
    Sleep 6
    Send("{h down}")
    Send("{s down}")
    Sleep 272
    Send("{h up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{j down}")
    Sleep 272
    Send("{g up}")
    Send("{j up}")
    Sleep 6
    Send("{g down}")
    Send("{h down}")
    Sleep 272
    Send("{g up}")
    Send("{h up}")
    Sleep 6
    Send("{m down}")
    Send("{d down}")
    Send("{5 down}")
    Sleep 272
    Send("{d up}")
    Send("{5 up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{m up}")
    Send("{h up}")
    Sleep 6
    Send("{j down}")
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{j down}")
    Sleep 272
    Send("{h up}")
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Sleep 6
    Send("{g down}")
    Send("{j down}")
    Sleep 272
    Send("{g up}")
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Send("{2 down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 272
    Send("{2 up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{z down}")
    Sleep 272
    Send("{h up}")
    Send("{z up}")
    Sleep 6
    Send("{h down}")
    Send("{s down}")
    Sleep 272
    Send("{h up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{j down}")
    Sleep 272
    Send("{g up}")
    Send("{j up}")
    Sleep 6
    Send("{g down}")
    Send("{h down}")
    Sleep 272
    Send("{g up}")
    Send("{h up}")
    Sleep 6
    Send("{d down}")
    Send("{d down}")
    Send("{5 down}")
    Sleep 272
    Send("{d up}")
    Send("{5 up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{d up}")
    Send("{h up}")
    Sleep 6
    Send("{s down}")
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Sleep 185
    Send("{s up}")
    Sleep 87
    Send("{j up}")
    Sleep 6
    Send("{m down}")
    Sleep 272
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{s down}")
    Send("{2 down}")
    Sleep 272
    Send("{2 up}")
    Send("{s up}")
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Sleep 185
    Send("{2 up}")
    Sleep 87
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{z down}")
    Sleep 272
    Send("{j up}")
    Send("{z up}")
    Sleep 6
    Send("{h down}")
    Send("{s down}")
    Sleep 272
    Send("{h up}")
    Send("{s up}")
    Sleep 6
    Send("{j down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Send("{h down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{d down}")
    Send("{5 down}")
    Sleep 272
    Send("{2 up}")
    Send("{d up}")
    Send("{5 up}")
    Sleep 6
    Send("{m down}")
    Send("{h down}")
    Sleep 133
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Send("{h up}")
    Sleep 6
    Send("{m down}")
    Send("{j down}")
    Sleep 133
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Send("{j up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{j down}")
    Sleep 272
    Send("{g up}")
    Send("{j up}")
    Sleep 6
    Send("{d down}")
    Send("{m down}")
    Sleep 272
    Send("{d up}")
    Send("{m up}")
    Sleep 6
    Send("{s down}")
    Send("{j down}")
    Sleep 272
    Send("{s up}")
    Send("{j up}")
    Sleep 6
    Send("{d down}")
    Send("{g down}")
    Sleep 272
    Send("{d up}")
    Send("{g up}")
    Sleep 6
    Send("{s down}")
    Send("{s down}")
    Send("{2 down}")
    Sleep 272
    Send("{s up}")
    Send("{s up}")
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Sleep 185
    Send("{2 up}")
    Sleep 87
    Send("{j up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{z down}")
    Sleep 272
    Send("{j up}")
    Send("{z up}")
    Sleep 6
    Send("{h down}")
    Send("{s down}")
    Sleep 272
    Send("{h up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{j down}")
    Sleep 272
    Send("{g up}")
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 272
    Send("{h up}")
    Sleep 6
    Send("{h down}")
    Send("{d down}")
    Send("{5 down}")
    Sleep 272
    Send("{d up}")
    Send("{5 up}")
    Sleep 278
    Send("{h up}")
    Sleep 6
    Send("{j down}")
    Sleep 1244
    Send("{j up}")
    Sleep 145
    Send("{2 down}")
    Sleep 411
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 272
    Send("{2 up}")
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{s down}")
    Sleep 272
    Send("{2 up}")
    Send("{s up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{s down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{s up}")
    Sleep 6
    Send("{2 down}")
    Send("{m down}")
    Sleep 272
    Send("{2 up}")
    Send("{m up}")
    Sleep 6
    Send("{2 down}")
    Send("{d down}")
    Sleep 272
    Send("{2 up}")
    Send("{d up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 272
    Send("{d up}")
    Sleep 6
    Send("{2 down}")
    Send("{z down}")
    Sleep 272
    Send("{2 up}")
    Send("{z up}")
    Sleep 6
    Send("{2 down}")
    Send("{d down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{d up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 272
    Send("{2 up}")
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{d down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{d up}")
    Sleep 6
    Send("{2 down}")
    Send("{m down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{m up}")
    Sleep 6
    Send("{2 down}")
    Send("{d down}")
    Sleep 272
    Send("{2 up}")
    Send("{d up}")
    Sleep 6
    Send("{3 down}")
    Send("{g down}")
    Sleep 133
    Send("{3 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 272
    Send("{d up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{s down}")
    Sleep 272
    Send("{2 up}")
    Send("{s up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 272
    Send("{2 up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{s down}")
    Sleep 133
    Send("{m up}")
    Sleep 6
    Send("{m down}")
    Sleep 133
    Send("{m up}")
    Send("{s up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Sleep 272
    Send("{j up}")
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Send("{d down}")
    Sleep 272
    Send("{j up}")
    Send("{d up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 139
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Send("{d up}")
    Sleep 6
    Send("{j down}")
    Send("{z down}")
    Sleep 272
    Send("{j up}")
    Send("{z up}")
    Sleep 6
    Send("{g down}")
    Send("{d down}")
    Sleep 272
    Send("{g up}")
    Send("{d up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{d down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{d up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Sleep 6
    Send("{g down}")
    Send("{d down}")
    Sleep 272
    Send("{g up}")
    Send("{d up}")
    Sleep 6
    Send("{d down}")
    Send("{g down}")
    Sleep 133
    Send("{d up}")
    Sleep 6
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 272
    Send("{d up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{s down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Send("{s up}")
    Sleep 6
    Send("{3 down}")
    Send("{g down}")
    Sleep 272
    Send("{3 up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{s down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{s up}")
    Sleep 6
    Send("{m down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{j up}")
    Send("{m up}")
    Sleep 6
    Send("{3 down}")
    Send("{d down}")
    Sleep 272
    Send("{3 up}")
    Send("{d up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{m down}")
    Sleep 133
    Send("{d up}")
    Sleep 6
    Send("{z down}")
    Sleep 133
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Sleep 133
    Send("{z up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{j up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{d up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{h down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{h up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Send("{d up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Sleep 6
    Send("{g down}")
    Send("{d down}")
    Sleep 272
    Send("{g up}")
    Send("{d up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 139
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Send("{d up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Sleep 6
    Send("{d down}")
    Sleep 272
    Send("{d up}")
    Sleep 6
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 139
    Send("{s down}")
    Sleep 133
    Send("{s up}")
    Send("{d up}")
    Sleep 6
    Send("{3 down}")
    Send("{z down}")
    Sleep 133
    Send("{3 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{z up}")
    Sleep 6
    Send("{2 down}")
    Send("{d down}")
    Sleep 272
    Send("{2 up}")
    Send("{d up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{d down}")
    Sleep 272
    Send("{2 up}")
    Send("{d up}")
    Sleep 6
    Send("{2 down}")
    Send("{m down}")
    Sleep 272
    Send("{m up}")
    Sleep 6
    Send("{d down}")
    Sleep 185
    Send("{2 up}")
    Sleep 87
    Send("{d up}")
    Sleep 6
    Send("{d down}")
    Sleep 411
    Send("{d up}")
    Sleep 6
    Send("{v down}")
    Sleep 133
    Send("{v up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{j up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 6
    Send("{d down}")
    Sleep 133
    Send("{d up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{s down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{s up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{m down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{2 up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{3 down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{3 up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{5 down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{5 up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{6 down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{6 up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{5 down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 185
    Send("{5 up}")
    Sleep 87
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{2 up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{m down}")
    Send("{g down}")
    Sleep 133
    Send("{g up}")
    Sleep 139
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{s down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{s up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 133
    Send("{2 up}")
    Sleep 6
    Send("{2 down}")
    Sleep 133
    Send("{2 up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{m down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{m up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{2 up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{3 down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{3 up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{5 down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{5 up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{6 down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{6 up}")
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{5 down}")
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 272
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{z down}")
    Send("{g down}")
    Sleep 185
    Send("{5 up}")
    Sleep 87
    Send("{z up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{h up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Sleep 6
    Send("{2 down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{2 up}")
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 272
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{g down}")
    Send("{s down}")
    Sleep 185
    Send("{j up}")
    Sleep 87
    Send("{g up}")
    Send("{s up}")
    Sleep 6
    Send("{h down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{h up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{g down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{g up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{h down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{h up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 6
    Send("{j down}")
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Send("{g down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 272
    Send("{j up}")
    Sleep 6
    Send("{d down}")
    Sleep 1522
    Send("{d up}")
    Sleep 278
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
    Send("{g up}")
    Send("{m up}")
    Send("{g up}")
}
