#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()

Hotkey "Esc", (*) => ExitApp()

PlaySong() {
    Send("{y down}")
    Sleep 501
    Send("{w down}")
    Sleep 17
    Send("{y up}")
    Sleep 991
    Send("{r down}")
    Sleep 39
    Send("{w up}")
    Sleep 462
    Send("{y down}")
    Sleep 20
    Send("{r up}")
    Sleep 493
    Send("{w down}")
    Sleep 18
    Send("{y up}")
    Sleep 995
    Send("{r down}")
    Sleep 39
    Send("{w up}")
    Sleep 457
    Send("{y down}")
    Sleep 19
    Send("{r up}")
    Sleep 29
    Send("{y up}")
    Sleep 220
    Send("{u down}")
    Sleep 485
    Send("{t down}")
    Sleep 19
    Send("{u up}")
    Sleep 477
    Send("{r down}")
    Sleep 19
    Send("{t up}")
    Sleep 230
    Send("{t down}")
    Sleep 29
    Send("{r up}")
    Sleep 217
    Send("{y down}")
    Sleep 29
    Send("{t up}")
    Sleep 467
    Send("{w down}")
    Sleep 17
    Send("{y up}")
    Sleep 496
    Send("{q down}")
    Sleep 19
    Send("{w up}")
    Sleep 228
    Send("{e down}")
    Sleep 29
    Send("{q up}")
    Sleep 220
    Send("{w down}")
    Sleep 29
    Send("{e up}")
    Sleep 2438
    Send("{w up}")
    Sleep 27
    Send("{y down}")
    Sleep 501
    Send("{w down}")
    Sleep 17
    Send("{y up}")
    Sleep 991
    Send("{r down}")
    Sleep 39
    Send("{w up}")
    Sleep 462
    Send("{y down}")
    Sleep 20
    Send("{r up}")
    Sleep 493
    Send("{w down}")
    Sleep 18
    Send("{y up}")
    Sleep 995
    Send("{r down}")
    Sleep 39
    Send("{w up}")
    Sleep 457
    Send("{y down}")
    Sleep 19
    Send("{r up}")
    Sleep 29
    Send("{y up}")
    Sleep 220
    Send("{u down}")
    Sleep 485
    Send("{t down}")
    Sleep 19
    Send("{u up}")
    Sleep 477
    Send("{r down}")
    Sleep 19
    Send("{t up}")
    Sleep 230
    Send("{t down}")
    Sleep 29
    Send("{r up}")
    Sleep 217
    Send("{y down}")
    Sleep 29
    Send("{t up}")
    Sleep 467
    Send("{w down}")
    Sleep 17
    Send("{y up}")
    Sleep 496
    Send("{q down}")
    Sleep 19
    Send("{w up}")
    Sleep 228
    Send("{e down}")
    Sleep 29
    Send("{q up}")
    Sleep 220
    Send("{w down}")
    Sleep 29
    Send("{e up}")
    Sleep 2438
    Send("{w up}")
}
