#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()

Hotkey "Esc", (*) => ExitApp()

PlaySong() {
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{6 down}")
    Sleep 222
    Send("{6 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{e down}")
    Sleep 222
    Send("{e up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{h down}")
    Sleep 222
    Send("{h up}")
    Send("{3 down}")
    Sleep 222
    Send("{3 up}")
    Send("{h down}")
    Sleep 222
    Send("{h up}")
    Send("{h down}")
    Sleep 222
    Send("{h up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{g down}")
    Sleep 222
    Send("{g up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{g down}")
    Sleep 222
    Send("{g up}")
    Send("{g down}")
    Sleep 222
    Send("{g up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Sleep 215
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{6 down}")
    Sleep 222
    Send("{6 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{e down}")
    Sleep 222
    Send("{e up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{n down}")
    Sleep 222
    Send("{n up}")
    Send("{h down}")
    Sleep 222
    Send("{h up}")
    Send("{3 down}")
    Sleep 222
    Send("{3 up}")
    Send("{h down}")
    Sleep 222
    Send("{h up}")
    Send("{h down}")
    Sleep 222
    Send("{h up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{g down}")
    Sleep 222
    Send("{g up}")
    Send("{2 down}")
    Sleep 222
    Send("{2 up}")
    Send("{g down}")
    Sleep 222
    Send("{g up}")
    Send("{g down}")
    Sleep 222
    Send("{g up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
    Send("{m down}")
    Sleep 222
    Send("{m up}")
}
