#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 119
    Send("{r up}")
    Sleep 7
    Send("{q up}")
    Send("{y up}")
    Sleep 2
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 161
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 226
    Send("{y down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 119
    Send("{y up}")
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Sleep 0
    Send("{t down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 142
    Send("{t up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 226
    Send("{r down}")
    Send("{7 down}")
    Send("{w down}")
    Sleep 120
    Send("{7 up}")
    Sleep 7
    Send("{r up}")
    Send("{w up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{q down}")
    Sleep 495
    Send("{r up}")
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{w down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 142
    Send("{w up}")
    Send("{t up}")
    Send("{7 up}")
    Sleep 226
    Send("{r down}")
    Send("{7 down}")
    Send("{w down}")
    Sleep 119
    Send("{7 up}")
    Sleep 7
    Send("{r up}")
    Send("{w up}")
    Sleep 2
    Send("{r down}")
    Send("{y down}")
    Send("{q down}")
    Sleep 161
    Send("{r up}")
    Send("{y up}")
    Send("{q up}")
    Sleep 232
    Send("{w down}")
    Send("{t down}")
    Send("{7 down}")
    Sleep 127
    Send("{w up}")
    Send("{t up}")
    Sleep 8
    Send("{7 up}")
    Sleep 1
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Sleep 154
    Send("{q up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 255
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 141
    Send("{q up}")
    Send("{e up}")
    Sleep 9
    Send("{t up}")
    Sleep 1
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 641
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 2
    Send("{b down}")
    Send("{j down}")
    Send("{e down}")
    Send("{z down}")
    Sleep 1681
    Send("{b up}")
    Send("{j up}")
    Send("{e up}")
    Sleep 300
    Send("{z up}")
    Sleep 2
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Sleep 15
    Send("{z down}")
    Send("{v down}")
    Sleep 98
    Send("{z up}")
    Send("{v up}")
    Sleep 150
    Send("{n down}")
    Sleep 118
    Send("{n up}")
    Sleep 8
    Send("{z down}")
    Send("{v down}")
    Sleep 45
    Send("{z up}")
    Send("{v up}")
    Sleep 76
    Send("{v down}")
    Sleep 234
    Send("{v up}")
    Sleep 15
    Send("{b down}")
    Sleep 234
    Send("{b up}")
    Sleep 15
    Send("{x down}")
    Send("{b down}")
    Sleep 96
    Send("{x up}")
    Send("{b up}")
    Sleep 150
    Send("{j down}")
    Sleep 118
    Send("{j up}")
    Sleep 8
    Send("{x down}")
    Send("{b down}")
    Sleep 45
    Send("{x up}")
    Send("{b up}")
    Sleep 76
    Send("{b down}")
    Sleep 232
    Send("{b up}")
    Sleep 17
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Sleep 15
    Send("{c down}")
    Send("{n down}")
    Sleep 98
    Send("{c up}")
    Send("{n up}")
    Sleep 150
    Send("{q down}")
    Sleep 118
    Send("{q up}")
    Sleep 8
    Send("{c down}")
    Send("{n down}")
    Sleep 45
    Send("{c up}")
    Send("{n up}")
    Sleep 76
    Send("{n down}")
    Sleep 234
    Send("{n up}")
    Sleep 15
    Send("{b down}")
    Sleep 234
    Send("{b up}")
    Sleep 15
    Send("{x down}")
    Send("{b down}")
    Sleep 96
    Send("{x up}")
    Send("{b up}")
    Sleep 150
    Send("{j down}")
    Sleep 118
    Send("{j up}")
    Sleep 8
    Send("{x down}")
    Send("{b down}")
    Sleep 45
    Send("{x up}")
    Send("{b up}")
    Sleep 76
    Send("{b down}")
    Sleep 232
    Send("{b up}")
    Sleep 17
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Sleep 15
    Send("{z down}")
    Send("{v down}")
    Sleep 98
    Send("{z up}")
    Send("{v up}")
    Sleep 150
    Send("{n down}")
    Sleep 118
    Send("{n up}")
    Sleep 8
    Send("{z down}")
    Send("{v down}")
    Sleep 45
    Send("{z up}")
    Send("{v up}")
    Sleep 76
    Send("{v down}")
    Sleep 234
    Send("{v up}")
    Sleep 15
    Send("{b down}")
    Sleep 234
    Send("{b up}")
    Sleep 15
    Send("{x down}")
    Send("{b down}")
    Sleep 96
    Send("{x up}")
    Send("{b up}")
    Sleep 150
    Send("{j down}")
    Sleep 118
    Send("{j up}")
    Sleep 8
    Send("{x down}")
    Send("{b down}")
    Sleep 45
    Send("{x up}")
    Send("{b up}")
    Sleep 76
    Send("{b down}")
    Sleep 232
    Send("{b up}")
    Sleep 17
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Sleep 15
    Send("{c down}")
    Send("{n down}")
    Sleep 98
    Send("{c up}")
    Send("{n up}")
    Sleep 150
    Send("{q down}")
    Sleep 118
    Send("{q up}")
    Sleep 8
    Send("{c down}")
    Send("{n down}")
    Sleep 45
    Send("{c up}")
    Send("{n up}")
    Sleep 76
    Send("{n down}")
    Sleep 234
    Send("{n up}")
    Sleep 15
    Send("{b down}")
    Sleep 234
    Send("{b up}")
    Sleep 15
    Send("{x down}")
    Send("{b down}")
    Sleep 96
    Send("{x up}")
    Send("{b up}")
    Sleep 150
    Send("{j down}")
    Sleep 118
    Send("{j up}")
    Sleep 8
    Send("{x down}")
    Send("{b down}")
    Sleep 45
    Send("{x up}")
    Send("{b up}")
    Sleep 76
    Send("{b down}")
    Sleep 232
    Send("{b up}")
    Sleep 17
    Send("{v down}")
    Sleep 250
    Send("{v up}")
    Sleep 15
    Send("{r down}")
    Send("{z down}")
    Send("{v down}")
    Sleep 98
    Send("{z up}")
    Send("{v up}")
    Sleep 135
    Send("{r up}")
    Sleep 15
    Send("{e down}")
    Send("{n down}")
    Sleep 118
    Send("{e up}")
    Send("{n up}")
    Sleep 8
    Send("{w down}")
    Send("{z down}")
    Send("{v down}")
    Sleep 45
    Send("{z up}")
    Send("{v up}")
    Sleep 68
    Send("{w up}")
    Sleep 8
    Send("{q down}")
    Send("{v down}")
    Sleep 113
    Send("{q up}")
    Sleep 8
    Send("{7 down}")
    Sleep 113
    Send("{v up}")
    Sleep 7
    Send("{7 up}")
    Sleep 8
    Send("{q down}")
    Send("{n down}")
    Sleep 234
    Send("{n up}")
    Sleep 15
    Send("{r down}")
    Send("{v down}")
    Send("{n down}")
    Sleep 29
    Send("{q up}")
    Sleep 67
    Send("{r up}")
    Send("{v up}")
    Send("{n up}")
    Sleep 150
    Send("{r down}")
    Send("{q down}")
    Sleep 118
    Send("{q up}")
    Sleep 8
    Send("{v down}")
    Send("{n down}")
    Sleep 13
    Send("{r up}")
    Sleep 32
    Send("{v up}")
    Send("{n up}")
    Sleep 76
    Send("{q down}")
    Send("{n down}")
    Sleep 232
    Send("{q up}")
    Send("{n up}")
    Sleep 17
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Sleep 15
    Send("{w down}")
    Send("{v down}")
    Send("{j down}")
    Sleep 98
    Send("{v up}")
    Send("{j up}")
    Sleep 150
    Send("{7 down}")
    Send("{w down}")
    Sleep 29
    Send("{w up}")
    Sleep 89
    Send("{w up}")
    Sleep 8
    Send("{v down}")
    Send("{j down}")
    Sleep 13
    Send("{7 up}")
    Sleep 32
    Send("{v up}")
    Send("{j up}")
    Sleep 76
    Send("{w down}")
    Send("{j down}")
    Sleep 99
    Send("{w up}")
    Sleep 135
    Send("{j up}")
    Sleep 15
    Send("{q down}")
    Send("{n down}")
    Sleep 234
    Send("{n up}")
    Sleep 15
    Send("{v down}")
    Send("{n down}")
    Sleep 96
    Send("{v up}")
    Send("{n up}")
    Sleep 150
    Send("{q up}")
    Sleep 0
    Send("{r down}")
    Send("{q down}")
    Sleep 118
    Send("{q up}")
    Sleep 8
    Send("{v down}")
    Send("{n down}")
    Sleep 45
    Send("{v up}")
    Send("{n up}")
    Sleep 76
    Send("{n down}")
    Sleep 232
    Send("{n up}")
    Sleep 15
    Send("{r up}")
    Sleep 2
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Sleep 15
    Send("{t down}")
    Send("{7 down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 98
    Send("{x up}")
    Send("{b up}")
    Sleep 135
    Send("{t up}")
    Sleep 15
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{j down}")
    Sleep 118
    Send("{r up}")
    Send("{j up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 45
    Send("{x up}")
    Send("{b up}")
    Sleep 68
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{b down}")
    Sleep 113
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Sleep 113
    Send("{b up}")
    Sleep 15
    Send("{q up}")
    Send("{e up}")
    Sleep 0
    Send("{q down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 234
    Send("{n up}")
    Sleep 15
    Send("{q up}")
    Send("{r up}")
    Sleep 0
    Send("{n down}")
    Send("{q down}")
    Send("{v down}")
    Send("{n down}")
    Sleep 96
    Send("{q up}")
    Send("{v up}")
    Send("{n up}")
    Sleep 42
    Send("{n up}")
    Sleep 108
    Send("{q down}")
    Send("{r down}")
    Send("{q down}")
    Sleep 118
    Send("{q up}")
    Sleep 8
    Send("{v down}")
    Send("{n down}")
    Sleep 45
    Send("{v up}")
    Send("{n up}")
    Sleep 75
    Send("{r up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 29
    Send("{q up}")
    Sleep 68
    Send("{y up}")
    Sleep 42
    Send("{r up}")
    Sleep 93
    Send("{n up}")
    Sleep 17
    Send("{m down}")
    Sleep 250
    Send("{m up}")
    Sleep 15
    Send("{w down}")
    Send("{t down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 98
    Send("{x up}")
    Send("{b up}")
    Sleep 150
    Send("{w up}")
    Send("{t up}")
    Sleep 0
    Send("{m down}")
    Send("{w down}")
    Send("{m down}")
    Sleep 96
    Send("{w up}")
    Sleep 22
    Send("{m up}")
    Sleep 8
    Send("{x down}")
    Send("{b down}")
    Sleep 13
    Send("{m up}")
    Sleep 32
    Send("{x up}")
    Send("{b up}")
    Sleep 76
    Send("{w down}")
    Send("{t down}")
    Send("{m down}")
    Sleep 99
    Send("{w up}")
    Send("{t up}")
    Sleep 135
    Send("{m up}")
    Sleep 15
    Send("{q down}")
    Send("{r down}")
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Send("{b down}")
    Sleep 97
    Send("{z up}")
    Send("{b up}")
    Sleep 152
    Send("{q up}")
    Send("{r up}")
    Sleep 1
    Send("{q down}")
    Send("{e down}")
    Send("{j down}")
    Sleep 121
    Send("{j up}")
    Sleep 8
    Send("{z down}")
    Send("{b down}")
    Sleep 47
    Send("{z up}")
    Send("{b up}")
    Sleep 78
    Send("{z down}")
    Sleep 241
    Send("{z up}")
    Sleep 15
    Send("{q up}")
    Send("{e up}")
    Sleep 3
    Send("{v down}")
    Sleep 254
    Send("{v up}")
    Sleep 15
    Send("{y down}")
    Send("{r down}")
    Send("{z down}")
    Send("{v down}")
    Sleep 98
    Send("{z up}")
    Send("{v up}")
    Sleep 135
    Send("{y up}")
    Sleep 15
    Send("{r up}")
    Sleep 0
    Send("{t down}")
    Send("{e down}")
    Send("{n down}")
    Sleep 118
    Send("{t up}")
    Send("{n up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{r down}")
    Send("{w down}")
    Send("{z down}")
    Send("{v down}")
    Sleep 45
    Send("{z up}")
    Send("{v up}")
    Sleep 68
    Send("{r up}")
    Sleep 7
    Send("{w up}")
    Sleep 0
    Send("{e down}")
    Send("{q down}")
    Send("{v down}")
    Sleep 113
    Send("{e up}")
    Sleep 7
    Send("{q up}")
    Sleep 0
    Send("{w down}")
    Send("{7 down}")
    Sleep 113
    Send("{v up}")
    Sleep 7
    Send("{w up}")
    Sleep 7
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 234
    Send("{n up}")
    Sleep 15
    Send("{r up}")
    Send("{q up}")
    Sleep 0
    Send("{n down}")
    Send("{r down}")
    Send("{v down}")
    Send("{n down}")
    Sleep 96
    Send("{v up}")
    Send("{n up}")
    Sleep 150
    Send("{n up}")
    Send("{r up}")
    Sleep 0
    Send("{n down}")
    Send("{r down}")
    Send("{q down}")
    Sleep 118
    Send("{q up}")
    Sleep 8
    Send("{v down}")
    Send("{n down}")
    Sleep 45
    Send("{v up}")
    Send("{n up}")
    Sleep 75
    Send("{r up}")
    Sleep 0
    Send("{r down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 29
    Send("{n up}")
    Sleep 181
    Send("{r up}")
    Sleep 22
    Send("{n up}")
    Sleep 15
    Send("{q up}")
    Sleep 2
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Sleep 15
    Send("{7 down}")
    Send("{w down}")
    Send("{v down}")
    Send("{j down}")
    Sleep 98
    Send("{v up}")
    Send("{j up}")
    Sleep 150
    Send("{7 up}")
    Send("{w up}")
    Sleep 0
    Send("{r down}")
    Send("{7 down}")
    Send("{w down}")
    Sleep 118
    Send("{w up}")
    Sleep 8
    Send("{v down}")
    Send("{j down}")
    Sleep 45
    Send("{v up}")
    Send("{j up}")
    Sleep 39
    Send("{r up}")
    Sleep 37
    Send("{7 up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{j down}")
    Sleep 234
    Send("{7 up}")
    Send("{j up}")
    Sleep 15
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 234
    Send("{n up}")
    Sleep 15
    Send("{v down}")
    Send("{n down}")
    Sleep 96
    Send("{v up}")
    Send("{n up}")
    Sleep 150
    Send("{y up}")
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Send("{r down}")
    Send("{q down}")
    Sleep 118
    Send("{q up}")
    Sleep 8
    Send("{v down}")
    Send("{n down}")
    Sleep 45
    Send("{v up}")
    Send("{n up}")
    Sleep 76
    Send("{n down}")
    Sleep 232
    Send("{n up}")
    Sleep 15
    Send("{q up}")
    Send("{r up}")
    Sleep 2
    Send("{b down}")
    Sleep 250
    Send("{b up}")
    Sleep 15
    Send("{t down}")
    Send("{7 down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 98
    Send("{x up}")
    Send("{b up}")
    Sleep 135
    Send("{t up}")
    Sleep 15
    Send("{7 up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{j down}")
    Sleep 118
    Send("{r up}")
    Send("{j up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 45
    Send("{x up}")
    Send("{b up}")
    Sleep 68
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{b down}")
    Sleep 113
    Send("{w up}")
    Sleep 7
    Send("{r up}")
    Sleep 0
    Send("{j down}")
    Send("{e down}")
    Sleep 113
    Send("{b up}")
    Sleep 7
    Send("{j up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{q down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 234
    Send("{n up}")
    Sleep 15
    Send("{r up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{v down}")
    Send("{n down}")
    Sleep 29
    Send("{q up}")
    Sleep 67
    Send("{v up}")
    Send("{n up}")
    Sleep 150
    Send("{r up}")
    Send("{y up}")
    Sleep 0
    Send("{r down}")
    Send("{q down}")
    Sleep 118
    Send("{q up}")
    Sleep 8
    Send("{v down}")
    Send("{n down}")
    Sleep 45
    Send("{v up}")
    Send("{n up}")
    Sleep 75
    Send("{r up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 210
    Send("{r up}")
    Sleep 22
    Send("{n up}")
    Sleep 15
    Send("{y up}")
    Sleep 2
    Send("{m down}")
    Sleep 250
    Send("{m up}")
    Sleep 15
    Send("{w down}")
    Send("{t down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 98
    Send("{x up}")
    Send("{b up}")
    Sleep 150
    Send("{w up}")
    Send("{t up}")
    Sleep 0
    Send("{m down}")
    Send("{w down}")
    Send("{m down}")
    Sleep 118
    Send("{m up}")
    Sleep 8
    Send("{x down}")
    Send("{b down}")
    Sleep 45
    Send("{x up}")
    Send("{b up}")
    Sleep 61
    Send("{m up}")
    Sleep 15
    Send("{w up}")
    Sleep 0
    Send("{w down}")
    Send("{t down}")
    Send("{m down}")
    Sleep 234
    Send("{w up}")
    Send("{m up}")
    Sleep 15
    Send("{t up}")
    Sleep 0
    Send("{q down}")
    Send("{r down}")
    Send("{z down}")
    Sleep 249
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Send("{b down}")
    Sleep 96
    Send("{z up}")
    Send("{b up}")
    Sleep 150
    Send("{q up}")
    Send("{r up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Send("{j down}")
    Sleep 118
    Send("{j up}")
    Sleep 8
    Send("{z down}")
    Send("{b down}")
    Sleep 45
    Send("{z up}")
    Send("{b up}")
    Sleep 76
    Send("{z down}")
    Sleep 232
    Send("{z up}")
    Sleep 15
    Send("{q up}")
    Send("{e up}")
    Sleep 2
    Send("{j down}")
    Sleep 265
    Send("{w down}")
    Sleep 114
    Send("{w up}")
    Sleep 8
    Send("{e down}")
    Sleep 119
    Send("{e up}")
    Sleep 8
    Send("{r down}")
    Sleep 231
    Send("{r up}")
    Sleep 15
    Send("{j up}")
    Sleep 0
    Send("{w down}")
    Send("{j down}")
    Sleep 113
    Send("{w up}")
    Sleep 8
    Send("{e down}")
    Sleep 113
    Send("{j up}")
    Sleep 7
    Send("{e up}")
    Sleep 8
    Send("{r down}")
    Send("{n down}")
    Sleep 234
    Send("{r up}")
    Sleep 15
    Send("{q down}")
    Sleep 246
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 231
    Send("{q up}")
    Sleep 15
    Send("{n up}")
    Sleep 0
    Send("{r down}")
    Send("{n down}")
    Sleep 232
    Send("{r up}")
    Send("{n up}")
    Sleep 17
    Send("{j down}")
    Sleep 265
    Send("{7 down}")
    Sleep 233
    Send("{7 up}")
    Sleep 15
    Send("{y down}")
    Sleep 118
    Send("{y up}")
    Sleep 8
    Send("{7 down}")
    Sleep 113
    Send("{7 up}")
    Sleep 7
    Send("{j up}")
    Sleep 0
    Send("{y down}")
    Send("{j down}")
    Sleep 113
    Send("{y up}")
    Sleep 8
    Send("{t down}")
    Sleep 113
    Send("{j up}")
    Sleep 7
    Send("{t up}")
    Sleep 8
    Send("{r down}")
    Send("{v down}")
    Sleep 495
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 246
    Send("{v up}")
    Sleep 0
    Send("{n down}")
    Sleep 232
    Send("{n up}")
    Sleep 15
    Send("{e up}")
    Sleep 2
    Send("{j down}")
    Sleep 265
    Send("{w down}")
    Sleep 114
    Send("{w up}")
    Sleep 8
    Send("{e down}")
    Sleep 119
    Send("{e up}")
    Sleep 8
    Send("{r down}")
    Sleep 231
    Send("{r up}")
    Sleep 15
    Send("{j up}")
    Sleep 0
    Send("{w down}")
    Send("{j down}")
    Sleep 113
    Send("{w up}")
    Sleep 8
    Send("{e down}")
    Sleep 113
    Send("{j up}")
    Sleep 7
    Send("{e up}")
    Sleep 8
    Send("{r down}")
    Send("{n down}")
    Sleep 234
    Send("{r up}")
    Sleep 15
    Send("{q down}")
    Sleep 246
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 231
    Send("{q up}")
    Sleep 15
    Send("{n up}")
    Sleep 0
    Send("{r down}")
    Send("{n down}")
    Sleep 232
    Send("{r up}")
    Send("{n up}")
    Sleep 17
    Send("{m down}")
    Sleep 265
    Send("{w down}")
    Sleep 233
    Send("{w up}")
    Sleep 15
    Send("{t down}")
    Sleep 231
    Send("{t up}")
    Sleep 15
    Send("{m up}")
    Sleep 0
    Send("{w down}")
    Send("{m down}")
    Sleep 234
    Send("{w up}")
    Send("{m up}")
    Sleep 15
    Send("{r down}")
    Send("{z down}")
    Sleep 500
    Send("{r up}")
    Sleep 1
    Send("{e down}")
    Sleep 253
    Send("{z up}")
    Sleep 1
    Send("{z down}")
    Sleep 241
    Send("{z up}")
    Sleep 15
    Send("{e up}")
    Sleep 3
    Send("{r down}")
    Send("{v down}")
    Sleep 254
    Send("{v up}")
    Sleep 15
    Send("{r up}")
    Sleep 0
    Send("{r down}")
    Send("{r down}")
    Send("{z down}")
    Send("{v down}")
    Sleep 98
    Send("{z up}")
    Send("{v up}")
    Sleep 135
    Send("{r up}")
    Send("{r up}")
    Sleep 15
    Send("{e down}")
    Send("{t down}")
    Send("{v down}")
    Send("{n down}")
    Sleep 118
    Send("{e up}")
    Sleep 7
    Send("{v up}")
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Send("{z down}")
    Send("{v down}")
    Sleep 45
    Send("{z up}")
    Send("{v up}")
    Sleep 61
    Send("{t up}")
    Sleep 7
    Send("{w up}")
    Sleep 8
    Send("{q down}")
    Send("{y down}")
    Send("{v down}")
    Sleep 113
    Send("{q up}")
    Sleep 8
    Send("{7 down}")
    Sleep 113
    Send("{y up}")
    Send("{v up}")
    Sleep 7
    Send("{7 up}")
    Sleep 8
    Send("{q down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 234
    Send("{r up}")
    Send("{n up}")
    Sleep 15
    Send("{r down}")
    Send("{q down}")
    Send("{v down}")
    Send("{n down}")
    Sleep 29
    Send("{q up}")
    Sleep 67
    Send("{v up}")
    Send("{n up}")
    Sleep 150
    Send("{r up}")
    Send("{q up}")
    Sleep 0
    Send("{r down}")
    Send("{q down}")
    Send("{n down}")
    Send("{q down}")
    Sleep 125
    Send("{n up}")
    Send("{q up}")
    Sleep 0
    Send("{v down}")
    Send("{n down}")
    Sleep 45
    Send("{v up}")
    Send("{n up}")
    Sleep 61
    Send("{q up}")
    Sleep 15
    Send("{q down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 29
    Send("{r up}")
    Sleep 181
    Send("{q up}")
    Sleep 22
    Send("{r up}")
    Send("{n up}")
    Sleep 17
    Send("{7 down}")
    Send("{j down}")
    Sleep 250
    Send("{j up}")
    Sleep 15
    Send("{7 up}")
    Sleep 0
    Send("{w down}")
    Send("{7 down}")
    Send("{v down}")
    Send("{j down}")
    Sleep 98
    Send("{v up}")
    Send("{j up}")
    Sleep 135
    Send("{7 up}")
    Sleep 15
    Send("{7 down}")
    Send("{r down}")
    Send("{j down}")
    Send("{w down}")
    Sleep 29
    Send("{w up}")
    Sleep 96
    Send("{j up}")
    Send("{w up}")
    Sleep 0
    Send("{v down}")
    Send("{j down}")
    Sleep 45
    Send("{v up}")
    Send("{j up}")
    Sleep 39
    Send("{7 up}")
    Sleep 22
    Send("{r up}")
    Sleep 15
    Send("{w down}")
    Send("{7 down}")
    Send("{j down}")
    Sleep 234
    Send("{w up}")
    Send("{7 up}")
    Send("{j up}")
    Sleep 15
    Send("{q down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 234
    Send("{y up}")
    Send("{n up}")
    Sleep 15
    Send("{w down}")
    Send("{v down}")
    Send("{n down}")
    Sleep 96
    Send("{v up}")
    Send("{n up}")
    Sleep 135
    Send("{w up}")
    Sleep 15
    Send("{q up}")
    Sleep 0
    Send("{r down}")
    Send("{q down}")
    Send("{n down}")
    Send("{q down}")
    Sleep 125
    Send("{n up}")
    Send("{q up}")
    Sleep 0
    Send("{v down}")
    Send("{n down}")
    Sleep 45
    Send("{v up}")
    Send("{n up}")
    Sleep 61
    Send("{q up}")
    Sleep 15
    Send("{e down}")
    Send("{n down}")
    Sleep 232
    Send("{e up}")
    Send("{n up}")
    Sleep 15
    Send("{r up}")
    Sleep 2
    Send("{w down}")
    Send("{b down}")
    Sleep 250
    Send("{w up}")
    Send("{b up}")
    Sleep 15
    Send("{7 down}")
    Send("{t down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 98
    Send("{x up}")
    Send("{b up}")
    Sleep 135
    Send("{7 up}")
    Send("{t up}")
    Sleep 15
    Send("{y down}")
    Send("{r down}")
    Send("{b down}")
    Send("{j down}")
    Sleep 118
    Send("{y up}")
    Sleep 7
    Send("{b up}")
    Send("{j up}")
    Sleep 0
    Send("{t down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 45
    Send("{x up}")
    Send("{b up}")
    Sleep 61
    Send("{r up}")
    Sleep 7
    Send("{t up}")
    Sleep 8
    Send("{r down}")
    Send("{j down}")
    Send("{b down}")
    Sleep 113
    Send("{r up}")
    Sleep 8
    Send("{e down}")
    Sleep 113
    Send("{j up}")
    Send("{b up}")
    Sleep 7
    Send("{e up}")
    Sleep 8
    Send("{r down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 234
    Send("{q up}")
    Send("{n up}")
    Sleep 15
    Send("{q down}")
    Send("{n down}")
    Send("{v down}")
    Send("{n down}")
    Sleep 29
    Send("{r up}")
    Sleep 67
    Send("{v up}")
    Send("{n up}")
    Sleep 113
    Send("{q up}")
    Sleep 22
    Send("{n up}")
    Sleep 15
    Send("{r down}")
    Send("{q down}")
    Send("{n down}")
    Send("{q down}")
    Sleep 125
    Send("{n up}")
    Send("{q up}")
    Sleep 0
    Send("{v down}")
    Send("{n down}")
    Sleep 45
    Send("{v up}")
    Send("{n up}")
    Sleep 61
    Send("{q up}")
    Sleep 15
    Send("{y down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 29
    Send("{r up}")
    Sleep 181
    Send("{y up}")
    Sleep 22
    Send("{r up}")
    Send("{n up}")
    Sleep 17
    Send("{b down}")
    Send("{b down}")
    Sleep 265
    Send("{w down}")
    Send("{t down}")
    Sleep 248
    Send("{w up}")
    Send("{t up}")
    Sleep 0
    Send("{j down}")
    Send("{w down}")
    Sleep 246
    Send("{j up}")
    Send("{w up}")
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{j down}")
    Send("{e down}")
    Send("{j down}")
    Send("{j down}")
    Sleep 234
    Send("{j up}")
    Send("{j up}")
    Sleep 15
    Send("{e up}")
    Send("{j up}")
    Sleep 0
    Send("{n down}")
    Send("{r down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 495
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{n down}")
    Sleep 367
    Send("{n up}")
    Sleep 0
    Send("{v down}")
    Sleep 119
    Send("{v up}")
    Sleep 7
    Send("{n up}")
    Send("{r up}")
    Sleep 2
    Send("{n down}")
    Send("{y down}")
    Send("{v down}")
    Send("{z down}")
    Sleep 264
    Send("{n up}")
    Send("{y up}")
    Send("{z up}")
    Sleep 0
    Send("{n down}")
    Send("{y down}")
    Send("{z down}")
    Sleep 248
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 246
    Send("{n up}")
    Send("{y up}")
    Send("{z up}")
    Sleep 0
    Send("{q down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 234
    Send("{q up}")
    Sleep 15
    Send("{q up}")
    Send("{v up}")
    Send("{z up}")
    Sleep 0
    Send("{b down}")
    Send("{t down}")
    Send("{c down}")
    Send("{z down}")
    Sleep 249
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 246
    Send("{b up}")
    Send("{t up}")
    Send("{z up}")
    Sleep 0
    Send("{q down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 246
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 247
    Send("{q up}")
    Send("{q up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 2
    Send("{g down}")
    Send("{5 down}")
    Send("{d down}")
    Send("{z down}")
    Sleep 264
    Send("{g up}")
    Send("{5 up}")
    Send("{z up}")
    Sleep 0
    Send("{g down}")
    Send("{5 down}")
    Send("{z down}")
    Sleep 248
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 246
    Send("{g up}")
    Send("{5 up}")
    Send("{z up}")
    Sleep 0
    Send("{q down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 234
    Send("{q up}")
    Sleep 15
    Send("{q up}")
    Send("{d up}")
    Send("{z up}")
    Sleep 0
    Send("{v down}")
    Send("{r down}")
    Send("{x down}")
    Send("{z down}")
    Sleep 249
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 246
    Send("{v up}")
    Send("{r up}")
    Send("{x up}")
    Send("{z up}")
    Sleep 0
    Send("{c down}")
    Send("{e down}")
    Send("{c down}")
    Send("{z down}")
    Sleep 246
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 247
    Send("{c up}")
    Send("{e up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 2
    Send("{n down}")
    Send("{y down}")
    Send("{v down}")
    Send("{z down}")
    Sleep 264
    Send("{n up}")
    Send("{y up}")
    Send("{z up}")
    Sleep 0
    Send("{n down}")
    Send("{y down}")
    Send("{z down}")
    Sleep 248
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 246
    Send("{n up}")
    Send("{y up}")
    Send("{z up}")
    Sleep 0
    Send("{q down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 234
    Send("{q up}")
    Sleep 15
    Send("{q up}")
    Send("{v up}")
    Send("{z up}")
    Sleep 0
    Send("{b down}")
    Send("{t down}")
    Send("{c down}")
    Send("{z down}")
    Sleep 249
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 246
    Send("{b up}")
    Send("{t up}")
    Send("{z up}")
    Sleep 0
    Send("{q down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 246
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 247
    Send("{q up}")
    Send("{q up}")
    Send("{c up}")
    Send("{z up}")
    Sleep 2
    Send("{g down}")
    Send("{5 down}")
    Send("{d down}")
    Send("{z down}")
    Sleep 264
    Send("{g up}")
    Send("{5 up}")
    Send("{z up}")
    Sleep 0
    Send("{g down}")
    Send("{5 down}")
    Send("{z down}")
    Sleep 248
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 246
    Send("{g up}")
    Send("{5 up}")
    Send("{z up}")
    Sleep 0
    Send("{q down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 234
    Send("{q up}")
    Sleep 15
    Send("{q up}")
    Send("{d up}")
    Send("{z up}")
    Sleep 0
    Send("{v down}")
    Send("{r down}")
    Send("{x down}")
    Send("{z down}")
    Sleep 249
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 246
    Send("{v up}")
    Send("{r up}")
    Send("{x up}")
    Send("{z up}")
    Sleep 0
    Send("{c down}")
    Send("{e down}")
    Send("{z down}")
    Send("{z down}")
    Sleep 246
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 247
    Send("{c up}")
    Send("{e up}")
    Send("{z up}")
    Sleep 2
    Send("{v down}")
    Send("{n down}")
    Send("{q down}")
    Sleep 13
    Send("{z up}")
    Sleep 252
    Send("{r down}")
    Sleep 233
    Send("{r up}")
    Sleep 15
    Send("{e down}")
    Sleep 118
    Send("{e up}")
    Sleep 8
    Send("{w down}")
    Sleep 113
    Send("{w up}")
    Sleep 8
    Send("{q down}")
    Sleep 113
    Send("{q up}")
    Sleep 8
    Send("{7 down}")
    Sleep 120
    Send("{7 up}")
    Sleep 7
    Send("{v up}")
    Send("{n up}")
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Send("{v down}")
    Send("{q down}")
    Sleep 249
    Send("{r down}")
    Sleep 29
    Send("{q up}")
    Sleep 217
    Send("{r up}")
    Send("{v up}")
    Send("{q up}")
    Sleep 0
    Send("{r down}")
    Send("{g down}")
    Send("{q down}")
    Sleep 231
    Send("{r up}")
    Sleep 15
    Send("{w down}")
    Sleep 113
    Send("{w up}")
    Sleep 8
    Send("{5 down}")
    Sleep 79
    Send("{g up}")
    Send("{q up}")
    Sleep 40
    Send("{5 up}")
    Sleep 10
    Send("{t down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 143
    Send("{u down}")
    Sleep 7
    Send("{t up}")
    Sleep 100
    Send("{b up}")
    Sleep 15
    Send("{b up}")
    Sleep 0
    Send("{t down}")
    Send("{t down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 7
    Send("{u up}")
    Sleep 114
    Send("{b up}")
    Send("{m up}")
    Sleep 0
    Send("{u down}")
    Send("{b down}")
    Sleep 7
    Send("{t up}")
    Sleep 104
    Send("{t up}")
    Sleep 15
    Send("{b up}")
    Sleep 0
    Send("{5 down}")
    Send("{t down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 7
    Send("{u up}")
    Sleep 111
    Send("{5 up}")
    Sleep 7
    Send("{b up}")
    Send("{m up}")
    Sleep 0
    Send("{e down}")
    Send("{u down}")
    Send("{b down}")
    Sleep 7
    Send("{t up}")
    Sleep 106
    Send("{e up}")
    Sleep 7
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{t down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 7
    Send("{u up}")
    Sleep 106
    Send("{w up}")
    Sleep 7
    Send("{b up}")
    Send("{m up}")
    Sleep 0
    Send("{q down}")
    Send("{u down}")
    Send("{b down}")
    Sleep 7
    Send("{t up}")
    Sleep 113
    Send("{q up}")
    Sleep 8
    Send("{w down}")
    Send("{t down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 7
    Send("{u up}")
    Send("{b up}")
    Sleep 122
    Send("{u down}")
    Sleep 7
    Send("{t up}")
    Sleep 100
    Send("{m up}")
    Sleep 15
    Send("{m up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 7
    Send("{u up}")
    Sleep 23
    Send("{w up}")
    Sleep 93
    Send("{b up}")
    Send("{m up}")
    Sleep 0
    Send("{t down}")
    Send("{b down}")
    Sleep 7
    Send("{w up}")
    Sleep 120
    Send("{t up}")
    Send("{b up}")
    Sleep 1
    Send("{t down}")
    Send("{w down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 7
    Send("{t up}")
    Sleep 121
    Send("{b up}")
    Send("{m up}")
    Sleep 1
    Send("{t down}")
    Send("{b down}")
    Sleep 7
    Send("{w up}")
    Sleep 117
    Send("{t up}")
    Send("{b up}")
    Sleep 1
    Send("{w down}")
    Send("{t down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 30
    Send("{t up}")
    Sleep 94
    Send("{b up}")
    Send("{m up}")
    Sleep 1
    Send("{u down}")
    Send("{b down}")
    Sleep 7
    Send("{t up}")
    Sleep 87
    Send("{w up}")
    Sleep 40
    Send("{e down}")
    Send("{z down}")
    Send("{q down}")
    Sleep 5
    Send("{u up}")
    Send("{b up}")
    Sleep 143
    Send("{t down}")
    Sleep 7
    Send("{e up}")
    Sleep 100
    Send("{z up}")
    Sleep 15
    Send("{q up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Send("{b down}")
    Send("{q down}")
    Sleep 7
    Send("{t up}")
    Sleep 114
    Send("{b up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{b down}")
    Sleep 7
    Send("{e up}")
    Sleep 119
    Send("{b up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Send("{b down}")
    Send("{q down}")
    Sleep 7
    Send("{t up}")
    Sleep 22
    Send("{e up}")
    Sleep 96
    Send("{b up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{b down}")
    Sleep 7
    Send("{e up}")
    Sleep 77
    Send("{q up}")
    Sleep 37
    Send("{b up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Send("{b down}")
    Send("{q down}")
    Sleep 7
    Send("{t up}")
    Sleep 114
    Send("{b up}")
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{b down}")
    Sleep 7
    Send("{e up}")
    Sleep 106
    Send("{e up}")
    Sleep 15
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 7
    Send("{t up}")
    Sleep 122
    Send("{t down}")
    Sleep 7
    Send("{w up}")
    Sleep 99
    Send("{b up}")
    Sleep 15
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 7
    Send("{t up}")
    Sleep 114
    Send("{b up}")
    Send("{m up}")
    Sleep 0
    Send("{t down}")
    Send("{b down}")
    Sleep 7
    Send("{w up}")
    Sleep 118
    Send("{w up}")
    Send("{b up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 7
    Send("{t up}")
    Sleep 118
    Send("{b up}")
    Send("{m up}")
    Sleep 0
    Send("{t down}")
    Send("{b down}")
    Sleep 7
    Send("{w up}")
    Sleep 114
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 7
    Send("{t up}")
    Sleep 114
    Send("{b up}")
    Send("{m up}")
    Sleep 0
    Send("{t down}")
    Send("{b down}")
    Sleep 7
    Send("{w up}")
    Sleep 119
    Send("{t up}")
    Sleep 2
    Send("{w down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 5
    Send("{t up}")
    Send("{b up}")
    Sleep 138
    Send("{5 down}")
    Sleep 7
    Send("{w up}")
    Sleep 100
    Send("{n up}")
    Sleep 15
    Send("{n up}")
    Sleep 0
    Send("{q down}")
    Send("{w down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 7
    Send("{5 up}")
    Sleep 114
    Send("{n up}")
    Send("{w up}")
    Sleep 0
    Send("{5 down}")
    Send("{n down}")
    Sleep 7
    Send("{w up}")
    Sleep 104
    Send("{q up}")
    Sleep 15
    Send("{n up}")
    Sleep 0
    Send("{u down}")
    Send("{w down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 7
    Send("{5 up}")
    Sleep 111
    Send("{u up}")
    Sleep 7
    Send("{n up}")
    Send("{w up}")
    Sleep 0
    Send("{y down}")
    Send("{5 down}")
    Send("{n down}")
    Sleep 7
    Send("{w up}")
    Sleep 106
    Send("{y up}")
    Sleep 7
    Send("{n up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Send("{n down}")
    Send("{w down}")
    Sleep 7
    Send("{5 up}")
    Sleep 106
    Send("{t up}")
    Sleep 7
    Send("{n up}")
    Send("{w up}")
    Sleep 0
    Send("{5 down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 7
    Send("{w up}")
    Sleep 113
    Send("{5 up}")
    Sleep 8
    Send("{t down}")
    Send("{w down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 7
    Send("{q up}")
    Send("{n up}")
    Sleep 122
    Send("{t down}")
    Sleep 7
    Send("{w up}")
    Sleep 99
    Send("{m up}")
    Sleep 15
    Send("{m up}")
    Sleep 0
    Send("{u down}")
    Send("{w down}")
    Send("{m down}")
    Send("{w down}")
    Sleep 7
    Send("{t up}")
    Sleep 22
    Send("{t up}")
    Sleep 91
    Send("{m up}")
    Send("{w up}")
    Sleep 0
    Send("{t down}")
    Send("{m down}")
    Sleep 7
    Send("{w up}")
    Sleep 82
    Send("{u up}")
    Sleep 37
    Send("{m up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Send("{m down}")
    Send("{w down}")
    Sleep 7
    Send("{t up}")
    Sleep 118
    Send("{m up}")
    Send("{w up}")
    Sleep 0
    Send("{t down}")
    Send("{m down}")
    Sleep 7
    Send("{w up}")
    Sleep 114
    Send("{m up}")
    Sleep 0
    Send("{u down}")
    Send("{w down}")
    Send("{m down}")
    Send("{w down}")
    Sleep 7
    Send("{t up}")
    Sleep 22
    Send("{t up}")
    Sleep 91
    Send("{m up}")
    Send("{w up}")
    Sleep 0
    Send("{t down}")
    Send("{m down}")
    Sleep 7
    Send("{w up}")
    Sleep 83
    Send("{u up}")
    Sleep 39
    Send("{2 down}")
    Send("{s down}")
    Send("{s down}")
    Sleep 5
    Send("{t up}")
    Send("{m up}")
    Sleep 138
    Send("{e down}")
    Sleep 7
    Send("{2 up}")
    Sleep 100
    Send("{s up}")
    Sleep 15
    Send("{s up}")
    Sleep 0
    Send("{y down}")
    Send("{2 down}")
    Send("{s down}")
    Send("{c down}")
    Sleep 7
    Send("{e up}")
    Sleep 114
    Send("{s up}")
    Send("{c up}")
    Sleep 0
    Send("{e down}")
    Send("{s down}")
    Sleep 7
    Send("{2 up}")
    Sleep 104
    Send("{y up}")
    Sleep 15
    Send("{s up}")
    Sleep 0
    Send("{e down}")
    Send("{2 down}")
    Send("{s down}")
    Send("{c down}")
    Sleep 7
    Send("{e up}")
    Sleep 119
    Send("{s up}")
    Send("{c up}")
    Sleep 0
    Send("{e down}")
    Send("{s down}")
    Sleep 7
    Send("{2 up}")
    Sleep 99
    Send("{e up}")
    Sleep 15
    Send("{s up}")
    Sleep 0
    Send("{y down}")
    Send("{2 down}")
    Send("{s down}")
    Send("{c down}")
    Sleep 7
    Send("{e up}")
    Sleep 114
    Send("{s up}")
    Send("{c up}")
    Sleep 0
    Send("{e down}")
    Send("{s down}")
    Sleep 7
    Send("{2 up}")
    Sleep 106
    Send("{y up}")
    Sleep 15
    Send("{t down}")
    Send("{m down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 7
    Send("{e up}")
    Send("{s up}")
    Sleep 122
    Send("{w down}")
    Sleep 7
    Send("{m up}")
    Sleep 100
    Send("{x up}")
    Sleep 15
    Send("{x up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 7
    Send("{w up}")
    Sleep 115
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{w down}")
    Send("{x down}")
    Sleep 7
    Send("{m up}")
    Sleep 120
    Send("{t up}")
    Send("{x up}")
    Sleep 1
    Send("{5 down}")
    Send("{n down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 7
    Send("{w up}")
    Sleep 121
    Send("{x up}")
    Send("{g up}")
    Sleep 1
    Send("{w down}")
    Send("{x down}")
    Sleep 7
    Send("{n up}")
    Sleep 117
    Send("{x up}")
    Sleep 1
    Send("{n down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 7
    Send("{w up}")
    Sleep 118
    Send("{x up}")
    Send("{g up}")
    Sleep 1
    Send("{w down}")
    Send("{x down}")
    Sleep 7
    Send("{n up}")
    Sleep 124
    Send("{5 up}")
    Sleep 3
    Send("{b down}")
    Sleep 5
    Send("{w up}")
    Send("{x up}")
    Sleep 249
    Send("{b up}")
    Sleep 15
    Send("{u down}")
    Send("{t down}")
    Send("{b down}")
    Sleep 98
    Send("{b up}")
    Sleep 135
    Send("{u up}")
    Sleep 15
    Send("{t up}")
    Sleep 0
    Send("{y down}")
    Send("{5 down}")
    Send("{m down}")
    Sleep 118
    Send("{y up}")
    Send("{m up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{t down}")
    Send("{e down}")
    Send("{b down}")
    Sleep 45
    Send("{b up}")
    Sleep 68
    Send("{t up}")
    Sleep 7
    Send("{e up}")
    Sleep 0
    Send("{5 down}")
    Send("{w down}")
    Send("{b down}")
    Sleep 113
    Send("{5 up}")
    Sleep 7
    Send("{w up}")
    Sleep 0
    Send("{e down}")
    Send("{q down}")
    Sleep 113
    Send("{b up}")
    Sleep 7
    Send("{e up}")
    Sleep 7
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Send("{m down}")
    Sleep 234
    Send("{m up}")
    Sleep 15
    Send("{t up}")
    Send("{w up}")
    Sleep 0
    Send("{m down}")
    Send("{t down}")
    Send("{m down}")
    Sleep 96
    Send("{m up}")
    Sleep 150
    Send("{m up}")
    Send("{t up}")
    Sleep 0
    Send("{m down}")
    Send("{t down}")
    Send("{w down}")
    Sleep 118
    Send("{w up}")
    Sleep 8
    Send("{m down}")
    Sleep 45
    Send("{m up}")
    Sleep 75
    Send("{t up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Send("{m down}")
    Sleep 29
    Send("{m up}")
    Sleep 181
    Send("{t up}")
    Sleep 22
    Send("{m up}")
    Sleep 15
    Send("{w up}")
    Sleep 2
    Send("{z down}")
    Sleep 250
    Send("{z up}")
    Sleep 15
    Send("{q down}")
    Send("{e down}")
    Send("{q down}")
    Sleep 98
    Send("{q up}")
    Sleep 150
    Send("{q up}")
    Send("{e up}")
    Sleep 0
    Send("{t down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 118
    Send("{e up}")
    Sleep 8
    Send("{q down}")
    Sleep 45
    Send("{q up}")
    Sleep 39
    Send("{t up}")
    Sleep 37
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Send("{z down}")
    Sleep 234
    Send("{q up}")
    Send("{z up}")
    Sleep 15
    Send("{e up}")
    Sleep 0
    Send("{u down}")
    Send("{w down}")
    Send("{m down}")
    Sleep 234
    Send("{m up}")
    Sleep 15
    Send("{m down}")
    Sleep 96
    Send("{m up}")
    Sleep 150
    Send("{u up}")
    Send("{w up}")
    Sleep 0
    Send("{w down}")
    Send("{t down}")
    Send("{w down}")
    Sleep 118
    Send("{w up}")
    Sleep 8
    Send("{m down}")
    Sleep 45
    Send("{m up}")
    Sleep 76
    Send("{m down}")
    Sleep 232
    Send("{m up}")
    Sleep 15
    Send("{w up}")
    Send("{t up}")
    Sleep 2
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Sleep 15
    Send("{y down}")
    Send("{q down}")
    Send("{n down}")
    Sleep 98
    Send("{n up}")
    Sleep 135
    Send("{y up}")
    Sleep 15
    Send("{q up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Send("{q down}")
    Sleep 118
    Send("{t up}")
    Send("{q up}")
    Sleep 7
    Send("{u up}")
    Sleep 0
    Send("{5 down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 45
    Send("{n up}")
    Sleep 68
    Send("{5 up}")
    Sleep 7
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{n down}")
    Sleep 113
    Send("{e up}")
    Sleep 7
    Send("{t up}")
    Sleep 0
    Send("{q down}")
    Send("{5 down}")
    Sleep 113
    Send("{n up}")
    Sleep 7
    Send("{q up}")
    Sleep 7
    Send("{5 up}")
    Sleep 0
    Send("{w down}")
    Send("{t down}")
    Send("{m down}")
    Sleep 234
    Send("{m up}")
    Sleep 15
    Send("{t up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Send("{m down}")
    Sleep 29
    Send("{w up}")
    Sleep 67
    Send("{m up}")
    Sleep 150
    Send("{t up}")
    Send("{u up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Sleep 118
    Send("{w up}")
    Sleep 8
    Send("{m down}")
    Sleep 45
    Send("{m up}")
    Sleep 75
    Send("{t up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Send("{m down}")
    Sleep 210
    Send("{t up}")
    Sleep 22
    Send("{m up}")
    Sleep 15
    Send("{u up}")
    Sleep 2
    Send("{s down}")
    Sleep 250
    Send("{s up}")
    Sleep 15
    Send("{e down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 98
    Send("{n up}")
    Sleep 150
    Send("{e up}")
    Send("{y up}")
    Sleep 0
    Send("{2 down}")
    Send("{e down}")
    Send("{2 down}")
    Sleep 118
    Send("{2 up}")
    Sleep 8
    Send("{n down}")
    Sleep 45
    Send("{n up}")
    Sleep 61
    Send("{2 up}")
    Sleep 15
    Send("{e up}")
    Sleep 0
    Send("{e down}")
    Send("{y down}")
    Send("{s down}")
    Sleep 234
    Send("{e up}")
    Send("{s up}")
    Sleep 15
    Send("{y up}")
    Sleep 0
    Send("{w down}")
    Send("{t down}")
    Send("{x down}")
    Sleep 238
    Send("{x up}")
    Sleep 16
    Send("{n down}")
    Sleep 103
    Send("{n up}")
    Sleep 166
    Send("{w up}")
    Send("{t up}")
    Sleep 1
    Send("{w down}")
    Send("{5 down}")
    Send("{q down}")
    Sleep 135
    Send("{q up}")
    Sleep 9
    Send("{n down}")
    Sleep 53
    Send("{n up}")
    Sleep 91
    Send("{x down}")
    Sleep 292
    Send("{x up}")
    Sleep 19
    Send("{w up}")
    Send("{5 up}")
    Sleep 3
    Send("{m down}")
    Send("{w down}")
    Send("{t down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 2281
    Send("{m up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 284
    Send("{b up}")
    Send("{b up}")
}
