#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{y down}")
    Send("{v down}")
    Send("{n down}")
    Send("{q down}")
    Sleep 106
    Send("{y up}")
    Sleep 6
    Send("{r down}")
    Sleep 91
    Send("{r up}")
    Sleep 6
    Send("{t down}")
    Sleep 91
    Send("{t up}")
    Sleep 6
    Send("{y down}")
    Sleep 95
    Send("{y up}")
    Sleep 6
    Send("{u down}")
    Sleep 95
    Send("{u up}")
    Sleep 6
    Send("{t down}")
    Sleep 90
    Send("{t up}")
    Sleep 6
    Send("{y down}")
    Sleep 91
    Send("{y up}")
    Sleep 6
    Send("{u down}")
    Sleep 96
    Send("{u up}")
    Sleep 6
    Send("{v up}")
    Send("{n up}")
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Send("{w down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 96
    Send("{q up}")
    Sleep 6
    Send("{y down}")
    Sleep 90
    Send("{y up}")
    Sleep 6
    Send("{u down}")
    Sleep 91
    Send("{u up}")
    Sleep 6
    Send("{q down}")
    Sleep 94
    Send("{q up}")
    Sleep 6
    Send("{w up}")
    Sleep 0
    Send("{w down}")
    Send("{t down}")
    Sleep 94
    Send("{w up}")
    Sleep 6
    Send("{e down}")
    Sleep 91
    Send("{e up}")
    Sleep 6
    Send("{r down}")
    Sleep 91
    Send("{r up}")
    Sleep 6
    Send("{t down}")
    Sleep 95
    Send("{t up}")
    Sleep 6
    Send("{t up}")
    Send("{b up}")
    Send("{m up}")
    Sleep 2
    Send("{2 down}")
    Send("{e down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 91
    Send("{n up}")
    Sleep 8
    Send("{e up}")
    Sleep 12
    Send("{2 up}")
    Send("{y up}")
    Sleep 496
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{n down}")
    Sleep 67
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Send("{n up}")
    Sleep 320
    Send("{2 down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 65
    Send("{e up}")
    Sleep 12
    Send("{2 up}")
    Send("{y up}")
    Sleep 517
    Send("{n down}")
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 80
    Send("{w up}")
    Sleep 12
    Send("{n up}")
    Send("{r up}")
    Send("{n up}")
    Sleep 516
    Send("{v down}")
    Send("{n down}")
    Send("{w down}")
    Send("{n down}")
    Sleep 67
    Send("{n up}")
    Sleep 12
    Send("{v up}")
    Send("{w up}")
    Send("{n up}")
    Sleep 320
    Send("{q down}")
    Send("{r down}")
    Send("{y down}")
    Send("{v down}")
    Sleep 65
    Send("{r up}")
    Sleep 12
    Send("{q up}")
    Send("{y up}")
    Sleep 120
    Send("{b down}")
    Sleep 23
    Send("{v up}")
    Sleep 88
    Send("{b up}")
    Sleep 86
    Send("{h down}")
    Sleep 78
    Send("{h up}")
    Sleep 122
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{n down}")
    Sleep 80
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Send("{n up}")
    Sleep 516
    Send("{c down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{n down}")
    Sleep 67
    Send("{n up}")
    Sleep 12
    Send("{c up}")
    Send("{2 up}")
    Send("{n up}")
    Sleep 320
    Send("{2 down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 65
    Send("{e up}")
    Sleep 12
    Send("{2 up}")
    Send("{y up}")
    Sleep 318
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 66
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Sleep 122
    Send("{n down}")
    Send("{w down}")
    Send("{r down}")
    Send("{n down}")
    Sleep 91
    Send("{n up}")
    Sleep 120
    Send("{r up}")
    Sleep 0
    Send("{e down}")
    Sleep 23
    Send("{n up}")
    Send("{w up}")
    Sleep 89
    Send("{e up}")
    Sleep 86
    Send("{r down}")
    Sleep 77
    Send("{r up}")
    Sleep 120
    Send("{w down}")
    Send("{r down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 67
    Send("{r up}")
    Sleep 12
    Send("{w up}")
    Send("{y up}")
    Send("{n up}")
    Sleep 320
    Send("{r down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 65
    Send("{y up}")
    Sleep 12
    Send("{r up}")
    Send("{w up}")
    Sleep 318
    Send("{c down}")
    Sleep 78
    Send("{c up}")
    Sleep 122
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 80
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Sleep 319
    Send("{y down}")
    Sleep 197
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 67
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Sleep 120
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Sleep 396
    Send("{e up}")
    Sleep 0
    Send("{y down}")
    Sleep 395
    Send("{y up}")
    Sleep 2
    Send("{6 down}")
    Send("{h down}")
    Send("{n down}")
    Send("{m down}")
    Send("{e down}")
    Sleep 80
    Send("{n up}")
    Send("{m up}")
    Sleep 12
    Send("{h up}")
    Send("{e up}")
    Sleep 516
    Send("{6 up}")
    Sleep 0
    Send("{e down}")
    Send("{h down}")
    Send("{n down}")
    Send("{m down}")
    Send("{e down}")
    Sleep 67
    Send("{n up}")
    Send("{m up}")
    Sleep 12
    Send("{h up}")
    Send("{e up}")
    Sleep 320
    Send("{n down}")
    Sleep 77
    Send("{n up}")
    Sleep 120
    Send("{e up}")
    Sleep 0
    Send("{6 down}")
    Sleep 395
    Send("{6 up}")
    Sleep 2
    Send("{5 down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 91
    Send("{n up}")
    Send("{5 up}")
    Sleep 12
    Send("{w up}")
    Sleep 504
    Send("{5 up}")
    Sleep 0
    Send("{w down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 79
    Send("{n up}")
    Send("{5 up}")
    Sleep 12
    Send("{w up}")
    Sleep 504
    Send("{w up}")
    Sleep 0
    Send("{5 down}")
    Sleep 395
    Send("{5 up}")
    Sleep 2
    Send("{e down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 80
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Sleep 516
    Send("{e up}")
    Sleep 0
    Send("{y down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 67
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Sleep 320
    Send("{n down}")
    Sleep 77
    Send("{n up}")
    Sleep 318
    Send("{h down}")
    Sleep 78
    Send("{h up}")
    Sleep 120
    Send("{y up}")
    Sleep 2
    Send("{b down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 80
    Send("{n up}")
    Send("{2 up}")
    Sleep 12
    Send("{b up}")
    Send("{e up}")
    Sleep 319
    Send("{y down}")
    Sleep 197
    Send("{b down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 67
    Send("{n up}")
    Send("{2 up}")
    Sleep 12
    Send("{b up}")
    Send("{e up}")
    Sleep 120
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Sleep 396
    Send("{e up}")
    Sleep 0
    Send("{y down}")
    Sleep 395
    Send("{y up}")
    Sleep 2
    Send("{u down}")
    Send("{b down}")
    Send("{m down}")
    Send("{w down}")
    Sleep 91
    Send("{b up}")
    Send("{w up}")
    Sleep 12
    Send("{m up}")
    Sleep 306
    Send("{u up}")
    Sleep 0
    Send("{y down}")
    Sleep 185
    Send("{y up}")
    Sleep 12
    Send("{t down}")
    Send("{b down}")
    Send("{m down}")
    Send("{w down}")
    Sleep 79
    Send("{b up}")
    Send("{w up}")
    Sleep 12
    Send("{m up}")
    Sleep 96
    Send("{t up}")
    Sleep 212
    Send("{w down}")
    Sleep 608
    Send("{w up}")
    Sleep 2
    Send("{2 down}")
    Send("{b down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 95
    Send("{b up}")
    Send("{e up}")
    Sleep 12
    Send("{n up}")
    Send("{2 up}")
    Sleep 306
    Send("{2 up}")
    Sleep 198
    Send("{y down}")
    Send("{b down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 79
    Send("{b up}")
    Send("{e up}")
    Sleep 12
    Send("{n up}")
    Send("{2 up}")
    Sleep 900
    Send("{y up}")
    Sleep 2
    Send("{y down}")
    Send("{b down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 80
    Send("{n up}")
    Send("{2 up}")
    Sleep 12
    Send("{b up}")
    Send("{e up}")
    Sleep 70
    Send("{y up}")
    Sleep 50
    Send("{y down}")
    Send("{2 down}")
    Sleep 136
    Send("{y up}")
    Sleep 12
    Send("{2 up}")
    Sleep 248
    Send("{2 down}")
    Send("{e down}")
    Send("{b down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 67
    Send("{n up}")
    Send("{2 up}")
    Sleep 12
    Send("{b up}")
    Send("{e up}")
    Sleep 58
    Send("{2 up}")
    Sleep 12
    Send("{e up}")
    Sleep 250
    Send("{e down}")
    Send("{y down}")
    Send("{b down}")
    Sleep 77
    Send("{b up}")
    Sleep 318
    Send("{h down}")
    Sleep 78
    Send("{h up}")
    Sleep 120
    Send("{e up}")
    Send("{y up}")
    Sleep 2
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 80
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Sleep 319
    Send("{y down}")
    Sleep 197
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 67
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Sleep 120
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Sleep 396
    Send("{e up}")
    Sleep 0
    Send("{y down}")
    Sleep 395
    Send("{y up}")
    Sleep 2
    Send("{6 down}")
    Send("{h down}")
    Send("{n down}")
    Send("{m down}")
    Send("{e down}")
    Sleep 80
    Send("{n up}")
    Send("{m up}")
    Sleep 12
    Send("{h up}")
    Send("{e up}")
    Sleep 516
    Send("{6 up}")
    Sleep 0
    Send("{e down}")
    Send("{h down}")
    Send("{n down}")
    Send("{m down}")
    Send("{e down}")
    Sleep 67
    Send("{n up}")
    Send("{m up}")
    Sleep 12
    Send("{h up}")
    Send("{e up}")
    Sleep 320
    Send("{n down}")
    Sleep 77
    Send("{n up}")
    Sleep 120
    Send("{e up}")
    Sleep 0
    Send("{6 down}")
    Sleep 395
    Send("{6 up}")
    Sleep 2
    Send("{5 down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 91
    Send("{n up}")
    Send("{5 up}")
    Sleep 12
    Send("{w up}")
    Sleep 504
    Send("{5 up}")
    Sleep 0
    Send("{w down}")
    Send("{n down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 79
    Send("{n up}")
    Send("{5 up}")
    Sleep 12
    Send("{w up}")
    Sleep 504
    Send("{w up}")
    Sleep 0
    Send("{5 down}")
    Sleep 395
    Send("{5 up}")
    Sleep 2
    Send("{e down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 80
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Sleep 516
    Send("{e up}")
    Sleep 0
    Send("{y down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 67
    Send("{2 up}")
    Sleep 12
    Send("{n up}")
    Send("{e up}")
    Sleep 320
    Send("{n down}")
    Sleep 77
    Send("{n up}")
    Sleep 318
    Send("{b down}")
    Sleep 78
    Send("{b up}")
    Sleep 120
    Send("{y up}")
    Sleep 2
    Send("{v down}")
    Send("{n down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 80
    Send("{n up}")
    Send("{q up}")
    Sleep 12
    Send("{v up}")
    Send("{e up}")
    Sleep 319
    Send("{y down}")
    Sleep 197
    Send("{v down}")
    Send("{n down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 67
    Send("{n up}")
    Send("{q up}")
    Sleep 12
    Send("{v up}")
    Send("{e up}")
    Sleep 120
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Sleep 396
    Send("{e up}")
    Sleep 0
    Send("{y down}")
    Sleep 395
    Send("{y up}")
    Sleep 2
    Send("{u down}")
    Send("{b down}")
    Send("{m down}")
    Send("{w down}")
    Sleep 91
    Send("{b up}")
    Send("{w up}")
    Sleep 12
    Send("{m up}")
    Sleep 306
    Send("{u up}")
    Sleep 0
    Send("{y down}")
    Sleep 185
    Send("{y up}")
    Sleep 12
    Send("{t down}")
    Send("{b down}")
    Send("{m down}")
    Send("{w down}")
    Sleep 79
    Send("{b up}")
    Send("{w up}")
    Sleep 12
    Send("{m up}")
    Sleep 96
    Send("{t up}")
    Sleep 211
    Send("{w down}")
    Send("{b down}")
    Sleep 77
    Send("{b up}")
    Sleep 515
    Send("{w up}")
    Sleep 2
    Send("{2 down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 91
    Send("{n up}")
    Send("{e up}")
    Sleep 12
    Send("{2 up}")
    Sleep 306
    Send("{2 up}")
    Sleep 198
    Send("{y down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 79
    Send("{n up}")
    Send("{e up}")
    Sleep 12
    Send("{2 up}")
    Sleep 916
    Send("{y up}")
    Sleep 2
    Send("{y down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 95
    Send("{n up}")
    Send("{e up}")
    Sleep 12
    Send("{2 up}")
    Sleep 58
    Send("{y up}")
    Sleep 50
    Send("{y down}")
    Send("{2 down}")
    Sleep 136
    Send("{y up}")
    Sleep 12
    Send("{2 up}")
    Sleep 248
    Send("{2 down}")
    Send("{e down}")
    Send("{n down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 79
    Send("{n up}")
    Send("{e up}")
    Sleep 12
    Send("{2 up}")
    Sleep 46
    Send("{2 up}")
    Sleep 12
    Send("{e up}")
    Sleep 250
    Send("{e down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 77
    Send("{n up}")
    Sleep 318
    Send("{n down}")
    Sleep 78
    Send("{n up}")
    Sleep 120
    Send("{e up}")
    Send("{y up}")
    Sleep 2
    Send("{j down}")
    Send("{j down}")
    Sleep 410
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 396
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 396
    Send("{w up}")
    Send("{r up}")
    Send("{7 up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 395
    Send("{7 up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 2
    Send("{t down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 100
    Send("{q up}")
    Sleep 12
    Send("{t up}")
    Send("{e up}")
    Sleep 100
    Send("{e down}")
    Send("{t down}")
    Send("{q down}")
    Sleep 86
    Send("{t up}")
    Sleep 12
    Send("{e up}")
    Send("{q up}")
    Sleep 100
    Send("{r down}")
    Send("{7 down}")
    Send("{w down}")
    Sleep 197
    Send("{j up}")
    Send("{j up}")
    Sleep 0
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 0
    Send("{v down}")
    Sleep 102
    Send("{j down}")
    Sleep 5
    Send("{v up}")
    Sleep 182
    Send("{j up}")
    Sleep 12
    Send("{v down}")
    Sleep 188
    Send("{v up}")
    Sleep 12
    Send("{j down}")
    Sleep 190
    Send("{j up}")
    Sleep 12
    Send("{v down}")
    Sleep 193
    Send("{v up}")
    Sleep 12
    Send("{r up}")
    Send("{7 up}")
    Send("{w up}")
    Sleep 2
    Send("{j down}")
    Send("{j down}")
    Sleep 414
    Send("{j down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 396
    Send("{j up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{7 down}")
    Sleep 396
    Send("{w up}")
    Send("{r up}")
    Send("{7 up}")
    Sleep 0
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 395
    Send("{7 up}")
    Send("{w up}")
    Send("{r up}")
    Sleep 2
    Send("{t down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 100
    Send("{q up}")
    Sleep 12
    Send("{t up}")
    Send("{e up}")
    Sleep 100
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Sleep 86
    Send("{w up}")
    Sleep 12
    Send("{7 up}")
    Send("{r up}")
    Sleep 100
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 197
    Send("{j up}")
    Send("{j up}")
    Sleep 0
    Send("{v down}")
    Sleep 96
    Send("{v up}")
    Sleep 0
    Send("{v down}")
    Sleep 102
    Send("{j down}")
    Sleep 5
    Send("{v up}")
    Sleep 182
    Send("{j up}")
    Sleep 12
    Send("{v down}")
    Sleep 187
    Send("{v up}")
    Sleep 12
    Send("{j down}")
    Sleep 187
    Send("{j up}")
    Sleep 12
    Send("{v down}")
    Sleep 189
    Send("{v up}")
    Sleep 12
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 2
    Send("{z down}")
    Send("{z down}")
    Sleep 410
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 396
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{q down}")
    Sleep 396
    Send("{e up}")
    Send("{t up}")
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Sleep 395
    Send("{q up}")
    Send("{e up}")
    Send("{t up}")
    Sleep 2
    Send("{y down}")
    Send("{w down}")
    Send("{5 down}")
    Sleep 100
    Send("{w up}")
    Sleep 12
    Send("{y up}")
    Send("{5 up}")
    Sleep 100
    Send("{5 down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 86
    Send("{y up}")
    Sleep 12
    Send("{5 up}")
    Send("{w up}")
    Sleep 100
    Send("{t down}")
    Send("{q down}")
    Send("{e down}")
    Sleep 197
    Send("{z up}")
    Send("{z up}")
    Sleep 0
    Send("{b down}")
    Sleep 96
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 102
    Send("{z down}")
    Sleep 5
    Send("{b up}")
    Sleep 182
    Send("{z up}")
    Sleep 12
    Send("{b down}")
    Sleep 187
    Send("{b up}")
    Sleep 12
    Send("{z down}")
    Sleep 187
    Send("{z up}")
    Sleep 12
    Send("{b down}")
    Sleep 189
    Send("{b up}")
    Sleep 12
    Send("{t up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 2
    Send("{x down}")
    Send("{x down}")
    Sleep 410
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Sleep 396
    Send("{w up}")
    Send("{5 up}")
    Send("{y up}")
    Sleep 0
    Send("{5 down}")
    Send("{y down}")
    Send("{w down}")
    Sleep 396
    Send("{5 up}")
    Send("{y up}")
    Send("{w up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Sleep 395
    Send("{w up}")
    Send("{5 up}")
    Send("{y up}")
    Send("{x up}")
    Send("{x up}")
    Sleep 2
    Send("{u down}")
    Send("{e down}")
    Send("{6 down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 100
    Send("{e up}")
    Sleep 12
    Send("{u up}")
    Send("{6 up}")
    Sleep 100
    Send("{w down}")
    Send("{5 down}")
    Send("{y down}")
    Sleep 86
    Send("{5 up}")
    Sleep 12
    Send("{w up}")
    Send("{y up}")
    Sleep 100
    Send("{e down}")
    Send("{6 down}")
    Send("{u down}")
    Sleep 197
    Send("{c up}")
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Send("{c down}")
    Sleep 399
    Send("{c up}")
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Send("{c down}")
    Sleep 200
    Send("{c up}")
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Send("{c down}")
    Sleep 407
    Send("{e up}")
    Send("{6 up}")
    Send("{u up}")
    Send("{c up}")
    Send("{c up}")
    Sleep 2
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{n down}")
    Sleep 83
    Send("{2 up}")
    Sleep 12
    Send("{y up}")
    Send("{e up}")
    Sleep 120
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 198
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 197
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{n down}")
    Sleep 67
    Send("{y up}")
    Sleep 12
    Send("{e up}")
    Send("{2 up}")
    Sleep 120
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 199
    Send("{n up}")
    Sleep 0
    Send("{2 down}")
    Send("{e down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 65
    Send("{e up}")
    Sleep 12
    Send("{2 up}")
    Send("{y up}")
    Sleep 120
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 197
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 200
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Send("{j down}")
    Sleep 10
    Send("{n up}")
    Sleep 70
    Send("{w up}")
    Sleep 12
    Send("{7 up}")
    Send("{r up}")
    Sleep 120
    Send("{j up}")
    Sleep 0
    Send("{j down}")
    Sleep 198
    Send("{j up}")
    Sleep 0
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 0
    Send("{r down}")
    Send("{7 down}")
    Send("{w down}")
    Send("{j down}")
    Sleep 67
    Send("{7 up}")
    Sleep 12
    Send("{r up}")
    Send("{w up}")
    Sleep 120
    Send("{j up}")
    Sleep 0
    Send("{j down}")
    Sleep 199
    Send("{j up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{7 down}")
    Send("{j down}")
    Sleep 65
    Send("{r up}")
    Sleep 12
    Send("{w up}")
    Send("{7 up}")
    Sleep 120
    Send("{j up}")
    Sleep 0
    Send("{j down}")
    Sleep 197
    Send("{j up}")
    Sleep 0
    Send("{j down}")
    Sleep 200
    Send("{u down}")
    Send("{3 down}")
    Send("{5 down}")
    Send("{m down}")
    Sleep 10
    Send("{j up}")
    Sleep 70
    Send("{3 up}")
    Sleep 12
    Send("{u up}")
    Send("{5 up}")
    Sleep 120
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Sleep 198
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 0
    Send("{5 down}")
    Send("{u down}")
    Send("{3 down}")
    Send("{m down}")
    Sleep 67
    Send("{u up}")
    Sleep 12
    Send("{5 up}")
    Send("{3 up}")
    Sleep 120
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Sleep 199
    Send("{m up}")
    Sleep 0
    Send("{3 down}")
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Sleep 65
    Send("{5 up}")
    Sleep 12
    Send("{3 up}")
    Send("{u up}")
    Sleep 120
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Sleep 197
    Send("{m up}")
    Sleep 0
    Send("{u down}")
    Send("{3 down}")
    Send("{5 down}")
    Send("{m down}")
    Sleep 66
    Send("{3 up}")
    Sleep 12
    Send("{u up}")
    Send("{5 up}")
    Sleep 122
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 10
    Send("{m up}")
    Sleep 201
    Send("{t up}")
    Send("{z up}")
    Sleep 0
    Send("{5 down}")
    Send("{z down}")
    Sleep 23
    Send("{q up}")
    Send("{e up}")
    Sleep 87
    Send("{5 up}")
    Sleep 84
    Send("{z up}")
    Sleep 0
    Send("{t down}")
    Send("{z down}")
    Sleep 75
    Send("{t up}")
    Sleep 115
    Send("{z up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 65
    Send("{t up}")
    Sleep 11
    Send("{e up}")
    Send("{q up}")
    Sleep 113
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 185
    Send("{z up}")
    Sleep 0
    Send("{q down}")
    Send("{z down}")
    Sleep 71
    Send("{q up}")
    Sleep 109
    Send("{z up}")
    Sleep 0
    Send("{w down}")
    Send("{z down}")
    Sleep 70
    Send("{w up}")
    Sleep 108
    Send("{z up}")
    Sleep 0
    Send("{e down}")
    Send("{z down}")
    Sleep 69
    Send("{e up}")
    Sleep 108
    Send("{6 down}")
    Send("{2 down}")
    Send("{r down}")
    Send("{s down}")
    Sleep 9
    Send("{z up}")
    Sleep 61
    Send("{2 up}")
    Sleep 10
    Send("{6 up}")
    Send("{r up}")
    Sleep 105
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Sleep 173
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Sleep 172
    Send("{s up}")
    Sleep 0
    Send("{r down}")
    Send("{6 down}")
    Send("{2 down}")
    Send("{s down}")
    Sleep 59
    Send("{6 up}")
    Sleep 10
    Send("{r up}")
    Send("{2 up}")
    Sleep 105
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Sleep 173
    Send("{s up}")
    Sleep 0
    Send("{2 down}")
    Send("{r down}")
    Send("{6 down}")
    Send("{s down}")
    Sleep 57
    Send("{r up}")
    Sleep 10
    Send("{2 up}")
    Send("{6 up}")
    Sleep 105
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Sleep 172
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Sleep 174
    Send("{y down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 9
    Send("{s up}")
    Sleep 61
    Send("{w up}")
    Sleep 10
    Send("{y up}")
    Send("{5 up}")
    Sleep 105
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 173
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 172
    Send("{x up}")
    Sleep 0
    Send("{5 down}")
    Send("{y down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 59
    Send("{y up}")
    Sleep 10
    Send("{5 up}")
    Send("{w up}")
    Sleep 105
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 173
    Send("{x up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 57
    Send("{w up}")
    Sleep 10
    Send("{y up}")
    Send("{5 up}")
    Sleep 105
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 172
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 174
    Send("{7 down}")
    Send("{3 down}")
    Send("{t down}")
    Send("{d down}")
    Sleep 9
    Send("{x up}")
    Sleep 61
    Send("{3 up}")
    Sleep 10
    Send("{7 up}")
    Send("{t up}")
    Sleep 105
    Send("{d up}")
    Sleep 0
    Send("{d down}")
    Sleep 173
    Send("{d up}")
    Sleep 0
    Send("{d down}")
    Sleep 172
    Send("{d up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{3 down}")
    Send("{d down}")
    Sleep 59
    Send("{7 up}")
    Sleep 10
    Send("{t up}")
    Send("{3 up}")
    Sleep 105
    Send("{d up}")
    Sleep 0
    Send("{d down}")
    Sleep 173
    Send("{d up}")
    Sleep 0
    Send("{3 down}")
    Send("{t down}")
    Send("{7 down}")
    Send("{d down}")
    Sleep 57
    Send("{t up}")
    Sleep 10
    Send("{3 up}")
    Send("{7 up}")
    Sleep 105
    Send("{d up}")
    Sleep 0
    Send("{d down}")
    Sleep 172
    Send("{d up}")
    Sleep 0
    Send("{7 down}")
    Send("{3 down}")
    Send("{t down}")
    Send("{d down}")
    Sleep 58
    Send("{3 up}")
    Sleep 10
    Send("{7 up}")
    Send("{t up}")
    Sleep 106
    Send("{u down}")
    Send("{e down}")
    Send("{6 down}")
    Send("{c down}")
    Sleep 9
    Send("{d up}")
    Sleep 175
    Send("{6 up}")
    Send("{c up}")
    Sleep 0
    Send("{t down}")
    Send("{c down}")
    Sleep 20
    Send("{u up}")
    Send("{e up}")
    Sleep 76
    Send("{t up}")
    Sleep 73
    Send("{c up}")
    Sleep 0
    Send("{6 down}")
    Send("{c down}")
    Sleep 65
    Send("{6 up}")
    Sleep 100
    Send("{c up}")
    Sleep 0
    Send("{6 down}")
    Send("{u down}")
    Send("{e down}")
    Send("{c down}")
    Sleep 56
    Send("{u up}")
    Sleep 10
    Send("{6 up}")
    Send("{e up}")
    Sleep 98
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 160
    Send("{c up}")
    Sleep 0
    Send("{u down}")
    Send("{c down}")
    Sleep 61
    Send("{u up}")
    Sleep 94
    Send("{c up}")
    Sleep 0
    Send("{2 down}")
    Send("{c down}")
    Sleep 60
    Send("{2 up}")
    Sleep 93
    Send("{c up}")
    Sleep 0
    Send("{3 down}")
    Send("{c down}")
    Sleep 59
    Send("{3 up}")
    Sleep 93
    Send("{y down}")
    Send("{2 down}")
    Send("{e down}")
    Send("{n down}")
    Sleep 8
    Send("{c up}")
    Sleep 52
    Send("{2 up}")
    Sleep 9
    Send("{y up}")
    Send("{e up}")
    Sleep 90
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 149
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 148
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{y down}")
    Send("{2 down}")
    Send("{n down}")
    Sleep 50
    Send("{y up}")
    Sleep 9
    Send("{e up}")
    Send("{2 up}")
    Sleep 90
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 149
    Send("{n up}")
    Sleep 0
    Send("{2 down}")
    Send("{e down}")
    Send("{y down}")
    Send("{n down}")
    Sleep 49
    Send("{e up}")
    Sleep 9
    Send("{2 up}")
    Send("{y up}")
    Sleep 90
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 148
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 150
    Send("{7 down}")
    Send("{w down}")
    Send("{r down}")
    Send("{j down}")
    Sleep 8
    Send("{n up}")
    Sleep 52
    Send("{w up}")
    Sleep 9
    Send("{7 up}")
    Send("{r up}")
    Sleep 90
    Send("{j up}")
    Sleep 0
    Send("{j down}")
    Sleep 149
    Send("{j up}")
    Sleep 0
    Send("{j down}")
    Sleep 148
    Send("{j up}")
    Sleep 0
    Send("{r down}")
    Send("{7 down}")
    Send("{w down}")
    Send("{j down}")
    Sleep 50
    Send("{7 up}")
    Sleep 9
    Send("{r up}")
    Send("{w up}")
    Sleep 90
    Send("{j up}")
    Sleep 0
    Send("{j down}")
    Sleep 149
    Send("{j up}")
    Sleep 0
    Send("{w down}")
    Send("{r down}")
    Send("{7 down}")
    Send("{j down}")
    Sleep 49
    Send("{r up}")
    Sleep 9
    Send("{w up}")
    Send("{7 up}")
    Sleep 90
    Send("{j up}")
    Sleep 0
    Send("{j down}")
    Sleep 148
    Send("{j up}")
    Sleep 0
    Send("{j down}")
    Sleep 150
    Send("{u down}")
    Send("{3 down}")
    Send("{5 down}")
    Send("{m down}")
    Sleep 8
    Send("{j up}")
    Sleep 52
    Send("{3 up}")
    Sleep 9
    Send("{u up}")
    Send("{5 up}")
    Sleep 90
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Sleep 148
    Send("{m up}")
    Sleep 0
    Send("{5 down}")
    Send("{u down}")
    Send("{3 down}")
    Send("{m down}")
    Sleep 50
    Send("{u up}")
    Sleep 9
    Send("{5 up}")
    Send("{3 up}")
    Sleep 90
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Sleep 149
    Send("{m up}")
    Sleep 0
    Send("{3 down}")
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Sleep 49
    Send("{5 up}")
    Sleep 9
    Send("{3 up}")
    Send("{u up}")
    Sleep 90
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Sleep 148
    Send("{m up}")
    Sleep 0
    Send("{u down}")
    Send("{3 down}")
    Send("{5 down}")
    Send("{m down}")
    Sleep 50
    Send("{3 up}")
    Sleep 9
    Send("{u up}")
    Send("{5 up}")
    Sleep 91
    Send("{q down}")
    Send("{e down}")
    Send("{t down}")
    Send("{z down}")
    Sleep 8
    Send("{m up}")
    Sleep 151
    Send("{t up}")
    Send("{z up}")
    Sleep 0
    Send("{5 down}")
    Send("{z down}")
    Sleep 18
    Send("{q up}")
    Send("{e up}")
    Sleep 66
    Send("{5 up}")
    Sleep 64
    Send("{z up}")
    Sleep 0
    Send("{t down}")
    Send("{z down}")
    Sleep 57
    Send("{t up}")
    Sleep 89
    Send("{z up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Send("{q down}")
    Send("{z down}")
    Sleep 50
    Send("{t up}")
    Sleep 9
    Send("{e up}")
    Send("{q up}")
    Sleep 89
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 146
    Send("{z up}")
    Sleep 0
    Send("{q down}")
    Send("{z down}")
    Sleep 56
    Send("{q up}")
    Sleep 88
    Send("{z up}")
    Sleep 0
    Send("{w down}")
    Send("{z down}")
    Sleep 56
    Send("{w up}")
    Sleep 87
    Send("{z up}")
    Sleep 0
    Send("{e down}")
    Send("{z down}")
    Sleep 56
    Send("{e up}")
    Sleep 88
    Send("{6 down}")
    Send("{2 down}")
    Send("{r down}")
    Send("{s down}")
    Sleep 7
    Send("{z up}")
    Sleep 50
    Send("{2 up}")
    Sleep 8
    Send("{6 up}")
    Send("{r up}")
    Sleep 87
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Sleep 143
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Sleep 142
    Send("{s up}")
    Sleep 0
    Send("{r down}")
    Send("{6 down}")
    Send("{2 down}")
    Send("{s down}")
    Sleep 48
    Send("{6 up}")
    Sleep 8
    Send("{r up}")
    Send("{2 up}")
    Sleep 87
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Sleep 143
    Send("{s up}")
    Sleep 0
    Send("{2 down}")
    Send("{r down}")
    Send("{6 down}")
    Send("{s down}")
    Sleep 47
    Send("{r up}")
    Sleep 8
    Send("{2 up}")
    Send("{6 up}")
    Sleep 87
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Sleep 142
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Sleep 144
    Send("{y down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 7
    Send("{s up}")
    Sleep 50
    Send("{w up}")
    Sleep 8
    Send("{y up}")
    Send("{5 up}")
    Sleep 87
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 143
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 142
    Send("{x up}")
    Sleep 0
    Send("{5 down}")
    Send("{y down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 48
    Send("{y up}")
    Sleep 8
    Send("{5 up}")
    Send("{w up}")
    Sleep 87
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 143
    Send("{x up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 47
    Send("{w up}")
    Sleep 8
    Send("{y up}")
    Send("{5 up}")
    Sleep 87
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 142
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Sleep 144
    Send("{7 down}")
    Send("{3 down}")
    Send("{t down}")
    Send("{d down}")
    Sleep 7
    Send("{x up}")
    Sleep 50
    Send("{3 up}")
    Sleep 8
    Send("{7 up}")
    Send("{t up}")
    Sleep 87
    Send("{d up}")
    Sleep 0
    Send("{d down}")
    Sleep 143
    Send("{d up}")
    Sleep 0
    Send("{d down}")
    Sleep 142
    Send("{d up}")
    Sleep 0
    Send("{t down}")
    Send("{7 down}")
    Send("{3 down}")
    Send("{d down}")
    Sleep 48
    Send("{7 up}")
    Sleep 8
    Send("{t up}")
    Send("{3 up}")
    Sleep 87
    Send("{d up}")
    Sleep 0
    Send("{d down}")
    Sleep 143
    Send("{d up}")
    Sleep 0
    Send("{3 down}")
    Send("{t down}")
    Send("{7 down}")
    Send("{d down}")
    Sleep 47
    Send("{t up}")
    Sleep 8
    Send("{3 up}")
    Send("{7 up}")
    Sleep 87
    Send("{d up}")
    Sleep 0
    Send("{d down}")
    Sleep 142
    Send("{d up}")
    Sleep 0
    Send("{7 down}")
    Send("{3 down}")
    Send("{t down}")
    Send("{d down}")
    Sleep 48
    Send("{3 up}")
    Sleep 8
    Send("{7 up}")
    Send("{t up}")
    Sleep 88
    Send("{u down}")
    Send("{e down}")
    Send("{6 down}")
    Send("{c down}")
    Sleep 7
    Send("{d up}")
    Sleep 145
    Send("{6 up}")
    Send("{c up}")
    Sleep 0
    Send("{t down}")
    Send("{c down}")
    Sleep 17
    Send("{u up}")
    Send("{e up}")
    Sleep 64
    Send("{t up}")
    Sleep 62
    Send("{c up}")
    Sleep 0
    Send("{6 down}")
    Send("{c down}")
    Sleep 56
    Send("{6 up}")
    Sleep 87
    Send("{c up}")
    Sleep 0
    Send("{6 down}")
    Send("{u down}")
    Send("{e down}")
    Send("{c down}")
    Sleep 48
    Send("{u up}")
    Send("{e up}")
    Sleep 8
    Send("{6 up}")
    Sleep 95
    Send("{c up}")
}
