#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{m down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 146
    Send("{e down}")
    Sleep 8
    Send("{m up}")
    Sleep 127
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{u down}")
    Sleep 8
    Send("{5 up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{u up}")
    Sleep 126
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{u down}")
    Sleep 8
    Send("{5 up}")
    Sleep 131
    Send("{5 down}")
    Sleep 8
    Send("{u up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{5 up}")
    Sleep 130
    Send("{u down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{5 down}")
    Sleep 8
    Send("{u up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{5 up}")
    Sleep 131
    Send("{m down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{e down}")
    Sleep 8
    Send("{m up}")
    Sleep 127
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{u down}")
    Sleep 8
    Send("{5 up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{u up}")
    Sleep 126
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{u down}")
    Sleep 8
    Send("{5 up}")
    Sleep 131
    Send("{5 down}")
    Sleep 8
    Send("{u up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{5 up}")
    Sleep 130
    Send("{u down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{5 down}")
    Sleep 8
    Send("{u up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{5 up}")
    Sleep 130
    Send("{c up}")
    Send("{c up}")
    Sleep 1
    Send("{m down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{e down}")
    Sleep 8
    Send("{m up}")
    Sleep 127
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{u down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{u up}")
    Sleep 126
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{u down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{u up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{u down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{u up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{m down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{e down}")
    Sleep 8
    Send("{m up}")
    Sleep 127
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{u down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{u up}")
    Sleep 126
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{u down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{u up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{u down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{u up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{m down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{e down}")
    Sleep 8
    Send("{m up}")
    Send("{c up}")
    Send("{c up}")
    Sleep 127
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{u down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{5 up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{u up}")
    Send("{c up}")
    Send("{c up}")
    Sleep 126
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{u down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{5 up}")
    Sleep 131
    Send("{5 down}")
    Sleep 8
    Send("{u up}")
    Send("{c up}")
    Send("{c up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{5 up}")
    Sleep 130
    Send("{u down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{5 down}")
    Sleep 8
    Send("{u up}")
    Send("{c up}")
    Send("{c up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{5 up}")
    Sleep 131
    Send("{m down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{e down}")
    Sleep 8
    Send("{m up}")
    Send("{c up}")
    Send("{c up}")
    Sleep 127
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{u down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{5 up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{u up}")
    Send("{c up}")
    Send("{c up}")
    Sleep 126
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{u down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{5 up}")
    Sleep 131
    Send("{5 down}")
    Sleep 8
    Send("{u up}")
    Send("{c up}")
    Send("{c up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{5 up}")
    Sleep 130
    Send("{u down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{e up}")
    Sleep 129
    Send("{c up}")
    Sleep 0
    Send("{5 down}")
    Sleep 8
    Send("{u up}")
    Send("{c up}")
    Sleep 127
    Send("{e down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{5 up}")
    Sleep 130
    Send("{c up}")
    Sleep 1
    Send("{m down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 7
    Send("{e up}")
    Send("{c up}")
    Sleep 140
    Send("{e down}")
    Sleep 8
    Send("{m up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 127
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{u down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{u up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 126
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{u down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{u up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{u down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{u up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{m down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{e down}")
    Sleep 8
    Send("{m up}")
    Send("{b up}")
    Send("{b up}")
    Sleep 127
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{u up}")
    Send("{b up}")
    Send("{b up}")
    Sleep 126
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{y down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 8
    Send("{u up}")
    Sleep 126
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{e down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 8
    Send("{y up}")
    Sleep 129
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{y down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 8
    Send("{e up}")
    Sleep 129
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{e down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 8
    Send("{y up}")
    Sleep 126
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{b up}")
    Sleep 1
    Send("{e down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 7
    Send("{u up}")
    Send("{b up}")
    Sleep 140
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{w down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{w down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{2 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{2 up}")
    Sleep 128
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{2 down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{e up}")
    Sleep 132
    Send("{y down}")
    Sleep 8
    Send("{2 up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 134
    Send("{c up}")
    Sleep 1
    Send("{e down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 7
    Send("{e up}")
    Sleep 8
    Send("{c up}")
    Sleep 134
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{n up}")
    Send("{n up}")
    Sleep 1
    Send("{w down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 7
    Send("{e up}")
    Sleep 132
    Send("{n up}")
    Send("{n up}")
    Sleep 8
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{w down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{e up}")
    Sleep 121
    Send("{n up}")
    Send("{n up}")
    Sleep 8
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{q down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{y down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{q up}")
    Sleep 126
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{y up}")
    Sleep 129
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{q down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{e up}")
    Sleep 129
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{y down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{q up}")
    Sleep 126
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{e up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 1
    Send("{e down}")
    Send("{n down}")
    Send("{z down}")
    Sleep 139
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 135
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Sleep 282
    Send("{e up}")
    Sleep 0
    Send("{n down}")
    Send("{n down}")
    Send("{z down}")
    Sleep 131
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 135
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{n down}")
    Send("{x down}")
    Sleep 131
    Send("{n up}")
    Send("{x up}")
    Sleep 286
    Send("{n up}")
    Sleep 1
    Send("{t down}")
    Send("{n down}")
    Send("{z down}")
    Sleep 139
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 135
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Sleep 282
    Send("{t up}")
    Sleep 0
    Send("{5 down}")
    Send("{n down}")
    Send("{z down}")
    Sleep 131
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 135
    Send("{5 up}")
    Send("{z up}")
    Sleep 0
    Send("{t down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{n down}")
    Send("{x down}")
    Sleep 131
    Send("{n up}")
    Send("{x up}")
    Sleep 8
    Send("{5 down}")
    Sleep 8
    Send("{t up}")
    Sleep 269
    Send("{5 up}")
    Sleep 1
    Send("{e down}")
    Send("{n down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 139
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Send("{c up}")
    Sleep 0
    Send("{z down}")
    Send("{c down}")
    Sleep 135
    Send("{z up}")
    Send("{c up}")
    Sleep 0
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{n down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Sleep 8
    Send("{g up}")
    Sleep 273
    Send("{e up}")
    Sleep 0
    Send("{n down}")
    Send("{n down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 131
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Send("{c up}")
    Sleep 0
    Send("{z down}")
    Send("{c down}")
    Sleep 134
    Send("{z up}")
    Send("{c up}")
    Sleep 0
    Send("{z down}")
    Send("{c down}")
    Sleep 129
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{n down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 129
    Send("{n up}")
    Send("{x up}")
    Sleep 8
    Send("{g up}")
    Sleep 274
    Send("{n down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 139
    Send("{n up}")
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 136
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{n down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Sleep 8
    Send("{g up}")
    Sleep 135
    Send("{x down}")
    Send("{g down}")
    Sleep 131
    Send("{x up}")
    Sleep 8
    Send("{n up}")
    Send("{g up}")
    Sleep 0
    Send("{n down}")
    Sleep 131
    Send("{n up}")
    Sleep 280
    Send("{m down}")
    Sleep 129
    Send("{m up}")
    Sleep 282
    Send("{e down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 139
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 135
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Sleep 8
    Send("{z down}")
    Send("{g down}")
    Sleep 130
    Send("{z up}")
    Send("{g up}")
    Sleep 282
    Send("{e up}")
    Sleep 0
    Send("{q down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 131
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 134
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 129
    Send("{c up}")
    Sleep 8
    Send("{z down}")
    Send("{g down}")
    Sleep 129
    Send("{z up}")
    Send("{g up}")
    Sleep 281
    Send("{q up}")
    Sleep 1
    Send("{t down}")
    Send("{x down}")
    Send("{c down}")
    Sleep 139
    Send("{x up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 135
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Sleep 8
    Send("{x down}")
    Send("{g down}")
    Sleep 130
    Send("{x up}")
    Send("{g up}")
    Sleep 282
    Send("{t up}")
    Sleep 0
    Send("{5 down}")
    Send("{x down}")
    Send("{c down}")
    Sleep 131
    Send("{x up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 134
    Send("{5 up}")
    Send("{c up}")
    Sleep 0
    Send("{t down}")
    Send("{c down}")
    Sleep 129
    Send("{c up}")
    Sleep 8
    Send("{x down}")
    Send("{g down}")
    Sleep 129
    Send("{x up}")
    Send("{g up}")
    Sleep 8
    Send("{y down}")
    Sleep 8
    Send("{t up}")
    Sleep 265
    Send("{y up}")
    Sleep 1
    Send("{u down}")
    Send("{c down}")
    Send("{b down}")
    Sleep 139
    Send("{c up}")
    Sleep 8
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 135
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Sleep 8
    Send("{c down}")
    Send("{g down}")
    Sleep 130
    Send("{c up}")
    Send("{g up}")
    Sleep 282
    Send("{u up}")
    Sleep 0
    Send("{e down}")
    Send("{c down}")
    Send("{b down}")
    Sleep 131
    Send("{c up}")
    Sleep 8
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 134
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 129
    Send("{b up}")
    Sleep 8
    Send("{c down}")
    Send("{g down}")
    Sleep 129
    Send("{c up}")
    Send("{g up}")
    Sleep 282
    Send("{c down}")
    Send("{b down}")
    Sleep 421
    Send("{c up}")
    Send("{b up}")
    Sleep 0
    Send("{c down}")
    Send("{g down}")
    Sleep 411
    Send("{e up}")
    Send("{c up}")
    Send("{g up}")
    Sleep 0
    Send("{c down}")
    Send("{b down}")
    Sleep 131
    Send("{c up}")
    Sleep 8
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 134
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 129
    Send("{b up}")
    Sleep 8
    Send("{m down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 410
    Send("{g up}")
    Sleep 1
    Send("{u down}")
    Send("{e down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 15
    Send("{m up}")
    Send("{x up}")
    Sleep 106
    Send("{c up}")
    Send("{c up}")
    Sleep 300
    Send("{c down}")
    Send("{w down}")
    Sleep 411
    Send("{u up}")
    Send("{e up}")
    Send("{c up}")
    Send("{w up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 131
    Send("{c up}")
    Send("{c up}")
    Sleep 280
    Send("{c down}")
    Send("{w down}")
    Sleep 410
    Send("{t up}")
    Send("{u up}")
    Send("{c up}")
    Send("{w up}")
    Sleep 1
    Send("{e down}")
    Send("{t down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 139
    Send("{c up}")
    Send("{c up}")
    Sleep 282
    Send("{c down}")
    Send("{w down}")
    Sleep 411
    Send("{e up}")
    Send("{t up}")
    Send("{c up}")
    Send("{w up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 131
    Send("{c up}")
    Send("{c up}")
    Sleep 143
    Send("{w up}")
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Sleep 138
    Send("{c down}")
    Send("{w down}")
    Sleep 137
    Send("{t up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 265
    Send("{w up}")
    Send("{5 up}")
    Send("{c up}")
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Send("{e down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 139
    Send("{v up}")
    Send("{v up}")
    Sleep 282
    Send("{v down}")
    Send("{q down}")
    Sleep 411
    Send("{q up}")
    Send("{e up}")
    Send("{v up}")
    Send("{q up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 131
    Send("{v up}")
    Send("{v up}")
    Sleep 284
    Send("{v down}")
    Send("{q down}")
    Sleep 421
    Send("{v up}")
    Send("{q up}")
    Sleep 1
    Send("{v down}")
    Send("{v down}")
    Sleep 423
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{v down}")
    Send("{v down}")
    Sleep 138
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{v down}")
    Send("{v down}")
    Sleep 134
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{v down}")
    Send("{v down}")
    Sleep 139
    Send("{r up}")
    Send("{y up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{v down}")
    Send("{v down}")
    Sleep 411
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{c down}")
    Send("{c down}")
    Sleep 410
    Send("{c up}")
    Send("{c up}")
    Sleep 1
    Send("{e down}")
    Send("{q down}")
    Send("{e down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 139
    Send("{x up}")
    Send("{x up}")
    Sleep 282
    Send("{x down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{x up}")
    Sleep 282
    Send("{e up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 0
    Send("{n down}")
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 131
    Send("{x up}")
    Send("{x up}")
    Sleep 280
    Send("{z down}")
    Send("{z down}")
    Sleep 129
    Send("{z up}")
    Send("{z up}")
    Sleep 281
    Send("{n up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Send("{w down}")
    Send("{t down}")
    Send("{j down}")
    Send("{j down}")
    Sleep 139
    Send("{j up}")
    Send("{j up}")
    Sleep 282
    Send("{j down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{j up}")
    Sleep 282
    Send("{t up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 0
    Send("{r down}")
    Send("{q down}")
    Send("{r down}")
    Send("{j down}")
    Send("{j down}")
    Sleep 131
    Send("{j up}")
    Send("{j up}")
    Sleep 143
    Send("{r up}")
    Send("{q up}")
    Send("{r up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 138
    Send("{j down}")
    Send("{j down}")
    Sleep 129
    Send("{j up}")
    Send("{j up}")
    Sleep 8
    Send("{t up}")
    Sleep 0
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 8
    Send("{t up}")
    Send("{w up}")
    Sleep 265
    Send("{y up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 1
    Send("{u down}")
    Send("{e down}")
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 139
    Send("{m up}")
    Send("{m up}")
    Sleep 282
    Send("{m down}")
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Send("{m down}")
    Sleep 139
    Send("{u up}")
    Send("{e up}")
    Send("{5 up}")
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Send("{m down}")
    Sleep 131
    Send("{m up}")
    Send("{m up}")
    Sleep 144
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 140
    Send("{m down}")
    Send("{m down}")
    Sleep 132
    Send("{m up}")
    Send("{m up}")
    Sleep 8
    Send("{e up}")
    Send("{y up}")
    Sleep 0
    Send("{u down}")
    Send("{e down}")
    Send("{u down}")
    Sleep 8
    Send("{y up}")
    Sleep 273
    Send("{u up}")
    Send("{e up}")
    Send("{u up}")
    Sleep 1
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 141
    Send("{c up}")
    Send("{c up}")
    Sleep 282
    Send("{c down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{c up}")
    Sleep 282
    Send("{y up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 0
    Send("{6 down}")
    Send("{e down}")
    Send("{6 down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 274
    Send("{y down}")
    Sleep 137
    Send("{c up}")
    Send("{c up}")
    Sleep 0
    Send("{m down}")
    Send("{m down}")
    Sleep 129
    Send("{m up}")
    Send("{m up}")
    Sleep 8
    Send("{w down}")
    Sleep 8
    Send("{y up}")
    Sleep 265
    Send("{6 up}")
    Send("{e up}")
    Send("{6 up}")
    Send("{w up}")
    Sleep 1
    Send("{2 down}")
    Send("{2 down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 138
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 146
    Send("{2 up}")
    Sleep 265
    Send("{2 up}")
    Sleep 0
    Send("{y down}")
    Send("{2 down}")
    Sleep 139
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 139
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 149
    Send("{2 up}")
    Sleep 130
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{c down}")
    Sleep 134
    Send("{c up}")
    Sleep 10
    Send("{2 down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 150
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 138
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 146
    Send("{2 up}")
    Sleep 126
    Send("{2 down}")
    Sleep 139
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Sleep 8
    Send("{2 up}")
    Sleep 265
    Send("{e up}")
    Sleep 0
    Send("{y down}")
    Sleep 267
    Send("{n up}")
    Sleep 8
    Send("{n up}")
    Sleep 0
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 8
    Send("{y up}")
    Sleep 265
    Send("{u up}")
    Send("{b up}")
    Send("{b up}")
    Sleep 1
    Send("{q down}")
    Send("{q down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 135
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 138
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Sleep 8
    Send("{u down}")
    Sleep 8
    Send("{q up}")
    Sleep 265
    Send("{u up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 139
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 135
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 139
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 149
    Send("{q up}")
    Sleep 130
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{z down}")
    Sleep 134
    Send("{z up}")
    Sleep 10
    Send("{y down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 150
    Send("{y up}")
    Sleep 0
    Send("{y down}")
    Sleep 135
    Send("{y up}")
    Sleep 0
    Send("{y down}")
    Sleep 138
    Send("{y up}")
    Sleep 0
    Send("{y down}")
    Sleep 146
    Send("{y up}")
    Sleep 126
    Send("{y down}")
    Sleep 139
    Send("{y up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{e down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 8
    Send("{y up}")
    Sleep 265
    Send("{e up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{y down}")
    Send("{z down}")
    Send("{z down}")
    Sleep 275
    Send("{z up}")
    Sleep 0
    Send("{e down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 8
    Send("{y up}")
    Send("{z up}")
    Sleep 265
    Send("{e up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 1
    Send("{w down}")
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 135
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 138
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 146
    Send("{u up}")
    Sleep 265
    Send("{w up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Sleep 139
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 135
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 139
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 149
    Send("{u up}")
    Sleep 130
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{x down}")
    Sleep 134
    Send("{x up}")
    Sleep 10
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 150
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 135
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 138
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 146
    Send("{u up}")
    Sleep 126
    Send("{u down}")
    Sleep 139
    Send("{u up}")
    Sleep 0
    Send("{w down}")
    Sleep 8
    Send("{u up}")
    Sleep 265
    Send("{w up}")
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{t down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 275
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 8
    Send("{t up}")
    Send("{b up}")
    Sleep 265
    Send("{w up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 1
    Send("{2 down}")
    Send("{2 down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 138
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 130
    Send("{2 up}")
    Sleep 8
    Send("{u down}")
    Sleep 8
    Send("{2 up}")
    Sleep 265
    Send("{u up}")
    Sleep 0
    Send("{y down}")
    Send("{2 down}")
    Sleep 139
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 139
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 149
    Send("{2 up}")
    Sleep 130
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{c down}")
    Sleep 134
    Send("{c up}")
    Sleep 10
    Send("{2 down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 150
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 138
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 146
    Send("{2 up}")
    Sleep 126
    Send("{2 down}")
    Sleep 139
    Send("{y up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{2 up}")
    Sleep 265
    Send("{e up}")
    Send("{e up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{y down}")
    Send("{y down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 275
    Send("{y up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{y up}")
    Send("{n up}")
    Sleep 239
    Send("{c up}")
    Send("{c up}")
    Sleep 26
    Send("{e up}")
    Send("{e up}")
    Sleep 1
    Send("{5 down}")
    Send("{5 down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x down}")
    Send("{g down}")
    Sleep 135
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{x down}")
    Send("{g down}")
    Sleep 138
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{x down}")
    Send("{g down}")
    Sleep 146
    Send("{x up}")
    Send("{g up}")
    Sleep 265
    Send("{5 up}")
    Send("{5 up}")
    Sleep 0
    Send("{y down}")
    Send("{y down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 139
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{x down}")
    Send("{g down}")
    Sleep 134
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{x down}")
    Send("{g down}")
    Sleep 137
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{x down}")
    Send("{g down}")
    Sleep 146
    Send("{x up}")
    Send("{g up}")
    Sleep 266
    Send("{x down}")
    Send("{c down}")
    Sleep 147
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{x down}")
    Send("{c down}")
    Sleep 135
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{x down}")
    Send("{c down}")
    Sleep 138
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{x down}")
    Send("{c down}")
    Sleep 146
    Send("{x up}")
    Send("{c up}")
    Sleep 265
    Send("{y up}")
    Send("{y up}")
    Sleep 0
    Send("{6 down}")
    Send("{6 down}")
    Send("{x down}")
    Send("{c down}")
    Sleep 139
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{x down}")
    Send("{c down}")
    Sleep 134
    Send("{6 up}")
    Send("{6 up}")
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Send("{x down}")
    Send("{c down}")
    Sleep 137
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{x down}")
    Send("{c down}")
    Sleep 137
    Send("{u up}")
    Sleep 0
    Send("{6 down}")
    Send("{6 down}")
    Sleep 8
    Send("{u up}")
    Send("{x up}")
    Send("{c up}")
    Sleep 265
    Send("{6 up}")
    Send("{6 up}")
    Send("{x up}")
    Send("{x up}")
    Sleep 1
    Send("{y down}")
    Send("{y down}")
    Send("{s down}")
    Send("{s down}")
    Sleep 147
    Send("{s down}")
    Send("{n down}")
    Sleep 135
    Send("{s up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Send("{n down}")
    Sleep 138
    Send("{s up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Send("{n down}")
    Sleep 146
    Send("{s up}")
    Send("{n up}")
    Sleep 265
    Send("{y up}")
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Send("{s down}")
    Send("{n down}")
    Sleep 139
    Send("{s up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Send("{n down}")
    Sleep 135
    Send("{s up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Send("{n down}")
    Sleep 139
    Send("{s up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Send("{n down}")
    Sleep 149
    Send("{s up}")
    Send("{n up}")
    Sleep 273
    Send("{s up}")
    Send("{s up}")
    Sleep 1
    Send("{g down}")
    Send("{g down}")
    Sleep 150
    Send("{g down}")
    Send("{n down}")
    Sleep 135
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 138
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 146
    Send("{g up}")
    Send("{n up}")
    Sleep 265
    Send("{e up}")
    Send("{e up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Send("{g down}")
    Send("{n down}")
    Sleep 139
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 134
    Send("{e up}")
    Send("{e up}")
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Send("{g down}")
    Send("{n down}")
    Sleep 137
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 137
    Send("{w up}")
    Sleep 0
    Send("{2 down}")
    Send("{2 down}")
    Sleep 8
    Send("{w up}")
    Send("{g up}")
    Send("{n up}")
    Sleep 265
    Send("{2 up}")
    Send("{2 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 1
    Send("{w down}")
    Send("{w down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 135
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 138
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 138
    Send("{b up}")
    Sleep 8
    Send("{m up}")
    Send("{x up}")
    Sleep 265
    Send("{w up}")
    Send("{w up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 139
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 135
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 139
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 149
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 130
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{x down}")
    Send("{x down}")
    Sleep 134
    Send("{x up}")
    Sleep 8
    Send("{x up}")
    Sleep 1
    Send("{b down}")
    Send("{b down}")
    Sleep 150
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 135
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 138
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 138
    Send("{b up}")
    Sleep 8
    Send("{m up}")
    Send("{x up}")
    Sleep 265
    Send("{u up}")
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 139
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 134
    Send("{u up}")
    Send("{u up}")
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{y down}")
    Send("{y down}")
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 137
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 137
    Send("{y up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Sleep 8
    Send("{y up}")
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 265
    Send("{u up}")
    Send("{u up}")
    Send("{b up}")
    Send("{b up}")
    Sleep 1
    Send("{w down}")
    Send("{w down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{b down}")
    Send("{n down}")
    Sleep 135
    Send("{b up}")
    Send("{n up}")
    Sleep 0
    Send("{b down}")
    Send("{n down}")
    Sleep 138
    Send("{b up}")
    Send("{n up}")
    Sleep 0
    Send("{b down}")
    Send("{n down}")
    Sleep 146
    Send("{b up}")
    Send("{n up}")
    Sleep 265
    Send("{b down}")
    Send("{n down}")
    Sleep 139
    Send("{b up}")
    Send("{n up}")
    Sleep 0
    Send("{b down}")
    Send("{n down}")
    Sleep 134
    Send("{b up}")
    Send("{n up}")
    Sleep 0
    Send("{b down}")
    Send("{n down}")
    Sleep 137
    Send("{b up}")
    Send("{n up}")
    Sleep 0
    Send("{b down}")
    Send("{n down}")
    Sleep 146
    Send("{b up}")
    Send("{n up}")
    Sleep 265
    Send("{w up}")
    Send("{w up}")
    Sleep 1
    Send("{e down}")
    Send("{e down}")
    Send("{n down}")
    Send("{2 down}")
    Sleep 147
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 135
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 138
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 272
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 139
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 139
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 134
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 137
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 137
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 134
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 138
    Send("{e up}")
    Send("{e up}")
    Send("{2 up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 1
    Send("{y down}")
    Sleep 7
    Send("{n up}")
    Sleep 414
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{y up}")
    Sleep 8
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 131
    Send("{y up}")
    Sleep 8
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Sleep 411
    Send("{x down}")
    Send("{n down}")
    Sleep 410
    Send("{w up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{y down}")
    Sleep 421
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{y up}")
    Sleep 8
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 131
    Send("{y up}")
    Sleep 8
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Sleep 411
    Send("{x down}")
    Send("{n down}")
    Sleep 410
    Send("{e up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{y down}")
    Sleep 421
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{y up}")
    Sleep 8
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 131
    Send("{y up}")
    Sleep 8
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{t down}")
    Sleep 273
    Send("{t up}")
    Sleep 0
    Send("{5 down}")
    Sleep 138
    Send("{x down}")
    Send("{n down}")
    Sleep 138
    Send("{e down}")
    Sleep 8
    Send("{5 up}")
    Sleep 265
    Send("{e up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{q down}")
    Sleep 282
    Send("{q up}")
    Sleep 0
    Send("{w down}")
    Sleep 138
    Send("{x down}")
    Send("{n down}")
    Sleep 138
    Send("{e down}")
    Sleep 8
    Send("{w up}")
    Sleep 265
    Send("{e up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{y down}")
    Sleep 414
    Send("{x down}")
    Send("{n down}")
    Sleep 416
    Send("{y up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{w down}")
    Send("{y down}")
    Send("{x down}")
    Send("{n down}")
    Sleep 421
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{w up}")
    Sleep 8
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 139
    Send("{y up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 413
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 416
    Send("{y up}")
    Send("{w up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{e down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 421
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{e up}")
    Sleep 8
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 131
    Send("{y up}")
    Sleep 8
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{u down}")
    Send("{e down}")
    Send("{x down}")
    Sleep 413
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 416
    Send("{u up}")
    Send("{e up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{5 down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 421
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{5 up}")
    Sleep 8
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 131
    Send("{y up}")
    Sleep 8
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Send("{t down}")
    Send("{x down}")
    Sleep 274
    Send("{w up}")
    Send("{t up}")
    Sleep 0
    Send("{y down}")
    Sleep 139
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 139
    Send("{t down}")
    Sleep 8
    Send("{y up}")
    Sleep 269
    Send("{t up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 282
    Send("{w up}")
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Sleep 138
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 138
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 265
    Send("{5 up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{q down}")
    Send("{x down}")
    Sleep 413
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 311
    Send("{m down}")
    Sleep 35
    Send("{m up}")
    Send("{q down}")
    Sleep 35
    Send("{q up}")
    Send("{w down}")
    Sleep 35
    Send("{q up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{w up}")
    Sleep 1
    Send("{e down}")
    Send("{e down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 282
    Send("{c up}")
    Send("{m up}")
    Sleep 138
    Send("{c down}")
    Send("{m down}")
    Sleep 111
    Send("{e up}")
    Sleep 26
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Sleep 126
    Send("{w up}")
    Sleep 8
    Send("{w up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Sleep 131
    Send("{e up}")
    Sleep 8
    Send("{e up}")
    Sleep 0
    Send("{t down}")
    Send("{t down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 275
    Send("{c up}")
    Send("{m up}")
    Sleep 140
    Send("{c down}")
    Send("{m down}")
    Sleep 279
    Send("{c up}")
    Send("{m up}")
    Sleep 143
    Send("{t up}")
    Send("{t up}")
    Sleep 1
    Send("{e down}")
    Send("{u down}")
    Send("{e down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 285
    Send("{c up}")
    Send("{m up}")
    Sleep 138
    Send("{c down}")
    Send("{m down}")
    Sleep 130
    Send("{e up}")
    Send("{u up}")
    Sleep 8
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Sleep 126
    Send("{w up}")
    Sleep 8
    Send("{w up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Sleep 131
    Send("{e up}")
    Sleep 8
    Send("{e up}")
    Sleep 0
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 273
    Send("{c up}")
    Send("{m up}")
    Sleep 138
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{c up}")
    Send("{m up}")
    Sleep 138
    Send("{y up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 1
    Send("{e down}")
    Send("{q down}")
    Send("{e down}")
    Send("{v down}")
    Send("{z down}")
    Sleep 282
    Send("{v up}")
    Send("{z up}")
    Sleep 138
    Send("{v down}")
    Send("{z down}")
    Sleep 130
    Send("{e up}")
    Send("{q up}")
    Sleep 8
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Sleep 126
    Send("{w up}")
    Sleep 8
    Send("{w up}")
    Send("{v up}")
    Send("{z up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Sleep 131
    Send("{e up}")
    Sleep 8
    Send("{e up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Send("{v down}")
    Send("{z down}")
    Sleep 274
    Send("{u up}")
    Send("{u up}")
    Send("{v up}")
    Send("{z up}")
    Sleep 0
    Send("{y down}")
    Send("{y down}")
    Sleep 139
    Send("{v down}")
    Send("{z down}")
    Sleep 139
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Send("{t down}")
    Sleep 8
    Send("{y up}")
    Sleep 128
    Send("{v up}")
    Send("{z up}")
    Sleep 141
    Send("{t up}")
    Send("{t up}")
    Sleep 1
    Send("{w down}")
    Send("{w down}")
    Send("{b down}")
    Send("{x down}")
    Sleep 282
    Send("{w up}")
    Send("{w up}")
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{q down}")
    Send("{q down}")
    Sleep 138
    Send("{b down}")
    Send("{x down}")
    Sleep 138
    Send("{q up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Sleep 8
    Send("{q up}")
    Sleep 126
    Send("{b up}")
    Send("{x up}")
    Sleep 139
    Send("{u up}")
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Send("{t down}")
    Send("{u down}")
    Send("{b down}")
    Send("{x down}")
    Sleep 139
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{b down}")
    Send("{x down}")
    Sleep 135
    Send("{u up}")
    Send("{t up}")
    Send("{u up}")
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Send("{b down}")
    Send("{x down}")
    Sleep 139
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{b down}")
    Send("{x down}")
    Sleep 139
    Send("{y up}")
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Send("{t down}")
    Send("{b down}")
    Send("{x down}")
    Sleep 8
    Send("{y up}")
    Send("{e up}")
    Sleep 128
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{b down}")
    Send("{x down}")
    Sleep 141
    Send("{t up}")
    Send("{w up}")
    Send("{t up}")
    Send("{x up}")
    Sleep 1
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Send("{n down}")
    Send("{c down}")
    Send("{n down}")
    Sleep 7
    Send("{b up}")
    Sleep 414
    Send("{y up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Sleep 138
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{w down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{w down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{2 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{2 up}")
    Sleep 128
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{n up}")
    Send("{c up}")
    Send("{n up}")
    Sleep 0
    Send("{2 down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{e up}")
    Sleep 132
    Send("{y down}")
    Sleep 8
    Send("{2 up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 134
    Send("{c up}")
    Send("{c up}")
    Sleep 1
    Send("{e down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 7
    Send("{e up}")
    Sleep 143
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{n up}")
    Send("{n up}")
    Sleep 1
    Send("{w down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{w down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{q down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{y down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{q up}")
    Sleep 126
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{y up}")
    Sleep 129
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{q down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{q up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{e down}")
    Send("{n down}")
    Send("{z down}")
    Sleep 7
    Send("{e up}")
    Sleep 132
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 135
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Sleep 282
    Send("{e up}")
    Sleep 0
    Send("{n down}")
    Send("{n down}")
    Send("{z down}")
    Sleep 131
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 135
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{n down}")
    Send("{x down}")
    Sleep 131
    Send("{n up}")
    Send("{x up}")
    Sleep 286
    Send("{n up}")
    Sleep 1
    Send("{t down}")
    Send("{n down}")
    Send("{z down}")
    Sleep 139
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 135
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{n down}")
    Send("{x down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Sleep 282
    Send("{t up}")
    Sleep 0
    Send("{5 down}")
    Send("{n down}")
    Send("{z down}")
    Sleep 131
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Sleep 0
    Send("{z down}")
    Sleep 135
    Send("{5 up}")
    Send("{z up}")
    Sleep 0
    Send("{t down}")
    Send("{z down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{n down}")
    Send("{x down}")
    Sleep 131
    Send("{n up}")
    Send("{x up}")
    Sleep 8
    Send("{5 down}")
    Sleep 8
    Send("{t up}")
    Sleep 269
    Send("{5 up}")
    Sleep 1
    Send("{e down}")
    Send("{n down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 139
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Send("{c up}")
    Sleep 0
    Send("{z down}")
    Send("{c down}")
    Sleep 135
    Send("{z up}")
    Send("{c up}")
    Sleep 0
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{n down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Sleep 8
    Send("{g up}")
    Sleep 273
    Send("{e up}")
    Sleep 0
    Send("{n down}")
    Send("{n down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 131
    Send("{n up}")
    Sleep 8
    Send("{z up}")
    Send("{c up}")
    Sleep 0
    Send("{z down}")
    Send("{c down}")
    Sleep 134
    Send("{z up}")
    Send("{c up}")
    Sleep 0
    Send("{z down}")
    Send("{c down}")
    Sleep 129
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{n down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 129
    Send("{n up}")
    Send("{x up}")
    Sleep 8
    Send("{g up}")
    Sleep 274
    Send("{n down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 139
    Send("{n up}")
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 136
    Send("{z down}")
    Send("{c down}")
    Sleep 130
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{n down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 130
    Send("{n up}")
    Send("{x up}")
    Sleep 8
    Send("{g up}")
    Sleep 135
    Send("{x down}")
    Send("{g down}")
    Sleep 131
    Send("{x up}")
    Sleep 8
    Send("{n up}")
    Send("{g up}")
    Sleep 0
    Send("{n down}")
    Sleep 131
    Send("{n up}")
    Sleep 280
    Send("{m down}")
    Sleep 129
    Send("{m up}")
    Sleep 282
    Send("{e down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 139
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 135
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Sleep 8
    Send("{z down}")
    Send("{g down}")
    Sleep 130
    Send("{z up}")
    Send("{g up}")
    Sleep 282
    Send("{e up}")
    Sleep 0
    Send("{q down}")
    Send("{z down}")
    Send("{c down}")
    Sleep 131
    Send("{z up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 134
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 129
    Send("{c up}")
    Sleep 8
    Send("{z down}")
    Send("{g down}")
    Sleep 129
    Send("{z up}")
    Send("{g up}")
    Sleep 281
    Send("{q up}")
    Sleep 1
    Send("{t down}")
    Send("{x down}")
    Send("{c down}")
    Sleep 139
    Send("{x up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 135
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Sleep 8
    Send("{x down}")
    Send("{g down}")
    Sleep 130
    Send("{x up}")
    Send("{g up}")
    Sleep 282
    Send("{t up}")
    Sleep 0
    Send("{5 down}")
    Send("{x down}")
    Send("{c down}")
    Sleep 131
    Send("{x up}")
    Sleep 8
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Sleep 134
    Send("{5 up}")
    Send("{c up}")
    Sleep 0
    Send("{t down}")
    Send("{c down}")
    Sleep 129
    Send("{c up}")
    Sleep 8
    Send("{x down}")
    Send("{g down}")
    Sleep 129
    Send("{x up}")
    Send("{g up}")
    Sleep 8
    Send("{y down}")
    Sleep 8
    Send("{t up}")
    Sleep 265
    Send("{y up}")
    Sleep 1
    Send("{u down}")
    Send("{c down}")
    Send("{b down}")
    Sleep 139
    Send("{c up}")
    Sleep 8
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 135
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 130
    Send("{b up}")
    Sleep 8
    Send("{c down}")
    Send("{g down}")
    Sleep 130
    Send("{c up}")
    Send("{g up}")
    Sleep 282
    Send("{u up}")
    Sleep 0
    Send("{e down}")
    Send("{c down}")
    Send("{b down}")
    Sleep 131
    Send("{c up}")
    Sleep 8
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 134
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 129
    Send("{b up}")
    Sleep 8
    Send("{c down}")
    Send("{g down}")
    Sleep 129
    Send("{c up}")
    Send("{g up}")
    Sleep 282
    Send("{c down}")
    Send("{b down}")
    Sleep 421
    Send("{c up}")
    Send("{b up}")
    Sleep 0
    Send("{c down}")
    Send("{g down}")
    Sleep 411
    Send("{e up}")
    Send("{c up}")
    Send("{g up}")
    Sleep 0
    Send("{c down}")
    Send("{b down}")
    Sleep 131
    Send("{c up}")
    Sleep 8
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 134
    Send("{b up}")
    Sleep 0
    Send("{b down}")
    Sleep 129
    Send("{b up}")
    Sleep 8
    Send("{m down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 410
    Send("{g up}")
    Sleep 1
    Send("{u down}")
    Send("{e down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 15
    Send("{m up}")
    Send("{x up}")
    Sleep 106
    Send("{c up}")
    Send("{c up}")
    Sleep 300
    Send("{c down}")
    Send("{w down}")
    Sleep 411
    Send("{u up}")
    Send("{e up}")
    Send("{c up}")
    Send("{w up}")
    Sleep 0
    Send("{t down}")
    Send("{u down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 131
    Send("{c up}")
    Send("{c up}")
    Sleep 280
    Send("{c down}")
    Send("{w down}")
    Sleep 410
    Send("{t up}")
    Send("{u up}")
    Send("{c up}")
    Send("{w up}")
    Sleep 1
    Send("{e down}")
    Send("{t down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 139
    Send("{c up}")
    Send("{c up}")
    Sleep 282
    Send("{c down}")
    Send("{w down}")
    Sleep 411
    Send("{e up}")
    Send("{t up}")
    Send("{c up}")
    Send("{w up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 131
    Send("{c up}")
    Send("{c up}")
    Sleep 143
    Send("{w up}")
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Send("{t down}")
    Sleep 138
    Send("{c down}")
    Send("{w down}")
    Sleep 137
    Send("{t up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 265
    Send("{w up}")
    Send("{5 up}")
    Send("{c up}")
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Send("{e down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 139
    Send("{v up}")
    Send("{v up}")
    Sleep 282
    Send("{v down}")
    Send("{q down}")
    Sleep 411
    Send("{q up}")
    Send("{e up}")
    Send("{v up}")
    Send("{q up}")
    Sleep 0
    Send("{r down}")
    Send("{y down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 131
    Send("{v up}")
    Send("{v up}")
    Sleep 284
    Send("{v down}")
    Send("{q down}")
    Sleep 421
    Send("{v up}")
    Send("{q up}")
    Sleep 1
    Send("{v down}")
    Send("{v down}")
    Sleep 423
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{v down}")
    Send("{v down}")
    Sleep 138
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{v down}")
    Send("{v down}")
    Sleep 134
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{v down}")
    Send("{v down}")
    Sleep 139
    Send("{r up}")
    Send("{y up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{v down}")
    Send("{v down}")
    Sleep 411
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{c down}")
    Send("{c down}")
    Sleep 410
    Send("{c up}")
    Send("{c up}")
    Sleep 1
    Send("{e down}")
    Send("{q down}")
    Send("{e down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 139
    Send("{x up}")
    Send("{x up}")
    Sleep 282
    Send("{x down}")
    Send("{x down}")
    Sleep 130
    Send("{x up}")
    Send("{x up}")
    Sleep 282
    Send("{e up}")
    Send("{q up}")
    Send("{e up}")
    Sleep 0
    Send("{n down}")
    Send("{r down}")
    Send("{y down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 131
    Send("{x up}")
    Send("{x up}")
    Sleep 280
    Send("{z down}")
    Send("{z down}")
    Sleep 129
    Send("{z up}")
    Send("{z up}")
    Sleep 281
    Send("{n up}")
    Send("{r up}")
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Send("{w down}")
    Send("{t down}")
    Send("{j down}")
    Send("{j down}")
    Sleep 139
    Send("{j up}")
    Send("{j up}")
    Sleep 282
    Send("{j down}")
    Send("{j down}")
    Sleep 130
    Send("{j up}")
    Send("{j up}")
    Sleep 282
    Send("{t up}")
    Send("{w up}")
    Send("{t up}")
    Sleep 0
    Send("{r down}")
    Send("{q down}")
    Send("{r down}")
    Send("{j down}")
    Send("{j down}")
    Sleep 131
    Send("{j up}")
    Send("{j up}")
    Sleep 143
    Send("{r up}")
    Send("{q up}")
    Send("{r up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Send("{t down}")
    Sleep 138
    Send("{j down}")
    Send("{j down}")
    Sleep 129
    Send("{j up}")
    Send("{j up}")
    Sleep 8
    Send("{t up}")
    Sleep 0
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 8
    Send("{t up}")
    Send("{w up}")
    Sleep 265
    Send("{y up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 1
    Send("{u down}")
    Send("{e down}")
    Send("{5 down}")
    Send("{u down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 139
    Send("{m up}")
    Send("{m up}")
    Sleep 282
    Send("{m down}")
    Send("{m down}")
    Sleep 138
    Send("{m up}")
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Send("{m down}")
    Sleep 134
    Send("{m up}")
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Send("{m down}")
    Sleep 139
    Send("{u up}")
    Send("{e up}")
    Send("{5 up}")
    Send("{u up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Send("{m down}")
    Sleep 131
    Send("{m up}")
    Send("{m up}")
    Sleep 144
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Sleep 140
    Send("{m down}")
    Send("{m down}")
    Sleep 132
    Send("{m up}")
    Send("{m up}")
    Sleep 8
    Send("{e up}")
    Send("{y up}")
    Sleep 0
    Send("{u down}")
    Send("{e down}")
    Send("{u down}")
    Sleep 8
    Send("{y up}")
    Sleep 273
    Send("{u up}")
    Send("{e up}")
    Send("{u up}")
    Sleep 1
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 141
    Send("{c up}")
    Send("{c up}")
    Sleep 282
    Send("{c down}")
    Send("{c down}")
    Sleep 130
    Send("{c up}")
    Send("{c up}")
    Sleep 282
    Send("{y up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 0
    Send("{6 down}")
    Send("{e down}")
    Send("{6 down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 274
    Send("{y down}")
    Sleep 137
    Send("{c up}")
    Send("{c up}")
    Sleep 0
    Send("{m down}")
    Send("{m down}")
    Sleep 129
    Send("{m up}")
    Send("{m up}")
    Sleep 8
    Send("{w down}")
    Sleep 8
    Send("{y up}")
    Sleep 265
    Send("{6 up}")
    Send("{e up}")
    Send("{6 up}")
    Send("{w up}")
    Sleep 1
    Send("{2 down}")
    Send("{2 down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 138
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 146
    Send("{2 up}")
    Sleep 265
    Send("{2 up}")
    Sleep 0
    Send("{y down}")
    Send("{2 down}")
    Sleep 139
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 139
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 149
    Send("{2 up}")
    Sleep 130
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{c down}")
    Sleep 134
    Send("{c up}")
    Sleep 10
    Send("{2 down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 150
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 138
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 146
    Send("{2 up}")
    Sleep 126
    Send("{2 down}")
    Sleep 139
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Sleep 8
    Send("{2 up}")
    Sleep 265
    Send("{e up}")
    Sleep 0
    Send("{y down}")
    Sleep 267
    Send("{n up}")
    Sleep 8
    Send("{n up}")
    Sleep 0
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 8
    Send("{y up}")
    Sleep 265
    Send("{u up}")
    Send("{b up}")
    Send("{b up}")
    Sleep 1
    Send("{q down}")
    Send("{q down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 147
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 135
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 138
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 130
    Send("{q up}")
    Sleep 8
    Send("{u down}")
    Sleep 8
    Send("{q up}")
    Sleep 265
    Send("{u up}")
    Sleep 0
    Send("{y down}")
    Send("{q down}")
    Sleep 139
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 135
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 139
    Send("{q up}")
    Sleep 0
    Send("{q down}")
    Sleep 149
    Send("{q up}")
    Sleep 130
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{z down}")
    Sleep 134
    Send("{z up}")
    Sleep 10
    Send("{y down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 150
    Send("{y up}")
    Sleep 0
    Send("{y down}")
    Sleep 135
    Send("{y up}")
    Sleep 0
    Send("{y down}")
    Sleep 138
    Send("{y up}")
    Sleep 0
    Send("{y down}")
    Sleep 146
    Send("{y up}")
    Sleep 126
    Send("{y down}")
    Sleep 139
    Send("{y up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{e down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 8
    Send("{y up}")
    Sleep 265
    Send("{e up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 0
    Send("{y down}")
    Send("{z down}")
    Send("{z down}")
    Sleep 275
    Send("{z up}")
    Sleep 0
    Send("{e down}")
    Send("{v down}")
    Send("{v down}")
    Sleep 8
    Send("{y up}")
    Send("{z up}")
    Sleep 265
    Send("{e up}")
    Send("{v up}")
    Send("{v up}")
    Sleep 1
    Send("{w down}")
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 135
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 138
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 146
    Send("{u up}")
    Sleep 265
    Send("{w up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Sleep 139
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 135
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 139
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 149
    Send("{u up}")
    Sleep 130
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{x down}")
    Sleep 134
    Send("{x up}")
    Sleep 10
    Send("{u down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 150
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 135
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 138
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Sleep 146
    Send("{u up}")
    Sleep 126
    Send("{u down}")
    Sleep 139
    Send("{u up}")
    Sleep 0
    Send("{w down}")
    Sleep 8
    Send("{u up}")
    Sleep 265
    Send("{w up}")
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{t down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 275
    Send("{b up}")
    Sleep 0
    Send("{w down}")
    Send("{m down}")
    Send("{m down}")
    Sleep 8
    Send("{t up}")
    Send("{b up}")
    Sleep 265
    Send("{w up}")
    Send("{m up}")
    Send("{m up}")
    Sleep 1
    Send("{2 down}")
    Send("{2 down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 138
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 130
    Send("{2 up}")
    Sleep 8
    Send("{u down}")
    Sleep 8
    Send("{2 up}")
    Sleep 265
    Send("{u up}")
    Sleep 0
    Send("{y down}")
    Send("{2 down}")
    Sleep 139
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 139
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 149
    Send("{2 up}")
    Sleep 130
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{c down}")
    Sleep 134
    Send("{c up}")
    Sleep 10
    Send("{2 down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 150
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 135
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 138
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 146
    Send("{2 up}")
    Sleep 126
    Send("{2 down}")
    Sleep 139
    Send("{y up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{2 up}")
    Sleep 265
    Send("{e up}")
    Send("{e up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{y down}")
    Send("{y down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 275
    Send("{y up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{y up}")
    Send("{n up}")
    Sleep 239
    Send("{c up}")
    Send("{c up}")
    Sleep 26
    Send("{e up}")
    Send("{e up}")
    Sleep 1
    Send("{5 down}")
    Send("{5 down}")
    Send("{x down}")
    Send("{x down}")
    Sleep 147
    Send("{x down}")
    Send("{g down}")
    Sleep 135
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{x down}")
    Send("{g down}")
    Sleep 138
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{x down}")
    Send("{g down}")
    Sleep 146
    Send("{x up}")
    Send("{g up}")
    Sleep 265
    Send("{5 up}")
    Send("{5 up}")
    Sleep 0
    Send("{y down}")
    Send("{y down}")
    Send("{x down}")
    Send("{g down}")
    Sleep 139
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{x down}")
    Send("{g down}")
    Sleep 134
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{x down}")
    Send("{g down}")
    Sleep 137
    Send("{x up}")
    Send("{g up}")
    Sleep 0
    Send("{x down}")
    Send("{g down}")
    Sleep 146
    Send("{x up}")
    Send("{g up}")
    Sleep 266
    Send("{x down}")
    Send("{c down}")
    Sleep 147
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{x down}")
    Send("{c down}")
    Sleep 135
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{x down}")
    Send("{c down}")
    Sleep 138
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{x down}")
    Send("{c down}")
    Sleep 146
    Send("{x up}")
    Send("{c up}")
    Sleep 265
    Send("{y up}")
    Send("{y up}")
    Sleep 0
    Send("{6 down}")
    Send("{6 down}")
    Send("{x down}")
    Send("{c down}")
    Sleep 139
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{x down}")
    Send("{c down}")
    Sleep 134
    Send("{6 up}")
    Send("{6 up}")
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Send("{x down}")
    Send("{c down}")
    Sleep 137
    Send("{x up}")
    Send("{c up}")
    Sleep 0
    Send("{x down}")
    Send("{c down}")
    Sleep 137
    Send("{u up}")
    Sleep 0
    Send("{6 down}")
    Send("{6 down}")
    Sleep 8
    Send("{u up}")
    Send("{x up}")
    Send("{c up}")
    Sleep 265
    Send("{6 up}")
    Send("{6 up}")
    Send("{x up}")
    Send("{x up}")
    Sleep 1
    Send("{y down}")
    Send("{y down}")
    Send("{s down}")
    Send("{s down}")
    Sleep 147
    Send("{s down}")
    Send("{n down}")
    Sleep 135
    Send("{s up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Send("{n down}")
    Sleep 138
    Send("{s up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Send("{n down}")
    Sleep 146
    Send("{s up}")
    Send("{n up}")
    Sleep 265
    Send("{y up}")
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Send("{s down}")
    Send("{n down}")
    Sleep 139
    Send("{s up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Send("{n down}")
    Sleep 135
    Send("{s up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Send("{n down}")
    Sleep 139
    Send("{s up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Send("{n down}")
    Sleep 149
    Send("{s up}")
    Send("{n up}")
    Sleep 273
    Send("{s up}")
    Send("{s up}")
    Sleep 1
    Send("{g down}")
    Send("{g down}")
    Sleep 150
    Send("{g down}")
    Send("{n down}")
    Sleep 135
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 138
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 146
    Send("{g up}")
    Send("{n up}")
    Sleep 265
    Send("{e up}")
    Send("{e up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Send("{g down}")
    Send("{n down}")
    Sleep 139
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 134
    Send("{e up}")
    Send("{e up}")
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Send("{g down}")
    Send("{n down}")
    Sleep 137
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 137
    Send("{w up}")
    Sleep 0
    Send("{2 down}")
    Send("{2 down}")
    Sleep 8
    Send("{w up}")
    Send("{g up}")
    Send("{n up}")
    Sleep 265
    Send("{2 up}")
    Send("{2 up}")
    Send("{g up}")
    Send("{g up}")
    Sleep 1
    Send("{w down}")
    Send("{w down}")
    Send("{b down}")
    Send("{b down}")
    Sleep 147
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 135
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 138
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 138
    Send("{b up}")
    Sleep 8
    Send("{m up}")
    Send("{x up}")
    Sleep 265
    Send("{w up}")
    Send("{w up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 139
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 135
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 139
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 149
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 130
    Send("{b up}")
    Send("{b up}")
    Sleep 0
    Send("{x down}")
    Send("{x down}")
    Sleep 134
    Send("{x up}")
    Sleep 8
    Send("{x up}")
    Sleep 1
    Send("{b down}")
    Send("{b down}")
    Sleep 150
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 135
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 138
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 138
    Send("{b up}")
    Sleep 8
    Send("{m up}")
    Send("{x up}")
    Sleep 265
    Send("{u up}")
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 139
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 134
    Send("{u up}")
    Send("{u up}")
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{y down}")
    Send("{y down}")
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 137
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 0
    Send("{m down}")
    Send("{x down}")
    Send("{b down}")
    Sleep 137
    Send("{y up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Sleep 8
    Send("{y up}")
    Send("{m up}")
    Send("{x up}")
    Send("{b up}")
    Sleep 265
    Send("{u up}")
    Send("{u up}")
    Send("{b up}")
    Send("{b up}")
    Sleep 1
    Send("{w down}")
    Send("{w down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 147
    Send("{b down}")
    Send("{n down}")
    Sleep 135
    Send("{b up}")
    Send("{n up}")
    Sleep 0
    Send("{b down}")
    Send("{n down}")
    Sleep 138
    Send("{b up}")
    Send("{n up}")
    Sleep 0
    Send("{b down}")
    Send("{n down}")
    Sleep 146
    Send("{b up}")
    Send("{n up}")
    Sleep 265
    Send("{b down}")
    Send("{n down}")
    Sleep 139
    Send("{b up}")
    Send("{n up}")
    Sleep 0
    Send("{b down}")
    Send("{n down}")
    Sleep 134
    Send("{b up}")
    Send("{n up}")
    Sleep 0
    Send("{b down}")
    Send("{n down}")
    Sleep 137
    Send("{b up}")
    Send("{n up}")
    Sleep 0
    Send("{b down}")
    Send("{n down}")
    Sleep 146
    Send("{b up}")
    Send("{n up}")
    Sleep 265
    Send("{w up}")
    Send("{w up}")
    Sleep 1
    Send("{e down}")
    Send("{e down}")
    Send("{n down}")
    Send("{2 down}")
    Sleep 147
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 135
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 138
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 272
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 139
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 139
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 134
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 137
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 137
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 134
    Send("{n up}")
    Send("{2 up}")
    Sleep 0
    Send("{n down}")
    Send("{2 down}")
    Sleep 138
    Send("{e up}")
    Send("{e up}")
    Send("{2 up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 1
    Send("{y down}")
    Sleep 7
    Send("{n up}")
    Sleep 414
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{y up}")
    Sleep 8
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 131
    Send("{y up}")
    Sleep 8
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Sleep 411
    Send("{x down}")
    Send("{n down}")
    Sleep 410
    Send("{w up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{y down}")
    Sleep 421
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{y up}")
    Sleep 8
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 131
    Send("{y up}")
    Sleep 8
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Sleep 411
    Send("{x down}")
    Send("{n down}")
    Sleep 410
    Send("{e up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{y down}")
    Sleep 421
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{y up}")
    Sleep 8
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 131
    Send("{y up}")
    Sleep 8
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{t down}")
    Sleep 273
    Send("{t up}")
    Sleep 0
    Send("{5 down}")
    Sleep 138
    Send("{x down}")
    Send("{n down}")
    Sleep 138
    Send("{e down}")
    Sleep 8
    Send("{5 up}")
    Sleep 265
    Send("{e up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{q down}")
    Sleep 282
    Send("{q up}")
    Sleep 0
    Send("{w down}")
    Sleep 138
    Send("{x down}")
    Send("{n down}")
    Sleep 138
    Send("{e down}")
    Sleep 8
    Send("{w up}")
    Sleep 265
    Send("{e up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{y down}")
    Sleep 414
    Send("{x down}")
    Send("{n down}")
    Sleep 416
    Send("{y up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{w down}")
    Send("{y down}")
    Send("{x down}")
    Send("{n down}")
    Sleep 421
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{w up}")
    Sleep 8
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 139
    Send("{y up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{y down}")
    Send("{w down}")
    Send("{x down}")
    Sleep 413
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 416
    Send("{y up}")
    Send("{w up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{e down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 421
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{e up}")
    Sleep 8
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 131
    Send("{y up}")
    Sleep 8
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{u down}")
    Send("{e down}")
    Send("{x down}")
    Sleep 413
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 416
    Send("{u up}")
    Send("{e up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{5 down}")
    Send("{y down}")
    Send("{x down}")
    Sleep 421
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 130
    Send("{5 up}")
    Sleep 8
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Sleep 126
    Send("{t up}")
    Sleep 8
    Send("{y down}")
    Sleep 131
    Send("{y up}")
    Sleep 8
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{w down}")
    Send("{t down}")
    Send("{x down}")
    Sleep 274
    Send("{w up}")
    Send("{t up}")
    Sleep 0
    Send("{y down}")
    Sleep 139
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 139
    Send("{t down}")
    Sleep 8
    Send("{y up}")
    Sleep 269
    Send("{t up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 1
    Send("{w down}")
    Send("{5 down}")
    Send("{x down}")
    Sleep 282
    Send("{w up}")
    Send("{5 up}")
    Sleep 0
    Send("{e down}")
    Sleep 138
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 138
    Send("{5 down}")
    Sleep 8
    Send("{e up}")
    Sleep 265
    Send("{5 up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{q down}")
    Send("{x down}")
    Sleep 413
    Send("{x up}")
    Sleep 0
    Send("{x down}")
    Send("{n down}")
    Sleep 311
    Send("{m down}")
    Sleep 35
    Send("{m up}")
    Send("{q down}")
    Sleep 35
    Send("{q up}")
    Send("{w down}")
    Sleep 35
    Send("{q up}")
    Send("{x up}")
    Send("{n up}")
    Sleep 0
    Send("{w up}")
    Sleep 1
    Send("{e down}")
    Send("{e down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 282
    Send("{c up}")
    Send("{m up}")
    Sleep 138
    Send("{c down}")
    Send("{m down}")
    Sleep 111
    Send("{e up}")
    Sleep 26
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Sleep 126
    Send("{w up}")
    Sleep 8
    Send("{w up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Sleep 131
    Send("{e up}")
    Sleep 8
    Send("{e up}")
    Sleep 0
    Send("{t down}")
    Send("{t down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 275
    Send("{c up}")
    Send("{m up}")
    Sleep 140
    Send("{c down}")
    Send("{m down}")
    Sleep 279
    Send("{c up}")
    Send("{m up}")
    Sleep 143
    Send("{t up}")
    Send("{t up}")
    Sleep 1
    Send("{e down}")
    Send("{u down}")
    Send("{e down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 285
    Send("{c up}")
    Send("{m up}")
    Sleep 138
    Send("{c down}")
    Send("{m down}")
    Sleep 130
    Send("{e up}")
    Send("{u up}")
    Sleep 8
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Sleep 126
    Send("{w up}")
    Sleep 8
    Send("{w up}")
    Send("{c up}")
    Send("{m up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Sleep 131
    Send("{e up}")
    Sleep 8
    Send("{e up}")
    Sleep 0
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Send("{c down}")
    Send("{m down}")
    Sleep 273
    Send("{c up}")
    Send("{m up}")
    Sleep 138
    Send("{c down}")
    Send("{m down}")
    Sleep 272
    Send("{c up}")
    Send("{m up}")
    Sleep 138
    Send("{y up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 1
    Send("{e down}")
    Send("{q down}")
    Send("{e down}")
    Send("{v down}")
    Send("{z down}")
    Sleep 282
    Send("{v up}")
    Send("{z up}")
    Sleep 138
    Send("{v down}")
    Send("{z down}")
    Sleep 130
    Send("{e up}")
    Send("{q up}")
    Sleep 8
    Send("{e up}")
    Sleep 0
    Send("{w down}")
    Send("{w down}")
    Sleep 126
    Send("{w up}")
    Sleep 8
    Send("{w up}")
    Send("{v up}")
    Send("{z up}")
    Sleep 0
    Send("{e down}")
    Send("{e down}")
    Sleep 131
    Send("{e up}")
    Sleep 8
    Send("{e up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Send("{v down}")
    Send("{z down}")
    Sleep 274
    Send("{u up}")
    Send("{u up}")
    Send("{v up}")
    Send("{z up}")
    Sleep 0
    Send("{y down}")
    Send("{y down}")
    Sleep 139
    Send("{v down}")
    Send("{z down}")
    Sleep 139
    Send("{y up}")
    Sleep 0
    Send("{t down}")
    Send("{t down}")
    Sleep 8
    Send("{y up}")
    Sleep 128
    Send("{v up}")
    Send("{z up}")
    Sleep 141
    Send("{t up}")
    Send("{t up}")
    Sleep 1
    Send("{w down}")
    Send("{w down}")
    Send("{b down}")
    Send("{x down}")
    Sleep 282
    Send("{w up}")
    Send("{w up}")
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{q down}")
    Send("{q down}")
    Sleep 138
    Send("{b down}")
    Send("{x down}")
    Sleep 138
    Send("{q up}")
    Sleep 0
    Send("{u down}")
    Send("{u down}")
    Sleep 8
    Send("{q up}")
    Sleep 126
    Send("{b up}")
    Send("{x up}")
    Sleep 139
    Send("{u up}")
    Send("{u up}")
    Sleep 0
    Send("{u down}")
    Send("{t down}")
    Send("{u down}")
    Send("{b down}")
    Send("{x down}")
    Sleep 139
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{b down}")
    Send("{x down}")
    Sleep 135
    Send("{u up}")
    Send("{t up}")
    Send("{u up}")
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Send("{b down}")
    Send("{x down}")
    Sleep 139
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{b down}")
    Send("{x down}")
    Sleep 139
    Send("{y up}")
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{t down}")
    Send("{w down}")
    Send("{t down}")
    Send("{b down}")
    Send("{x down}")
    Sleep 8
    Send("{y up}")
    Send("{e up}")
    Sleep 128
    Send("{b up}")
    Send("{x up}")
    Sleep 0
    Send("{b down}")
    Send("{x down}")
    Sleep 141
    Send("{t up}")
    Send("{w up}")
    Send("{t up}")
    Send("{x up}")
    Sleep 1
    Send("{y down}")
    Send("{e down}")
    Send("{y down}")
    Send("{n down}")
    Send("{c down}")
    Send("{n down}")
    Sleep 7
    Send("{b up}")
    Sleep 414
    Send("{y up}")
    Send("{e up}")
    Send("{y up}")
    Sleep 0
    Send("{e down}")
    Sleep 138
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{w down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{w down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{2 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{2 up}")
    Sleep 128
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{n up}")
    Send("{c up}")
    Send("{n up}")
    Sleep 0
    Send("{2 down}")
    Send("{c down}")
    Send("{c down}")
    Sleep 8
    Send("{e up}")
    Sleep 132
    Send("{y down}")
    Sleep 8
    Send("{2 up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 134
    Send("{c up}")
    Send("{c up}")
    Sleep 1
    Send("{e down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 7
    Send("{e up}")
    Sleep 143
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{e down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{e up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{3 down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{3 up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{n up}")
    Send("{n up}")
    Sleep 1
    Send("{w down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 7
    Send("{e up}")
    Sleep 140
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 130
    Send("{w down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{w up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 126
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{q down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{e up}")
    Sleep 131
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{y down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{q up}")
    Sleep 126
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{e down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{y up}")
    Sleep 129
    Send("{n up}")
    Send("{n up}")
    Sleep 0
    Send("{q down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 8
    Send("{e up}")
    Sleep 130
    Send("{y down}")
    Sleep 8
    Send("{q up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 127
    Send("{e down}")
    Sleep 8
    Send("{y up}")
    Sleep 131
    Send("{y down}")
    Send("{y down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 7
    Send("{e up}")
    Sleep 264
    Send("{y up}")
    Sleep 73
    Send("{2 down}")
    Sleep 34
    Send("{2 up}")
    Send("{e down}")
    Sleep 34
    Send("{e up}")
    Sleep 2
    Send("{y down}")
    Send("{y down}")
    Sleep 6
    Send("{y up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 55
    Send("{y up}")
    Send("{y up}")
    Sleep 83
    Send("{n down}")
    Send("{y down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 51
    Send("{n up}")
    Send("{y up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 83
    Send("{n down}")
    Send("{y down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 56
    Send("{n up}")
    Send("{y up}")
    Send("{n up}")
    Send("{n up}")
    Sleep 83
    Send("{n down}")
    Send("{y down}")
    Send("{n down}")
    Send("{n down}")
    Sleep 411
    Send("{n up}")
    Send("{y up}")
    Send("{n up}")
    Send("{n up}")
}
