#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{m down}")
    Send("{e down}")
    Sleep 400
    Send("{e up}")
    Send("{m up}")
    Sleep 8
    Send("{h down}")
    Send("{m down}")
    Sleep 197
    Send("{n down}")
    Send("{q down}")
    Sleep 3
    Send("{m up}")
    Send("{h up}")
    Sleep 196
    Send("{m down}")
    Send("{w down}")
    Sleep 1
    Send("{q up}")
    Send("{n up}")
    Sleep 198
    Send("{e down}")
    Sleep 1
    Send("{w up}")
    Send("{m up}")
    Sleep 96
    Send("{w down}")
    Sleep 3
    Send("{e up}")
    Sleep 97
    Send("{w up}")
    Sleep 1
    Send("{n down}")
    Send("{q down}")
    Sleep 197
    Send("{h down}")
    Send("{m down}")
    Sleep 3
    Send("{q up}")
    Send("{n up}")
    Sleep 197
    Send("{m up}")
    Send("{h up}")
    Send("{c down}")
    Send("{n down}")
    Sleep 400
    Send("{n up}")
    Send("{c up}")
    Sleep 10
    Send("{c down}")
    Send("{n down}")
    Sleep 197
    Send("{n down}")
    Send("{q down}")
    Sleep 3
    Send("{n up}")
    Send("{c up}")
    Sleep 196
    Send("{q down}")
    Send("{e down}")
    Sleep 1
    Send("{q up}")
    Send("{n up}")
    Sleep 396
    Send("{m down}")
    Send("{w down}")
    Sleep 3
    Send("{e up}")
    Send("{q up}")
    Sleep 194
    Send("{n down}")
    Send("{q down}")
    Sleep 3
    Send("{w up}")
    Send("{m up}")
    Sleep 197
    Send("{q up}")
    Send("{n up}")
    Send("{h down}")
    Send("{m down}")
    Sleep 200
    Send("{h up}")
    Sleep 11
    Send("{c down}")
    Sleep 189
    Send("{m up}")
    Sleep 10
    Send("{h down}")
    Sleep 1
    Send("{c up}")
    Sleep 196
    Send("{q down}")
    Send("{h down}")
    Sleep 3
    Send("{h up}")
    Sleep 196
    Send("{w down}")
    Send("{m down}")
    Sleep 1
    Send("{h up}")
    Send("{q up}")
    Sleep 396
    Send("{e down}")
    Send("{q down}")
    Sleep 3
    Send("{m up}")
    Send("{w up}")
    Sleep 394
    Send("{n down}")
    Send("{q down}")
    Sleep 3
    Send("{q up}")
    Send("{e up}")
    Sleep 397
    Send("{q up}")
    Send("{n up}")
    Sleep 10
    Send("{c down}")
    Send("{n down}")
    Sleep 396
    Send("{c down}")
    Send("{n down}")
    Sleep 4
    Send("{n up}")
    Send("{c up}")
    Sleep 396
    Send("{n up}")
    Send("{c up}")
    Sleep 605
    Send("{w down}")
    Send("{v down}")
    Sleep 396
    Send("{r down}")
    Send("{n down}")
    Sleep 4
    Send("{v up}")
    Send("{w up}")
    Sleep 195
    Send("{q down}")
    Send("{y down}")
    Sleep 1
    Send("{n up}")
    Send("{r up}")
    Sleep 198
    Send("{q down}")
    Sleep 1
    Send("{q up}")
    Sleep 96
    Send("{q down}")
    Sleep 3
    Send("{q up}")
    Sleep 97
    Send("{q up}")
    Sleep 1
    Send("{t down}")
    Send("{m down}")
    Sleep 3
    Send("{y up}")
    Sleep 194
    Send("{r down}")
    Send("{n down}")
    Sleep 3
    Send("{m up}")
    Send("{t up}")
    Sleep 197
    Send("{n up}")
    Send("{r up}")
    Send("{e down}")
    Send("{b down}")
    Sleep 400
    Send("{b up}")
    Send("{e up}")
    Sleep 207
    Send("{q down}")
    Send("{c down}")
    Sleep 199
    Send("{b down}")
    Send("{e down}")
    Sleep 1
    Send("{c up}")
    Send("{q up}")
    Sleep 198
    Send("{n down}")
    Sleep 1
    Send("{b up}")
    Sleep 96
    Send("{b down}")
    Sleep 3
    Send("{n up}")
    Sleep 97
    Send("{b up}")
    Sleep 1
    Send("{w down}")
    Send("{v down}")
    Sleep 3
    Send("{e up}")
    Sleep 194
    Send("{q down}")
    Send("{c down}")
    Sleep 3
    Send("{v up}")
    Send("{w up}")
    Sleep 197
    Send("{c up}")
    Send("{q up}")
    Send("{h down}")
    Send("{m down}")
    Sleep 200
    Send("{h up}")
    Sleep 11
    Send("{c down}")
    Sleep 189
    Send("{m up}")
    Sleep 10
    Send("{m down}")
    Send("{h down}")
    Sleep 1
    Send("{c up}")
    Sleep 196
    Send("{q down}")
    Send("{n down}")
    Sleep 3
    Send("{h up}")
    Send("{m up}")
    Sleep 196
    Send("{m down}")
    Send("{w down}")
    Sleep 1
    Send("{n up}")
    Send("{q up}")
    Sleep 198
    Send("{h down}")
    Sleep 1
    Send("{m up}")
    Sleep 197
    Send("{q down}")
    Send("{e down}")
    Sleep 2
    Send("{h up}")
    Sleep 1
    Send("{w up}")
    Sleep 194
    Send("{h down}")
    Sleep 3
    Send("{q up}")
    Sleep 197
    Send("{h up}")
    Send("{n down}")
    Send("{q down}")
    Sleep 3
    Send("{e up}")
    Sleep 197
    Send("{n up}")
    Sleep 11
    Send("{c down}")
    Sleep 189
    Send("{q up}")
    Sleep 10
    Send("{n down}")
    Send("{c down}")
    Sleep 1
    Send("{c up}")
    Sleep 395
    Send("{n down}")
    Send("{c down}")
    Sleep 4
    Send("{c up}")
    Send("{n up}")
    Sleep 396
    Send("{c up}")
    Send("{n up}")
    Sleep 396
    Send("{m down}")
    Send("{e down}")
    Sleep 400
    Send("{e up}")
    Send("{m up}")
    Sleep 8
    Send("{h down}")
    Send("{m down}")
    Sleep 197
    Send("{n down}")
    Send("{q down}")
    Sleep 3
    Send("{m up}")
    Send("{h up}")
    Sleep 196
    Send("{m down}")
    Send("{w down}")
    Sleep 1
    Send("{q up}")
    Send("{n up}")
    Sleep 198
    Send("{e down}")
    Sleep 1
    Send("{w up}")
    Send("{m up}")
    Sleep 96
    Send("{w down}")
    Sleep 3
    Send("{e up}")
    Sleep 97
    Send("{w up}")
    Sleep 1
    Send("{n down}")
    Send("{q down}")
    Sleep 197
    Send("{h down}")
    Send("{m down}")
    Sleep 3
    Send("{q up}")
    Send("{n up}")
    Sleep 197
    Send("{m up}")
    Send("{h up}")
    Send("{c down}")
    Send("{n down}")
    Sleep 400
    Send("{n up}")
    Send("{c up}")
    Sleep 10
    Send("{c down}")
    Send("{n down}")
    Sleep 197
    Send("{n down}")
    Send("{q down}")
    Sleep 3
    Send("{n up}")
    Send("{c up}")
    Sleep 196
    Send("{q down}")
    Send("{e down}")
    Sleep 1
    Send("{q up}")
    Send("{n up}")
    Sleep 396
    Send("{m down}")
    Send("{w down}")
    Sleep 3
    Send("{e up}")
    Send("{q up}")
    Sleep 194
    Send("{n down}")
    Send("{q down}")
    Sleep 3
    Send("{w up}")
    Send("{m up}")
    Sleep 197
    Send("{q up}")
    Send("{n up}")
    Send("{h down}")
    Send("{m down}")
    Sleep 200
    Send("{h up}")
    Sleep 11
    Send("{c down}")
    Sleep 189
    Send("{m up}")
    Sleep 10
    Send("{h down}")
    Sleep 1
    Send("{c up}")
    Sleep 196
    Send("{q down}")
    Send("{h down}")
    Sleep 3
    Send("{h up}")
    Sleep 196
    Send("{w down}")
    Send("{m down}")
    Sleep 1
    Send("{h up}")
    Send("{q up}")
    Sleep 396
    Send("{e down}")
    Send("{q down}")
    Sleep 3
    Send("{m up}")
    Send("{w up}")
    Sleep 394
    Send("{n down}")
    Send("{q down}")
    Sleep 3
    Send("{q up}")
    Send("{e up}")
    Sleep 397
    Send("{q up}")
    Send("{n up}")
    Sleep 10
    Send("{c down}")
    Send("{n down}")
    Sleep 396
    Send("{c down}")
    Send("{n down}")
    Sleep 4
    Send("{n up}")
    Send("{c up}")
    Sleep 396
    Send("{n up}")
    Send("{c up}")
    Sleep 605
    Send("{w down}")
    Send("{v down}")
    Sleep 396
    Send("{r down}")
    Send("{n down}")
    Sleep 4
    Send("{v up}")
    Send("{w up}")
    Sleep 195
    Send("{q down}")
    Send("{y down}")
    Sleep 1
    Send("{n up}")
    Send("{r up}")
    Sleep 198
    Send("{q down}")
    Sleep 1
    Send("{q up}")
    Sleep 96
    Send("{q down}")
    Sleep 3
    Send("{q up}")
    Sleep 97
    Send("{q up}")
    Sleep 1
    Send("{t down}")
    Send("{m down}")
    Sleep 3
    Send("{y up}")
    Sleep 194
    Send("{r down}")
    Send("{n down}")
    Sleep 3
    Send("{m up}")
    Send("{t up}")
    Sleep 197
    Send("{n up}")
    Send("{r up}")
    Send("{e down}")
    Send("{b down}")
    Sleep 400
    Send("{b up}")
    Send("{e up}")
    Sleep 207
    Send("{q down}")
    Send("{c down}")
    Sleep 199
    Send("{b down}")
    Send("{e down}")
    Sleep 1
    Send("{c up}")
    Send("{q up}")
    Sleep 198
    Send("{n down}")
    Sleep 1
    Send("{b up}")
    Sleep 96
    Send("{b down}")
    Sleep 3
    Send("{n up}")
    Sleep 97
    Send("{b up}")
    Sleep 1
    Send("{w down}")
    Send("{v down}")
    Sleep 3
    Send("{e up}")
    Sleep 194
    Send("{q down}")
    Send("{c down}")
    Sleep 3
    Send("{v up}")
    Send("{w up}")
    Sleep 197
    Send("{c up}")
    Send("{q up}")
    Send("{h down}")
    Send("{m down}")
    Sleep 200
    Send("{h up}")
    Sleep 11
    Send("{c down}")
    Sleep 189
    Send("{m up}")
    Sleep 10
    Send("{m down}")
    Send("{h down}")
    Sleep 1
    Send("{c up}")
    Sleep 196
    Send("{q down}")
    Send("{n down}")
    Sleep 3
    Send("{h up}")
    Send("{m up}")
    Sleep 196
    Send("{m down}")
    Send("{w down}")
    Sleep 1
    Send("{n up}")
    Send("{q up}")
    Sleep 198
    Send("{h down}")
    Sleep 1
    Send("{m up}")
    Sleep 197
    Send("{q down}")
    Send("{e down}")
    Sleep 2
    Send("{h up}")
    Sleep 1
    Send("{w up}")
    Sleep 194
    Send("{h down}")
    Sleep 3
    Send("{q up}")
    Sleep 197
    Send("{h up}")
    Send("{n down}")
    Send("{q down}")
    Sleep 3
    Send("{e up}")
    Sleep 197
    Send("{n up}")
    Sleep 11
    Send("{c down}")
    Sleep 189
    Send("{q up}")
    Sleep 10
    Send("{n down}")
    Send("{c down}")
    Sleep 1
    Send("{c up}")
    Sleep 395
    Send("{n down}")
    Send("{c down}")
    Sleep 4
    Send("{c up}")
    Send("{n up}")
    Sleep 396
    Send("{c up}")
    Send("{n up}")
    Sleep 394
    Send("{z down}")
    Send("{c down}")
    Sleep 800
    Send("{c up}")
    Send("{z up}")
    Sleep 6
    Send("{z down}")
    Sleep 794
    Send("{m down}")
    Send("{x down}")
    Sleep 6
    Send("{z up}")
    Sleep 794
    Send("{x up}")
    Send("{m up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Sleep 794
    Send("{n down}")
    Send("{z down}")
    Sleep 6
    Send("{m up}")
    Send("{h up}")
    Sleep 794
    Send("{z up}")
    Send("{n up}")
    Sleep 6
    Send("{c down}")
    Send("{n down}")
    Sleep 794
    Send("{c down}")
    Send("{h down}")
    Sleep 6
    Send("{n up}")
    Send("{c up}")
    Sleep 794
    Send("{h up}")
    Send("{c up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Sleep 400
    Send("{m up}")
    Send("{h up}")
    Sleep 394
    Send("{z down}")
    Send("{c down}")
    Sleep 800
    Send("{c up}")
    Send("{z up}")
    Sleep 6
    Send("{n down}")
    Send("{z down}")
    Sleep 794
    Send("{m down}")
    Send("{x down}")
    Sleep 6
    Send("{z up}")
    Send("{n up}")
    Sleep 794
    Send("{x up}")
    Send("{m up}")
    Sleep 6
    Send("{h down}")
    Send("{m down}")
    Sleep 794
    Send("{n down}")
    Send("{z down}")
    Sleep 6
    Send("{m up}")
    Send("{h up}")
    Sleep 394
    Send("{z up}")
    Send("{n up}")
    Sleep 10
    Send("{z down}")
    Send("{c down}")
    Sleep 388
    Send("{c down}")
    Send("{n down}")
    Send("{c down}")
    Sleep 8
    Send("{n down}")
    Sleep 4
    Send("{c up}")
    Send("{z up}")
    Sleep 196
    Send("{n up}")
    Sleep 592
    Send("{c up}")
    Send("{n up}")
    Send("{c up}")
    Send("{x down}")
    Send("{h down}")
    Sleep 2
    Send("{h down}")
    Sleep 200
    Send("{h up}")
    Sleep 598
    Send("{h up}")
    Send("{x up}")
}
