#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{7 down}")
    Sleep 416
    Send("{7 up}")
    Sleep 1
    Send("{q down}")
    Sleep 416
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 416
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{t down}")
    Sleep 207
    Send("{t up}")
    Sleep 209
    Send("{q down}")
    Sleep 416
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 416
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Sleep 416
    Send("{t up}")
    Sleep 1
    Send("{t down}")
    Sleep 207
    Send("{t up}")
    Sleep 1
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 418
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{3 down}")
    Sleep 416
    Send("{3 up}")
    Sleep 1
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{w down}")
    Sleep 1041
    Send("{w up}")
    Sleep 626
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 416
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 416
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 416
    Send("{q up}")
    Sleep 1459
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{y down}")
    Sleep 207
    Send("{y up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 416
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 416
    Send("{7 up}")
    Sleep 1251
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{q down}")
    Sleep 416
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 416
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 207
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Sleep 207
    Send("{t up}")
    Sleep 209
    Send("{q down}")
    Sleep 416
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 416
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Sleep 416
    Send("{t up}")
    Sleep 1
    Send("{t down}")
    Sleep 207
    Send("{t up}")
    Sleep 1
    Send("{r down}")
    Sleep 416
    Send("{r up}")
    Sleep 209
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{3 down}")
    Sleep 416
    Send("{3 up}")
    Sleep 1
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{w down}")
    Sleep 832
    Send("{w up}")
    Sleep 834
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 416
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 416
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 416
    Send("{q up}")
    Sleep 1459
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{y down}")
    Sleep 207
    Send("{y up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 416
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{y down}")
    Sleep 103
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 103
    Send("{y up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{y down}")
    Sleep 103
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{y down}")
    Sleep 103
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{t down}")
    Sleep 207
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{q down}")
    Sleep 103
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{r down}")
    Sleep 103
    Send("{r up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{t down}")
    Sleep 207
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{q down}")
    Sleep 103
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{t down}")
    Sleep 207
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{q down}")
    Sleep 103
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 105
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{t down}")
    Sleep 207
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{q down}")
    Sleep 103
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{r down}")
    Sleep 103
    Send("{r up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 105
    Send("{3 down}")
    Sleep 103
    Send("{3 up}")
    Sleep 209
    Send("{y down}")
    Sleep 103
    Send("{y up}")
    Sleep 105
    Send("{r down}")
    Sleep 103
    Send("{r up}")
    Sleep 1
    Send("{t down}")
    Sleep 103
    Send("{t up}")
    Sleep 105
    Send("{3 down}")
    Sleep 103
    Send("{3 up}")
    Sleep 209
    Send("{y down}")
    Sleep 207
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 418
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 312
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 626
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{r down}")
    Sleep 416
    Send("{r up}")
    Sleep 1
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1459
    Send("{y down}")
    Sleep 207
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 103
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 416
    Send("{7 up}")
    Sleep 313
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 209
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 312
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 416
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 418
    Send("{w down}")
    Sleep 416
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 624
    Send("{q up}")
    Sleep 1
    Send("{y down}")
    Sleep 207
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1459
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 209
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 209
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 209
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 209
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 103
    Send("{w up}")
    Sleep 209
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{w down}")
    Sleep 624
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 207
    Send("{w up}")
    Sleep 1
    Send("{w down}")
    Sleep 312
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{w down}")
    Sleep 312
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 312
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{r down}")
    Sleep 416
    Send("{r up}")
    Sleep 1
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{w down}")
    Sleep 312
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 312
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{r down}")
    Sleep 416
    Send("{r up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{y down}")
    Sleep 207
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Sleep 312
    Send("{t up}")
    Sleep 1
    Send("{r down}")
    Sleep 312
    Send("{r up}")
    Sleep 1
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{r down}")
    Sleep 312
    Send("{r up}")
    Sleep 1
    Send("{w down}")
    Sleep 312
    Send("{w up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 312
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Sleep 416
    Send("{t up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 832
    Send("{7 up}")
    Sleep 834
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 312
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{r down}")
    Sleep 416
    Send("{r up}")
    Sleep 209
    Send("{w down}")
    Sleep 312
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 312
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{r down}")
    Sleep 416
    Send("{r up}")
    Sleep 1
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{w down}")
    Sleep 312
    Send("{w up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 207
    Send("{q up}")
    Sleep 1
    Send("{q down}")
    Sleep 312
    Send("{q up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 312
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{r down}")
    Sleep 416
    Send("{r up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{y down}")
    Sleep 207
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Sleep 312
    Send("{t up}")
    Sleep 1
    Send("{r down}")
    Sleep 312
    Send("{r up}")
    Sleep 1
    Send("{r down}")
    Sleep 207
    Send("{r up}")
    Sleep 1
    Send("{r down}")
    Sleep 312
    Send("{r up}")
    Sleep 1
    Send("{w down}")
    Sleep 312
    Send("{w up}")
    Sleep 1
    Send("{7 down}")
    Sleep 207
    Send("{7 up}")
    Sleep 1
    Send("{7 down}")
    Sleep 312
    Send("{7 up}")
    Sleep 1
    Send("{y down}")
    Sleep 312
    Send("{y up}")
    Sleep 1
    Send("{t down}")
    Sleep 416
    Send("{t up}")
    Sleep 1
    Send("{y down}")
    Sleep 416
    Send("{y up}")
    Sleep 1
    Send("{7 down}")
    Sleep 1874
    Send("{7 up}")
}
