#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"
SetWorkingDir A_ScriptDir

~::PlaySong()
Esc::ExitApp()

PlaySong() {
    Send("{w down}")
    Send("{5 down}")
    Send("{m down}")
    Sleep 209
    Send("{w up}")
    Send("{5 up}")
    Send("{m up}")
    Sleep 300
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 150
    Send("{y down}")
    Send("{2 down}")
    Sleep 99
    Send("{y up}")
    Send("{2 up}")
    Sleep 399
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 397
    Send("{w down}")
    Send("{5 down}")
    Sleep 97
    Send("{w up}")
    Send("{5 up}")
    Sleep 152
    Send("{w down}")
    Send("{h down}")
    Sleep 114
    Send("{w up}")
    Send("{h up}")
    Sleep 150
    Send("{w down}")
    Send("{h down}")
    Sleep 98
    Send("{w up}")
    Send("{h up}")
    Sleep 150
    Send("{w down}")
    Send("{h down}")
    Sleep 96
    Send("{w up}")
    Send("{h up}")
    Sleep 1142
    Send("{2 down}")
    Send("{v down}")
    Sleep 250
    Send("{w down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 27
    Send("{2 up}")
    Send("{v up}")
    Sleep 87
    Send("{w up}")
    Sleep 76
    Send("{g up}")
    Sleep 74
    Send("{w down}")
    Send("{5 down}")
    Sleep 33
    Send("{m up}")
    Sleep 65
    Send("{w up}")
    Send("{5 up}")
    Sleep 150
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 150
    Send("{y down}")
    Send("{2 down}")
    Sleep 99
    Send("{y up}")
    Send("{2 up}")
    Sleep 399
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 397
    Send("{w down}")
    Send("{5 down}")
    Sleep 97
    Send("{w up}")
    Send("{5 up}")
    Sleep 152
    Send("{e down}")
    Send("{6 down}")
    Send("{e down}")
    Send("{h down}")
    Sleep 759
    Send("{e up}")
    Send("{6 up}")
    Send("{e up}")
    Send("{h up}")
    Sleep 0
    Send("{3 down}")
    Send("{t down}")
    Send("{3 down}")
    Send("{b down}")
    Sleep 234
    Send("{3 up}")
    Send("{t up}")
    Send("{b up}")
    Sleep 15
    Send("{3 up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Send("{w down}")
    Send("{g down}")
    Sleep 195
    Send("{w up}")
    Send("{5 up}")
    Send("{w up}")
    Send("{g up}")
    Sleep 796
    Send("{6 down}")
    Send("{n down}")
    Sleep 114
    Send("{6 up}")
    Send("{n up}")
    Sleep 398
    Send("{2 down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 82
    Send("{e up}")
    Sleep 15
    Send("{2 up}")
    Send("{2 up}")
    Sleep 150
    Send("{5 down}")
    Sleep 99
    Send("{5 up}")
    Sleep 399
    Send("{2 down}")
    Send("{c down}")
    Sleep 96
    Send("{2 up}")
    Send("{c up}")
    Sleep 397
    Send("{6 down}")
    Send("{h down}")
    Sleep 97
    Send("{6 up}")
    Send("{h up}")
    Sleep 417
    Send("{2 down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 98
    Send("{2 up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 397
    Send("{t down}")
    Send("{b down}")
    Sleep 249
    Send("{5 down}")
    Send("{g down}")
    Sleep 29
    Send("{t up}")
    Send("{b up}")
    Sleep 183
    Send("{5 up}")
    Send("{g up}")
    Sleep 284
    Send("{e down}")
    Send("{2 down}")
    Sleep 96
    Send("{e up}")
    Send("{2 up}")
    Sleep 400
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 114
    Send("{g up}")
    Send("{q up}")
    Send("{x up}")
    Sleep 150
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 98
    Send("{g up}")
    Send("{q up}")
    Send("{x up}")
    Sleep 150
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 82
    Send("{q up}")
    Sleep 15
    Send("{g up}")
    Send("{x up}")
    Sleep 895
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{q up}")
    Send("{x up}")
    Sleep 150
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 97
    Send("{g up}")
    Send("{q up}")
    Send("{x up}")
    Sleep 152
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 114
    Send("{g up}")
    Send("{x up}")
    Sleep 15
    Send("{q up}")
    Sleep 879
    Send("{h down}")
    Send("{m down}")
    Send("{3 down}")
    Sleep 495
    Send("{h up}")
    Send("{m up}")
    Send("{3 up}")
    Sleep 0
    Send("{b down}")
    Send("{j down}")
    Send("{w down}")
    Sleep 494
    Send("{b up}")
    Send("{j up}")
    Send("{w up}")
    Sleep 2
    Send("{w down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{n down}")
    Send("{2 down}")
    Sleep 212
    Send("{w up}")
    Send("{5 up}")
    Sleep 37
    Send("{g up}")
    Send("{n up}")
    Send("{2 up}")
    Sleep 263
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 150
    Send("{y down}")
    Send("{2 down}")
    Sleep 99
    Send("{y up}")
    Send("{2 up}")
    Sleep 399
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 397
    Send("{3 down}")
    Send("{5 down}")
    Send("{w down}")
    Sleep 247
    Send("{5 up}")
    Send("{w up}")
    Sleep 2
    Send("{e down}")
    Send("{h down}")
    Send("{w down}")
    Sleep 27
    Send("{3 up}")
    Sleep 87
    Send("{e up}")
    Send("{h up}")
    Send("{w up}")
    Sleep 150
    Send("{e down}")
    Send("{h down}")
    Send("{w down}")
    Sleep 98
    Send("{e up}")
    Send("{h up}")
    Send("{w up}")
    Sleep 150
    Send("{e down}")
    Send("{h down}")
    Send("{w down}")
    Sleep 82
    Send("{w up}")
    Sleep 15
    Send("{e up}")
    Send("{h up}")
    Sleep 399
    Send("{6 down}")
    Send("{e down}")
    Sleep 99
    Send("{6 up}")
    Send("{e up}")
    Sleep 150
    Send("{6 down}")
    Send("{e down}")
    Sleep 96
    Send("{6 up}")
    Send("{e up}")
    Sleep 150
    Send("{6 down}")
    Send("{e down}")
    Sleep 82
    Send("{e up}")
    Sleep 15
    Send("{6 up}")
    Sleep 400
    Send("{m down}")
    Sleep 212
    Send("{m up}")
    Sleep 52
    Send("{w down}")
    Send("{5 down}")
    Sleep 98
    Send("{w up}")
    Send("{5 up}")
    Sleep 150
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 150
    Send("{y down}")
    Send("{2 down}")
    Sleep 99
    Send("{y up}")
    Send("{2 up}")
    Sleep 401
    Send("{5 down}")
    Send("{y down}")
    Sleep 97
    Send("{5 up}")
    Send("{y up}")
    Sleep 407
    Send("{w down}")
    Send("{5 down}")
    Sleep 101
    Send("{w up}")
    Send("{5 up}")
    Sleep 158
    Send("{e down}")
    Send("{6 down}")
    Send("{2 down}")
    Send("{c down}")
    Sleep 1013
    Send("{e up}")
    Send("{6 up}")
    Send("{2 up}")
    Send("{c up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Send("{u down}")
    Send("{x down}")
    Sleep 195
    Send("{w up}")
    Send("{5 up}")
    Send("{u up}")
    Send("{x up}")
    Sleep 796
    Send("{u down}")
    Send("{c down}")
    Sleep 250
    Send("{u up}")
    Sleep 15
    Send("{t down}")
    Sleep 233
    Send("{t up}")
    Sleep 15
    Send("{c up}")
    Sleep 0
    Send("{w down}")
    Send("{m down}")
    Sleep 96
    Send("{m up}")
    Sleep 135
    Send("{w up}")
    Sleep 15
    Send("{2 down}")
    Send("{n down}")
    Sleep 483
    Send("{2 up}")
    Send("{n up}")
    Sleep 15
    Send("{u down}")
    Send("{n down}")
    Send("{2 down}")
    Sleep 96
    Send("{n up}")
    Send("{2 up}")
    Sleep 135
    Send("{u up}")
    Sleep 15
    Send("{t down}")
    Sleep 231
    Send("{t up}")
    Sleep 15
    Send("{2 down}")
    Sleep 232
    Send("{2 up}")
    Sleep 17
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{y up}")
    Sleep 15
    Send("{5 down}")
    Sleep 233
    Send("{5 up}")
    Sleep 15
    Send("{x up}")
    Sleep 0
    Send("{q down}")
    Send("{n down}")
    Sleep 96
    Send("{n up}")
    Sleep 135
    Send("{q up}")
    Sleep 15
    Send("{m down}")
    Send("{b down}")
    Sleep 483
    Send("{m up}")
    Send("{b up}")
    Sleep 15
    Send("{r down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 96
    Send("{b up}")
    Send("{m up}")
    Sleep 135
    Send("{r up}")
    Sleep 15
    Send("{w down}")
    Sleep 231
    Send("{w up}")
    Sleep 15
    Send("{m down}")
    Sleep 232
    Send("{m up}")
    Sleep 17
    Send("{g down}")
    Send("{2 down}")
    Send("{m down}")
    Send("{c down}")
    Sleep 114
    Send("{g up}")
    Send("{2 up}")
    Send("{m up}")
    Send("{c up}")
    Sleep 150
    Send("{g down}")
    Send("{2 down}")
    Send("{m down}")
    Send("{c down}")
    Sleep 98
    Send("{g up}")
    Send("{2 up}")
    Send("{m up}")
    Send("{c up}")
    Sleep 150
    Send("{g down}")
    Send("{2 down}")
    Send("{m down}")
    Send("{c down}")
    Sleep 82
    Send("{2 up}")
    Sleep 15
    Send("{g up}")
    Send("{m up}")
    Sleep 15
    Send("{c up}")
    Sleep 1126
    Send("{7 down}")
    Send("{s down}")
    Sleep 250
    Send("{u down}")
    Send("{x down}")
    Sleep 27
    Send("{7 up}")
    Send("{s up}")
    Sleep 129
    Send("{u up}")
    Send("{x up}")
    Sleep 108
    Send("{2 down}")
    Send("{b down}")
    Sleep 248
    Send("{w down}")
    Send("{h down}")
    Sleep 29
    Send("{2 up}")
    Send("{b up}")
    Sleep 109
    Send("{w up}")
    Send("{h up}")
    Sleep 108
    Send("{5 down}")
    Send("{2 down}")
    Sleep 249
    Send("{y down}")
    Send("{t down}")
    Sleep 29
    Send("{5 up}")
    Send("{2 up}")
    Sleep 112
    Send("{y up}")
    Send("{t up}")
    Sleep 1859
    Send("{n down}")
    Sleep 496
    Send("{j down}")
    Sleep 19
    Send("{n up}")
    Sleep 477
    Send("{m down}")
    Send("{c down}")
    Sleep 17
    Send("{j up}")
    Sleep 495
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Send("{b down}")
    Sleep 231
    Send("{c up}")
    Sleep 15
    Send("{b up}")
    Sleep 0
    Send("{j down}")
    Send("{m down}")
    Sleep 29
    Send("{m up}")
    Sleep 220
    Send("{m down}")
    Sleep 29
    Send("{j up}")
    Sleep 205
    Send("{m up}")
    Sleep 15
    Send("{c down}")
    Send("{b down}")
    Sleep 740
    Send("{c up}")
    Send("{b up}")
    Sleep 2
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Sleep 15
    Send("{c down}")
    Send("{b down}")
    Sleep 226
    Send("{m up}")
    Sleep 22
    Send("{n down}")
    Sleep 246
    Send("{c up}")
    Send("{b up}")
    Sleep 0
    Send("{j down}")
    Send("{c down}")
    Sleep 29
    Send("{n up}")
    Sleep 220
    Send("{m down}")
    Sleep 29
    Send("{j up}")
    Sleep 220
    Send("{5 down}")
    Sleep 29
    Send("{m up}")
    Sleep 217
    Send("{c up}")
    Sleep 0
    Send("{g down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 247
    Send("{2 down}")
    Sleep 19
    Send("{5 up}")
    Sleep 228
    Send("{g up}")
    Send("{b up}")
    Send("{m up}")
    Sleep 2
    Send("{m down}")
    Send("{x down}")
    Sleep 27
    Send("{2 up}")
    Sleep 485
    Send("{x up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 231
    Send("{g up}")
    Sleep 15
    Send("{n up}")
    Sleep 0
    Send("{j down}")
    Send("{n down}")
    Sleep 29
    Send("{m up}")
    Sleep 220
    Send("{m down}")
    Sleep 29
    Send("{j up}")
    Sleep 205
    Send("{n up}")
    Sleep 15
    Send("{g down}")
    Send("{n down}")
    Sleep 493
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Sleep 232
    Send("{s up}")
    Sleep 17
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Sleep 15
    Send("{g down}")
    Send("{n down}")
    Sleep 494
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 249
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Sleep 495
    Send("{n up}")
    Sleep 0
    Send("{q down}")
    Send("{g down}")
    Send("{n down}")
    Sleep 19
    Send("{m up}")
    Sleep 475
    Send("{g up}")
    Send("{n up}")
    Sleep 2
    Send("{2 down}")
    Send("{g down}")
    Sleep 17
    Send("{q up}")
    Sleep 495
    Send("{g up}")
    Sleep 0
    Send("{d down}")
    Send("{m down}")
    Sleep 231
    Send("{d up}")
    Sleep 15
    Send("{m up}")
    Sleep 0
    Send("{q down}")
    Send("{s down}")
    Sleep 29
    Send("{2 up}")
    Sleep 220
    Send("{2 down}")
    Sleep 29
    Send("{q up}")
    Sleep 219
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Send("{j down}")
    Sleep 493
    Send("{s up}")
    Send("{j up}")
    Sleep 0
    Send("{v down}")
    Sleep 232
    Send("{v up}")
    Sleep 17
    Send("{g down}")
    Sleep 250
    Send("{g up}")
    Sleep 15
    Send("{s down}")
    Send("{j down}")
    Sleep 248
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 246
    Send("{s up}")
    Send("{j up}")
    Sleep 0
    Send("{q down}")
    Send("{s down}")
    Sleep 29
    Send("{2 up}")
    Sleep 220
    Send("{2 down}")
    Sleep 29
    Send("{q up}")
    Sleep 220
    Send("{6 down}")
    Sleep 29
    Send("{2 up}")
    Sleep 217
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Send("{j down}")
    Sleep 247
    Send("{3 down}")
    Sleep 19
    Send("{6 up}")
    Sleep 228
    Send("{s up}")
    Send("{j up}")
    Sleep 2
    Send("{2 down}")
    Send("{g down}")
    Sleep 27
    Send("{3 up}")
    Sleep 485
    Send("{g up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 231
    Send("{g up}")
    Sleep 15
    Send("{n up}")
    Sleep 0
    Send("{3 down}")
    Send("{m down}")
    Sleep 29
    Send("{2 up}")
    Sleep 220
    Send("{m down}")
    Sleep 29
    Send("{3 up}")
    Sleep 205
    Send("{m up}")
    Sleep 15
    Send("{g down}")
    Send("{n down}")
    Sleep 471
    Send("{m up}")
    Sleep 22
    Send("{2 down}")
    Sleep 247
    Send("{g up}")
    Send("{n up}")
    Sleep 2
    Send("{w down}")
    Send("{c down}")
    Sleep 27
    Send("{2 up}")
    Sleep 129
    Send("{w up}")
    Sleep 108
    Send("{5 down}")
    Send("{y down}")
    Sleep 194
    Send("{5 up}")
    Send("{y up}")
    Sleep 300
    Send("{w down}")
    Sleep 234
    Send("{w up}")
    Sleep 15
    Send("{c up}")
    Sleep 0
    Send("{e down}")
    Send("{6 down}")
    Send("{s down}")
    Send("{m down}")
    Sleep 99
    Send("{e up}")
    Send("{6 up}")
    Send("{s up}")
    Send("{m up}")
    Sleep 150
    Send("{e down}")
    Send("{6 down}")
    Send("{s down}")
    Send("{m down}")
    Sleep 96
    Send("{e up}")
    Send("{6 up}")
    Send("{s up}")
    Send("{m up}")
    Sleep 150
    Send("{e down}")
    Send("{6 down}")
    Send("{s down}")
    Send("{m down}")
    Sleep 194
    Send("{e up}")
    Send("{6 up}")
    Send("{s up}")
    Send("{m up}")
    Sleep 305
    Send("{w down}")
    Send("{5 down}")
    Send("{m down}")
    Sleep 209
    Send("{w up}")
    Send("{5 up}")
    Send("{m up}")
    Sleep 300
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 150
    Send("{y down}")
    Send("{2 down}")
    Sleep 99
    Send("{y up}")
    Send("{2 up}")
    Sleep 399
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 397
    Send("{w down}")
    Send("{5 down}")
    Sleep 97
    Send("{w up}")
    Send("{5 up}")
    Sleep 152
    Send("{w down}")
    Send("{h down}")
    Sleep 114
    Send("{w up}")
    Send("{h up}")
    Sleep 150
    Send("{w down}")
    Send("{h down}")
    Sleep 98
    Send("{w up}")
    Send("{h up}")
    Sleep 150
    Send("{w down}")
    Send("{h down}")
    Sleep 96
    Send("{w up}")
    Send("{h up}")
    Sleep 1142
    Send("{2 down}")
    Send("{v down}")
    Sleep 250
    Send("{w down}")
    Send("{m down}")
    Send("{g down}")
    Sleep 27
    Send("{2 up}")
    Send("{v up}")
    Sleep 87
    Send("{w up}")
    Sleep 76
    Send("{g up}")
    Sleep 74
    Send("{w down}")
    Send("{5 down}")
    Sleep 33
    Send("{m up}")
    Sleep 65
    Send("{w up}")
    Send("{5 up}")
    Sleep 150
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 150
    Send("{y down}")
    Send("{2 down}")
    Sleep 99
    Send("{y up}")
    Send("{2 up}")
    Sleep 399
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 397
    Send("{w down}")
    Send("{5 down}")
    Sleep 97
    Send("{w up}")
    Send("{5 up}")
    Sleep 152
    Send("{e down}")
    Send("{6 down}")
    Send("{e down}")
    Send("{h down}")
    Sleep 759
    Send("{e up}")
    Send("{6 up}")
    Send("{e up}")
    Send("{h up}")
    Sleep 0
    Send("{3 down}")
    Send("{t down}")
    Send("{3 down}")
    Send("{b down}")
    Sleep 234
    Send("{3 up}")
    Send("{t up}")
    Send("{b up}")
    Sleep 15
    Send("{3 up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Send("{w down}")
    Send("{g down}")
    Sleep 195
    Send("{w up}")
    Send("{5 up}")
    Send("{w up}")
    Send("{g up}")
    Sleep 796
    Send("{6 down}")
    Send("{n down}")
    Sleep 114
    Send("{6 up}")
    Send("{n up}")
    Sleep 398
    Send("{2 down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 82
    Send("{e up}")
    Sleep 15
    Send("{2 up}")
    Send("{2 up}")
    Sleep 150
    Send("{5 down}")
    Sleep 99
    Send("{5 up}")
    Sleep 399
    Send("{2 down}")
    Send("{c down}")
    Sleep 96
    Send("{2 up}")
    Send("{c up}")
    Sleep 397
    Send("{6 down}")
    Send("{h down}")
    Sleep 97
    Send("{6 up}")
    Send("{h up}")
    Sleep 417
    Send("{2 down}")
    Send("{2 down}")
    Send("{e down}")
    Sleep 98
    Send("{2 up}")
    Send("{2 up}")
    Send("{e up}")
    Sleep 397
    Send("{t down}")
    Send("{b down}")
    Sleep 249
    Send("{5 down}")
    Send("{g down}")
    Sleep 29
    Send("{t up}")
    Send("{b up}")
    Sleep 183
    Send("{5 up}")
    Send("{g up}")
    Sleep 284
    Send("{e down}")
    Send("{2 down}")
    Sleep 96
    Send("{e up}")
    Send("{2 up}")
    Sleep 400
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 114
    Send("{g up}")
    Send("{q up}")
    Send("{x up}")
    Sleep 150
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 98
    Send("{g up}")
    Send("{q up}")
    Send("{x up}")
    Sleep 150
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 82
    Send("{q up}")
    Sleep 15
    Send("{g up}")
    Send("{x up}")
    Sleep 895
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 96
    Send("{g up}")
    Send("{q up}")
    Send("{x up}")
    Sleep 150
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 97
    Send("{g up}")
    Send("{q up}")
    Send("{x up}")
    Sleep 152
    Send("{g down}")
    Send("{q down}")
    Send("{x down}")
    Sleep 114
    Send("{g up}")
    Send("{x up}")
    Sleep 15
    Send("{q up}")
    Sleep 879
    Send("{h down}")
    Send("{m down}")
    Send("{3 down}")
    Sleep 495
    Send("{h up}")
    Send("{m up}")
    Send("{3 up}")
    Sleep 0
    Send("{b down}")
    Send("{j down}")
    Send("{w down}")
    Sleep 494
    Send("{b up}")
    Send("{j up}")
    Send("{w up}")
    Sleep 2
    Send("{w down}")
    Send("{5 down}")
    Send("{g down}")
    Send("{n down}")
    Send("{2 down}")
    Sleep 212
    Send("{w up}")
    Send("{5 up}")
    Sleep 37
    Send("{g up}")
    Send("{n up}")
    Send("{2 up}")
    Sleep 263
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 150
    Send("{y down}")
    Send("{2 down}")
    Sleep 99
    Send("{y up}")
    Send("{2 up}")
    Sleep 399
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 397
    Send("{3 down}")
    Send("{5 down}")
    Send("{w down}")
    Sleep 247
    Send("{5 up}")
    Send("{w up}")
    Sleep 2
    Send("{e down}")
    Send("{h down}")
    Send("{w down}")
    Sleep 27
    Send("{3 up}")
    Sleep 87
    Send("{e up}")
    Send("{h up}")
    Send("{w up}")
    Sleep 150
    Send("{e down}")
    Send("{h down}")
    Send("{w down}")
    Sleep 98
    Send("{e up}")
    Send("{h up}")
    Send("{w up}")
    Sleep 150
    Send("{e down}")
    Send("{h down}")
    Send("{w down}")
    Sleep 82
    Send("{w up}")
    Sleep 15
    Send("{e up}")
    Send("{h up}")
    Sleep 399
    Send("{6 down}")
    Send("{e down}")
    Sleep 99
    Send("{6 up}")
    Send("{e up}")
    Sleep 150
    Send("{6 down}")
    Send("{e down}")
    Sleep 96
    Send("{6 up}")
    Send("{e up}")
    Sleep 150
    Send("{6 down}")
    Send("{e down}")
    Sleep 82
    Send("{e up}")
    Sleep 15
    Send("{6 up}")
    Sleep 400
    Send("{m down}")
    Sleep 212
    Send("{m up}")
    Sleep 52
    Send("{w down}")
    Send("{5 down}")
    Sleep 98
    Send("{w up}")
    Send("{5 up}")
    Sleep 150
    Send("{5 down}")
    Send("{y down}")
    Sleep 96
    Send("{5 up}")
    Send("{y up}")
    Sleep 150
    Send("{y down}")
    Send("{2 down}")
    Sleep 99
    Send("{y up}")
    Send("{2 up}")
    Sleep 401
    Send("{5 down}")
    Send("{y down}")
    Sleep 97
    Send("{5 up}")
    Send("{y up}")
    Sleep 407
    Send("{w down}")
    Send("{5 down}")
    Sleep 101
    Send("{w up}")
    Send("{5 up}")
    Sleep 158
    Send("{e down}")
    Send("{6 down}")
    Send("{2 down}")
    Send("{c down}")
    Sleep 1013
    Send("{e up}")
    Send("{6 up}")
    Send("{2 up}")
    Send("{c up}")
    Sleep 0
    Send("{w down}")
    Send("{5 down}")
    Send("{u down}")
    Send("{x down}")
    Sleep 195
    Send("{w up}")
    Send("{5 up}")
    Send("{u up}")
    Send("{x up}")
    Sleep 796
    Send("{u down}")
    Send("{c down}")
    Sleep 250
    Send("{u up}")
    Sleep 15
    Send("{t down}")
    Sleep 233
    Send("{t up}")
    Sleep 15
    Send("{c up}")
    Sleep 0
    Send("{w down}")
    Send("{m down}")
    Sleep 96
    Send("{m up}")
    Sleep 135
    Send("{w up}")
    Sleep 15
    Send("{2 down}")
    Send("{n down}")
    Sleep 483
    Send("{2 up}")
    Send("{n up}")
    Sleep 15
    Send("{u down}")
    Send("{n down}")
    Send("{2 down}")
    Sleep 96
    Send("{n up}")
    Send("{2 up}")
    Sleep 135
    Send("{u up}")
    Sleep 15
    Send("{t down}")
    Sleep 231
    Send("{t up}")
    Sleep 15
    Send("{2 down}")
    Sleep 232
    Send("{2 up}")
    Sleep 17
    Send("{y down}")
    Send("{x down}")
    Sleep 250
    Send("{y up}")
    Sleep 15
    Send("{5 down}")
    Sleep 233
    Send("{5 up}")
    Sleep 15
    Send("{x up}")
    Sleep 0
    Send("{q down}")
    Send("{n down}")
    Sleep 96
    Send("{n up}")
    Sleep 135
    Send("{q up}")
    Sleep 15
    Send("{m down}")
    Send("{b down}")
    Sleep 483
    Send("{m up}")
    Send("{b up}")
    Sleep 15
    Send("{r down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 96
    Send("{b up}")
    Send("{m up}")
    Sleep 135
    Send("{r up}")
    Sleep 15
    Send("{w down}")
    Sleep 231
    Send("{w up}")
    Sleep 15
    Send("{m down}")
    Sleep 232
    Send("{m up}")
    Sleep 17
    Send("{g down}")
    Send("{2 down}")
    Send("{m down}")
    Send("{c down}")
    Sleep 114
    Send("{g up}")
    Send("{2 up}")
    Send("{m up}")
    Send("{c up}")
    Sleep 150
    Send("{g down}")
    Send("{2 down}")
    Send("{m down}")
    Send("{c down}")
    Sleep 98
    Send("{g up}")
    Send("{2 up}")
    Send("{m up}")
    Send("{c up}")
    Sleep 150
    Send("{g down}")
    Send("{2 down}")
    Send("{m down}")
    Send("{c down}")
    Sleep 82
    Send("{2 up}")
    Sleep 15
    Send("{g up}")
    Send("{m up}")
    Sleep 15
    Send("{c up}")
    Sleep 1126
    Send("{7 down}")
    Send("{s down}")
    Sleep 250
    Send("{u down}")
    Send("{x down}")
    Sleep 27
    Send("{7 up}")
    Send("{s up}")
    Sleep 129
    Send("{u up}")
    Send("{x up}")
    Sleep 108
    Send("{2 down}")
    Send("{b down}")
    Sleep 248
    Send("{w down}")
    Send("{h down}")
    Sleep 29
    Send("{2 up}")
    Send("{b up}")
    Sleep 109
    Send("{w up}")
    Send("{h up}")
    Sleep 108
    Send("{5 down}")
    Send("{2 down}")
    Sleep 249
    Send("{y down}")
    Send("{t down}")
    Sleep 29
    Send("{5 up}")
    Send("{2 up}")
    Sleep 112
    Send("{y up}")
    Send("{t up}")
    Sleep 1859
    Send("{n down}")
    Sleep 496
    Send("{j down}")
    Sleep 19
    Send("{n up}")
    Sleep 477
    Send("{m down}")
    Send("{c down}")
    Sleep 17
    Send("{j up}")
    Sleep 495
    Send("{c up}")
    Sleep 0
    Send("{c down}")
    Send("{b down}")
    Sleep 231
    Send("{c up}")
    Sleep 15
    Send("{b up}")
    Sleep 0
    Send("{j down}")
    Send("{m down}")
    Sleep 29
    Send("{m up}")
    Sleep 220
    Send("{m down}")
    Sleep 29
    Send("{j up}")
    Sleep 205
    Send("{m up}")
    Sleep 15
    Send("{c down}")
    Send("{b down}")
    Sleep 740
    Send("{c up}")
    Send("{b up}")
    Sleep 2
    Send("{n down}")
    Sleep 250
    Send("{n up}")
    Sleep 15
    Send("{c down}")
    Send("{b down}")
    Sleep 226
    Send("{m up}")
    Sleep 22
    Send("{n down}")
    Sleep 246
    Send("{c up}")
    Send("{b up}")
    Sleep 0
    Send("{j down}")
    Send("{c down}")
    Sleep 29
    Send("{n up}")
    Sleep 220
    Send("{m down}")
    Sleep 29
    Send("{j up}")
    Sleep 220
    Send("{5 down}")
    Sleep 29
    Send("{m up}")
    Sleep 217
    Send("{c up}")
    Sleep 0
    Send("{g down}")
    Send("{b down}")
    Send("{m down}")
    Sleep 247
    Send("{2 down}")
    Sleep 19
    Send("{5 up}")
    Sleep 228
    Send("{g up}")
    Send("{b up}")
    Send("{m up}")
    Sleep 2
    Send("{m down}")
    Send("{x down}")
    Sleep 27
    Send("{2 up}")
    Sleep 485
    Send("{x up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 231
    Send("{g up}")
    Sleep 15
    Send("{n up}")
    Sleep 0
    Send("{j down}")
    Send("{n down}")
    Sleep 29
    Send("{m up}")
    Sleep 220
    Send("{m down}")
    Sleep 29
    Send("{j up}")
    Sleep 205
    Send("{n up}")
    Sleep 15
    Send("{g down}")
    Send("{n down}")
    Sleep 493
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{s down}")
    Sleep 232
    Send("{s up}")
    Sleep 17
    Send("{x down}")
    Sleep 250
    Send("{x up}")
    Sleep 15
    Send("{g down}")
    Send("{n down}")
    Sleep 494
    Send("{g up}")
    Send("{n up}")
    Sleep 0
    Send("{n down}")
    Sleep 249
    Send("{m up}")
    Sleep 0
    Send("{m down}")
    Sleep 495
    Send("{n up}")
    Sleep 0
    Send("{q down}")
    Send("{g down}")
    Send("{n down}")
    Sleep 19
    Send("{m up}")
    Sleep 475
    Send("{g up}")
    Send("{n up}")
    Sleep 2
    Send("{2 down}")
    Send("{g down}")
    Sleep 17
    Send("{q up}")
    Sleep 495
    Send("{g up}")
    Sleep 0
    Send("{d down}")
    Send("{m down}")
    Sleep 231
    Send("{d up}")
    Sleep 15
    Send("{m up}")
    Sleep 0
    Send("{q down}")
    Send("{s down}")
    Sleep 29
    Send("{2 up}")
    Sleep 220
    Send("{2 down}")
    Sleep 29
    Send("{q up}")
    Sleep 219
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Send("{j down}")
    Sleep 493
    Send("{s up}")
    Send("{j up}")
    Sleep 0
    Send("{v down}")
    Sleep 232
    Send("{v up}")
    Sleep 17
    Send("{g down}")
    Sleep 250
    Send("{g up}")
    Sleep 15
    Send("{s down}")
    Send("{j down}")
    Sleep 248
    Send("{2 up}")
    Sleep 0
    Send("{2 down}")
    Sleep 246
    Send("{s up}")
    Send("{j up}")
    Sleep 0
    Send("{q down}")
    Send("{s down}")
    Sleep 29
    Send("{2 up}")
    Sleep 220
    Send("{2 down}")
    Sleep 29
    Send("{q up}")
    Sleep 220
    Send("{6 down}")
    Sleep 29
    Send("{2 up}")
    Sleep 217
    Send("{s up}")
    Sleep 0
    Send("{s down}")
    Send("{j down}")
    Sleep 247
    Send("{3 down}")
    Sleep 19
    Send("{6 up}")
    Sleep 228
    Send("{s up}")
    Send("{j up}")
    Sleep 2
    Send("{2 down}")
    Send("{g down}")
    Sleep 27
    Send("{3 up}")
    Sleep 485
    Send("{g up}")
    Sleep 0
    Send("{g down}")
    Send("{n down}")
    Sleep 231
    Send("{g up}")
    Sleep 15
    Send("{n up}")
    Sleep 0
    Send("{3 down}")
    Send("{m down}")
    Sleep 29
    Send("{2 up}")
    Sleep 220
    Send("{m down}")
    Sleep 29
    Send("{3 up}")
    Sleep 205
    Send("{m up}")
    Sleep 15
    Send("{g down}")
    Send("{n down}")
    Sleep 471
    Send("{m up}")
    Sleep 22
    Send("{2 down}")
    Sleep 247
    Send("{g up}")
    Send("{n up}")
    Sleep 2
    Send("{w down}")
    Send("{c down}")
    Sleep 27
    Send("{2 up}")
    Sleep 129
    Send("{w up}")
    Sleep 108
    Send("{5 down}")
    Send("{y down}")
    Sleep 194
    Send("{5 up}")
    Send("{y up}")
    Sleep 300
    Send("{w down}")
    Sleep 234
    Send("{w up}")
    Sleep 15
    Send("{c up}")
    Sleep 0
    Send("{e down}")
    Send("{6 down}")
    Send("{s down}")
    Send("{m down}")
    Sleep 99
    Send("{e up}")
    Send("{6 up}")
    Send("{s up}")
    Send("{m up}")
    Sleep 150
    Send("{e down}")
    Send("{6 down}")
    Send("{s down}")
    Send("{m down}")
    Sleep 96
    Send("{e up}")
    Send("{6 up}")
    Send("{s up}")
    Send("{m up}")
    Sleep 150
    Send("{e down}")
    Send("{6 down}")
    Send("{s down}")
    Send("{m down}")
    Sleep 194
    Send("{e up}")
    Send("{6 up}")
    Send("{s up}")
    Send("{m up}")
}
